final Map<String, String> ch = {
  "Select Language" : "选择语言",
  "Awareness":"意识",
  "Enter Mobile Number" : "输入手机号码",
  "SEND OTP" : "发送验证码","How do you feel today ?" : "你今天感觉怎么样？","Online" : "在线","Offline" : "离线","Image Uploaded" : "图片已上传","Type a message" : "輸入訊息","Choose photo from :" : "从中选择照片","Get Connected with doctors" : "与医生连接","Connect with Doctor" : "与医生联系","Connect with Health worker" : "聯繫衛生工作者","Connect with AlloBot" : "与 AlloBot 联系","Sorry No Awareness Post" : "抱歉，没有宣传帖","Checkup Completed" : "体检完成","Waiting for Doctor Feedback" : "等待医生反馈","Checkup need to be done" : "需要做体检","Checkup" : "清理","No Checkup Found" : "未找到体检","Checkup Details" : "体检详情","Doctor Name" : "医生姓名","Date:" : "日期","Health Status:" : "健康状况","Case Summary" : "案例总结","Prescription" : "处方","Next Appointment Time" : "下次预约时间","Symptoms" : "症状","Vitals" : "生命体征","Add Prescription" : "添加处方","ADD PRESCRIPTION" : "添加处方","Click to Add Image" : "点击添加图片","View Prescription" : "查看处方","Error loading image" : "加载图片错误","Prescription Type" : "处方类型","Date Added" : "添加日期","Description" : "描述","Add Report" : "添加报告","NO IMAGE" : "没有图片","Click Add Image Button" : "点击添加图片按钮","ADD IMAGE" : "添加图片","ADD REPORT" : "点击添加图片按钮","Report" : "报告","Scan and Add new Report" : "扫描并添加新报告","Self Screening" : "自我筛查","BACK" : "返回","NEXT" : "下一","Finish" : "完成","Summary Report" : "总结报告","Submit" : "提交","Let's begin the test" : "让我们开始测试","Hemoglobin Test" : "血红蛋白测试","Easily get your Reading by Performing the scans below" : "“通過執行以下掃描輕鬆獲取讀數”，","Fetal Monitoring" : "胎儿监护","Upload Report" : "上传报告","Tap to Change" : "点击更改","Heart Rate" : "心率","BPM" : "每分钟节拍","Kick Count" : "踢腿次数","Tap to Increase the Count" : "轻触增加计数","Add Glucose Report" : "添加血糖报告","Blood Glucose Value" : "血糖值","Add Hemoglobin Report" : "添加血红蛋白报告","Hemoglobin Value" : "血红蛋白值","Ultra Sound" : "超声波","Fasting" : "禁食","At rest" : "“休息時”，","After Walk" : "散步后","Select Height" : "选择身高","Select Weight" : "选择体重","After walk" : "散步后","Address Information" : "地址信息","Search" : "搜索","Continue" : "继续","Phone Number" : "电话号码","Profile Details" : "“個人資料詳細資料”，","Gender" : "性别","Male" : "男性","Female" : "女性","Select Blood Group" : "选择血型","Select Last cycle Date" : "选择上次周期日期","Are you my mom or dad?" : "你是我妈妈还是爸爸？","Dad" : "爸爸","Mom" : "妈妈","Enter your Partner Details" : "输入您的伴侣信息","Pregnancy Status" : "怀孕状态","Partner Pregnancy Status" : "伴侣怀孕状态","Average Length of Cycles" : "周期平均长度","Day" : "天","Not yet started" : "尚未开始","NORMAL" : "正常","Health Status" : "健康状况","Last Screened" : "上次筛查","GOLD" : "黄金","Subscription Plan" : "订阅计划","No News Feed" : "没有新闻动态","Probable Reason" : "可能原因","Recommendations" : "推荐","Hi!" : "嗨","How do you feel today?" : "今天你感觉怎么样","Select Exercise that have you done today?" : "选择你今天做过的运动","None" : "没有","Select tablets that you have taken" : "选择你已服用的药片","Sleep Duration" : "睡眠时长","Do you have any of these Symptoms?" : "你有这些症状吗？","Baby Voice is Recording" : "宝宝的声音正在录音","STOP" : "停","Click the Record Button to Start Recording" : "点击录音按钮开始录音","Record" : "录音","How many Glass of water have you drunk today?" : "你今天喝了多少杯水？","OTP Verification" : "OTP 验证","Enter OTP sent to" : "请输入发送到的 OTP","Verify and proceed" : "验证并继续","Appointment" : "预约时间","Select Hospital" : "选择医院","Select Doctor" : "选择医生","Appointment Date" : "预约日期","Available slots" : "可用时间","No Slots Available" : "没有可用的空档","View Available Slots" : "查看可用空档","Start time Slot:" : "开始时间段","Diagnosis Description" : "诊断描述","Book" : "书","Update" : "升级","Heart Rate" : "心率","Respiratory Rate" : "呼吸频率","Appointments" : "预约时间","As a companion in your pregnancy we help you with the following" : "作为您孕期的伴侣，我们将为您提供以下帮助","Book An Appointment" : "预约一个时间","Pregnancy Monitoring" : "孕期监测","Help Line" : "求助热线","Current Appointment" : "当前预约","No Upcoming Appointments" : "没有即将到来的预约","Time" : "时间","Status" : "地位”，","Reason" : "“原因”，","Cancel Appointment" : "“取消預訂”，","Show Appointment" : "“顯示預約”，","My Appointments" : "“我的約會”，","Appointment Status" : "預約狀態","App Info" : "应用信息","CHECK FOR UPDATES" : "检查更新","Edit Profile" : "编辑个人资料","Help" : "帮助","Tell us what's going on" : "“告訴我們發生了什麼事”，","Tell us why you're reaching us" : "告诉我们你为什么联系我们","How do you feel? (Optional)" : "你感觉怎么样？（可选）","My Hospital" : "我的医院","No hospitals found" : "未找到医院","District:" : "区：","Settings" : "设置","English" : "英语","Logout Successful" : "注销成功","Subscribe" : "订阅","Subscription" : "訂閱","Current Plan" : "当前计划","Monthly" : "每月","Yearly" : "每年","Based on patient reviews" : "根据患者评价","Working Hours" : "工作时间","Contact Information" : "联系信息","Personalised Pregnancy Care" : "个性化孕期护理","Helps you to consult Doctor Virtually" : "帮助您在线咨询医生","Engage with Doctor through video and audio" : "通过视频和音频与医生互动","Keep on track your Health" : "保持健康追踪","By continuing, You agree that you have read and accept our" : "继续操作，即表示您同意已阅读并接受我们的","T&C and Privacy Policy" : "条款与隐私政策","Allobot" : "阿洛博特","Thinking..." : "正在思考...","Your maternal AI assistant is processing your question" : "“您的產婦人工智慧助理正在處理您的問題”，","Your Maternal AI Assistant" : "“你的產婦人工智慧助理”，","Welcome to Allobot!" : "欢迎来到 Allobot！","I'm here to support you through your maternal journey. Ask me anything about pregnancy, childbirth, or early motherhood." : "我在这里支持您的孕期旅程。关于怀孕、分娩或早期母亲身份的任何问题，尽管问我","What You Can Ask Me:" : "您可以问我","Pregnancy health tips" : "孕期健康小贴士","Nutrition advice" : "营养建议","Baby care basics" : "宝宝护理基础","Trimester milestones" : "“三個月的里程碑”，","Ask Allobot..." : "向 Allobot 询问...","Incoming Call" : "来电","Waiting" : "等待","No messages yet" : "还没有消息","Tablets" : "平板电脑","Units" : "单元","Timing" : "计时","No prescriptions found." : "未找到处方","No description available" : "暂无描述","No reports found" : "未找到报告","Report Details" : "报告详情","Unknown Report Type" : "未知报告类型","Test Results" : "测试结果","Delete Report" : "删除报告","Are you sure you want to delete this report?" : "您确定要删除此报告吗？","CANCEL" : "取消","DELETE" : "删除","Normal" : "正常","Body pain" : "身体疼痛","Burning Stomach" : "胃部灼热","Cold cough" : "感冒咳嗽","Dizziness" : "头晕","Headache" : "头痛","Vomiting" : "呕吐","Other" : "其他","Blood Pressure" : "血压","Temperature" : "温度","Blood Saturation" : "血氧饱和度","Blood Glucose" : "血糖","BMI" : "体质指数","HRV" : "心率变异性","Baby Cry Not Detected." : "「未偵測到嬰兒哭聲。」,","The baby cry detection process failed. Please check your connection or try again." : "宝宝哭泣检测过程失败。请检查您的连接或重试","Retry" : "重试","Please select Appointment Date" : "请选择预约日期","Please enter Diagnosis Description" : "请输入诊断描述","No data available" : "暂无数据","Pregnant" : "怀孕","Not Pregnant" : "没有怀孕","Summary" : "总结","Upcoming Appointments" : "即将到来的预约","No appointments scheduled" : "没有安排预约","No" : "不","Yes" : "是","No appointments found" : "未找到预约","JioVio Healthcare" : "“JioVio醫療保健”，","General Details" : "一般详情","Partner Details" : "合作伙伴详情","Pregnancy Details" : "怀孕详情","Address Details" : "地址详情","Contact Us" : "地址详情","Something not Working" : "某些功能无法正常工作","Feature Request" : "功能请求","Question" : "问题","FeedBack" : "反馈","Other" : "其他","SEND" : "发送","My Subscription" : "我的订阅","Language" : "语言","Terms & Conditions" : "条款与条件","Privacy Policy" : "隐私政策","Log Out" : "登出","Are you sure to logout?" : "您确定要登出吗？","Cancel" : "取消","Ok" : "好的","Change Default" : "更改默认","Write Description" : "写描述","Please enter Description" : "请输入描述","Description" : "描述","Door No" : "门牌号","Please enter Door No" : "请输入门牌号","Street Name" : "街道名称","Please enter Street Name" : "请输入街道名称","Pincode" : "邮政编码","Please enter Pincode" : "请输入邮政编码","Search Area" : "搜索区域","Select Area Name" : "选择区域名称","Enter your Name" : "请输入您的姓名","Please enter your name" : "请输入您的姓名","Enter Email Id" : "请输入电子邮件地址","Please Select Gender" : "请选择性别","Age" : "年龄","Please enter age" : "请输入年龄","Please enter corrent age" : "请输入正确的年龄","LMP Date" : "末次月经日期","Please enter LMP Date" : "请输入末次月经日期","ED Date" : "预产期日期","Average Length of Cycles" : "周期平均长度","Please enter LMP Date" : "请输入末次月经日期","Date of delivery" : "预产期","Please enter Delivery Date" : "请输入分娩日期","Please enter Partner Name" : "请输入伴侣姓名","Partner Name" : "请输入伴侣姓名","Please enter Partner Mobile Number" : "请输入伴侣手机号码","Partner Mobile Number" : "伴侣手机号码","Bed Time" : "睡觉时间","Please enter Date of Birth" : "请输入出生日期","Wake Up Time" : "起床时间","Please enter Date of Birth" : "请输入出生日期","Name" : "姓名","Please Select Gender" : "请选择性别","Age" : "年龄","Please enter age" : "请输入年龄","Please enter Partner Name" : "请输入伴侣姓名","Partner Name" : "伴侣姓名","Please enter Partner Mobile Number" : "请输入伴侣手机号码","Partner Mobile Number" : "伴侣手机号码","Please Select Parent Type" : "请选择父母类型","Mom" : "妈妈","Dad" : "爸爸","Parent Type" : "父母类型","LMP Date" : "末次月经日期","Please enter LMP Date" : "请输入末次月经日期","Please enter ED date" : "请输入预产期日期","ED Date" : "预产期日期","Please Select Pregnant Status" : "请选择怀孕状态","Status" : "状态","Please enter Door No" : "请输入门牌号","Door No" : "门牌号","Please enter Street name" : "请输入街道名称","Street Name" : "街道名称","Please enter Area" : "请输入区域","Area" : "区域","Please enter pincode" : "请输入邮政编码","Pincode" : "邮政编码","Services" : "服务","AlloBaby" : "阿罗宝贝",
  "Glucose Test": "血糖检查",
"Ultrasound Test": "超声检查",
"Urine Test": "尿液检查",
...babycrys
  };

  final Map<String, String> babycrys = {
"Hunger Crying"	:	"饥饿的哭泣",
"Sleepy Crying"	:	"困哭",
"Pain Crying"	:	"痛苦哭泣",
"Discomfort Crying"	:	"不适 哭泣",
"Colic Crying"	:	"绞痛哭泣",
"Attention Crying"	:	"注意哭泣",
"Hunger Cry"	:	"饥饿的哭泣",
"Sleepy Cry"	:	"困哭",
"Pain Cry"	:	"痛苦哭泣",
"Discomfort Cry"	:	"不适 哭泣",
"Colic Cry"	:	"绞痛哭泣",
"Attention Cry"	:	"注意哭泣",
"Rhythmic, repetitive cries that grow louder if the baby isn't fed. Often accompanied by hand-sucking and rooting behavior."	:	"有节奏的重复哭声，如果婴儿没有吃奶，哭声会更大。通常伴有吸吮手和生根行为。",
"A whiny, nasal cry that sounds weaker than a hunger cry, often accompanied by yawning and eye-rubbing."	:	"呜的鼻腔哭泣，听起来比饥饿的哭声更微弱，通常伴有打哈欠和揉眼睛。",
"A sudden, high-pitched, intense cry that comes in bursts with breathing pauses. Often accompanied by physical tension."	:	"一声突如其来的、尖锐的、强烈的叫声，伴随着呼吸的暂停。通常伴随着身体紧张。",
"A fussy, irritated cry that typically stops when the source of discomfort is addressed."	:	"烦躁、烦躁的哭声，通常在解决不适的根源时停止。",
"Prolonged, intense crying episodes, typically in the evening, with physical signs of distress."	:	"长时间、剧烈的哭泣发作，通常在晚上，伴有痛苦的身体迹象。",
"A mild cry that starts softly and increases if ignored, often accompanied by eye contact and reaching out."	:	"轻微的哭泣，开始时轻柔，如果被忽视，则会增加，通常伴有眼神交流和伸出手。",
"Hunger cries are rhythmic, repetitive, and grow louder if the baby isn't fed."	:	"饥饿的哭声是有节奏的、重复的，如果婴儿没有吃奶，哭声会变得更大。",
"Babies may also:"	:	"婴儿还可能：",
"• Suck on hands or fingers"	:	"• 吮吸手或手指",
"• Smack lips, root (turn head searching for a nipple)"	:	"• 咂嘴唇，根部（转头寻找）",
"• Get fussy even after being comforted"	:	"• 即使在得到安慰后也要挑剔",
"A whiny, nasal cry that may sound weaker than a hunger cry."	:	"呜呜呜的鼻腔哭泣，听起来可能比饥饿的哭声更微弱。",
"Babies may also:"	:	"婴儿还可能：",
"• Yawn frequently"	:	"• 经常打哈欠",
"• Rub their eyes or pull their ears"	:	"• 揉揉他们的眼睛或拉他们的耳朵",
"• Become fussy and harder to soothe"	:	"• 变得挑剔，更难舒缓",
"A sudden, high-pitched, intense cry that may come in bursts with pauses for breath."	:	"突然、高亢、激烈的哭泣，可能会突然出现，并伴有呼吸暂停。",
"Babies may also:"	:	"婴儿还可能：",
"• Clench fists or arch their back"	:	"• 握紧拳头或拱起背部",
"• Become stiff or tense"	:	"• 变得僵硬或紧张",
"• Show signs of discomfort (scrunched face, difficulty calming down)"	:	"• 出现不适迹象（皱缩的脸、难以平静下来）",
"A fussy, irritated cry that may stop when the issue is resolved."	:	"烦躁、烦躁的哭泣，当问题得到解决时可能会停止。",
"Babies may also:"	:	"婴儿还可能：",
"• Wiggle or squirm a lot"	:	"• 经常摆动或蠕动",
"• Tug at their clothing or ears"	:	"• 拉扯他们的衣服或耳朵",
"• Appear restless or uneasy"	:	"• 显得焦躁不安或不安",
"A prolonged, intense, high-pitched cry that often occurs in the evening."	:	"一种长时间、强烈、高亢的哭声，经常发生在晚上。",
"Babies may also:"	:	"婴儿还可能：",
"• Clench fists, arch their back, or pull up legs"	:	"• 握紧拳头、拱起背部或拉起双腿",
"• Have a tense, bloated belly"	:	"• 腹部紧张、肿胀",
"• Be difficult to soothe, even after feeding"	:	"• 即使在喂食后也难以安抚",
"A mild, whimpering cry that starts softly and gets louder if ignored."	:	"一种温和的呜咽声，开始时很轻柔，如果被忽视，声音会更大。",
"Babies may also:"	:	"婴儿还可能：",
"• Make eye contact while crying"	:	"• 哭泣时进行眼神交流",
"• Reach out for comfort"	:	"• 伸出手寻求舒适",
"• Stop crying quickly when picked up"	:	"• 被捡起后迅速停止哭泣",
"Feed Promptly – Responding early prevents excessive crying and makes feeding easier."	:	"及时喂奶 – 及早反应可以防止过度哭泣，使喂奶更容易。",
"Watch for Hunger Cues – Crying is a late sign; look for early signs like lip-smacking, rooting, sticking out tongue, or sucking on hands."	:	"注意饥饿线索 – 哭泣是一个迟到的迹象;寻找早期迹象，如咂嘴、发根、伸舌或吮吸手。",
"Ensure Proper Latch – If breastfeeding, ensure a deep latch to avoid discomfort."	:	"确保正确的衔乳 – 如果是母乳喂养，请确保深吸乳以避免不适。",
"Check Feeding Schedule – Newborns need feeding every 2-3 hours."	:	"检查喂养时间表 – 新生儿需要每 2-3 小时喂养一次。",
"Burp Baby After Feeding – Helps prevent gas and fussiness."	:	"喂奶后给宝宝打嗝 – 有助于防止胀气和烦躁。",
"Look for Sleep Cues Early – Yawning, zoning out, or rubbing eyes signal it's time to sleep."	:	"尽早寻找睡眠线索 – 打哈欠、划定区域或揉眼睛表明该睡觉了。",
"Create a Calm Sleep Environment – Dim lights, reduce noise, and use white noise if needed."	:	"创造一个平静的睡眠环境 – 调暗灯光，减少噪音，并在需要时使用白噪声。",
"Use Gentle Rocking – Motion, swaddling, or a pacifier can help."	:	"使用轻柔的摇摆 – 运动、襁褓或安抚奶嘴会有所帮助。",
"Follow a Sleep Routine – A consistent bedtime routine helps babies recognize sleep time."	:	"遵循睡眠习惯 – 一致的就寝时间有助于婴儿识别睡眠时间。",
"Avoid Overstimulation – Too much activity before bed can make sleep harder."	:	"避免过度刺激 – 睡前过多的活动会使睡眠更加困难。",
"Check for Obvious Issues – Look for diaper rash, teething pain, or tight clothing."	:	"检查明显问题 – 寻找尿布疹、出牙疼痛或紧身衣服。",
"Soothe with Gentle Touch – Skin-to-skin contact or holding them close can help."	:	"轻柔的触摸舒缓 – 肌肤接触或紧贴身体会有所帮助。",
"Try Pain Relief Techniques – For teething, offer a chilled teether; for gas, try tummy massage."	:	"尝试止痛技巧 – 对于出牙，提供冰镇牙胶;对于气体，请尝试腹部按摩。",
"Monitor for Fever or Illness – If crying persists with fever, vomiting, or lethargy, consult a doctor."	:	"监测发烧或疾病 – 如果哭泣伴有发烧、呕吐或嗜睡，请咨询医生。",
"Trust Your Instincts – If the baby seems in severe pain, seek medical advice immediately."	:	"相信你的直觉 – 如果婴儿看起来剧烈疼痛，请立即就医。",
"Check the Diaper – A wet or soiled diaper is a common cause of discomfort."	:	"检查尿布 – 潮湿或脏污的尿布是导致不适的常见原因。",
"Ensure Comfortable Clothing – Dress baby in breathable, soft fabrics and check for tight clothing."	:	"确保衣服舒适 – 给宝宝穿上透气、柔软的面料，并检查衣服是否紧身。",
"Adjust Temperature – Feel baby's neck/back to see if they are too hot or cold."	:	"调整温度 – 摸摸宝宝的脖子/背部，看看他们是太热还是太冷。",
"Check for External Irritants – Tags, rough fabric, or hair wrapped around fingers/toes can cause irritation."	:	"检查外部刺激物 – 标签、粗糙的织物或缠绕在手指/脚趾上的头发会引起刺激。",
"Reposition Baby – Changing positions or holding them differently can sometimes help."	:	"重新定位婴儿 – 改变姿势或以不同的方式保持它们有时会有所帮助。",
"Use Gentle Motions – Rocking, swaying, or holding baby in a 'colic carry' (on their tummy along your forearm) can help."	:	"使用轻柔的动作 – 摇晃、摇摆或以“绞痛背带”（沿着前臂趴着）抱着婴儿会有所帮助。",
"Try White Noise – Rhythmic sounds, like a fan or heartbeat sound, can be soothing."	:	"尝试白噪声 – 有节奏的声音，如风扇声或心跳声，可以起到舒缓作用。",
"Burp Baby Well – Gas buildup can make colic worse. Burp frequently during feeds."	:	"打嗝婴儿井 – 气体积聚会使绞痛恶化。喂奶时经常打嗝。",
"Massage the Tummy – A gentle circular tummy massage can relieve gas."	:	"按摩腹部 – 轻柔的圆形腹部按摩可以缓解胀气。",
"Consult a Pediatrician – If colic persists, discuss options like probiotic drops or diet changes (for breastfeeding moms)."	:	"咨询儿科医生 – 如果绞痛持续存在，请讨论益生菌滴剂或改变饮食（适用于母乳喂养的妈妈）等选择。",
"Respond with Reassurance – Holding, talking, or making eye contact helps babies feel secure."	:	"以保证回应 – 抱着、说话或进行眼神交流有助于婴儿感到安全。",
"Try Gentle Touch – A cuddle or soft pat on the back can be calming."	:	"尝试轻柔的触摸 – 拥抱或轻轻拍打背部可以让人平静。",
"Engage with Soothing Sounds – Humming or talking in a calm voice can reassure the baby."	:	"与舒缓的声音互动 – 哼唱或用平静的声音说话可以让宝宝放心。",
"Encourage Independent Comforting – Allow baby to self-soothe briefly before immediately responding."	:	"鼓励独立安慰 – 让宝宝先短暂地自我安抚，然后再立即做出反应。",
"Maintain a Balance – Meeting attention needs is important, but consistency in response helps babies learn security."	:	"保持平衡 – 满足注意力需求很重要，但一致的反应有助于婴儿学习安全感。",
  
  "Cry History":"哭泣的历史",
"Record" :"记录"
  };