final Map<String, String> hi = {
  "Select Language"	:	"भाषा चुनें",
"Enter Mobile Number"	:	"मोबाइल नंबर दर्ज करें",
"SEND OTP"	:	"ओटीपी भेजें",
"How do you feel today ?"	:	"आप आज कैसा महसूस कर रहे हैं?",
"Online"	:	"ऑनलाइन",
"Offline"	:	"ऑफलाइन",
"Image Uploaded"	:	"छवि अपलोड की गई",
"Type a message"	:	"एक संदेश टाइप करें",
"Choose photo from"	:	"फोटो चुनें",
"Get Connected with doctors"	:	"डॉक्टरों से जुड़ें",
"Connect with Doctor"	:	"डॉक्टर से संपर्क करें",
"Connect with Health worker"	:	"स्वास्थ्य कार्यकर्ता से संपर्क करें",
"Connect with AlloBot"	:	"अलोबॉट से जुड़ें",
"Sorry No Awareness Post"	:	"क्षमा करें, कोई जागरूकता पोस्ट नहीं है।",
"Checkup Completed"	:	"चेकअप पूरा हुआ",
"Waiting for Doctor Feedback"	:	"डॉक्टर की प्रतिक्रिया का इंतजार कर रहे हैं",
"Checkup need to be done"	:	"चेकअप करना आवश्यक है",
"Checkup"	:	"चेकअप",
"No Checkup Found"	:	"कोई जांच नहीं मिली",
"Checkup Details"	:	"चेकअप विवरण",
"Doctor Name"	:	"डॉक्टर का नाम",
"Date"	:	"तारीख",
"Health Status"	:	"स्वास्थ्य स्थिति",
"Case Summary"	:	"मामले का सारांश",
"Prescription"	:	"पर्चा",
"Next Appointment Time"	:	"अगली नियुक्ति का समय",
"Symptoms"	:	"लक्षण",
"Vitals"	:	"जीवित तत्व",
"Add Prescription"	:	"प्रिस्क्रिप्शन जोड़ें",
"ADD PRESCRIPTION"	:	"प्रिस्क्रिप्शन जोड़ें",
"Click to Add Image"	:	"छवि जोड़ने के लिए क्लिक करें",
"View Prescription"	:	"प्रिस्क्रिप्शन देखें",
"Error loading image"	:	"छवि लोड करने में त्रुटि",
"Prescription Type"	:	"प्रिस्क्रिप्शन प्रकार",
"Date Added"	:	"जोड़ने की तारीख",
"Description"	:	"विवरण",
"Add Report"	:	"रिपोर्ट जोड़ें",
"NO IMAGE"	:	"कोई छवि नहीं",
"Click Add Image Button"	:	"इमेज जोड़ें बटन पर क्लिक करें",
"ADD IMAGE"	:	"छवि जोड़ें",
"ADD REPORT"	:	"रिपोर्ट जोड़ें",
"Report"	:	"रिपोर्ट",
"Scan and Add new Report"	:	"स्कैन करें और नई रिपोर्ट जोड़ें",
"Self Screening"	:	"स्वयं स्क्रीनिंग",
"BACK"	:	"पीछे",
"NEXT"	:	"अगला",
"Finish"	:	"समाप्त",
"Summary Report"	:	"सारांश रिपोर्ट",
"Submit"	:	"जमा करें",
"Let's begin the test"	:	"आइए परीक्षण शुरू करें",
"Hemoglobin Test"	:	"हीमोग्लोबिन परीक्षण",
"Easily get your Reading by Performing the scans below"	:	"नीचे दिए गए स्कैन करके आसानी से अपनी रीडिंग प्राप्त करें",
"Fetal Monitoring"	:	"भ्रूण निगरानी",
"Upload Report"	:	"रिपोर्ट अपलोड करें",
"Tap to Change"	:	"बदलने के लिए टैप करें",
"Heart Rate"	:	"हृदय गति",
"BPM"	:	"धड़कन प्रति मिनट",
"Kick Count"	:	"किक गिनती",
"Tap to Increase the Count"	:	"गिनती बढ़ाने के लिए टैप करें",
"Add Glucose Report"	:	"ग्लूकोज रिपोर्ट जोड़ें",
"Blood Glucose Value"	:	"रक्त ग्लूकोज मान",
"Add Hemoglobin Report"	:	"हेमोग्लोबिन रिपोर्ट जोड़ें",
"Hemoglobin Value"	:	"हेमोग्लोबिन मान",
"Ultra Sound"	:	"अल्ट्रा साउंड",
"Fasting"	:	"उपवास",
"At rest"	:	"विश्राम की अवस्था में",
"After Walk"	:	"चलने के बाद",
"Select Height"	:	"ऊंचाई चुनें",
"Select Weight"	:	"वजन चुनें",
"After walk"	:	"चलने के बाद",
"Address Information"	:	"पता जानकारी",
"Search"	:	"खोज",
"Continue"	:	"जारी रखें",
"Phone Number"	:	"फोन नंबर",
"Profile Details"	:	"प्रोफ़ाइल विवरण",
"Gender"	:	"लिंग",
"Male"	:	"पुरुष",
"Female"	:	"महिला",
"Select Blood Group"	:	"रक्त समूह चुनें",
"Select Last cycle Date"	:	"अंतिम चक्र की तारीख चुनें",
"Are you my mom or dad?"	:	"क्या आप मेरी माँ हैं या मेरे पिता?",
"Dad"	:	"पिता",
"Mom"	:	"माँ",
"Enter your Partner Details"	:	"अपने साथी का विवरण दर्ज करें",
"Pregnancy Status"	:	"गर्भावस्था की स्थिति",
"Partner Pregnancy Status"	:	"साथी की गर्भावस्था की स्थिति",
"Average Length of Cycles"	:	"चक्रों की औसत लंबाई",
"Day"	:	"दिन",
"Not yet started"	:	"अभी तक शुरू नहीं हुआ",
"NORMAL"	:	"सामान्य",
"Health Status"	:	"स्वास्थ्य स्थिति",
"Last Screened"	:	"आखिरी बार जांची गई",
"GOLD"	:	"सोना",
"Subscription Plan"	:	"सदस्यता योजना",
"No News Feed"	:	"कोई समाचार फीड नहीं",
"Probable Reason"	:	"संभावित कारण",
"Recommendations"	:	"सिफारिशें",
"Hi!"	:	"हाय!",
"How do you feel today?"	:	"आज आप कैसा महसूस कर रहे हैं",
"Select Exercise that have you done today?"	:	"आज आपने जो व्यायाम किया है, उसे चुनें?",
"None"	:	"कोई नहीं",
"Select tablets that you have taken"	:	"वह गोलियाँ चुनें जो आपने ली हैं",
"Sleep Duration"	:	"नींद की अवधि",
"Do you have any of these Symptoms?"	:	"क्या आपको इनमें से कोई लक्षण हैं",
"Baby Voice is Recording"	:	"बच्चे की आवाज़ रिकॉर्ड हो रही है",
"STOP"	:	"रोकें",
"Click the Record Button to Start Recording"	:	"रिकॉर्ड बटन पर क्लिक करें ताकि रिकॉर्डिंग शुरू हो सके",
"Record"	:	"रिकॉर्ड",
"How many Glass of water have you drunk today?"	:	"आज आपने कितने गिलास पानी पिया है",
"OTP Verification"	:	"ओटीपी सत्यापन",
"Enter OTP sent to"	:	"ओटीपी दर्ज करें जो भेजा गया है",
"Verify and proceed"	:	"सत्यापित करें और आगे बढ़ें",
"Appointment"	:	"अपॉइंटमेंट",
"Select Hospital"	:	"अस्पताल चुनें",
"Select Doctor"	:	"डॉक्टर चुनें",
"Appointment Date"	:	"नियुक्ति की तारीख",
"Available slots"	:	"उपलब्ध स्लॉट्स",
"No Slots Available"	:	"कोई स्लॉट उपलब्ध नहीं है",
"View Available Slots"	:	"उपलब्ध स्लॉट्स देखें",
"Start time Slot"	:	"प्रारंभ समय स्लॉट",
"Diagnosis Description"	:	"निदान विवरण",
"Book"	:	"बुक",
"Update"	:	"अपडेट",
"Respiratory Rate"	:	"श्वसन दर",
"Appointments"	:	"अपॉइंटमेंट",
"As a companion in your pregnancy we help you with the following"	:	"आपकी गर्भावस्था में एक साथी के रूप में हम आपकी निम्नलिखित चीजों में मदद करते हैं",
"Book An Appointment"	:	"कृपया एक अपॉइंटमेंट बुक करें।",
"Pregnancy Monitoring"	:	"गर्भावस्था निगरानी",
"Help Line"	:	"हेल्पलाइन",
"Current Appointment"	:	"वर्तमान अपॉइंटमेंट",
"No Upcoming Appointments"	:	"कोई आगामी अपॉइंटमेंट नहीं है",
"Time"	:	"समय",
"Status"	:	"स्टेटस",
"Reason"	:	"कारण",
"Cancel Appointment"	:	"अपना अपॉइंटमेंट रद्द करें।",
"Show Appointment"	:	"अपॉइंटमेंट दिखाएँ",
"My Appointments"	:	"मेरे अपॉइंटमेंट्स",
"Appointment Status"	:	"अपॉइंटमेंट की स्थिति",
"App Info"	:	"ऐप जानकारी",
"CHECK FOR UPDATES"	:	"अपडेट्स के लिए जांचें",
"Edit Profile"	:	"प्रोफ़ाइल संपादित करें",
"Help"	:	"सहायता",
"Tell us what's going on"	:	"हमें बताइए क्या हो रहा है?",
"Tell us why you're reaching us"	:	"हमें बताइए आप हमसे क्यों संपर्क कर रहे हैं",
"How do you feel? (Optional)"	:	"आप कैसा महसूस कर रहे हैं? (वैकल्पिक)",
"My Hospital"	:	"मेरा अस्पताल",
"No hospitals found"	:	"कोई अस्पताल नहीं मिला",
"District"	:	"जिला",
"Settings"	:	"सेटिंग्स",
"English"	:	"अंग्रेज़ी",
"Logout Successful"	:	"लॉगआउट सफल हुआ",
"Subscribe"	:	"सदस्यता लें",
"Subscription"	:	"सदस्यता",
"Current Plan"	:	"वर्तमान योजना",
"Monthly"	:	"मासिक",
"Yearly"	:	"वार्षिक",
"Based on patient reviews"	:	"रोगी की समीक्षाओं के आधार पर",
"Working Hours"	:	"कार्यकाल",
"Contact Information"	:	"संपर्क जानकारी",
"Personalised Pregnancy Care"	:	"व्यक्तिगत गर्भावस्था देखभाल",
"Helps you to consult Doctor Virtually"	:	"आपको डॉक्टर से वर्चुअली परामर्श लेने में मदद करता है",
"Engage with Doctor through video and audio"	:	"वीडियो और ऑडियो के माध्यम से डॉक्टर से जुड़ें",
"Keep on track your Health"	:	"अपनी सेहत पर नज़र रखें",
"By continuing, You agree that you have read and accept our"	:	"जारी रखने से, आप सहमत होते हैं कि आपने हमारे",
"T&C and Privacy Policy"	:	"नियम और शर्तें",
"Thinking..."	:	"सोच रहे हैं",
"Your maternal AI assistant is processing your question"	:	"आपकी मातृक AI सहायक आपके प्रश्न को संसाधित कर रही है।",
"Your Maternal AI Assistant"	:	"आपकी मातृक AI सहायक",
"Welcome to Allobot!"	:	"में आपका स्वागत है!",
"I'm here to support you through your maternal journey. Ask me anything about pregnancy, childbirth, or early motherhood."	:	"मैं आपकी मातृत्व यात्रा में आपका समर्थन करने के लिए यहां हूं। गर्भावस्था, प्रसव या प्रारंभिक मातृत्व के बारे में मुझसे कुछ भी पूछें।",
"What You Can Ask Me"	:	"आप मुझसे क्या पूछ सकते हैं",
"Pregnancy health tips"	:	"गर्भावस्था स्वास्थ्य युक्तियाँ",
"Nutrition advice"	:	"पोषण संबंधी सलाह",
"Baby care basics"	:	"शिशु देखभाल की मूल बातें",
"Trimester milestones"	:	"त्रैमासिक मील के पत्थर",
"Ask Allobot..."	:	"एलोबोट से पूछें",
"Incoming Call"	:	"एक फोन आ रहा है",
"Waiting"	:	"इंतज़ार में",
"No messages yet"	:	"अभी तक कोई संदेश नहीं है",
"Tablets"	:	"टैबलेट",
"Units"	:	"इकाइयाँ",
"Timing"	:	"समय",
"No prescriptions found."	:	"कोई नुस्खा नहीं मिला।",
"No description available"	:	"कोई विवरण उपलब्ध नहीं है",
"No reports found"	:	"कोई रिपोर्ट नहीं मिली",
"Report Details"	:	"रिपोर्ट विवरण",
"Unknown Report Type"	:	"अज्ञात रिपोर्ट प्रकार",
"Test Results"	:	"परीक्षण परिणाम",
"Delete Report"	:	"रिपोर्ट हटाएं",
"Are you sure you want to delete this report?"	:	"क्या आप सच में इस रिपोर्ट को हटाना चाहते हैं?",
"CANCEL"	:	"रद्द करें",
"DELETE"	:	"हटाएं",
"Normal"	:	"सामान्य",
"Body pain"	:	"शरीर में दर्द",
"Burning Stomach"	:	"पेट में जलन जैसी दर्द",
"Cold cough"	:	"सर्दी और खांसी",
"Dizziness"	:	"चक्कर आना",
"Headache"	:	"सिरदर्द",
"Vomiting"	:	"उल्टी",
"Other"	:	"अन्य",
"Blood Pressure"	:	"रक्तचाप",
"Temperature"	:	"तापमान",
"Blood Saturation"	:	"रक्त संतृप्ति",
"Blood Glucose"	:	"रक्त ग्लूकोज",
"BMI"	:	"बीएमआई",
"HRV"	:	"एचआरवी",
"Baby Cry Not Detected."	:	"बच्चे की रोने की आवाज़ का पता नहीं चला।",
"The baby cry detection process failed. Please check your connection or try again."	:	"बच्चे का रोना नहीं पाया गया।",
"Retry"	:	"पुनर्प्रयास",
"Please select Appointment Date"	:	"कृपया नियुक्ति की तारीख चुनें",
"Please enter Diagnosis Description"	:	"कृपया निदान विवरण दर्ज करें",
"No data available"	:	"कोई डेटा उपलब्ध नहीं है",
"Pregnant"	:	"गर्भवती",
"Not Pregnant"	:	"गर्भवती नहीं",
"Summary"	:	"सारांश",
"Upcoming Appointments"	:	"आगामी नियुक्तियाँ",
"No appointments scheduled"	:	"कोई नियुक्तियाँ निर्धारित नहीं हैं",
"No"	:	"नहीं",
"Yes"	:	"हाँ",
"No appointments found"	:	"कोई नियुक्तियाँ नहीं मिलीं",
"JioVio Healthcare"	:	"जियोवियो हेल्थकेयर",
"General Details"	:	"सामान्य विवरण",
"Partner Details"	:	"साझेदार विवरण",
"Pregnancy Details"	:	"गर्भावस्था विवरण",
"Address Details"	:	"पता विवरण",
"Contact Us"	:	"हमसे संपर्क करें",
"Something not Working"	:	"कुछ काम नहीं कर रहा है",
"Feature Request"	:	"फीचर अनुरोध",
"Question"	:	"प्रश्न",
"FeedBack"	:	"प्रतिक्रिया",
"SEND"	:	"भेजना",
"My Subscription"	:	"मेरी सदस्यता",
"Language"	:	"भाषा",
"Terms & Conditions"	:	"नियम और शर्तें",
"Privacy Policy"	:	"गोपनीयता नीति",
"Log Out"	:	"लॉग आउट",
"Are you sure to logout?"	:	"क्या आप लॉगआउट करने के लिए सुनिश्चित हैं?",
"Cancel"	:	"रद्द करें",
"Ok"	:	"ठीक है",
"Change Default"	:	"डिफ़ॉल्ट बदलें",
"Write Description"	:	"विवरण लिखें",
"Please enter Description"	:	"कृपया विवरण दर्ज करें",
"Door No"	:	"दरवाजा संख्या",
"Please enter Door No"	:	"कृपया दरवाजा संख्या दर्ज करें",
"Street Name"	:	"सड़क का नाम",
"Please enter Street Name"	:	"कृपया सड़क का नाम दर्ज करें",
"Pincode"	:	"पिनकोड",
"Please enter Pincode"	:	"कृपया पिनकोड दर्ज करें",
"Search Area"	:	"खोज क्षेत्र",
"Select Area Name"	:	"क्षेत्र का नाम चुनें",
"Enter your Name"	:	"अपना नाम दर्ज करें",
"Please enter your name"	:	"कृपया अपना नाम दर्ज करें",
"Enter Email Id"	:	"ईमेल आईडी दर्ज करें",
"Please Select Gender"	:	"कृपया लिंग चुनें",
"Age"	:	"उम्र",
"Please enter age"	:	"कृपया आयु दर्ज करें",
"Please enter correct age"	:	"कृपया सही उम्र दर्ज करें",
"LMP Date"	:	"एलएमपी तिथि",
"Please enter LMP Date"	:	"कृपया LMP तिथि दर्ज करें",
"ED Date"	:	"ईडी तिथि",
"Date of delivery"	:	"डिलीवरी की तारीख",
"Please enter Delivery Date"	:	"कृपया डिलीवरी की तारीख दर्ज करें",
"Please enter Partner Name"	:	"कृपया भागीदार का नाम दर्ज करें",
"Partner Name"	:	"साझेदार का नाम",
"Please enter Partner Mobile Number"	:	"कृपया पार्टनर मोबाइल नंबर दर्ज करें",
"Partner Mobile Number"	:	"साझेदार मोबाइल नंबर",
"Bed Time"	:	"सोने का समय",
"Please enter Date of Birth"	:	"कृपया जन्म तिथि दर्ज करें",
"Wake Up Time"	:	"जागने का समय",
"Name"	:	"नाम",
"Please Select Parent Type"	:	"कृपया माता-पिता का प्रकार चुनें",
"Parent Type"	:	"अभिभावक प्रकार",
"Please Select Pregnant Status"	:	"कृपया गर्भवती स्थिति चुनें",
"Please enter Area"	:	"कृपया क्षेत्र दर्ज करें",
"Area"	:	"क्षेत्र",
"Services"	:	"सेवाएँ",
"AlloBaby"	:	"अलोबेबी",
"Awareness"	:	"जागरूकता",
"Screening"	:	"स्क्रीनिंग",
"Glucose Test"	:	"ग्लूकोज परीक्षण",
"Ultrasound Test"	:	"अल्ट्रासाउंड परीक्षण",
"Urine Test"	:	"मूत्र परीक्षण",
"Home"	:	"घर",
"Service"	:	"सेवा",
"Chat"	:	"चैट",
"Logout"	:	"लॉगआउट",
"Notification"	:	"सूचना",
"ON"	:	"चालू",
"OFF"	:	"बंद",
"ON/OFF"	:	"चालू/बंद",
"AI Recommendation"	:	"एआई सिफारिश",
"Analyzing your health data..."	:	"आपके स्वास्थ्य डेटा का विश्लेषण किया जा रहा है...",
"No summary available"	:	"कोई सारांश उपलब्ध नहीं है।",
"Book Appointment"	:	"अपॉइंटमेंट बुक करें",
"SCAN AND ADD REPORT"	:	"स्कैन करें और रिपोर्ट जोड़ें",
"Allobot"	:	"ऑलॉबॉट",
  ...babycrys

};

final Map<String, String> babycrys = {
"Hunger Crying" :"भुखमरी की पुकार",
"Sleepy Crying" :	"नींद में रोना",
"Pain Crying" :	"दर्द की चीख",
"Discomfort Crying" :	"असुविधा रोना",
"Colic Crying" :	"कोलिक रोना",
"Attention Crying" :	"ध्यान रोना",

"Hunger Cry" :"भुखमरी की पुकार",
"Sleepy Cry" :	"नींद में रोना",
"Pain Cry" :	"दर्द की चीख",
"Discomfort Cry" :	"असुविधा रोना",
"Colic Cry" :	"कोलिक रोना",
"Attention Cry" :	"ध्यान रोना",
	
	
"Rhythmic, repetitive cries that grow louder if the baby isn't fed. Often accompanied by hand-sucking and rooting behavior." :	"लयबद्ध, दोहराए जाने वाले रोने की आवाजें जो तेज होती हैं यदि बच्चे को खाना नहीं दिया जाता। अक्सर हाथ चूसने और जड़ने के व्यवहार के साथ होती हैं।",
"A whiny, nasal cry that sounds weaker than a hunger cry, often accompanied by yawning and eye-rubbing." :	"एक चिढ़चिढ़ी, नासिका वाली चीख जो भूख की चीख से कमजोर लगती है, अक्सर जम्हाई लेने और आंखें रगड़ने के साथ होती है।",
"A sudden, high-pitched, intense cry that comes in bursts with breathing pauses. Often accompanied by physical tension." :	"एक अचानक, उच्च-पिच, तीव्र चीख जो सांस लेने के विराम के साथ फटने में आती है। अक्सर शारीरिक तनाव के साथ होती है।",
"A fussy, irritated cry that typically stops when the source of discomfort is addressed." :	"एक चिड़चिड़ी, परेशान करने वाली चीख जो आमतौर पर तब रुक जाती है जब असुविधा के स्रोत को संबोधित किया जाता है।",
"Prolonged, intense crying episodes, typically in the evening, with physical signs of distress." :	"लंबे, तीव्र रोने के एपिसोड, आमतौर पर शाम को, शारीरिक संकट के संकेतों के साथ।",
"A mild cry that starts softly and increases if ignored, often accompanied by eye contact and reaching out." :	"एक हल्की पुकार जो धीरे-धीरे शुरू होती है और अगर अनदेखा किया जाए तो बढ़ जाती है, अक्सर आंखों के संपर्क और हाथ बढ़ाने के साथ होती है।",
	
	
"Hunger cries are rhythmic, repetitive, and grow louder if the baby isn't fed." :	"भूख की चीखें लयबद्ध, दोहराई जाने वाली होती हैं, और यदि बच्चे को खाना नहीं दिया जाता है तो ये तेज होती जाती हैं।",
"Babies may also:" :	"बच्चे भी कर सकते हैं:",
"• Suck on hands or fingers" :	"• हाथों या उंगलियों को चूसना",
"• Smack lips, root (turn head searching for a nipple)" :	"• होंठों को चिपकाना, जड़ (निप्पल की तलाश में सिर घुमाना)",
"• Get fussy even after being comforted" :	"• सांत्वना मिलने के बाद भी चिड़चिड़ा होना",
	
	
"A whiny, nasal cry that may sound weaker than a hunger cry." :	"एक चिढ़चिढ़ी, नासिका वाली चीख जो भूख की चीख से कमजोर लग सकती है।",
"Babies may also:" :	"बच्चे भी कर सकते हैं:",
"• Yawn frequently" :	"• बार-बार जम्हाई लेना",
"• Rub their eyes or pull their ears" :	"• अपनी आँखें रगड़ें या अपने कान खींचें",
"• Become fussy and harder to soothe" :	"• नखरे करने वाले और शांत करने में कठिन हो जाएं",
	
	
"A sudden, high-pitched, intense cry that may come in bursts with pauses for breath." :	"एक अचानक, उच्च-पिच, तीव्र चीख जो सांस लेने के लिए रुकावटों के साथ फटने में आ सकती है।",
"Babies may also:" :	"बच्चे भी कर सकते हैं:",
"• Clench fists or arch their back" :	"• मुट्ठियाँ भींचना या अपनी पीठ को मोड़ना",
"• Become stiff or tense" :	"• कठोर या तनावग्रस्त हो जाना",
"• Show signs of discomfort (scrunched face, difficulty calming down)" :	"• असुविधा के संकेत दिखाएं (संकुचित चेहरा, शांत होने में कठिनाई)",
	
	
"A fussy, irritated cry that may stop when the issue is resolved." :	"एक चिड़चिड़ी, परेशान करने वाली चीख जो तब रुक सकती है जब समस्या का समाधान हो जाए।",
"Babies may also:" :	"बच्चे भी कर सकते हैं:",
"• Wiggle or squirm a lot" :	"• बहुत हिलना-डुलना या मचलना",
"• Tug at their clothing or ears" :	"• उनके कपड़ों या कानों को खींचें",
"• Appear restless or uneasy" :	"• बेचैन या असहज दिखाई देना",
	
	
"A prolonged, intense, high-pitched cry that often occurs in the evening." :	"एक लंबी, तीव्र, उच्च स्वर की चीख जो अक्सर शाम को होती है।",
"Babies may also:" :	"बच्चे भी कर सकते हैं:",
"• Clench fists, arch their back, or pull up legs" :	"• मुट्ठियाँ भींचें, अपनी पीठ को आर्च करें, या पैरों को ऊपर खींचें",
"• Have a tense, bloated belly" :	"• एक तनावपूर्ण, फूली हुई पेट हो",
"• Be difficult to soothe, even after feeding" :	"• खिलाने के बाद भी शांत करना मुश्किल हो।",
	
	
"A mild, whimpering cry that starts softly and gets louder if ignored." :	"एक हल्की, कराहती आवाज जो धीरे-धीरे शुरू होती है और अगर अनदेखा किया जाए तो louder हो जाती है।",
"Babies may also:" :	"बच्चे भी कर सकते हैं:",
"• Make eye contact while crying" :	"• रोते समय आंखों का संपर्क बनाएं",
"• Reach out for comfort" :	"• आराम के लिए संपर्क करें",
"• Stop crying quickly when picked up" :	"• उठाए जाने पर जल्दी रोना बंद करें",
	
	
"Feed Promptly – Responding early prevents excessive crying and makes feeding easier." :	"समय पर खिलाना - जल्दी प्रतिक्रिया देने से अत्यधिक रोने से बचा जा सकता है और खिलाना आसान हो जाता है।",
"Watch for Hunger Cues – Crying is a late sign; look for early signs like lip-smacking, rooting, sticking out tongue, or sucking on hands." :	"भूख के संकेतों पर ध्यान दें - रोना एक देर से संकेत है; होंठ चाटने, मुंह में उंगली डालने, जीभ बाहर निकालने या हाथ चूसने जैसे शुरुआती संकेतों की तलाश करें।",
"Ensure Proper Latch – If breastfeeding, ensure a deep latch to avoid discomfort." :	"सही लॅच सुनिश्चित करें - यदि आप स्तनपान करा रहे हैं, तो असुविधा से बचने के लिए गहरा लॅच सुनिश्चित करें।",
"Check Feeding Schedule – Newborns need feeding every 2-3 hours." :	"खुराक की जांच करें - नवजात शिशुओं को हर 2-3 घंटे में भोजन की आवश्यकता होती है।",
"Burp Baby After Feeding – Helps prevent gas and fussiness." :	"खाना खिलाने के बाद बच्चे को डकार दिलाना - गैस और चिड़चिड़ापन रोकने में मदद करता है।",
	
	
"Look for Sleep Cues Early – Yawning, zoning out, or rubbing eyes signal it's time to sleep." :	"नींद के संकेतों की जल्दी तलाश करें - जम्हाई लेना, ध्यान भटकाना, या आंखें रगड़ना यह संकेत देते हैं कि सोने का समय है।",
"Create a Calm Sleep Environment – Dim lights, reduce noise, and use white noise if needed." :	"एक शांत नींद का वातावरण बनाएं - रोशनी को मंद करें, शोर को कम करें, और यदि आवश्यक हो तो सफेद शोर का उपयोग करें।",
"Use Gentle Rocking – Motion, swaddling, or a pacifier can help." :	"नरम झूलने का उपयोग करें - गति, लपेटना, या एक चूसनी मदद कर सकते हैं।",
"Follow a Sleep Routine – A consistent bedtime routine helps babies recognize sleep time." :	"नींद की दिनचर्या का पालन करें - एक सुसंगत सोने की दिनचर्या शिशुओं को नींद के समय को पहचानने में मदद करती है।",
"Avoid Overstimulation – Too much activity before bed can make sleep harder." :	"अधिक उत्तेजना से बचें - बिस्तर से पहले बहुत अधिक गतिविधि नींद को कठिन बना सकती है।",
	
	
"Check for Obvious Issues – Look for diaper rash, teething pain, or tight clothing." :	"स्पष्ट समस्याओं की जांच करें - डायपर रैश, दांत निकलने का दर्द, या तंग कपड़ों की तलाश करें।",
"Soothe with Gentle Touch – Skin-to-skin contact or holding them close can help." :	"मुलायम स्पर्श से शांति दें - त्वचा से त्वचा का संपर्क या उन्हें करीब रखना मदद कर सकता है।",
"Try Pain Relief Techniques – For teething, offer a chilled teether; for gas, try tummy massage." :	"दर्द निवारण तकनीकों का प्रयास करें - दांत निकलने के लिए, एक ठंडी चबाने वाली चीज़ दें; गैस के लिए, पेट की मालिश करने का प्रयास करें।",
"Monitor for Fever or Illness – If crying persists with fever, vomiting, or lethargy, consult a doctor." :	"बुखार या बीमारी की निगरानी करें - यदि रोना बुखार, उल्टी या सुस्ती के साथ जारी रहता है, तो डॉक्टर से परामर्श करें।",
"Trust Your Instincts – If the baby seems in severe pain, seek medical advice immediately." :	"अपने अंतर्ज्ञान पर भरोसा करें - यदि बच्चे को गंभीर दर्द हो रहा है, तो तुरंत चिकित्सा सलाह लें।",
	
	
"Check the Diaper – A wet or soiled diaper is a common cause of discomfort." :	"डायपर की जांच करें - गीला या गंदा डायपर असुविधा का एक सामान्य कारण है।",
"Ensure Comfortable Clothing – Dress baby in breathable, soft fabrics and check for tight clothing." :	"आरामदायक कपड़े सुनिश्चित करें - बच्चे को सांस लेने योग्य, मुलायम कपड़ों में पहनाएं और तंग कपड़ों की जांच करें।",
"Adjust Temperature – Feel baby's neck/back to see if they are too hot or cold." :	"तापमान समायोजित करें - देखें कि क्या बच्चे का गला/पीठ बहुत गर्म या ठंडा है।",
"Check for External Irritants – Tags, rough fabric, or hair wrapped around fingers/toes can cause irritation." :	"बाहरी उत्तेजक तत्वों की जांच करें - टैग, खुरदरी कपड़ा, या उंगलियों/पैरों के चारों ओर लिपटी हुई बाल जलन पैदा कर सकते हैं।",
"Reposition Baby – Changing positions or holding them differently can sometimes help." :	"बेबी को फिर से स्थिति में लाना - स्थिति बदलना या उन्हें अलग तरीके से पकड़ना कभी-कभी मदद कर सकता है।",
	
	
"Use Gentle Motions – Rocking, swaying, or holding baby in a 'colic carry' (on their tummy along your forearm) can help." :	"नरम गति का उपयोग करें - झूलना, लहराना, या बच्चे को 'कोलिक कैरी' (उनकी पेट के बल आपके अग्रभुज पर) में पकड़ना मदद कर सकता है।",
"Try White Noise – Rhythmic sounds, like a fan or heartbeat sound, can be soothing." :	"व्हाइट नॉइज़ आज़माएँ - तालबद्ध ध्वनियाँ, जैसे पंखा या दिल की धड़कन की आवाज़, सुखदायक हो सकती हैं।",
"Burp Baby Well – Gas buildup can make colic worse. Burp frequently during feeds." :	"बर्प बेबी वेल - गैस का संचय कोलिक को और खराब कर सकता है। फीडिंग के दौरान बार-बार बर्प करें।",
"Massage the Tummy – A gentle circular tummy massage can relieve gas." :	"पेट की मालिश करें - एक हल्की गोलाकार पेट की मालिश गैस को कम कर सकती है।",
"Consult a Pediatrician – If colic persists, discuss options like probiotic drops or diet changes (for breastfeeding moms)." :	"बाल रोग विशेषज्ञ से परामर्श करें - यदि पेट दर्द जारी रहता है, तो प्रोबायोटिक ड्रॉप्स या आहार में बदलाव (स्तनपान कराने वाली माताओं के लिए) जैसे विकल्पों पर चर्चा करें।",
	
	
"Respond with Reassurance – Holding, talking, or making eye contact helps babies feel secure." :	"आत्मविश्वास के साथ प्रतिक्रिया दें - पकड़ना, बात करना या आंखों में संपर्क बनाना बच्चों को सुरक्षित महसूस करने में मदद करता है।",
"Try Gentle Touch – A cuddle or soft pat on the back can be calming." :	"कोमल स्पर्श का प्रयास करें - एक आलिंगन या पीठ पर हल्का थपकी देना शांत करने वाला हो सकता है।",
"Engage with Soothing Sounds – Humming or talking in a calm voice can reassure the baby." :	"सुखद ध्वनियों के साथ जुड़ें - मधुर गुनगुनाना या शांत आवाज में बात करना बच्चे को आश्वस्त कर सकता है।",
"Encourage Independent Comforting – Allow baby to self-soothe briefly before immediately responding." :	"स्वतंत्र सांत्वना को प्रोत्साहित करें - बच्चे को तुरंत प्रतिक्रिया देने से पहले थोड़ी देर के लिए आत्म-सांत्वना करने दें।",
"Maintain a Balance – Meeting attention needs is important, but consistency in response helps babies learn security." :	"संतुलन बनाए रखें - ध्यान की आवश्यकताओं को पूरा करना महत्वपूर्ण है, लेकिन प्रतिक्रिया में निरंतरता बच्चों को सुरक्षा सीखने में मदद करती है।",

"Cry History":"रोने का इतिहास",
"Record" :"अभिलेख",


"Cry History"	:	"रोने का इतिहास",
"Record"	:	"रिकॉर्ड",
"Allocry"	:	"एलोक्राई",
"Baby can cry due to"	:	"बच्चा रो सकता है क्योंकि",
"Recording"	:	"रिकॉर्डिंग",
"Start Recording"	:	"रिकॉर्डिंग शुरू करें",
"Getting Your Baby Sound…"	:	"अपने बच्चे को आवाज़ में लाना...",
"Try to avoid background noise"	:	"पृष्ठभूमि के शोर से बचने की कोशिश करें",
"High-pitched, intense crying often indicates pain or immediate needs."	:	"उच्च स्वर, तीव्र रोना अक्सर दर्द या तत्काल आवश्यकताओं का संकेत देता है।",
"Rhythmic crying that gets louder and softer might mean your baby is tired."	:	"लयबद्ध रोना जो तेज और धीमा होता है, इसका मतलब हो सकता है कि आपका बच्चा थका हुआ है।",
"Short, low-pitched cries repeated every few seconds usually signal hunger."	:	"छोटी, नीची आवाज़ में की गई चीखें जो हर कुछ सेकंड में दोहराई जाती हैं, आमतौर पर भूख का संकेत देती हैं।",
"Whimpering or whining sounds might indicate mild discomfort or wanting attention."	:	"कुड़कुड़ाने या कराहने की आवाजें हल्की असुविधा या ध्यान चाहने का संकेत दे सकती हैं।",
"Long, high-pitched screams could be signs of colic or stomach pain."	:	"लंबी, ऊँची आवाज़ की चीखें कोलिक या पेट दर्द के संकेत हो सकती हैं।",
"Sudden, sharp cries might mean your baby is too hot or cold."	:	"अचानक, तेज़ चीखें यह संकेत कर सकती हैं कि आपका बच्चा बहुत गर्म या बहुत ठंडा है।",
"Persistent crying with leg movement often indicates diaper change needs."	:	"लगातार रोना और पैर हिलाना अक्सर डायपर बदलने की आवश्यकता को दर्शाता है।",
"Baby Cry Not Detected"	:	"बच्चे का रोना नहीं पाया गया",

};



