final Map<String, String> hi = {
  //registersation screen

  "Helps you to consult patient Virtually":
      "वस्तुत रोगी से परामर्श करने में आपकी सहायता करता है",
  "Engage with patient through video and audio":
      "वीडियो और ऑडियो के माध्यम से रोगी से जुड़ें",
  "Keeps on track your patient Health":
      "अपने मरीज के स्वास्थ्य पर नज़र रखता है",
  "Username": "उपयोगकर्ता नाम",
  "password": "पासवर्ड",
  "CONTINUE": "पासवर्ड",
  "By continuing, You agree that you have read and accept our T&C and Privacy Policy":
      "जारी रखकर, आप सहमत हैं कि आपने हमारी नियम एवं शर्तें और गोपनीयता नीति को पढ़ लिया है और स्वीकार कर लिया है",
  "LoggedIn Successfully": "सफलतापूर्वक लॉग इन हो चुका है",
  "Invalid Credential": "अमान्य क्रेडेंशियल",

//Home Screen

  "AlloLab": "एलोलैब",
  "Welcome savemom": "स्वागत है सेवमॉम",
  "Worker ID": "कार्यकर्ता आईडी",
  "Recently Added Patient": "हाल ही में जोड़ा गया रोगी",
  "Mobile No:": "मोबाइल नहीं है:",
  "Start Screening": "स्क्रीनिंग शुरू करें",
  "Select Language": "भाषा चुने",
  "English": "अंग्रेज़ी",
  "Tamil": "तमिल",
  "Hindi": "हिन्दी",
  "Face Recognition": "चेहरा पहचान",
  "Start Screening with Face Recongnition":
      "चेहरे की पहचान के साथ स्क्रीनिंग शुरू करें",
  "CAPTURE": "कब्जा",
  "User Not Found": "उपयोगकर्ता नहीं मिला",
  "Search with Phone Number": "फ़ोन नंबर से खोजें",
  "Enter Phone Number": "फोन नंबर दर्ज",
  "Add New Patient": "नया रोगी जोड़ें",
  "Add Patient to Start Screening":
      "स्क्रीनिंग शुरू करने के लिए रोगी को जोड़ें",
  "Personal Details": "व्यक्तिगत विवरण",
  "Capture Image": "छवि कैप्चर करें",
  "Name": "नाम",
  "EmailID": "ईमेल आईडी",
  "Phone Number": "फ़ोन नंबर",
  "Gender": "लिंग",
  "Male": "पुरुष",
  "Female": "महिला",
  "Blood Group": "रक्त समूह",
  "Date of Birth": "जन्म की तारीख",
  "Age": "उम्र",
  "OK": "ठीक है",
  "CANCEL": "रद्द करना",
  "Address Details": "पते का विवरण",
  "AddressLine": "पता पंक्ति",
  "Pincode": "पिन कोड",
  "City": "शहर",
  "State": "राज्य",
  "Enter Correct Pincode": "सही पिनकोड दर्ज करें",
  "Patient Name": "रोगी का नाम",
  "Checkup Details": "चेकअप विवरण",
  "Appointment": "मुलाकात",
  "Book an Appointment": "एक अपॉइंटमेंट बुक करें",
  "Select Doctor": "डॉक्टर का चयन करें",
  "Appointment Date": "मिलने की तारीख",
  "View Available Slots": "उपलब्ध स्लॉट देखें",
  "No Slot Selected": "कोई स्लॉट नहीं चुना गया",
  "Diagnosis Desc": "निदान विवरण",
  "Book": "पुस्तक",
  "Appointment Book Successfully": "नियुक्ति पुस्तक सफलतापूर्वक",
  "CheckUp": "जांच",
  "No CheckUp found": "कोई चेकअप नहीं मिला",
  "Today": "आज",
  "No available slot for selected date":
      "चयनित तिथि के लिए कोई स्लॉट उपलब्ध नहीं है",
  "View appointment": "अपॉइंटमेंट देखें",
  "completed": "पूरा किया हुआ",
  "Appointments": "नियुक्तियाँ",
  "Upcoming": "आगामी",
  "Date": "दिनांक",
  "Time": "समय",
  "Status": "स्थिति",
  "View Appointment": "अपॉइंटमेंट देखें",
  "Cancel Appointment": "अपॉइंटमेंट रद्द करें",
  "Add Symptoms and Vitals": "लक्षण और महत्वपूर्ण जोड़ें",
  "Select Symptoms": "लक्षण चुनें",
  "Body Pain": "बदन दर्द",
  "Burning Stomach": "जलता हुआ पेट",
  "Cold Cough": "ठंड खांसी",
  "Dizziness": "चक्कर आना",
  "Headache": "सिरदर्द",
  "Vomiting": "उल्टी करना",
  "NEXT": "अगला",
  "Vitals": "महत्वपूर्ण",
  "Blood Pressue": "रक्तचाप",
  "Temperature": "तापमान",
  "Blood Saturation": "रक्त संतृप्ति",
  "Heart Rate": "हृदय दर",
  "Blood Glucose": "रक्त द्राक्ष - शर्करा",
  "BMI": "बीएमआई",
  "Respiratory Rate": "श्वसन दर",
  "HRV": "एचआरवी",
  "BACK": "पीछे",
  "SAVE": "सहेजें",
  "CheckUp Added Sucessfully": "चेकअप सफलतापूर्वक जोड़ा गया",
  "CheckUp completed": "चेकअप पूरा हुआ",
  "COMPLETED": "पूरा किया हुआ",
  "Appointment Status": "नियुक्ति की स्थिति",
  "Doctor Name": "डॉक्टर का नाम",
  "Health Status": "स्वास्थ्य की स्थिति",
  "NORMAL": "सामान्य",
  "Case Summary": "केस सारांश",
  "Prescription": "पर्चे",
  "Tablets": "गोलियाँ",
  "Units": "इकाइयों",
  "Timing": "समय",
  "Requested lab supported": "अनुरोधित लैब समर्थित",
  "Next Appointment Date": "अगली नियुक्ति तिथि",
  "Next Appointment Time": "अगली नियुक्ति समय",
  "Symptoms": "लक्षण",
  "Are you sure to cancel the appointment?":
      "क्या आप निश्चित रूप से अपॉइंटमेंट रद्द करना चाहते हैं?",
  "Screening": "स्क्रीनिंग",
  "Go to Screening": "स्क्रीनिंग पर जाएं",
  "Reports": "रिपोर्ट",
  "Report Details": "रिपोर्ट विवरण",
  "Report": "प्रतिवेदन",
  "SCAN AND ADD NEW REPORT": "स्कैन करें और नई रिपोर्ट जोड़ें",
  "Click Add Images Button": "छवियां जोड़ें बटन पर क्लिक करें",
  "NO IMAGE": "कोई तस्वीर नहीं",
  "No Report Added": "कोई रिपोर्ट नहीं जोड़ी गई",
  "ADD IMAGE": "छवि जोड़ें",
  "Choose Photo from :": "से फोटो चुनें:",
  "Type of Report": "रिपोर्ट का प्रकार",
  "Write Description": "विवरण लिखें",
  "ADD REPORT": "रिपोर्ट जोड़ें",
  "Report Added Successfully": "रिपोर्ट सफलतापूर्वक जोड़ी गई",
  "Report Deleted Successfully": "रिपोर्ट सफलतापूर्वक हटाई गई",
  "Report Date": "रिपोर्ट तिथि",
  "Report Time": "रिपोर्ट समय",
  "Report Desc": "रिपोर्ट विवरण",
  "UPDATE IMAGE": "अद्यतन छवि",
  "DELETE REPORT": "रिपोर्ट हटाएं",
  "UPDATE REPORT": "अपडेट रिपोर्ट",
  "Report Updated Successfully": "रिपोर्ट सफलतापूर्वक अपडेट की गई",
  "Education": "शिक्षा",
  "Knowledge Transfer": "ज्ञान स्थानांतरण",
  "Sorry No Awareness Post Found": "क्षमा करें कोई जागरूकता पोस्ट नहीं मिला",
  "Patient List": "रोगी सूची",
  "Search Patient By Name": "नाम से रोगी खोजें",

//Chat screen

  "Chat": "चैट",
  "DOCTORS": "डॉक्टर",
  "NURSE": "नर्स",
  "Type a message": "एक संदेश लिखें",
  "View Case Details": "केस विवरण देखें",

//Settings Screen

  "Settings": "समायोजन",
  "Worker ID": "कार्यकर्ता आईडी",
  "General Details": "सामान्य विवरण",
  "Name": "नाम",
  "Year of Experience": "अनुभव का वर्ष",
  "Title": "शीर्षक",
  "Address Details": "पते का विवरण",
  "Address": "पता",
  "Pincode": "पिन कोड",
  "Edit Profile": "प्रोफ़ाइल संपादित करें",
  "Notification": "अधिसूचना",
  "ON": "पर",
  "OFF": "बंद",
  "Terms & Conditions": "नियम एवं शर्तें",
  "Privacy Policy": "गोपनीयता नीति",
  "Help": "मदद",
  "Contact Us": "संपर्क करें",
  "Tell us what's going on": "हमें बताओ क्या हो रहा है",
  "Tell us why you're reaching us":
      "हमें बताएं कि आप हम तक क्यों पहुंच रहे हैं",
  "Something not Working": "कुछ काम नहीं कर रहा",
  "Feature Request": "महत्वपूर्ण लेख मांगना",
  "Question": "प्रश्न",
  "FeedBack": "प्रतिक्रिया",
  "How do you feel? (Optional)": "आप कैसा महसूस कर रहे हैं? (वैकल्पिक)",
  "SEND": "भेजना",
  "App Info": "अनुप्रयोग की जानकारी",
  "Log out": "लॉग आउट",
  "Are you sure to log out?": "क्या आप निश्चित रूप से लॉग आउट करना चाहते हैं?",
  "No": "नहीं",
  "Yes": "हां",

  'Select Language': 'भाषा चुनें',
  'T&C and Privacy Policy': 'नियम एवं शर्तें एवं गोपनीयता नीति',
  'By continuing, You agree that you have read and accept our': 'जारी रखते हुए, आप सहमत हैं कि आपने हमारा पढ़ा है और स्वीकार किया है',
  'Personalised Pregnancy Care': 'वैयक्तिकृत गर्भावस्था देखभाल',
  'Helps you to consult Doctor Virtually': 'आपको वर्चुअली डॉक्टर से परामर्श लेने में मदद करता है',
  'Engage with Doctor through video and audio': 'वीडियो और ऑडियो के माध्यम से डॉक्टर से जुड़ें',
  'Pregnancy health tips': 'गर्भावस्था स्वास्थ्य युक्तियाँ',
  'Nutrition advice': 'पोषण संबंधी सलाह',
  'Baby care basics': 'शिशु देखभाल की मूल बातें',
  'Trimester milestones': 'त्रैमासिक मील के पत्थर',
  'Your conversation will appear here...': 'आपकी बातचीत यहां दिखाई देगी...',
  'How do you feel today?': 'आज आप कैसा महसूस कर रहे हैं?',
  'Allobot': 'एलोबोट',
  'Your Maternal AI Assistant': 'आपका मातृ AI सहायक',
  'Welcome to Allobot!': 'एलोबोट में आपका स्वागत है!',
  'I`m here to support you through your maternal journey. Ask me anything about pregnancy, childbirth, or early motherhood.': 'मैं आपकी मातृ यात्रा में आपका समर्थन करने के लिए यहां हूं। मुझसे गर्भावस्था, प्रसव, या शीघ्र मातृत्व के बारे में कुछ भी पूछें।',
  'What You Can Ask Me:': 'आप मुझसे क्या पूछ सकते हैं:',
  'Incoming Call': 'एक फोन आ रहा है',
  'Waiting': 'इंतज़ार में',
  'Choose photo from :': 'से फोटो चुनें',
  'Online': 'ऑनलाइन',
  'Connect with Doctor': 'डॉक्टर से जुड़ें',
  'Connect with Health worker': 'स्वास्थ्य कार्यकर्ता से जुड़ें',
  'Get Connected with doctors': 'डॉक्टरों से जुड़ें',
  'Sorry No Awareness Post': 'क्षमा करें कोई जागरूकता पोस्ट नहीं',
  'Checkup Details': 'चेकअप विवरण',
  'Checkup Completed': 'चेकअप पूरा हुआ',
  'Waiting for Doctor Feedback': 'डॉक्टर की प्रतिक्रिया का इंतजार कर रहे हैं',
  'Checkup need to be done': 'चेकअप किया जाना चाहिए',
  'Checkup': 'चेकअप',
  'No Checkup Found': 'कोई चेकअप नहीं मिला',
  'Doctor Name': 'डॉक्टर का नाम',
  'Date:': 'तारीख',
  'Health Status:': 'स्वास्थ्य स्थिति',
  'Case Summary': 'मामला सारांश',
  'Prescription': 'नुस्खा',
  'Tablets': 'टैबलेट्स',
  'Units': 'इकाइयाँ',
  'Timing': 'समय',
  'Morning': 'सुबह',
  'Night': 'रात',
  'Requested lab supported': 'अनुरोधित लैब समर्थित',
  'Next Appointment Time': 'अगली अपॉइंटमेंट का समय',
  'Symptoms': 'लक्षण',
  'Vitals': 'महत्वपूर्ण संकेत',
  'ECG': 'ECG',
  'Blood Test': 'रक्त परीक्षण',
  'HCG': 'HCG',
  'Lab Test': 'लैब टेस्ट',
  'X-Ray': 'एक्स-रे',
  'Ultrasound Scan': 'अल्ट्रासाउंड स्कैन',
  'CT Scan': 'सीटी स्कैन',
  'Mammogram': 'मैमोग्राम',
  'MRI': 'MRI',
  'Others': 'अन्य',
  'Please add an image': 'कृपया एक चित्र जोड़ें',
  'Please select prescription type': 'कृपया नुस्खे का प्रकार चुनें',
  'Error': 'त्रुटि',
  'Add Prescription': 'नुस्खा जोड़ें',
  'Scan and Add new Prescription': 'नया नुस्खा स्कैन करें और जोड़ें',
  'No prescriptions found.': 'कोई नुस्खा नहीं मिला।',
  'View Prescription': 'नुस्खा देखें',
  'Prescription Type': 'नुस्खे का प्रकार',
  'Date Added': 'जोड़ने की तारीख',
  'Description': 'विवरण',
  'No description available': 'कोई विवरण उपलब्ध नहीं है',
  'Error loading image': 'चित्र लोड करने में त्रुटि',
  'Please enter Description': 'कृपया विवरण दर्ज करें',
  'Write Description': 'विवरण लिखें',
  'ADD REPORT': 'रिपोर्ट जोड़ें',
  'Add Report': 'रिपोर्ट जोड़ें',
  'NO IMAGE': 'कोई चित्र नहीं',
  'Report': 'रिपोर्ट',
  'Scan and Add new Report': 'नयी रिपोर्ट स्कैन करें और जोड़ें',
  'No reports found': 'कोई रिपोर्ट नहीं मिली',
  'Report Details': 'रिपोर्ट विवरण',
  'Unknown Report Type': 'अज्ञात रिपोर्ट प्रकार',
  'Test Results': 'परीक्षण परिणाम',
  'Delete Report': 'रिपोर्ट हटाएं',
  'Are you sure you want to delete this report?': 'क्या आप सच में इस रिपोर्ट को हटाना चाहते हैं?',
  'CANCEL': 'रद्द करें',
  'DELETE': 'हटाएं',
  'Hemoglobin Test': 'हीमोग्लोबिन परीक्षण',
  'Easily get your Reading by Performing the scans below': 'नीचे दिए गए स्कैन करके आसानी से अपना रीडिंग प्राप्त करें',
  'Fetal Monitoring': 'गर्भस्थ शिशु की निगरानी',
  'Click Add Image Button': 'चित्र जोड़ने वाले बटन पर क्लिक करें',
  'Upload Report': 'रिपोर्ट अपलोड करें',
  'Heart Rate': 'हृदय गति',
  'BPM': 'BPM',
  'Kick Count :': 'लात गिनती',
  'Tap to Increase the Count.': 'गिनती बढ़ाने के लिए टैप करें।',
  'Tap to Change': 'बदलने के लिए टैप करें',
  'Blood Glucose Value': 'ब्लड शुगर वैल्यू',
  'Add Glucose Report': 'ग्लूकोज रिपोर्ट जोड़ें',
  'Add Hemoglobin Report': 'हीमोग्लोबिन रिपोर्ट जोड़ें',
  'Fetal Presentation': 'गर्भस्थ शिशु की स्थिति',
  'Alpamine Present': 'अल्पामाइन वर्तमान',
  'Add Urine Test Report': 'मूत्र परीक्षण रिपोर्ट जोड़ें',
  'Vital Test': 'महत्वपूर्ण परीक्षण',
  'Urine Test': 'मूत्र परीक्षण',
  'Glucose Test': 'ग्लूकोज परीक्षण',
  'Ultrasound Test': 'अल्ट्रासाउंड परीक्षण',
  'Self Screening': 'स्व-स्क्रीनिंग',
  'Let\'s begin the test': 'आइए, हम परीक्षण शुरू करते हैं',
  'Fasting': 'उपवास',
  'At rest': 'विश्राम की स्थिति में',
  'After Walk': 'चलने के बाद',
};
