final Map<String, String> ka = {
    "Select Language": "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    "Enter Mobile Number": "ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
    "SEND OTP": "OTP ಕಳುಹಿಸಿ",
    "How do you feel today ?": "ನೀವು ಇಂದು ಹೇಗಿದ್ದೀರಿ?",
    "Online": "ಆನ್ಲೈನ್",
    "Offline": "ಆಫ್‌ಲೈನ್",
    "Image Uploaded": "ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಲಾಗಿದೆ",
    "Type a message": "ಸಂದೇಶವನ್ನು ಟೈಪ್ ಮಾಡಿ",
    "Choose photo from :": "ಇಂದಿನಿಂದ ಫೋಟೋ ಆಯ್ಕೆಮಾಡಿ:",
    "Get Connected with doctors": "ವೈದ್ಯರೊಂದಿಗೆ ಸಂಪರ್ಕಿಸಿರಿ",
    "Connect with Doctor": "ವೈದ್ಯರೊಂದಿಗೆ ಸಂಪರ್ಕಿಸಿ",
    "Connect with Health worker": "ಆರೋಗ್ಯ ಕಾರ್ಯಕರ್ತರೊಂದಿಗೆ ಸಂಪರ್ಕಿಸಿ",
    "Connect with AlloBot": "AlloBot ಜೊತೆಗೆ ಸಂಪರ್ಕಿಸಿ",
    "Sorry No Awareness Post": "ಕ್ಷಮಿಸಿ ಜಾಗೃತಿ ಪೋಷ್ಟ್ ಇಲ್ಲ",
    "Checkup Completed": "ಪರಿಶೀಲನೆ ಮುಗಿದಿದೆ",
    "Waiting for Doctor Feedback": "ವೈದ್ಯರ ಪ್ರತಿಕ್ರಿಯೆಗೆ ಕಾಯುತ್ತಿದೆ",
    "Checkup need to be done": "ಪರಿಶೀಲನೆ ಮಾಡಬೇಕಾಗಿದೆ",
    "Checkup": "ಪರಿಶೀಲನೆ",
    "No Checkup Found": "ಯಾವುದೇ ಪರಿಶೀಲನೆ ಕಂಡುಬಂದಿಲ್ಲ",
    "Checkup Details": "ಪರಿಶೀಲನೆ ವಿವರಗಳು",
    "Doctor Name": "ವೈದ್ಯರ ಹೆಸರು",
    "Date:": "ದಿನಾಂಕ:",
    "Health Status:": "ಆರೋಗ್ಯ ಸ್ಥಿತಿ:",
    "Case Summary": "ಸಂದರ್ಭ ಸಮರಾಸ",
    "Prescription": "ಔಷಧ ನೋಟ",
    "Next Appointment Time": "ಮುಂದಿನ ಭೇಟಿಯ ಸಮಯ",
    "Symptoms": "ಲಕ್ಷಣಗಳು",
    "Vitals": "ಜೀವನಾಂಶಗಳು",
    "Add Prescription": "ಔಷಧ ನೋಟವನ್ನು ಸೇರಿಸಿ",
    "ADD PRESCRIPTION": "ಔಷಧ ನೋಟವನ್ನು ಸೇರಿಸಿ",
    "Click to Add Image": "ಚಿತ್ರವನ್ನು ಸೇರಿಸಲು ಕ್ಲಿಕ್ ಮಾಡಿ",
    "View Prescription": "ಔಷಧ ನೋಟವನ್ನು ನೋಡಿ",
    "Error loading image": "ಚಿತ್ರ ಲೋಡ್ ಮಾಡುವಲ್ಲಿ ದೋಷ",
    "Prescription Type": "ಔಷಧ ನೋಟದ ಪ್ರಕಾರ",
    "Date Added": "ಸೇರಿಸಿದ ದಿನಾಂಕ",
    "Description": "ವಿವರಣೆ",
    "Add Report": "ವರದಿಯನ್ನು ಸೇರಿಸಿ",
    "NO IMAGE": "ಚಿತ್ರವಿಲ್ಲ",
    "Click Add Image Button": "ಚಿತ್ರವನ್ನು ಸೇರಿಸಲು ಬಟನ್ ಕ್ಲಿಕ್ ಮಾಡಿ",
    "ADD IMAGE": "ಚಿತ್ರವನ್ನು ಸೇರಿಸಿ",
    "ADD REPORT": "ವರದಿಯನ್ನು ಸೇರಿಸಿ",
    "Report": "ವರದಿ",
    "Scan and Add new Report": "ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ಮತ್ತು ಹೊಸ ವರದಿಯನ್ನು ಸೇರಿಸಿ",
    "Self Screening": "ಸ್ವಯಂ ತಪಾಸಣೆ",
    "BACK": "ಹಿಂದೆ",
    "NEXT": "ಮುಂದೆ",
    "Finish": "ಮುಗಿಸಿ",
    "Summary Report": "ಸಂಗ್ರಹ ವರದಿ",
    "Submit": "ಸಲ್ಲಿಸು",
    "Let's begin the test": "ಪರೀಕ್ಷೆಯನ್ನು ಪ್ರಾರಂಭಿಸೋಣ",
    "Hemoglobin Test": "ಹಿಮೋಗ್ಲೋಬಿನ್ ಪರೀಕ್ಷೆ",
    "Easily get your Reading by Performing the scans below": "ಕೆಳಗಿನ ಸ್ಕ್ಯಾನ್‌ಗಳನ್ನು ಮಾಡಿ ನಿಮ್ಮ ಓದುವಿಕೆಯನ್ನು ಸುಲಭವಾಗಿ ಪಡೆಯಿರಿ",
    "Fetal Monitoring": "ಭ್ರೂಣದ ಮೇಲ್ವಿಚಾರಣೆ",
    "Upload Report": "ವರದಿಯನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    "Tap to Change": "ಬದಲಿಸಲು ಟ್ಯಾಪ್ ಮಾಡಿ",
    "Heart Rate": "ಹೃದಯದ ಓಟ",
    "BPM": "ಬಿಪಿಎಮ್",
    "Kick Count": "ಉದೆ ಎಣಿಕೆ",
    "Tap to Increase the Count": "ಎಣಿಕೆಯನ್ನು ಹೆಚ್ಚಿಸಲು ಟ್ಯಾಪ್ ಮಾಡಿ",
    "Add Glucose Report": "ಗ್ಲೂಕೋಸ್ ವರದಿಯನ್ನು ಸೇರಿಸಿ",
    "Blood Glucose Value": "ರಕ್ತ ಗ್ಲೂಕೋಸ್ ಮೌಲ್ಯ",
    "Add Hemoglobin Report": "ಹಿಮೋಗ್ಲೋಬಿನ್ ವರದಿಯನ್ನು ಸೇರಿಸಿ",
    "Hemoglobin Value": "ಹಿಮೋಗ್ಲೋಬಿನ್ ಮೌಲ್ಯ",
    "Ultra Sound": "ಅಲ್ಟ್ರಾಸೌಂಡ್",
    "Fasting": "ಉಪವಾಸ",
    "At rest": "ವಿಶ್ರಾಂತಿಯಲ್ಲಿ",
    "After Walk": "ನಡೆಯಲು ನಂತರ",
    "Select Height": "ಎತ್ತರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    "Select Weight": "ತೂಕವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    "After walk": "ನಡೆಯಲು ನಂತರ",
    "Address Information": "ವಿಳಾಸ ಮಾಹಿತಿ",
    "Search": "ಹುಡುಕು",
    "Continue": "ಮುಂದುವರಿಸಿ",
    "Phone Number": "ಫೋನ್ ಸಂಖ್ಯೆ",
    "Profile Details": "ಪ್ರೊಫೈಲ್ ವಿವರಗಳು",
    "Gender": "ಲಿಂಗ",
    "Male": "ಪುರುಷ",
    "Female": "ಸ್ತ್ರೀ",
    "Select Blood Group": "ರಕ್ತದ ಗುಂಪನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    "Select Last cycle Date": "ಕೊನೆಯ ಚಕ್ರದ ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ",
    "Are you my mom or dad?": "ನೀವು ನನ್ನ ಅಮ್ಮ ಅಥವಾ ಅಪ್ಪ?",
    "Dad": "ಅಪ್ಪ",
    "Mom": "ಅಮ್ಮ",
    "Enter your Partner Details": "ನಿಮ್ಮ ಜೊತೆಯವರ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ",
    "Pregnancy Status": "ಗರ್ಭಿಣಿ ಸ್ಥಿತಿ",
    "Partner Pregnancy Status": "ಸಹೋದರ ಗರ್ಭಿಣಿ ಸ್ಥಿತಿ",
    "Average Length of Cycles": "ಚಕ್ರಗಳ ಸರಾಸರಿ ಉದ್ದ",
    "Day": "ದಿನ",
    "Not yet started": "ಇನ್ನೂ ಪ್ರಾರಂಭವಾಗಿಲ್ಲ",
    "NORMAL": "ಸಾಮಾನ್ಯ",
    "Health Status": "ಆರೋಗ್ಯ ಸ್ಥಿತಿ",
    "Last Screened": "ಕೊನೆಯ ಬಾರಿಗೆ ತಪಾಸಿಸಲಾಯಿತು",
    "GOLD": "ಚಿನ್ನ",
    "Subscription Plan": "ಚಂದಾ ಯೋಜನೆ",
    "No News Feed": "ಯಾವುದೇ ಸುದ್ದಿಗಳ ಪೋಷಣೆ ಇಲ್ಲ",
    "Probable Reason": "ಶಕ್ಯತೆಯ ಕಾರಣ",
    "Recommendations": "ಶಿಫಾರಸುಗಳು",
    "Hi!": "ಹಲೋ!",
    "How do you feel today?": "ನೀವು ಇಂದು ಹೇಗಿದ್ದೀರಿ?",
    "Select Exercise that have you done today?": "ನೀವು ಇಂದು ಮಾಡಿದ ವ್ಯಾಯಾಮವನ್ನು ಆಯ್ಕೆಮಾಡಿ?",
    "None": "ಯಾವುದೂ ಇಲ್ಲ",
    "Select tablets that you have taken": "ನೀವು ತೆಗೆದುಕೊಂಡ ಗುಳಿಕೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    "Sleep Duration": "ನಿದ್ರಾ ಅವಧಿ",
    "Do you have any of these Symptoms?": "ಈ ಲಕ್ಷಣಗಳಲ್ಲಿ ಯಾವುದಾದರೂ ನಿಮ್ಮಲ್ಲಿದೆಯೆ?",
    "Baby Voice is Recording": "ಹಸುಗೂಸಿನ ಧ್ವನಿ ದಾಖಲಾಗುತ್ತಿದೆ",
    "STOP": "ನಿಲ್ಲಿಸಿ",
    "Click the Record Button to Start Recording": "ದಾಖಲು ಪ್ರಾರಂಭಿಸಲು ರೆಕಾರ್ಡ್ ಬಟನ್ ಕ್ಲಿಕ್ ಮಾಡಿ",
    "Record": "ದಾಖಲೆ",
    "How many Glass of water have you drunk today?": "ನೀವು ಇಂದು ಎಷ್ಟು ಗ್ಲಾಸ್ ನೀರನ್ನು ಕುಡಿದಿದ್ದೀರಿ?",
    "OTP Verification": "OTP ಪರಿಶೀಲನೆ",
    "Enter OTP sent to": "OTP ಅನ್ನು ನಮೂದಿಸಿ",
    "Verify and proceed": "ಪರಿಶೀಲಿಸಿ ಮುಂದುವರಿಸಿ",
    "Appointment": "ಕರೆ",
    "Select Hospital": "ಆಸ್ಪತ್ರೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    "Select Doctor": "ವೈದ್ಯರನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    "Appointment Date": "ಸಮಯದ ದಿನಾಂಕ",
    "Available slots": "ಲಭ್ಯವಿರುವ ಸ್ಲಾಟ್ಸ್",
    "No Slots Available": "ಲಭ್ಯವಿರುವ ಸ್ಲಾಟ್ಸ್ ಇಲ್ಲ",
    "View Available Slots": "ಲಭ್ಯವಿರುವ ಸ್ಲಾಟ್ಸ್ ಅನ್ನು ನೋಡಿ",
    "Start time Slot:": "ಪ್ರಾರಂಭ ಸಮಯ:",
    "Diagnosis Description": "ರೋಗದ ವಿವರಣೆ",
    "Book": "ಬುಕಿಂಗ್",
    "Update": "ನವೀಕರಿಸಿ",
    "Respiratory Rate": "ಶ್ವಾಸದ ಪ್ರಮಾಣ",
    "Appointments": "ಆಯ್ಕೆ",
    "As a companion in your pregnancy we help you with the following": "ನಿಮ್ಮ ಗರ್ಭಕಾಲದ ಬಗ್ಗೆಯೂ ಅನುಸರಿಸುವಲ್ಲಿ ಸಹಾಯ",
    "Book An Appointment": "ಭೇಟಿಯನ್ನು ಬುಕಿಂಗ್ ಮಾಡಿ",
    "Pregnancy Monitoring": "ಗರ್ಭಪಾತದ ನಿರ್ವಹಣೆ",
    "Help Line": "ಸಹಾಯ ಲೈನ್",
"Current Appointment": "ಪ್ರಸ್ತುತ ಭೇಟಿಗೆ",
"No Upcoming Appointments": "ಮುಂಬರುವ ಭೇಟಿಗಳು ಇಲ್ಲ",
"Time": "ಸಮಯ",
"Status": "ಸ್ಥಿತಿ",
"Reason": "ಕಾರಣ",
"Cancel Appointment": "ಬೇಟಿಯನ್ನು ರದ್ದುಗೊಳಿಸಿ",
"Show Appointment": "ಬೇಟಿಯನ್ನು ತೋರಿಸಿ",
"My Appointments": "ನನ್ನ ಭೇಟಿಗಳು",
"Appointment Status": "ಬೇಟಿ ಸ್ಥಿತಿ",
"App Info": "ಆಪ್ ಮಾಹಿತಿ",
"CHECK FOR UPDATES": "ನವೀಕರಣಗಳನ್ನು ಪರಿಶೀಲಿಸಿ",
"Edit Profile": "ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ",
"Help": "ಸಹಾಯ",
"Tell us what's going on": "ನಡೆಯುತ್ತಿರುವುದು ನಮಗೆ ತಿಳಿಸಿ",
"Tell us why you're reaching us": "ನೀವು ನಮಗೆ ಏಕೆ ತಲುಪುತ್ತಿರುವಿರಿ ಎಂಬುದನ್ನು ತಿಳಿಸಿ",
"How do you feel? (Optional)": "ನೀವು ಹೇಗಾಗಿದ್ದೀರಿ? (ಐಚ್ಛಿಕ)",
"My Hospital": "ನನ್ನ ಆಸ್ಪತ್ರೆಗೆ",
"No hospitals found": "ಆಸ್ಪತ್ರೆಗಳು ಸಿಗಲಿಲ್ಲ",
"District:": "ಜಿಲ್ಲೆ:",
"Settings": "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
"English": "ಇಂಗ್ಲಿಷ್",
"Logout Successful": "ಯಶಸ್ವಿಯಾಗಿ ಲಾಗ್‌ಔಟ್ ಆಯಿತು",
"Subscribe": "ಚಂದಾದಾರರಾಗಿರಿ",
"Subscription": "ಚಂದಾ",
"Current Plan": "ಪ್ರಸ್ತುತ ಯೋಜನೆ",
"Monthly": "ಮಾಸಿಕ",
"Yearly": "ವಾರ್ಷಿಕ",
"Based on patient reviews": "ರೋಗಿಗಳ ವಿಮರ್ಶೆಗಳ ಆಧಾರದಲ್ಲಿ",
"Working Hours": "ಕೆಲಸದ ಸಮಯ",
"Contact Information": "ಸಂಪರ್ಕ ಮಾಹಿತಿ",
"Personalised Pregnancy Care": "ವೈಯಕ್ತಿಕ ಗರ್ಭಧಾರಣೆಯ ಆರೈಕೆ",
"Helps you to consult Doctor Virtually": "ನಿಮಗೆ ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ",
"Engage with Doctor through video and audio": "ವೀಡಿಯೋ ಮತ್ತು ಆಡಿಯೊ ಮೂಲಕ ವೈದ್ಯರೊಂದಿಗೆ ಸಂವಾದಿಸಿ",
"Keep on track your Health": "ನಿಮ್ಮ ಆರೋಗ್ಯವನ್ನು ಹಾದಿಯಲ್ಲಿಡಿ",
"By continuing, You agree that you have read and accept our": "ಮುಂದುವರಿಸುವ ಮೂಲಕ, ನೀವು ನಮ್ಮದನ್ನು ಓದಿದ್ದು ಮತ್ತು ಒಪ್ಪಿಕೊಂಡಿರುವಿರಿ",
"T&C and Privacy Policy": "ನಿಯಮಗಳು ಮತ್ತು ಗೌಪ್ಯತಾ ನೀತಿ",
"Thinking...": "ಯೋಚಿಸುತ್ತಿದೆ...",
"Your maternal AI assistant is processing your question": "ನಿಮ್ಮ ತಾಯಿ AI ಸಹಾಯಕನನ್ನು ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುತ್ತಿದೆ",
"Your Maternal AI Assistant": "ನಿಮ್ಮ ತಾಯಿ AI ಸಹಾಯಕ",
"Welcome to Allobot!": "ಅಲ್ಲೋಬಾಟ್‌ಗೆ ಸುಸ್ವಾಗತ!",
"I'm here to support you through your maternal journey. Ask me anything about pregnancy, childbirth, or early motherhood.": "ನಾನು ನಿಮ್ಮ ತಾಯಿ ಪ್ರವಾಸದಲ್ಲಿ ನಿಮಗೆ ಬೆಂಬಲ ನೀಡಲು ಇಲ್ಲಿ ಇದ್ದೇನೆ. ಗರ್ಭಧಾರಣೆ, ಹೆರಿಗೆ ಅಥವಾ ಪ್ರಾರಂಭಿಕ ತಾಯ್ತನದ ಬಗ್ಗೆ ನನಗೆ ಯಾವುದೇ ಪ್ರಶ್ನೆ ಕೇಳಿ.",
"What You Can Ask Me:": "ನನಗೆ ನೀವು ಕೇಳಬಹುದಾದವು:",
"Pregnancy health tips": "ಗರ್ಭಧಾರಣೆಯ ಆರೋಗ್ಯ ಸಲಹೆಗಳು",
"Nutrition advice": "ಪೋಷಣೆಯ ಸಲಹೆ",
"Baby care basics": "ಮಗು ಆರೈಕೆ ಮೂಲಭೂತ",
"Trimester milestones": "ತ್ರೈಮಾಸಿಕ ಮೈಲುಗಲ್ಲುಗಳು",
"Ask Allobot...": "ಅಲ್ಲೋಬಾಟ್ ಅನ್ನು ಕೇಳಿ...",
"Incoming Call": "ಒಳಹರಿವು ಕಾಲ್",
"Waiting": "ಕಾಯುತ್ತಿದೆ",
"No messages yet": "ಇನ್ನೂ ಸಂದೇಶಗಳಿಲ್ಲ",
"Tablets": "ಮಾತ್ತಿಗಳು",
"Units": "ಘಟಕಗಳು",
"Timing": "ಸಮಯ",
"No prescriptions found.": "ಮಾರ್ಗದರ್ಶಿಗಳು ಸಿಗಲಿಲ್ಲ",
"No description available": "ವಿವರಣೆ ಲಭ್ಯವಿಲ್ಲ",
"No reports found": "ವರದಿಗಳು ಸಿಗಲಿಲ್ಲ",
"Report Details": "ವರದಿ ವಿವರಗಳು",
"Unknown Report Type": "ಅಜ್ಞಾತ ವರದಿ ಪ್ರಕಾರ",
"Test Results": "ಪರೀಕ್ಷಾ ಫಲಿತಾಂಶಗಳು",
"Delete Report": "ವರದಿಯನ್ನು ಅಳಿಸಿ",
"Are you sure you want to delete this report?": "ನೀವು ಈ ವರದಿಯನ್ನು ಅಳಿಸಲು ಖಚಿತವಾಗಿದ್ದೀರಾ?",
"CANCEL": "ರದ್ದುಗೊಳಿಸಿ",
"DELETE": "ಅಳಿಸಿ",
"Normal": "ಸಾಮಾನ್ಯ",
"Body pain": "ದೇಹದ ನೋವು",
"Burning Stomach": "ಜ್ವಾಲೆ ಹೊಡೆಯುತ್ತಿರುವ ಹೊಟ್ಟೆ",
"Cold cough": "ಚಳಿ ಕೆಮ್ಮು",
"Dizziness": "ತಲೆಚುಚ್ಚು",
"Headache": "ತಲೆನೋವು",
"Vomiting": "ಓಕು",
"Other": "ಇತರೆ",
"Blood Pressure": "ರಕ್ತದ ಒತ್ತಡ",
"Temperature": "ತಾಪಮಾನ",
"Blood Saturation": "ರಕ್ತದ ಪ್ರತ್ಯೇಕತೆ",
"Blood Glucose": "ರಕ್ತ ಗ್ಲೂಕೋಸ್",
"BMI": "ಬಿಎಮ್‌ಐ",
"HRV": "ಎಚ್ಆರ್‌ವಿ",
"Baby Cry Not Detected.": "ಮಗು ಅಳುವುದನ್ನು ಪತ್ತೆಹಚ್ಚಲಾಗಲಿಲ್ಲ.",
"The baby cry detection process failed. Please check your connection or try again.": "ಮಗು ಅಳುವ ಪತ್ತೆಹಚ್ಚುವ ಪ್ರಕ್ರಿಯೆ ವಿಫಲವಾಯಿತು. ದಯವಿಟ್ಟು ನಿಮ್ಮ ಸಂಪರ್ಕವನ್ನು ಪರಿಶೀಲಿಸಿ ಅಥವಾ ಮರುಪ್ರಯತ್ನಿಸಿ.",
"Retry": "ಮರುಪ್ರಯತ್ನಿಸಿ",
"Please select Appointment Date": "ಬೇಟಿ ದಿನಾಂಕವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
"Please enter Diagnosis Description": "ರೋಗನಿರ್ಣಯದ ವಿವರವನ್ನು ನಮೂದಿಸಿ",
"No data available": "ಮಾಹಿತಿ ಲಭ್ಯವಿಲ್ಲ",
"Pregnant": "ಗರ್ಭಿಣಿ",
"Not Pregnant": "ಗರ್ಭಿಣಿ ಅಲ್ಲ",
"Summary": "ಸಾರಾಂಶ",
"Upcoming Appointments": "ಮುಂಬರುವ ಭೇಟಿಗಳು",
"No appointments scheduled": "ಯಾವುದೇ ಭೇಟಿಗಳನ್ನು ಗುರ್ತಿಸಲಾಗಿಲ್ಲ",
"No": "ಇಲ್ಲ",
"Yes": "ಹೌದು",
"No appointments found": "ಯಾವುದೇ ಭೇಟಿಗಳು ಸಿಗಲಿಲ್ಲ",
"JioVio Healthcare": "ಜಿಯೋವಿಯೋ ಆರೋಗ್ಯ",
"General Details": "ಸಾಮಾನ್ಯ ವಿವರಗಳು",
"Partner Details": "ಭಾಗಿದಾರರ ವಿವರಗಳು",
"Pregnancy Details": "ಗರ್ಭಧಾರಣೆಯ ವಿವರಗಳು",
"Address Details": "ವಿಳಾಸದ ವಿವರಗಳು",
"Contact Us": "ನಮಗೆ ಸಂಪರ್ಕಿಸಿ",
"Something not Working": "ಏನೋ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತಿಲ್ಲ",
"Feature Request": "ವೈಶಿಷ್ಟ್ಯಯ ವಿನಂತಿ",
"Question": "ಪ್ರಶ್ನೆ",
"FeedBack": "ಅಭಿಪ್ರಾಯ",
"SEND": "ಕಳುಹಿಸಿ",
"My Subscription": "ನನ್ನ ಚಂದಾ",
"Language": "ಭಾಷೆ",
"Terms & Conditions": "ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳು",
"Privacy Policy": "ಗೌಪ್ಯತಾ ನೀತಿ",
"Log Out": "ಲಾಗ್ ಔಟ್",
"Are you sure to logout?": "ನೀವು ಲಾಗ್ ಔಟ್ ಮಾಡಲು ಖಚಿತವಾಗಿದ್ದೀರಾ?",
"Cancel": "ರದ್ದುಗೊಳಿಸಿ",
"Ok": "ಸರಿ",
"Change Default": "ಪೂರ್ವನಿಯೋಜಿತವನ್ನು ಬದಲಿಸಿ",
"Write Description": "ವಿವರವನ್ನು ಬರೆಯಿರಿ",
"Please enter Description": "ವಿವರವನ್ನು ನಮೂದಿಸಿ",
"Door No": "ಬಾಗಿಲು ಸಂಖ್ಯೆ",
"Please enter Door No": "ಬಾಗಿಲು ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
"Street Name": "ರಸ್ತೆ ಹೆಸರು",
"Please enter Street Name": "ರಸ್ತೆ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
"Pincode": "ಪಿನ್‌ ಕೋಡ್",
"Please enter Pincode": "ಪಿನ್‌ ಕೋಡ್ ಅನ್ನು ನಮೂದಿಸಿ",
"Search Area": "ಹುಡುಕಾಟ ಪ್ರದೇಶ",
"Select Area Name": "ಪ್ರದೇಶದ ಹೆಸರನ್ನು ಆಯ್ಕೆಮಾಡಿ",
"Enter your Name": "ನಿಮ್ಮ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
"Please enter your name": "ನಿಮ್ಮ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
"Enter Email Id": "ಇಮೇಲ್ ಐಡಿಯನ್ನು ನಮೂದಿಸಿ",
"Please Select Gender": "ಲಿಂಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
"Age": "ವಯಸ್ಸು",
"Please enter age": "ವಯಸ್ಸು ನಮೂದಿಸಿ",
"Please enter correct age": "ಸರಿಯಾದ ವಯಸ್ಸು ನಮೂದಿಸಿ",
"LMP Date": "ಎಲ್ಎಂಪಿ ದಿನಾಂಕ",
"Please enter LMP Date": "ಎಲ್ಎಂಪಿ ದಿನಾಂಕವನ್ನು ನಮೂದಿಸಿ",
"ED Date": "ಇಡಿ ದಿನಾಂಕ",
"Date of delivery": "ವಿತರಣಾ ದಿನಾಂಕ",
"Please enter Delivery Date": "ವಿತರಣಾ ದಿನಾಂಕವನ್ನು ನಮೂದಿಸಿ",
"Please enter Partner Name": "ಭಾಗಿದಾರರ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
"Partner Name": "ಭಾಗಿದಾರರ ಹೆಸರು",
"Please enter Partner Mobile Number": "ಭಾಗಿದಾರರ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
"Partner Mobile Number": "ಭಾಗಿದಾರರ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
"Bed Time": "ಮಲಗುವ ಸಮಯ",
"Please enter Date of Birth": "ಜನ್ಮ ದಿನಾಂಕವನ್ನು ನಮೂದಿಸಿ",
"Wake Up Time": "ಎದ್ದ ಮೇಲಿನ ಸಮಯ",
"Name": "ಹೆಸರು",
"Please Select Parent Type": "ಪೋಷಕ ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
"Parent Type": "ಪೋಷಕ ಪ್ರಕಾರ",
"Please Select Pregnant Status": "ಗರ್ಭಿಣಿ ಸ್ಥಿತಿಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
"Please enter Area": "ಪ್ರದೇಶವನ್ನು ನಮೂದಿಸಿ",
"Area": "ಪ್ರದೇಶ",
"Services": "ಸೇವೆಗಳು",
"AlloBaby": "ಅಲೋಬೆಬಿ",
"Awareness": "ಜಾಗೃತಿ",
"Screening": "ಪರಿಶೀಲನೆ",
"Glucose Test": "ಗ್ಲೂಕೋಸ್ ಪರೀಕ್ಷೆ",
"Ultrasound Test": "ಅಲ್ಟ್ರಾಸೌಂಡ್ ಪರೀಕ್ಷೆ",
"Urine Test": "ಮೂತ್ರ ಪರೀಕ್ಷೆ",
...babycrys
};


final Map<String, String> babycrys = {
"Hunger Crying"	:	"ಹಸಿವು ಅಳುವುದು",
"Sleepy Crying"	:	"ನಿದ್ರೆಯ ಅಳು",
"Pain Crying"	:	"ನೋವು ಅಳುವುದು",
"Discomfort Crying"	:	"ಅಸ್ವಸ್ಥತೆ ಅಳುವುದು",
"Colic Crying"	:	"ಕೊಲಿಕ್ ಅಳುವಿಕೆ",
"Attention Crying"	:	"ಕೊಲಿಕ್ ಅಳುವಿಕೆ",
"Rhythmic, repetitive cries that grow louder if the baby isn't fed. Often accompanied by hand-sucking and rooting behavior."	:	"ಮಗುವಿಗೆ ಆಹಾರವನ್ನು ನೀಡದಿದ್ದರೆ ಲಯಬದ್ಧ, ಪುನರಾವರ್ತಿತ ಅಳುಗಳು ಜೋರಾಗಿ ಬೆಳೆಯುತ್ತವೆ. ಆಗಾಗ್ಗೆ ಕೈ ಚೀಪುವುದು ಮತ್ತು ಬೇರುಬಿಡುವ ನಡವಳಿಕೆಯೊಂದಿಗೆ.",
"A whiny, nasal cry that sounds weaker than a hunger cry, often accompanied by yawning and eye-rubbing."	:	"ಹಸಿವಿನ ಕೂಗಿಗಿಂತ ದುರ್ಬಲವಾದ ಗೊಣಗುವ, ಮೂಗಿನ ಕೂಗು, ಆಗಾಗ್ಗೆ ಆಕಳಿಕೆ ಮತ್ತು ಕಣ್ಣು ಉಜ್ಜುವಿಕೆಯೊಂದಿಗೆ.",
"A sudden, high-pitched, intense cry that comes in bursts with breathing pauses. Often accompanied by physical tension."	:	"ಹಠಾತ್, ಎತ್ತರದ ಕೂಗು, ತೀವ್ರವಾದ ಕೂಗು ಉಸಿರಾಟದ ವಿರಾಮಗಳೊಂದಿಗೆ ಸ್ಫೋಟಗೊಳ್ಳುತ್ತದೆ. ಆಗಾಗ್ಗೆ ದೈಹಿಕ ಉದ್ವೇಗದೊಂದಿಗೆ.",
"A fussy, irritated cry that typically stops when the source of discomfort is addressed."	:	"ಅಸ್ವಸ್ಥತೆಯ ಮೂಲವನ್ನು ಪರಿಹರಿಸಿದಾಗ ಸಾಮಾನ್ಯವಾಗಿ ನಿಲ್ಲುವ ಗಲಾಟೆ, ಕಿರಿಕಿರಿಯ ಕೂಗು.",
"Prolonged, intense crying episodes, typically in the evening, with physical signs of distress."	:	"ದೀರ್ಘಕಾಲದ, ತೀವ್ರವಾದ ಅಳುವ ಪ್ರಸಂಗಗಳು, ಸಾಮಾನ್ಯವಾಗಿ ಸಂಜೆ, ಸಂಕಟದ ದೈಹಿಕ ಚಿಹ್ನೆಗಳೊಂದಿಗೆ.",
"A mild cry that starts softly and increases if ignored, often accompanied by eye contact and reaching out."	:	"ಸೌಮ್ಯವಾದ ಅಳುವಿಕೆಯು ಮೃದುವಾಗಿ ಪ್ರಾರಂಭವಾಗುತ್ತದೆ ಮತ್ತು ನಿರ್ಲಕ್ಷಿಸಿದರೆ ಹೆಚ್ಚಾಗುತ್ತದೆ, ಆಗಾಗ್ಗೆ ಕಣ್ಣಿನ ಸಂಪರ್ಕ ಮತ್ತು ತಲುಪುವಿಕೆಯೊಂದಿಗೆ.",
"Hunger cries are rhythmic, repetitive, and grow louder if the baby isn't fed."	:	"ಹಸಿವಿನ ಕೂಗು ಲಯಬದ್ಧವಾಗಿರುತ್ತದೆ, ಪುನರಾವರ್ತಿತವಾಗಿರುತ್ತದೆ ಮತ್ತು ಮಗುವಿಗೆ ಆಹಾರವನ್ನು ನೀಡದಿದ್ದರೆ ಜೋರಾಗಿ ಬೆಳೆಯುತ್ತದೆ.",
"Babies may also:"	:	"ಶಿಶುಗಳು ಸಹ ಈ ಕೆಳಗಿನವುಗಳನ್ನು ಮಾಡಬಹುದು:",
"• Suck on hands or fingers"	:	"• ಕೈಗಳು ಅಥವಾ ಬೆರಳುಗಳ ಮೇಲೆ ಚೀಪುವುದು",
"• Smack lips, root (turn head searching for a nipple)"	:	"• ತುಟಿಗಳು, ಬೇರುಗಳನ್ನು ಹೊಡೆಯಿರಿ (ಮೊಲೆತೊಟ್ಟನ್ನು ಹುಡುಕುತ್ತಾ ತಲೆಯನ್ನು ತಿರುಗಿಸಿ)",
"• Get fussy even after being comforted"	:	"• ಸಮಾಧಾನಗೊಂಡ ನಂತರವೂ ಗಲಾಟೆ ಮಾಡಿ",
"A whiny, nasal cry that may sound weaker than a hunger cry."	:	"ಹಸಿವಿನ ಕೂಗಿಗಿಂತ ದುರ್ಬಲವಾದ ಗೊಣಗುವ, ಮೂಗಿನ ಕೂಗು.",
"Babies may also:"	:	"ಶಿಶುಗಳು ಸಹ ಈ ಕೆಳಗಿನವುಗಳನ್ನು ಮಾಡಬಹುದು:",
"• Yawn frequently"	:	"• ಆಗಾಗ್ಗೆ ಆಕಳಿಕೆ",
"• Rub their eyes or pull their ears"	:	"• ಕಣ್ಣುಗಳನ್ನು ಉಜ್ಜಿಕೊಳ್ಳಿ ಅಥವಾ ಕಿವಿಗಳನ್ನು ಎಳೆಯಿರಿ",
"• Become fussy and harder to soothe"	:	"• ಗೊಂದಲಮಯವಾಗಿ ಮತ್ತು ಶಮನಗೊಳಿಸಲು ಕಷ್ಟವಾಗುವಂತೆ ಮಾಡಿ",
"A sudden, high-pitched, intense cry that may come in bursts with pauses for breath."	:	"ಹಠಾತ್, ಎತ್ತರದ ಕೂಗು, ತೀವ್ರವಾದ ಕೂಗು ಉಸಿರಾಟದ ವಿರಾಮಗಳೊಂದಿಗೆ ಸ್ಫೋಟಗೊಳ್ಳಬಹುದು.",
"Babies may also:"	:	"ಶಿಶುಗಳು ಸಹ ಈ ಕೆಳಗಿನವುಗಳನ್ನು ಮಾಡಬಹುದು:",
"• Clench fists or arch their back"	:	"• ಮುಷ್ಟಿಗಳನ್ನು ಬಿಗಿಹಿಡಿದು ಅಥವಾ ಬೆನ್ನನ್ನು ಬಾಗಿಸಿ",
"• Become stiff or tense"	:	"• ಗಟ್ಟಿಯಾಗುವುದು ಅಥವಾ ಉದ್ವಿಗ್ನರಾಗುವುದು",
"• Show signs of discomfort (scrunched face, difficulty calming down)"	:	"• ಅಸ್ವಸ್ಥತೆಯ ಚಿಹ್ನೆಗಳನ್ನು ತೋರಿಸಿ (ಮುಖವು ಕುಗ್ಗಿದೆ, ಶಾಂತವಾಗಲು ಕಷ್ಟವಾಗುತ್ತದೆ)",
"A fussy, irritated cry that may stop when the issue is resolved."	:	"ಸಮಸ್ಯೆ ಬಗೆಹರಿದಾಗ ನಿಲ್ಲಬಹುದಾದ ಗಲಾಟೆ, ಕಿರಿಕಿರಿಯ ಕೂಗು.",
"Babies may also:"	:	"ಶಿಶುಗಳು ಸಹ ಈ ಕೆಳಗಿನವುಗಳನ್ನು ಮಾಡಬಹುದು:",
"• Wiggle or squirm a lot"	:	"• ತುಂಬಾ ಗೊಣಗುವುದು ಅಥವಾ ನಡುಗುವುದು",
"• Tug at their clothing or ears"	:	"• ಅವರ ಬಟ್ಟೆ ಅಥವಾ ಕಿವಿಗಳನ್ನು ಎಳೆಯಿರಿ",
"• Appear restless or uneasy"	:	"• ಪ್ರಕ್ಷುಬ್ಧ ಅಥವಾ ಅಹಿತಕರವಾಗಿ ಕಾಣಿ",
"A prolonged, intense, high-pitched cry that often occurs in the evening."	:	"ದೀರ್ಘಕಾಲದ, ತೀವ್ರವಾದ, ಎತ್ತರದ ಕೂಗು ಆಗಾಗ್ಗೆ ಸಂಜೆ ಸಂಭವಿಸುತ್ತದೆ.",
"Babies may also:"	:	"ಶಿಶುಗಳು ಸಹ ಈ ಕೆಳಗಿನವುಗಳನ್ನು ಮಾಡಬಹುದು:",
"• Clench fists, arch their back, or pull up legs"	:	"• ಮುಷ್ಟಿಗಳನ್ನು ಬಿಗಿಹಿಡಿದು, ಬೆನ್ನನ್ನು ಬಾಗಿಸಿ, ಅಥವಾ ಕಾಲುಗಳನ್ನು ಮೇಲಕ್ಕೆ ಎಳೆಯಿರಿ",
"• Have a tense, bloated belly"	:	"• ಉದ್ವಿಗ್ನವಾದ, ಉಬ್ಬಿದ ಹೊಟ್ಟೆಯನ್ನು ಹೊಂದಿರಿ",
"• Be difficult to soothe, even after feeding"	:	"• ಹಾಲುಣಿಸಿದ ನಂತರವೂ ಶಮನಗೊಳಿಸಲು ಕಷ್ಟವಾಗುತ್ತದೆ",
"A mild, whimpering cry that starts softly and gets louder if ignored."	:	"ಸೌಮ್ಯವಾದ, ಗೊಣಗುವ ಕೂಗು ಮೃದುವಾಗಿ ಪ್ರಾರಂಭವಾಗುತ್ತದೆ ಮತ್ತು ನಿರ್ಲಕ್ಷಿಸಿದರೆ ಜೋರಾಗಿರುತ್ತದೆ.",
"Babies may also:"	:	"ಶಿಶುಗಳು ಸಹ ಈ ಕೆಳಗಿನವುಗಳನ್ನು ಮಾಡಬಹುದು:",
"• Make eye contact while crying"	:	"• ಅಳುವಾಗ ಕಣ್ಣಿನ ಸಂಪರ್ಕವನ್ನು ಮಾಡಿಕೊಳ್ಳಿ",
"• Reach out for comfort"	:	"• ಆರಾಮಕ್ಕಾಗಿ ಕೈ ಚಾಚಿ",
"• Stop crying quickly when picked up"	:	"• ಎತ್ತಿಕೊಂಡಾಗ ಬೇಗನೆ ಅಳುವುದನ್ನು ನಿಲ್ಲಿಸಿ",
"Feed Promptly – Responding early prevents excessive crying and makes feeding easier."	:	"ತಕ್ಷಣ ಆಹಾರ ನೀಡಿ - ಬೇಗನೆ ಪ್ರತಿಕ್ರಿಯಿಸುವುದು ಅತಿಯಾದ ಅಳುವಿಕೆಯನ್ನು ತಡೆಯುತ್ತದೆ ಮತ್ತು ಆಹಾರವನ್ನು ಸುಲಭಗೊಳಿಸುತ್ತದೆ.",
"Watch for Hunger Cues – Crying is a late sign; look for early signs like lip-smacking, rooting, sticking out tongue, or sucking on hands."	:	"ಹಸಿವಿನ ಸೂಚನೆಗಳನ್ನು ಗಮನಿಸಿ - ಅಳುವುದು ತಡವಾಗಿ ಬರುವ ಚಿಹ್ನೆ; ತುಟಿ ಬಡಿಯುವುದು, ಬೇರು ಬಿಡುವುದು, ನಾಲಿಗೆಯನ್ನು ಹೊರತೆಗೆಯುವುದು ಅಥವಾ ಕೈಗಳನ್ನು ಚೀಪುವುದು ಮುಂತಾದ ಆರಂಭಿಕ ಚಿಹ್ನೆಗಳನ್ನು ನೋಡಿ.",
"Ensure Proper Latch – If breastfeeding, ensure a deep latch to avoid discomfort."	:	"ಸರಿಯಾದ ಲಾಚ್ ಅನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ - ಸ್ತನ್ಯಪಾನ ಮಾಡುತ್ತಿದ್ದರೆ, ಅಸ್ವಸ್ಥತೆಯನ್ನು ತಪ್ಪಿಸಲು ಆಳವಾದ ಲಾಚ್ ಅನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ.",
"Check Feeding Schedule – Newborns need feeding every 2-3 hours."	:	"ಫೀಡಿಂಗ್ ವೇಳಾಪಟ್ಟಿಯನ್ನು ಪರಿಶೀಲಿಸಿ - ನವಜಾತ ಶಿಶುಗಳಿಗೆ ಪ್ರತಿ 2-3 ಗಂಟೆಗಳಿಗೊಮ್ಮೆ ಆಹಾರದ ಅಗತ್ಯವಿದೆ.",
"Burp Baby After Feeding – Helps prevent gas and fussiness."	:	"ಹಾಲುಣಿಸಿದ ನಂತರ ಮಗುವನ್ನು ಬರ್ಪ್ ಮಾಡಿ - ಗ್ಯಾಸ್ ಮತ್ತು ಗಲಾಟೆಯನ್ನು ತಡೆಯಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
"Look for Sleep Cues Early – Yawning, zoning out, or rubbing eyes signal it's time to sleep."	:	"ನಿದ್ರೆಯ ಸೂಚನೆಗಳನ್ನು ಬೇಗನೆ ಹುಡುಕಿ - ಆಕಳಿಕೆ, ವಲಯ ಮಾಡುವುದು ಅಥವಾ ಕಣ್ಣುಗಳನ್ನು ಉಜ್ಜುವುದು ಇದು ನಿದ್ರೆಯ ಸಮಯ ಎಂದು ಸೂಚಿಸುತ್ತದೆ.",
"Create a Calm Sleep Environment – Dim lights, reduce noise, and use white noise if needed."	:	"ಶಾಂತ ನಿದ್ರೆಯ ವಾತಾವರಣವನ್ನು ರಚಿಸಿ - ಮಂದ ದೀಪಗಳು, ಶಬ್ದವನ್ನು ಕಡಿಮೆ ಮಾಡಿ ಮತ್ತು ಅಗತ್ಯವಿದ್ದರೆ ಬಿಳಿ ಶಬ್ದವನ್ನು ಬಳಸಿ.",
"Use Gentle Rocking – Motion, swaddling, or a pacifier can help."	:	"ಸೌಮ್ಯ ರಾಕಿಂಗ್ ಬಳಸಿ - ಚಲನೆ, ಸ್ವಾಡ್ಲಿಂಗ್ ಅಥವಾ ಪ್ಯಾಸಿಫೈಯರ್ ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
"Follow a Sleep Routine – A consistent bedtime routine helps babies recognize sleep time."	:	"ನಿದ್ರೆಯ ದಿನಚರಿಯನ್ನು ಅನುಸರಿಸಿ - ಸ್ಥಿರವಾದ ಮಲಗುವ ಸಮಯದ ದಿನಚರಿ ಶಿಶುಗಳಿಗೆ ನಿದ್ರೆಯ ಸಮಯವನ್ನು ಗುರುತಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
"Avoid Overstimulation – Too much activity before bed can make sleep harder."	:	"ಅತಿಯಾದ ಪ್ರಚೋದನೆಯನ್ನು ತಪ್ಪಿಸಿ - ಮಲಗುವ ಮೊದಲು ಹೆಚ್ಚಿನ ಚಟುವಟಿಕೆಯು ನಿದ್ರೆಯನ್ನು ಕಷ್ಟಕರವಾಗಿಸುತ್ತದೆ.",
"Check for Obvious Issues – Look for diaper rash, teething pain, or tight clothing."	:	"ಸ್ಪಷ್ಟವಾದ ಸಮಸ್ಯೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ - ಡಯಾಪರ್ ದದ್ದು, ಹಲ್ಲುಜ್ಜುವ ನೋವು ಅಥವಾ ಬಿಗಿಯಾದ ಬಟ್ಟೆಗಳನ್ನು ನೋಡಿ.",
"Soothe with Gentle Touch – Skin-to-skin contact or holding them close can help."	:	"ಸೌಮ್ಯ ಸ್ಪರ್ಶದಿಂದ ಶಮನಗೊಳಿಸಿ - ಚರ್ಮದಿಂದ ಚರ್ಮದ ಸಂಪರ್ಕ ಅಥವಾ ಅವುಗಳನ್ನು ಹತ್ತಿರವಾಗಿ ಹಿಡಿದುಕೊಳ್ಳುವುದು ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
"Try Pain Relief Techniques – For teething, offer a chilled teether; for gas, try tummy massage."	:	"ನೋವು ನಿವಾರಕ ತಂತ್ರಗಳನ್ನು ಪ್ರಯತ್ನಿಸಿ - ಹಲ್ಲುಜ್ಜಲು, ತಂಪಾದ ಹಲ್ಲುಗಳನ್ನು ನೀಡಿ; ಗ್ಯಾಸ್ ಗಾಗಿ, ಹೊಟ್ಟೆಯ ಮಸಾಜ್ ಪ್ರಯತ್ನಿಸಿ.",
"Monitor for Fever or Illness – If crying persists with fever, vomiting, or lethargy, consult a doctor."	:	"ಜ್ವರ ಅಥವಾ ಅನಾರೋಗ್ಯದ ಮೇಲ್ವಿಚಾರಣೆ - ಜ್ವರ, ವಾಂತಿ ಅಥವಾ ಆಲಸ್ಯದೊಂದಿಗೆ ಅಳುವುದು ಮುಂದುವರಿದರೆ, ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.",
"Trust Your Instincts – If the baby seems in severe pain, seek medical advice immediately."	:	"ನಿಮ್ಮ ಪ್ರವೃತ್ತಿಗಳನ್ನು ನಂಬಿ - ಮಗುವು ತೀವ್ರ ನೋವಿನಿಂದ ಬಳಲುತ್ತಿದ್ದರೆ, ತಕ್ಷಣ ವೈದ್ಯಕೀಯ ಸಲಹೆಯನ್ನು ಪಡೆಯಿರಿ.",
"Check the Diaper – A wet or soiled diaper is a common cause of discomfort."	:	"ಡಯಾಪರ್ ಪರಿಶೀಲಿಸಿ - ಒದ್ದೆಯಾದ ಅಥವಾ ಕೊಳೆತ ಡಯಾಪರ್ ಅಸ್ವಸ್ಥತೆಗೆ ಸಾಮಾನ್ಯ ಕಾರಣವಾಗಿದೆ.",
"Ensure Comfortable Clothing – Dress baby in breathable, soft fabrics and check for tight clothing."	:	"ಆರಾಮದಾಯಕ ಬಟ್ಟೆಗಳನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ - ಮಗುವಿಗೆ ಉಸಿರಾಡಬಹುದಾದ, ಮೃದುವಾದ ಬಟ್ಟೆಗಳನ್ನು ಧರಿಸಿ ಮತ್ತು ಬಿಗಿಯಾದ ಬಟ್ಟೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.",
"Adjust Temperature – Feel baby's neck/back to see if they are too hot or cold."	:	"ತಾಪಮಾನವನ್ನು ಸರಿಹೊಂದಿಸಿ - ಮಗುವಿನ ಕುತ್ತಿಗೆ / ಬೆನ್ನು ತುಂಬಾ ಬಿಸಿಯಾಗಿದೆಯೇ ಅಥವಾ ತಣ್ಣಗಿದೆಯೇ ಎಂದು ಭಾವಿಸಿ.",
"Check for External Irritants – Tags, rough fabric, or hair wrapped around fingers/toes can cause irritation."	:	"ಬಾಹ್ಯ ಕಿರಿಕಿರಿಗಳನ್ನು ಪರಿಶೀಲಿಸಿ - ಟ್ಯಾಗ್ ಗಳು, ಒರಟು ಬಟ್ಟೆ, ಅಥವಾ ಬೆರಳುಗಳು / ಕಾಲ್ಬೆರಳುಗಳ ಸುತ್ತಲೂ ಸುತ್ತಿದ ಕೂದಲು ಕಿರಿಕಿರಿಯನ್ನು ಉಂಟುಮಾಡಬಹುದು.",
"Reposition Baby – Changing positions or holding them differently can sometimes help."	:	"ಮಗುವನ್ನು ಮರುಸ್ಥಾಪಿಸಿ - ಸ್ಥಾನಗಳನ್ನು ಬದಲಾಯಿಸುವುದು ಅಥವಾ ಅವುಗಳನ್ನು ವಿಭಿನ್ನವಾಗಿ ಹಿಡಿದಿಟ್ಟುಕೊಳ್ಳುವುದು ಕೆಲವೊಮ್ಮೆ ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
"Use Gentle Motions – Rocking, swaying, or holding baby in a 'colic carry' (on their tummy along your forearm) can help."	:	"ಸೌಮ್ಯ ಚಲನೆಗಳನ್ನು ಬಳಸಿ - ಮಗುವನ್ನು 'ಕೊಲಿಕ್ ಕ್ಯಾರಿ' ಯಲ್ಲಿ (ನಿಮ್ಮ ಮುಂಗೈಯ ಉದ್ದಕ್ಕೂ ಅವರ ಹೊಟ್ಟೆಯ ಮೇಲೆ) ಅಲುಗಾಡಿಸುವುದು, ಅಲುಗಾಡಿಸುವುದು ಅಥವಾ ಹಿಡಿದುಕೊಳ್ಳುವುದು ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
"Try White Noise – Rhythmic sounds, like a fan or heartbeat sound, can be soothing."	:	"ಬಿಳಿ ಶಬ್ದವನ್ನು ಪ್ರಯತ್ನಿಸಿ - ಫ್ಯಾನ್ ಅಥವಾ ಹೃದಯ ಬಡಿತದ ಧ್ವನಿಯಂತಹ ಲಯಬದ್ಧ ಶಬ್ದಗಳು ಹಿತಕರವಾಗಿರುತ್ತವೆ.",
"Burp Baby Well – Gas buildup can make colic worse. Burp frequently during feeds."	:	"ಬರ್ಪ್ ಬೇಬಿ ವೆಲ್ - ಗ್ಯಾಸ್ ನಿರ್ಮಾಣವು ಕೊಲಿಕ್ ಅನ್ನು ಇನ್ನಷ್ಟು ಹದಗೆಡಿಸುತ್ತದೆ. ಫೀಡ್ ಮಾಡುವಾಗ ಆಗಾಗ್ಗೆ ಬರ್ಪ್ ಮಾಡಿ.",
"Massage the Tummy – A gentle circular tummy massage can relieve gas."	:	"ಹೊಟ್ಟೆಯನ್ನು ಮಸಾಜ್ ಮಾಡಿ - ಮೃದುವಾದ ವೃತ್ತಾಕಾರದ ಹೊಟ್ಟೆಯ ಮಸಾಜ್ ಅನಿಲವನ್ನು ನಿವಾರಿಸುತ್ತದೆ.",
"Consult a Pediatrician – If colic persists, discuss options like probiotic drops or diet changes (for breastfeeding moms)."	:	"ಶಿಶುವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ - ಹೊಟ್ಟೆನೋವು ಮುಂದುವರಿದರೆ, ಪ್ರೋಬಯಾಟಿಕ್ ಹನಿಗಳು ಅಥವಾ ಆಹಾರ ಬದಲಾವಣೆಗಳಂತಹ ಆಯ್ಕೆಗಳನ್ನು ಚರ್ಚಿಸಿ (ಹಾಲುಣಿಸುವ ತಾಯಂದಿರಿಗೆ).",
"Respond with Reassurance – Holding, talking, or making eye contact helps babies feel secure."	:	"ಭರವಸೆಯೊಂದಿಗೆ ಪ್ರತಿಕ್ರಿಯಿಸಿ - ಹಿಡಿದಿಟ್ಟುಕೊಳ್ಳುವುದು, ಮಾತನಾಡುವುದು ಅಥವಾ ಕಣ್ಣಿನ ಸಂಪರ್ಕವನ್ನು ಮಾಡುವುದು ಶಿಶುಗಳಿಗೆ ಸುರಕ್ಷಿತ ಭಾವನೆಯನ್ನು ಅನುಭವಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
"Try Gentle Touch – A cuddle or soft pat on the back can be calming."	:	"ಸೌಮ್ಯ ಸ್ಪರ್ಶವನ್ನು ಪ್ರಯತ್ನಿಸಿ - ಬೆನ್ನಿನ ಮೇಲೆ ಮುದ್ದು ಅಥವಾ ಮೃದುವಾದ ತಟ್ಟುವಿಕೆಯು ಶಾಂತವಾಗಬಹುದು.",
"Engage with Soothing Sounds – Humming or talking in a calm voice can reassure the baby."	:	"ಹಿತವಾದ ಶಬ್ದಗಳೊಂದಿಗೆ ತೊಡಗಿಸಿಕೊಳ್ಳಿ - ಹಮ್ಮಿಂಗ್ ಅಥವಾ ಶಾಂತ ಧ್ವನಿಯಲ್ಲಿ ಮಾತನಾಡುವುದು ಮಗುವಿಗೆ ಭರವಸೆ ನೀಡುತ್ತದೆ.",
"Encourage Independent Comforting – Allow baby to self-soothe briefly before immediately responding."	:	"ಸ್ವತಂತ್ರ ಸಾಂತ್ವನವನ್ನು ಪ್ರೋತ್ಸಾಹಿಸಿ - ತಕ್ಷಣ ಪ್ರತಿಕ್ರಿಯಿಸುವ ಮೊದಲು ಮಗುವಿಗೆ ಸಂಕ್ಷಿಪ್ತವಾಗಿ ಸ್ವಯಂ ಶಮನಗೊಳಿಸಲು ಅವಕಾಶ ನೀಡಿ.",
"Maintain a Balance – Meeting attention needs is important, but consistency in response helps babies learn security."	:	"ಸಮತೋಲನವನ್ನು ಕಾಪಾಡಿಕೊಳ್ಳಿ - ಗಮನದ ಅಗತ್ಯಗಳನ್ನು ಪೂರೈಸುವುದು ಮುಖ್ಯ, ಆದರೆ ಪ್ರತಿಕ್ರಿಯೆಯಲ್ಲಿ ಸ್ಥಿರತೆಯು ಶಿಶುಗಳಿಗೆ ಸುರಕ್ಷತೆಯನ್ನು ಕಲಿಯಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.",

  "Cry History":"ಕ್ರೈ ಹಿಸ್ಟರಿ",
"Record" :"ರೆಕಾರ್ಡ್ ಮಾಡಿ"
};