final Map<String, String> ka = {
    "Select Language": "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    "Enter Mobile Number": "ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
    "SEND OTP": "OTP ಕಳುಹಿಸಿ",
    "How do you feel today ?": "ನೀವು ಇಂದು ಹೇಗಿದ್ದೀರಿ?",
    "Online": "ಆನ್ಲೈನ್",
    "Offline": "ಆಫ್‌ಲೈನ್",
    "Image Uploaded": "ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಲಾಗಿದೆ",
    "Type a message": "ಸಂದೇಶವನ್ನು ಟೈಪ್ ಮಾಡಿ",
    "Choose photo from :": "ಇಂದಿನಿಂದ ಫೋಟೋ ಆಯ್ಕೆಮಾಡಿ:",
    "Get Connected with doctors": "ವೈದ್ಯರೊಂದಿಗೆ ಸಂಪರ್ಕಿಸಿರಿ",
    "Connect with Doctor": "ವೈದ್ಯರೊಂದಿಗೆ ಸಂಪರ್ಕಿಸಿ",
    "Connect with Health worker": "ಆರೋಗ್ಯ ಕಾರ್ಯಕರ್ತರೊಂದಿಗೆ ಸಂಪರ್ಕಿಸಿ",
    "Connect with AlloBot": "AlloBot ಜೊತೆಗೆ ಸಂಪರ್ಕಿಸಿ",
    "Sorry No Awareness Post": "ಕ್ಷಮಿಸಿ ಜಾಗೃತಿ ಪೋಷ್ಟ್ ಇಲ್ಲ",
    "Checkup Completed": "ಪರಿಶೀಲನೆ ಮುಗಿದಿದೆ",
    "Waiting for Doctor Feedback": "ವೈದ್ಯರ ಪ್ರತಿಕ್ರಿಯೆಗೆ ಕಾಯುತ್ತಿದೆ",
    "Checkup need to be done": "ಪರಿಶೀಲನೆ ಮಾಡಬೇಕಾಗಿದೆ",
    "Checkup": "ಪರಿಶೀಲನೆ",
    "No Checkup Found": "ಯಾವುದೇ ಪರಿಶೀಲನೆ ಕಂಡುಬಂದಿಲ್ಲ",
    "Checkup Details": "ಪರಿಶೀಲನೆ ವಿವರಗಳು",
    "Doctor Name": "ವೈದ್ಯರ ಹೆಸರು",
    "Date:": "ದಿನಾಂಕ:",
    "Health Status:": "ಆರೋಗ್ಯ ಸ್ಥಿತಿ:",
    "Case Summary": "ಸಂದರ್ಭ ಸಮರಾಸ",
    "Prescription": "ಔಷಧ ನೋಟ",
    "Next Appointment Time": "ಮುಂದಿನ ಭೇಟಿಯ ಸಮಯ",
    "Symptoms": "ಲಕ್ಷಣಗಳು",
    "Vitals": "ಜೀವನಾಂಶಗಳು",
    "Add Prescription": "ಔಷಧ ನೋಟವನ್ನು ಸೇರಿಸಿ",
    "ADD PRESCRIPTION": "ಔಷಧ ನೋಟವನ್ನು ಸೇರಿಸಿ",
    "Click to Add Image": "ಚಿತ್ರವನ್ನು ಸೇರಿಸಲು ಕ್ಲಿಕ್ ಮಾಡಿ",
    "View Prescription": "ಔಷಧ ನೋಟವನ್ನು ನೋಡಿ",
    "Error loading image": "ಚಿತ್ರ ಲೋಡ್ ಮಾಡುವಲ್ಲಿ ದೋಷ",
    "Prescription Type": "ಔಷಧ ನೋಟದ ಪ್ರಕಾರ",
    "Date Added": "ಸೇರಿಸಿದ ದಿನಾಂಕ",
    "Description": "ವಿವರಣೆ",
    "Add Report": "ವರದಿಯನ್ನು ಸೇರಿಸಿ",
    "NO IMAGE": "ಚಿತ್ರವಿಲ್ಲ",
    "Click Add Image Button": "ಚಿತ್ರವನ್ನು ಸೇರಿಸಲು ಬಟನ್ ಕ್ಲಿಕ್ ಮಾಡಿ",
    "ADD IMAGE": "ಚಿತ್ರವನ್ನು ಸೇರಿಸಿ",
    "ADD REPORT": "ವರದಿಯನ್ನು ಸೇರಿಸಿ",
    "Report": "ವರದಿ",
    "Scan and Add new Report": "ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ಮತ್ತು ಹೊಸ ವರದಿಯನ್ನು ಸೇರಿಸಿ",
    "Self Screening": "ಸ್ವಯಂ ತಪಾಸಣೆ",
    "BACK": "ಹಿಂದೆ",
    "NEXT": "ಮುಂದೆ",
    "Finish": "ಮುಗಿಸಿ",
    "Summary Report": "ಸಂಗ್ರಹ ವರದಿ",
    "Submit": "ಸಲ್ಲಿಸು",
    "Let's begin the test": "ಪರೀಕ್ಷೆಯನ್ನು ಪ್ರಾರಂಭಿಸೋಣ",
    "Hemoglobin Test": "ಹಿಮೋಗ್ಲೋಬಿನ್ ಪರೀಕ್ಷೆ",
    "Easily get your Reading by Performing the scans below": "ಕೆಳಗಿನ ಸ್ಕ್ಯಾನ್‌ಗಳನ್ನು ಮಾಡಿ ನಿಮ್ಮ ಓದುವಿಕೆಯನ್ನು ಸುಲಭವಾಗಿ ಪಡೆಯಿರಿ",
    "Fetal Monitoring": "ಭ್ರೂಣದ ಮೇಲ್ವಿಚಾರಣೆ",
    "Upload Report": "ವರದಿಯನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    "Tap to Change": "ಬದಲಿಸಲು ಟ್ಯಾಪ್ ಮಾಡಿ",
    "Heart Rate": "ಹೃದಯದ ಓಟ",
    "BPM": "ಬಿಪಿಎಮ್",
    "Kick Count": "ಉದೆ ಎಣಿಕೆ",
    "Tap to Increase the Count": "ಎಣಿಕೆಯನ್ನು ಹೆಚ್ಚಿಸಲು ಟ್ಯಾಪ್ ಮಾಡಿ",
    "Add Glucose Report": "ಗ್ಲೂಕೋಸ್ ವರದಿಯನ್ನು ಸೇರಿಸಿ",
    "Blood Glucose Value": "ರಕ್ತ ಗ್ಲೂಕೋಸ್ ಮೌಲ್ಯ",
    "Add Hemoglobin Report": "ಹಿಮೋಗ್ಲೋಬಿನ್ ವರದಿಯನ್ನು ಸೇರಿಸಿ",
    "Hemoglobin Value": "ಹಿಮೋಗ್ಲೋಬಿನ್ ಮೌಲ್ಯ",
    "Ultra Sound": "ಅಲ್ಟ್ರಾಸೌಂಡ್",
    "Fasting": "ಉಪವಾಸ",
    "At rest": "ವಿಶ್ರಾಂತಿಯಲ್ಲಿ",
    "After Walk": "ನಡೆಯಲು ನಂತರ",
    "Select Height": "ಎತ್ತರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    "Select Weight": "ತೂಕವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    "After walk": "ನಡೆಯಲು ನಂತರ",
    "Address Information": "ವಿಳಾಸ ಮಾಹಿತಿ",
    "Search": "ಹುಡುಕು",
    "Continue": "ಮುಂದುವರಿಸಿ",
    "Phone Number": "ಫೋನ್ ಸಂಖ್ಯೆ",
    "Profile Details": "ಪ್ರೊಫೈಲ್ ವಿವರಗಳು",
    "Gender": "ಲಿಂಗ",
    "Male": "ಪುರುಷ",
    "Female": "ಸ್ತ್ರೀ",
    "Select Blood Group": "ರಕ್ತದ ಗುಂಪನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    "Select Last cycle Date": "ಕೊನೆಯ ಚಕ್ರದ ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ",
    "Are you my mom or dad?": "ನೀವು ನನ್ನ ಅಮ್ಮ ಅಥವಾ ಅಪ್ಪ?",
    "Dad": "ಅಪ್ಪ",
    "Mom": "ಅಮ್ಮ",
    "Enter your Partner Details": "ನಿಮ್ಮ ಜೊತೆಯವರ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ",
    "Pregnancy Status": "ಗರ್ಭಿಣಿ ಸ್ಥಿತಿ",
    "Partner Pregnancy Status": "ಸಹೋದರ ಗರ್ಭಿಣಿ ಸ್ಥಿತಿ",
    "Average Length of Cycles": "ಚಕ್ರಗಳ ಸರಾಸರಿ ಉದ್ದ",
    "Day": "ದಿನ",
    "Not yet started": "ಇನ್ನೂ ಪ್ರಾರಂಭವಾಗಿಲ್ಲ",
    "NORMAL": "ಸಾಮಾನ್ಯ",
    "Health Status": "ಆರೋಗ್ಯ ಸ್ಥಿತಿ",
    "Last Screened": "ಕೊನೆಯ ಬಾರಿಗೆ ತಪಾಸಿಸಲಾಯಿತು",
    "GOLD": "ಚಿನ್ನ",
    "Subscription Plan": "ಚಂದಾ ಯೋಜನೆ",
    "No News Feed": "ಯಾವುದೇ ಸುದ್ದಿಗಳ ಪೋಷಣೆ ಇಲ್ಲ",
    "Probable Reason": "ಶಕ್ಯತೆಯ ಕಾರಣ",
    "Recommendations": "ಶಿಫಾರಸುಗಳು",
    "Hi!": "ಹಲೋ!",
    "How do you feel today?": "ನೀವು ಇಂದು ಹೇಗಿದ್ದೀರಿ?",
    "Select Exercise that have you done today?": "ನೀವು ಇಂದು ಮಾಡಿದ ವ್ಯಾಯಾಮವನ್ನು ಆಯ್ಕೆಮಾಡಿ?",
    "None": "ಯಾವುದೂ ಇಲ್ಲ",
    "Select tablets that you have taken": "ನೀವು ತೆಗೆದುಕೊಂಡ ಗುಳಿಕೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    "Sleep Duration": "ನಿದ್ರಾ ಅವಧಿ",
    "Do you have any of these Symptoms?": "ಈ ಲಕ್ಷಣಗಳಲ್ಲಿ ಯಾವುದಾದರೂ ನಿಮ್ಮಲ್ಲಿದೆಯೆ?",
    "Baby Voice is Recording": "ಹಸುಗೂಸಿನ ಧ್ವನಿ ದಾಖಲಾಗುತ್ತಿದೆ",
    "STOP": "ನಿಲ್ಲಿಸಿ",
    "Click the Record Button to Start Recording": "ದಾಖಲು ಪ್ರಾರಂಭಿಸಲು ರೆಕಾರ್ಡ್ ಬಟನ್ ಕ್ಲಿಕ್ ಮಾಡಿ",
    "Record": "ದಾಖಲೆ",
    "How many Glass of water have you drunk today?": "ನೀವು ಇಂದು ಎಷ್ಟು ಗ್ಲಾಸ್ ನೀರನ್ನು ಕುಡಿದಿದ್ದೀರಿ?",
    "OTP Verification": "OTP ಪರಿಶೀಲನೆ",
    "Enter OTP sent to": "OTP ಅನ್ನು ನಮೂದಿಸಿ",
    "Verify and proceed": "ಪರಿಶೀಲಿಸಿ ಮುಂದುವರಿಸಿ",
    "Appointment": "ಕರೆ",
    "Select Hospital": "ಆಸ್ಪತ್ರೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    "Select Doctor": "ವೈದ್ಯರನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    "Appointment Date": "ಸಮಯದ ದಿನಾಂಕ",
    "Available slots": "ಲಭ್ಯವಿರುವ ಸ್ಲಾಟ್ಸ್",
    "No Slots Available": "ಲಭ್ಯವಿರುವ ಸ್ಲಾಟ್ಸ್ ಇಲ್ಲ",
    "View Available Slots": "ಲಭ್ಯವಿರುವ ಸ್ಲಾಟ್ಸ್ ಅನ್ನು ನೋಡಿ",
    "Start time Slot:": "ಪ್ರಾರಂಭ ಸಮಯ:",
    "Diagnosis Description": "ರೋಗದ ವಿವರಣೆ",
    "Book": "ಬುಕಿಂಗ್",
    "Update": "ನವೀಕರಿಸಿ",
    "Respiratory Rate": "ಶ್ವಾಸದ ಪ್ರಮಾಣ",
    "Appointments": "ಆಯ್ಕೆ",
    "As a companion in your pregnancy we help you with the following": "ನಿಮ್ಮ ಗರ್ಭಕಾಲದ ಬಗ್ಗೆಯೂ ಅನುಸರಿಸುವಲ್ಲಿ ಸಹಾಯ",
    "Book An Appointment": "ಭೇಟಿಯನ್ನು ಬುಕಿಂಗ್ ಮಾಡಿ",
    "Pregnancy Monitoring": "ಗರ್ಭಪಾತದ ನಿರ್ವಹಣೆ",
    "Help Line": "ಸಹಾಯ ಲೈನ್",
"Current Appointment": "ಪ್ರಸ್ತುತ ಭೇಟಿಗೆ",
"No Upcoming Appointments": "ಮುಂಬರುವ ಭೇಟಿಗಳು ಇಲ್ಲ",
"Time": "ಸಮಯ",
"Status": "ಸ್ಥಿತಿ",
"Reason": "ಕಾರಣ",
"Cancel Appointment": "ಬೇಟಿಯನ್ನು ರದ್ದುಗೊಳಿಸಿ",
"Show Appointment": "ಬೇಟಿಯನ್ನು ತೋರಿಸಿ",
"My Appointments": "ನನ್ನ ಭೇಟಿಗಳು",
"Appointment Status": "ಬೇಟಿ ಸ್ಥಿತಿ",
"App Info": "ಆಪ್ ಮಾಹಿತಿ",
"CHECK FOR UPDATES": "ನವೀಕರಣಗಳನ್ನು ಪರಿಶೀಲಿಸಿ",
"Edit Profile": "ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ",
"Help": "ಸಹಾಯ",
"Tell us what's going on": "ನಡೆಯುತ್ತಿರುವುದು ನಮಗೆ ತಿಳಿಸಿ",
"Tell us why you're reaching us": "ನೀವು ನಮಗೆ ಏಕೆ ತಲುಪುತ್ತಿರುವಿರಿ ಎಂಬುದನ್ನು ತಿಳಿಸಿ",
"How do you feel? (Optional)": "ನೀವು ಹೇಗಾಗಿದ್ದೀರಿ? (ಐಚ್ಛಿಕ)",
"My Hospital": "ನನ್ನ ಆಸ್ಪತ್ರೆಗೆ",
"No hospitals found": "ಆಸ್ಪತ್ರೆಗಳು ಸಿಗಲಿಲ್ಲ",
"District:": "ಜಿಲ್ಲೆ:",
"Settings": "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
"English": "ಇಂಗ್ಲಿಷ್",
"Logout Successful": "ಯಶಸ್ವಿಯಾಗಿ ಲಾಗ್‌ಔಟ್ ಆಯಿತು",
"Subscribe": "ಚಂದಾದಾರರಾಗಿರಿ",
"Subscription": "ಚಂದಾ",
"Current Plan": "ಪ್ರಸ್ತುತ ಯೋಜನೆ",
"Monthly": "ಮಾಸಿಕ",
"Yearly": "ವಾರ್ಷಿಕ",
"Based on patient reviews": "ರೋಗಿಗಳ ವಿಮರ್ಶೆಗಳ ಆಧಾರದಲ್ಲಿ",
"Working Hours": "ಕೆಲಸದ ಸಮಯ",
"Contact Information": "ಸಂಪರ್ಕ ಮಾಹಿತಿ",
"Personalised Pregnancy Care": "ವೈಯಕ್ತಿಕ ಗರ್ಭಧಾರಣೆಯ ಆರೈಕೆ",
"Helps you to consult Doctor Virtually": "ನಿಮಗೆ ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ",
"Engage with Doctor through video and audio": "ವೀಡಿಯೋ ಮತ್ತು ಆಡಿಯೊ ಮೂಲಕ ವೈದ್ಯರೊಂದಿಗೆ ಸಂವಾದಿಸಿ",
"Keep on track your Health": "ನಿಮ್ಮ ಆರೋಗ್ಯವನ್ನು ಹಾದಿಯಲ್ಲಿಡಿ",
"By continuing, You agree that you have read and accept our": "ಮುಂದುವರಿಸುವ ಮೂಲಕ, ನೀವು ನಮ್ಮದನ್ನು ಓದಿದ್ದು ಮತ್ತು ಒಪ್ಪಿಕೊಂಡಿರುವಿರಿ",
"T&C and Privacy Policy": "ನಿಯಮಗಳು ಮತ್ತು ಗೌಪ್ಯತಾ ನೀತಿ",
"Thinking...": "ಯೋಚಿಸುತ್ತಿದೆ...",
"Your maternal AI assistant is processing your question": "ನಿಮ್ಮ ತಾಯಿ AI ಸಹಾಯಕನನ್ನು ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುತ್ತಿದೆ",
"Your Maternal AI Assistant": "ನಿಮ್ಮ ತಾಯಿ AI ಸಹಾಯಕ",
"Welcome to Allobot!": "ಅಲ್ಲೋಬಾಟ್‌ಗೆ ಸುಸ್ವಾಗತ!",
"I'm here to support you through your maternal journey. Ask me anything about pregnancy, childbirth, or early motherhood.": "ನಾನು ನಿಮ್ಮ ತಾಯಿ ಪ್ರವಾಸದಲ್ಲಿ ನಿಮಗೆ ಬೆಂಬಲ ನೀಡಲು ಇಲ್ಲಿ ಇದ್ದೇನೆ. ಗರ್ಭಧಾರಣೆ, ಹೆರಿಗೆ ಅಥವಾ ಪ್ರಾರಂಭಿಕ ತಾಯ್ತನದ ಬಗ್ಗೆ ನನಗೆ ಯಾವುದೇ ಪ್ರಶ್ನೆ ಕೇಳಿ.",
"What You Can Ask Me:": "ನನಗೆ ನೀವು ಕೇಳಬಹುದಾದವು:",
"Pregnancy health tips": "ಗರ್ಭಧಾರಣೆಯ ಆರೋಗ್ಯ ಸಲಹೆಗಳು",
"Nutrition advice": "ಪೋಷಣೆಯ ಸಲಹೆ",
"Baby care basics": "ಮಗು ಆರೈಕೆ ಮೂಲಭೂತ",
"Trimester milestones": "ತ್ರೈಮಾಸಿಕ ಮೈಲುಗಲ್ಲುಗಳು",
"Ask Allobot...": "ಅಲ್ಲೋಬಾಟ್ ಅನ್ನು ಕೇಳಿ...",
"Incoming Call": "ಒಳಹರಿವು ಕಾಲ್",
"Waiting": "ಕಾಯುತ್ತಿದೆ",
"No messages yet": "ಇನ್ನೂ ಸಂದೇಶಗಳಿಲ್ಲ",
"Tablets": "ಮಾತ್ತಿಗಳು",
"Units": "ಘಟಕಗಳು",
"Timing": "ಸಮಯ",
"No prescriptions found.": "ಮಾರ್ಗದರ್ಶಿಗಳು ಸಿಗಲಿಲ್ಲ",
"No description available": "ವಿವರಣೆ ಲಭ್ಯವಿಲ್ಲ",
"No reports found": "ವರದಿಗಳು ಸಿಗಲಿಲ್ಲ",
"Report Details": "ವರದಿ ವಿವರಗಳು",
"Unknown Report Type": "ಅಜ್ಞಾತ ವರದಿ ಪ್ರಕಾರ",
"Test Results": "ಪರೀಕ್ಷಾ ಫಲಿತಾಂಶಗಳು",
"Delete Report": "ವರದಿಯನ್ನು ಅಳಿಸಿ",
"Are you sure you want to delete this report?": "ನೀವು ಈ ವರದಿಯನ್ನು ಅಳಿಸಲು ಖಚಿತವಾಗಿದ್ದೀರಾ?",
"CANCEL": "ರದ್ದುಗೊಳಿಸಿ",
"DELETE": "ಅಳಿಸಿ",
"Normal": "ಸಾಮಾನ್ಯ",
"Body pain": "ದೇಹದ ನೋವು",
"Burning Stomach": "ಜ್ವಾಲೆ ಹೊಡೆಯುತ್ತಿರುವ ಹೊಟ್ಟೆ",
"Cold cough": "ಚಳಿ ಕೆಮ್ಮು",
"Dizziness": "ತಲೆಚುಚ್ಚು",
"Headache": "ತಲೆನೋವು",
"Vomiting": "ಓಕು",
"Other": "ಇತರೆ",
"Blood Pressure": "ರಕ್ತದ ಒತ್ತಡ",
"Temperature": "ತಾಪಮಾನ",
"Blood Saturation": "ರಕ್ತದ ಪ್ರತ್ಯೇಕತೆ",
"Blood Glucose": "ರಕ್ತ ಗ್ಲೂಕೋಸ್",
"BMI": "ಬಿಎಮ್‌ಐ",
"HRV": "ಎಚ್ಆರ್‌ವಿ",
"Baby Cry Not Detected.": "ಮಗು ಅಳುವುದನ್ನು ಪತ್ತೆಹಚ್ಚಲಾಗಲಿಲ್ಲ.",
"The baby cry detection process failed. Please check your connection or try again.": "ಮಗು ಅಳುವ ಪತ್ತೆಹಚ್ಚುವ ಪ್ರಕ್ರಿಯೆ ವಿಫಲವಾಯಿತು. ದಯವಿಟ್ಟು ನಿಮ್ಮ ಸಂಪರ್ಕವನ್ನು ಪರಿಶೀಲಿಸಿ ಅಥವಾ ಮರುಪ್ರಯತ್ನಿಸಿ.",
"Retry": "ಮರುಪ್ರಯತ್ನಿಸಿ",
"Please select Appointment Date": "ಬೇಟಿ ದಿನಾಂಕವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
"Please enter Diagnosis Description": "ರೋಗನಿರ್ಣಯದ ವಿವರವನ್ನು ನಮೂದಿಸಿ",
"No data available": "ಮಾಹಿತಿ ಲಭ್ಯವಿಲ್ಲ",
"Pregnant": "ಗರ್ಭಿಣಿ",
"Not Pregnant": "ಗರ್ಭಿಣಿ ಅಲ್ಲ",
"Summary": "ಸಾರಾಂಶ",
"Upcoming Appointments": "ಮುಂಬರುವ ಭೇಟಿಗಳು",
"No appointments scheduled": "ಯಾವುದೇ ಭೇಟಿಗಳನ್ನು ಗುರ್ತಿಸಲಾಗಿಲ್ಲ",
"No": "ಇಲ್ಲ",
"Yes": "ಹೌದು",
"No appointments found": "ಯಾವುದೇ ಭೇಟಿಗಳು ಸಿಗಲಿಲ್ಲ",
"JioVio Healthcare": "ಜಿಯೋವಿಯೋ ಆರೋಗ್ಯ",
"General Details": "ಸಾಮಾನ್ಯ ವಿವರಗಳು",
"Partner Details": "ಭಾಗಿದಾರರ ವಿವರಗಳು",
"Pregnancy Details": "ಗರ್ಭಧಾರಣೆಯ ವಿವರಗಳು",
"Address Details": "ವಿಳಾಸದ ವಿವರಗಳು",
"Contact Us": "ನಮಗೆ ಸಂಪರ್ಕಿಸಿ",
"Something not Working": "ಏನೋ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತಿಲ್ಲ",
"Feature Request": "ವೈಶಿಷ್ಟ್ಯಯ ವಿನಂತಿ",
"Question": "ಪ್ರಶ್ನೆ",
"FeedBack": "ಅಭಿಪ್ರಾಯ",
"SEND": "ಕಳುಹಿಸಿ",
"My Subscription": "ನನ್ನ ಚಂದಾ",
"Language": "ಭಾಷೆ",
"Terms & Conditions": "ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳು",
"Privacy Policy": "ಗೌಪ್ಯತಾ ನೀತಿ",
"Log Out": "ಲಾಗ್ ಔಟ್",
"Are you sure to logout?": "ನೀವು ಲಾಗ್ ಔಟ್ ಮಾಡಲು ಖಚಿತವಾಗಿದ್ದೀರಾ?",
"Cancel": "ರದ್ದುಗೊಳಿಸಿ",
"Ok": "ಸರಿ",
"Change Default": "ಪೂರ್ವನಿಯೋಜಿತವನ್ನು ಬದಲಿಸಿ",
"Write Description": "ವಿವರವನ್ನು ಬರೆಯಿರಿ",
"Please enter Description": "ವಿವರವನ್ನು ನಮೂದಿಸಿ",
"Door No": "ಬಾಗಿಲು ಸಂಖ್ಯೆ",
"Please enter Door No": "ಬಾಗಿಲು ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
"Street Name": "ರಸ್ತೆ ಹೆಸರು",
"Please enter Street Name": "ರಸ್ತೆ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
"Pincode": "ಪಿನ್‌ ಕೋಡ್",
"Please enter Pincode": "ಪಿನ್‌ ಕೋಡ್ ಅನ್ನು ನಮೂದಿಸಿ",
"Search Area": "ಹುಡುಕಾಟ ಪ್ರದೇಶ",
"Select Area Name": "ಪ್ರದೇಶದ ಹೆಸರನ್ನು ಆಯ್ಕೆಮಾಡಿ",
"Enter your Name": "ನಿಮ್ಮ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
"Please enter your name": "ನಿಮ್ಮ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
"Enter Email Id": "ಇಮೇಲ್ ಐಡಿಯನ್ನು ನಮೂದಿಸಿ",
"Please Select Gender": "ಲಿಂಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
"Age": "ವಯಸ್ಸು",
"Please enter age": "ವಯಸ್ಸು ನಮೂದಿಸಿ",
"Please enter correct age": "ಸರಿಯಾದ ವಯಸ್ಸು ನಮೂದಿಸಿ",
"LMP Date": "ಎಲ್ಎಂಪಿ ದಿನಾಂಕ",
"Please enter LMP Date": "ಎಲ್ಎಂಪಿ ದಿನಾಂಕವನ್ನು ನಮೂದಿಸಿ",
"ED Date": "ಇಡಿ ದಿನಾಂಕ",
"Date of delivery": "ವಿತರಣಾ ದಿನಾಂಕ",
"Please enter Delivery Date": "ವಿತರಣಾ ದಿನಾಂಕವನ್ನು ನಮೂದಿಸಿ",
"Please enter Partner Name": "ಭಾಗಿದಾರರ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
"Partner Name": "ಭಾಗಿದಾರರ ಹೆಸರು",
"Please enter Partner Mobile Number": "ಭಾಗಿದಾರರ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
"Partner Mobile Number": "ಭಾಗಿದಾರರ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
"Bed Time": "ಮಲಗುವ ಸಮಯ",
"Please enter Date of Birth": "ಜನ್ಮ ದಿನಾಂಕವನ್ನು ನಮೂದಿಸಿ",
"Wake Up Time": "ಎದ್ದ ಮೇಲಿನ ಸಮಯ",
"Name": "ಹೆಸರು",
"Please Select Parent Type": "ಪೋಷಕ ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
"Parent Type": "ಪೋಷಕ ಪ್ರಕಾರ",
"Please Select Pregnant Status": "ಗರ್ಭಿಣಿ ಸ್ಥಿತಿಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
"Please enter Area": "ಪ್ರದೇಶವನ್ನು ನಮೂದಿಸಿ",
"Area": "ಪ್ರದೇಶ",
"Services": "ಸೇವೆಗಳು",
"AlloBaby": "ಅಲೋಬೆಬಿ",
"Awareness": "ಜಾಗೃತಿ",
"Screening": "ಪರಿಶೀಲನೆ",
"Glucose Test": "ಗ್ಲೂಕೋಸ್ ಪರೀಕ್ಷೆ",
"Ultrasound Test": "ಅಲ್ಟ್ರಾಸೌಂಡ್ ಪರೀಕ್ಷೆ",
"Urine Test": "ಮೂತ್ರ ಪರೀಕ್ಷೆ"
};
