final Map<String, String> ka = {
    "Select Language"	:	"ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
"Enter Mobile Number"	:	"ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ",
"SEND OTP"	:	"ಒಟಿಪಿ ಕಳುಹಿಸಿ",
"How do you feel today ?"	:	"ಇವತ್ತು ನಿಮಗೆ ಹೇಗನಿಸುತ್ತಿದೆ?",
"Online"	:	"ಆನ್ಲೈನ್",
"Offline"	:	"ಆಫ್ಲೈನ್",
"Image Uploaded"	:	"ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಲಾಗಿದೆ",
"Type a message"	:	"ಸಂದೇಶವನ್ನು ಟೈಪ್ ಮಾಡಿ",
"Choose photo from"	:	"ಚಿತ್ರವನ್ನು ಆರಿಸು",
"Get Connected with doctors"	:	"ವೈದ್ಯರೊಂದಿಗೆ ಸಂಪರ್ಕ ಸಾಧಿಸಿ",
"Connect with Doctor"	:	"ವೈದ್ಯರೊಂದಿಗೆ ಸಂಪರ್ಕ ಸಾಧಿಸಿ",
"Connect with Health worker"	:	"ಆರೋಗ್ಯ ಕಾರ್ಯಕರ್ತರೊಂದಿಗೆ ಸಂಪರ್ಕ ಸಾಧಿಸಿ",
"Connect with AlloBot"	:	"ಅಲ್ಲೋಬಾಟ್‌ ಜೊತೆ ಸಂಪರ್ಕಿಸು",
"Sorry No Awareness Post"	:	"ಕ್ಷಮಿಸಿ, ಜಾಗೃತಿ ಪೋಸ್ಟ್ ಇಲ್ಲ",
"Checkup Completed"	:	"ಚೆಕ್‌ಅಪ್ ಪೂರ್ಣಗೊಂಡಿದೆ",
"Waiting for Doctor Feedback"	:	"ವೈದ್ಯರ ಪ್ರತಿಕ್ರಿಯೆಗಾಗಿ ಕಾಯುತ್ತಿದೆ",
"Checkup need to be done"	:	"ತಪಾಸಣೆ ಮಾಡಬೇಕಾಗಿದೆ",
"Checkup"	:	"ಚೆಕ್‌ಅಪ್",
"No Checkup Found"	:	"ಚೆಕ್‌ಅಪ್ ಕಂಡುಬಂದಿಲ್ಲ",
"Checkup Details"	:	"ತಪಾಸಣೆ ವಿವರಗಳು",
"Doctor Name"	:	"ವೈದ್ಯರ ಹೆಸರು",
"Date"	:	"ದಿನಾಂಕ",
"Health Status"	:	"ಆರೋಗ್ಯ ಸ್ಥಿತಿ",
"Case Summary"	:	"ಕೇಸ್ ಸಾರಾಂಶ",
"Prescription"	:	"ಊರಿಕೆ",
"Next Appointment Time"	:	"ಮುಂದಿನ ಅಪಾಯಿಂಟ್ಮೆಂಟ್ ಸಮಯ",
"Symptoms"	:	"ಲಕ್ಷಣಗಳು",
"Vitals"	:	"ಜೀವಾಧಾರಗಳು",
"Add Prescription"	:	"ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಸೇರಿಸು",
"ADD PRESCRIPTION"	:	"ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಸೇರಿಸು",
"Click to Add Image"	:	"ಇಮೇಜ್ ಸೇರಿಸಲು ಕ್ಲಿಕ್ ಮಾಡಿ",
"View Prescription"	:	"ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ವೀಕ್ಷಿಸಿ",
"Error loading image"	:	"ಇಮೇಜ್ ಲೋಡ್ ಮಾಡುವಾಗ ದೋಷ",
"Prescription Type"	:	"ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಪ್ರಕಾರ",
"Date Added"	:	"ಸೇರಿಸಲಾದ ದಿನಾಂಕ",
"Description"	:	"ವಿವರಣೆ",
"Add Report"	:	"ವರದಿ ಸೇರಿಸಿ",
"NO IMAGE"	:	"ಚಿತ್ರ ಇಲ್ಲ",
"Click Add Image Button"	:	"ಇಮೇಜ್ ಸೇರಿಸು ಬಟನ್ ಕ್ಲಿಕ್ ಮಾಡಿ",
"ADD IMAGE"	:	"ಚಿತ್ರ ಸೇರಿಸಿ",
"ADD REPORT"	:	"ವರದಿ ಸೇರಿಸಿ",
"Report"	:	"ವರದಿ",
"Scan and Add new Report"	:	"ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ಹೊಸ ವರದಿ ಸೇರಿಸಿ",
"Self Screening"	:	"ಸ್ವಯಂ ಸ್ಕ್ರೀನಿಂಗ್",
"BACK"	:	"ಹಿಂದು",
"NEXT"	:	"ಮುಂದೆ",
"Finish"	:	"ಮುಗಿಯಿರಿ",
"Summary Report"	:	"ಸಾರಾಂಶ ವರದಿ",
"Submit"	:	"ಸಲ್ಲಿಸಿ",
"Let's begin the test"	:	"ಪರೀಕ್ಷೆಯನ್ನು ಪ್ರಾರಂಭಿಸೋಣ",
"Hemoglobin Test"	:	"ಹಿಮೋಗ್ಲೋಬಿನ್ ಪರೀಕ್ಷೆ",
"Easily get your Reading by Performing the scans below"	:	"ಕೆಳಗಿನ ಸ್ಕ್ಯಾನ್‌ಗಳನ್ನು ನಿರ್ವಹಿಸುವ ಮೂಲಕ ನಿಮ್ಮ ಓದುವಿಕೆಯನ್ನು ಸುಲಭವಾಗಿ ಪಡೆಯಿರಿ",
"Fetal Monitoring"	:	"ಭ್ರೂಣದ ಮಾನಿಟರಿಂಗ್",
"Upload Report"	:	"ವರದಿಯನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
"Tap to Change"	:	"ಬದಲಾಯಿಸಲು ಟ್ಯಾಪ್ ಮಾಡಿ",
"Heart Rate"	:	"ಹೃದಯ ಬಡಿತ",
"BPM"	:	"ಬಿಪಿಎಂ",
"Kick Count"	:	"ಕಿಕ್ ಕೌಂಟ್",
"Tap to Increase the Count"	:	"ಎಣಿಕೆಯನ್ನು ಹೆಚ್ಚಿಸಲು ಟ್ಯಾಪ್ ಮಾಡಿ",
"Add Glucose Report"	:	"ಗ್ಲೂಕೋಸ್ ವರದಿಯನ್ನು ಸೇರಿಸಿ",
"Blood Glucose Value"	:	"ರಕ್ತದ ಗ್ಲೂಕೋಸ್ ಮೌಲ್ಯ",
"Add Hemoglobin Report"	:	"ಹಿಮೋಗ್ಲೋಬಿನ್ ವರದಿಯನ್ನು ಸೇರಿಸಿ",
"Hemoglobin Value"	:	"ಹಿಮೋಗ್ಲೋಬಿನ್ ಮೌಲ್ಯ",
"Ultra Sound"	:	"ಅಲ್ಟ್ರಾಸೌಂಡ್",
"Fasting"	:	"ಉಪವಾಸ",
"At rest"	:	"ವಿಶ್ರಾಂತಿಯಲ್ಲಿ",
"After Walk"	:	"ವಾಕ್ ನಂತರ",
"Select Height"	:	"ಎತ್ತರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
"Select Weight"	:	"ತೂಕವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
"After walk"	:	"ನಡಿಗೆಯ ನಂತರ",
"Address Information"	:	"ವಿಳಾಸ ಮಾಹಿತಿ",
"Search"	:	"ಹುಡುಕು",
"Continue"	:	"ಮುಂದುವರಿಸಿ",
"Phone Number"	:	"ದೂರವಾಣಿ ಸಂಖ್ಯೆ",
"Profile Details"	:	"ಪ್ರೊಫೈಲ್ ವಿವರಗಳು",
"Gender"	:	"ಲಿಂಗ",
"Male"	:	"ಗಂಡು",
"Female"	:	"ಹೆಣ್ಣು",
"Select Blood Group"	:	"ರಕ್ತದ ಗುಂಪನ್ನು ಆಯ್ಕೆಮಾಡಿ",
"Select Last cycle Date"	:	"ಕೊನೆಯ ಚಕ್ರ ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ",
"Are you my mom or dad?"	:	"ನೀವು ನನ್ನ ತಾಯಿ ಅಥವಾ ತಂದೆಯೇ?",
"Dad"	:	"ಅಪ್ಪ",
"Mom"	:	"ಅಮ್ಮಾ",
"Enter your Partner Details"	:	"ನಿಮ್ಮ ಸಂಗಾತಿಯ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ",
"Pregnancy Status"	:	"ಗರ್ಭಧಾರಣೆಯ ಸ್ಥಿತಿ",
"Partner Pregnancy Status"	:	"ಸಂಗಾತಿಯ ಗರ್ಭಧಾರಣೆಯ ಸ್ಥಿತಿ",
"Average Length of Cycles"	:	"ಚಕ್ರಗಳ ಸರಾಸರಿ ಉದ್ದ",
"Day"	:	"ದಿನ",
"Not yet started"	:	"ಇನ್ನೂ ಪ್ರಾರಂಭವಾಗಿಲ್ಲ",
"NORMAL"	:	"ಸಾಮಾನ್ಯ",
"Health Status"	:	"ಆರೋಗ್ಯ ಸ್ಥಿತಿ",
"Last Screened"	:	"ಕೊನೆಯದಾಗಿ ಪರೀಕ್ಷಿಸಲಾಗಿದೆ",
"GOLD"	:	"ಚಿನ್ನ",
"Subscription Plan"	:	"ಚಂದಾದಾರಿಕೆ ಯೋಜನೆ",
"No News Feed"	:	"ಸುದ್ದಿ ಫೀಡ್ ಇಲ್ಲ",
"Probable Reason"	:	"ಸಂಭವನೀಯ ಕಾರಣ",
"Recommendations"	:	"ಶಿಫಾರಸುಗಳು",
"Hi!"	:	"ನಮಸ್ತೆ!",
"How do you feel today?"	:	"ಇಂದು ನಿಮಗೆ ಹೇಗನಿಸುತ್ತದೆ?",
"Select Exercise that have you done today?"	:	"ನೀವು ಇಂದು ಮಾಡಿದ ವ್ಯಾಯಾಮವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ?",
"None"	:	"ಯಾವುದೂ ಇಲ್ಲ",
"Select tablets that you have taken"	:	"ನೀವು ತೆಗೆದುಕೊಂಡಿರುವ ಮಾತ್ರೆಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ",
"Sleep Duration"	:	"ನಿದ್ರೆಯ ಅವಧಿ",
"Do you have any of these Symptoms?"	:	"ನೀವು ಈ ಯಾವುದೇ ರೋಗಲಕ್ಷಣಗಳನ್ನು ಹೊಂದಿದ್ದೀರಾ?",
"Baby Voice is Recording"	:	"ಬೇಬಿ ವಾಯ್ಸ್ ರೆಕಾರ್ಡಿಂಗ್ ಆಗುತ್ತಿದೆ",
"STOP"	:	"ನಿಲ್ಲಿಸು",
"Click the Record Button to Start Recording"	:	"ರೆಕಾರ್ಡಿಂಗ್ ಪ್ರಾರಂಭಿಸಲು ದಾಖಲೆ ಬಟನ್ ಕ್ಲಿಕ್ ಮಾಡಿ",
"Record"	:	"ದಾಖಲೆ",
"How many Glass of water have you drunk today?"	:	"ನೀವು ಇಂದು ಎಷ್ಟು ಲೋಟ ನೀರು ಕುಡಿದಿದ್ದೀರಿ?",
"OTP Verification"	:	"OTP ಪರಿಶೀಲನೆ",
"Enter OTP sent to"	:	"ಗೆ ಕಳುಹಿಸಲಾದ OTP ನಮೂದಿಸಿ",
"Verify and proceed"	:	"ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಮುಂದುವರಿಯಿರಿ",
"Appointment"	:	"ನೇಮಕಾತಿ",
"Select Hospital"	:	"ಆಸ್ಪತ್ರೆ ಆಯ್ಕೆಮಾಡಿ",
"Select Doctor"	:	"ವೈದ್ಯರನ್ನು ಆಯ್ಕೆಮಾಡಿ",
"Appointment Date"	:	"ನೇಮಕಾತಿ ದಿನಾಂಕ",
"Available slots"	:	"ಲಭ್ಯವಿರುವ ಸ್ಲಾಟ್ ಗಳು",
"No Slots Available"	:	"ಯಾವುದೇ ಸ್ಲಾಟ್ ಗಳು ಲಭ್ಯವಿಲ್ಲ",
"View Available Slots"	:	"ಲಭ್ಯವಿರುವ ಸ್ಲಾಟ್ ಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
"Start time Slot"	:	"ಪ್ರಾರಂಭ ಸಮಯ ಸ್ಲಾಟ್",
"Diagnosis Description"	:	"ರೋಗನಿರ್ಣಯದ ವಿವರಣೆ",
"Book"	:	"ಪುಸ್ತಕ",
"Update"	:	"ನವೀಕರಿಸಿ",
"Respiratory Rate"	:	"ಉಸಿರಾಟದ ದರ",
"Appointments"	:	"ನೇಮಕಾತಿಗಳು",
"As a companion in your pregnancy we help you with the following"	:	"ನಿಮ್ಮ ಗರ್ಭಾವಸ್ಥೆಯಲ್ಲಿ ಒಡನಾಡಿಯಾಗಿ ನಾವು ಈ ಕೆಳಗಿನವುಗಳೊಂದಿಗೆ ನಿಮಗೆ ಸಹಾಯ ಮಾಡುತ್ತೇವೆ",
"Book An Appointment"	:	"ನೇಮಕಾತಿಯನ್ನು ಕಾಯ್ದಿರಿಸಿ",
"Pregnancy Monitoring"	:	"ಪ್ರೆಗ್ನೆನ್ಸಿ ಮಾನಿಟರಿಂಗ್",
"Help Line"	:	"ಸಹಾಯ ಲೈನ್",
"Current Appointment"	:	"ಪ್ರಸ್ತುತ ನೇಮಕಾತಿ",
"No Upcoming Appointments"	:	"ಯಾವುದೇ ಮುಂಬರುವ ನೇಮಕಾತಿಗಳಿಲ್ಲ",
"Time"	:	"ಸಮಯ",
"Status"	:	"ಸ್ಥಿತಿ",
"Reason"	:	"ಕಾರಣ",
"Cancel Appointment"	:	"ನೇಮಕಾತಿ ರದ್ದುಗೊಳಿಸಿ",
"Show Appointment"	:	"ನೇಮಕಾತಿ ತೋರಿಸು",
"My Appointments"	:	"ನನ್ನ ನೇಮಕಾತಿಗಳು",
"Appointment Status"	:	"ನೇಮಕಾತಿ ಸ್ಥಿತಿ",
"App Info"	:	"ಅಪ್ಲಿಕೇಶನ್ ಮಾಹಿತಿ",
"CHECK FOR UPDATES"	:	"ನವೀಕರಣಗಳಿಗಾಗಿ ಪರಿಶೀಲಿಸಿ",
"Edit Profile"	:	"ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ",
"Help"	:	"ಸಹಾಯ",
"Tell us what's going on"	:	"ಏನು ನಡೆಯುತ್ತಿದೆ ಎಂದು ನಮಗೆ ತಿಳಿಸಿ",
"Tell us why you're reaching us"	:	"ನೀವು ನಮ್ಮನ್ನು ಏಕೆ ತಲುಪುತ್ತಿದ್ದೀರಿ ಎಂದು ನಮಗೆ ತಿಳಿಸಿ",
"How do you feel? (Optional)"	:	"ನಿಮಗೆ ಹೇಗನಿಸುತ್ತದೆ? (ಐಚ್ಛಿಕ)",
"My Hospital"	:	"ನನ್ನ ಆಸ್ಪತ್ರೆ",
"No hospitals found"	:	"ಯಾವುದೇ ಆಸ್ಪತ್ರೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
"District"	:	"ಜಿಲ್ಲೆ",
"Settings"	:	"ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
"English"	:	"ಇಂಗ್ಲೀಷ್",
"Logout Successful"	:	"ಲಾಗ್‌ಔಟ್ ಯಶಸ್ವಿಯಾಗಿದೆ",
"Subscribe"	:	"ಚಂದಾದಾರರಾಗಿ",
"Subscription"	:	"ಚಂದಾದಾರಿಕೆ",
"Current Plan"	:	"ಪ್ರಸ್ತುತ ಯೋಜನೆ",
"Monthly"	:	"ಮಾಸಿಕ",
"Yearly"	:	"ವಾರ್ಷಿಕ",
"Based on patient reviews"	:	"ರೋಗಿಯ ವಿಮರ್ಶೆಗಳ ಆಧಾರದ ಮೇಲೆ",
"Working Hours"	:	"ಕೆಲಸದ ಸಮಯ",
"Contact Information"	:	"ಸಂಪರ್ಕ ಮಾಹಿತಿ",
"Personalised Pregnancy Care"	:	"ವೈಯಕ್ತಿಕಗೊಳಿಸಿದ ಗರ್ಭಧಾರಣೆಯ ಆರೈಕೆ",
"Helps you to consult Doctor Virtually"	:	"ವಾಸ್ತವಿಕವಾಗಿ ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಲು ನಿಮಗೆ ಸಹಾಯ ಮಾಡುತ್ತದೆ",
"Engage with Doctor through video and audio"	:	"ವೀಡಿಯೊ ಮತ್ತು ಆಡಿಯೊ ಮೂಲಕ ವೈದ್ಯರೊಂದಿಗೆ ತೊಡಗಿಸಿಕೊಳ್ಳಿ",
"Keep on track your Health"	:	"ನಿಮ್ಮ ಆರೋಗ್ಯವನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
"By continuing, You agree that you have read and accept our"	:	"ಮುಂದುವರಿಸುವ ಮೂಲಕ, ನೀವು ನಮ್ಮದನ್ನು ಓದಿದ್ದೀರಿ ಮತ್ತು ಸ್ವೀಕರಿಸಿದ್ದೀರಿ ಎಂದು ನೀವು ಒಪ್ಪುತ್ತೀರಿ",
"T&C and Privacy Policy"	:	"T&C ಮತ್ತು ಗೌಪ್ಯತೆ ನೀತಿ",
"Thinking..."	:	"ಯೋಚಿಸುತ್ತಿದೆ...",
"Your maternal AI assistant is processing your question"	:	"ನಿಮ್ಮ ತಾಯಿಯ AI ಸಹಾಯಕರು ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುತ್ತಿದ್ದಾರೆ",
"Your Maternal AI Assistant"	:	"ನಿಮ್ಮ ತಾಯಿಯ AI ಸಹಾಯಕ",
"Welcome to Allobot!"	:	"Allobot ಗೆ ಸುಸ್ವಾಗತ!",
"I'm here to support you through your maternal journey. Ask me anything about pregnancy, childbirth, or early motherhood."	:	"ನಿಮ್ಮ ತಾಯಿಯ ಪ್ರಯಾಣದ ಮೂಲಕ ನಿಮ್ಮನ್ನು ಬೆಂಬಲಿಸಲು ನಾನು ಇಲ್ಲಿದ್ದೇನೆ. ಗರ್ಭಾವಸ್ಥೆ, ಹೆರಿಗೆ ಅಥವಾ ಆರಂಭಿಕ ತಾಯ್ತನದ ಬಗ್ಗೆ ನನ್ನನ್ನು ಕೇಳಿ.",
"What You Can Ask Me"	:	"ನೀವು ನನ್ನನ್ನು ಏನು ಕೇಳಬಹುದು:",
"Pregnancy health tips"	:	"ಗರ್ಭಧಾರಣೆಯ ಆರೋಗ್ಯ ಸಲಹೆಗಳು",
"Nutrition advice"	:	"ಪೋಷಣೆಯ ಸಲಹೆ",
"Baby care basics"	:	"ಬೇಬಿ ಕೇರ್ ಮೂಲಗಳು",
"Trimester milestones"	:	"ತ್ರೈಮಾಸಿಕ ಮೈಲಿಗಲ್ಲುಗಳು",
"Ask Allobot..."	:	"ಅಲ್ಲೋಬೋಟ್ ಅವರನ್ನು ಕೇಳಿ",
"Incoming Call"	:	"ಒಳಬರುವ ಕರೆ",
"Waiting"	:	"ಕಾಯುತ್ತಿದೆ",
"No messages yet"	:	"ಇನ್ನೂ ಸಂದೇಶಗಳು ಇಲ್ಲ",
"Tablets"	:	"ಟ್ಯಾಬ್ಲೆಟ್",
"Units"	:	"ಘಟಕಗಳು",
"Timing"	:	"ಟೈಮಿಂಗ್",
"No prescriptions found."	:	"ಏನೂ ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ಗಳು ದೊರಕುತ್ತಿಲ್ಲ",
"No description available"	:	"ಯಾವುದೇ ವಿವರಣೆ ಲಭ್ಯವಿಲ್ಲ",
"No reports found"	:	"ಯಾವುದೇ ವರದಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
"Report Details"	:	"ವಿವರಗಳನ್ನು ವರದಿ ಮಾಡಿ",
"Unknown Report Type"	:	"ಅಜ್ಞಾತ ವರದಿ ಪ್ರಕಾರ",
"Test Results"	:	"ಪರೀಕ್ಷಾ ಫಲಿತಾಂಶಗಳು",
"Delete Report"	:	"ವರದಿಯನ್ನು ಅಳಿಸಿ",
"Are you sure you want to delete this report?"	:	"ನೀವು ಈ ವರದಿಯನ್ನು ಅಳಿಸಲು ಖಚಿತವಾಗಿದ್ದೀರಾ?",
"CANCEL"	:	"ರದ್ದುಗೊಳಿಸಿ",
"DELETE"	:	"ಅಳಿಸಿ",
"Normal"	:	"ಸಾಮಾನ್ಯ",
"Body pain"	:	"ದೇಹ ನೋವು",
"Burning Stomach"	:	"ಹುಚ್ಚು ಹೊತ್ತ ಹೊಟ್ಟೆ",
"Cold cough"	:	"ಚಳಿ ಮತ್ತುಕ್ಕ",
"Dizziness"	:	"ಚಕ್ರವರ್ತಿ",
"Headache"	:	"ತಲೆನೋವು",
"Vomiting"	:	"ವಾಂತಿ",
"Other"	:	"ಇತರೆ",
"Blood Pressure"	:	"ರಕ್ತದೊತ್ತಡ",
"Temperature"	:	"ತಾಪಮಾನ",
"Blood Saturation"	:	"ರಕ್ತದ ಶುದ್ಧತ್ವ",
"Blood Glucose"	:	"ರಕ್ತದ ಗ್ಲೂಕೋಸ್",
"BMI"	:	"ಶರೀರ ದ್ರವ್ಯ ಮೌಲ್ಯ ಸೂಚಕ",
"HRV"	:	"ಹೃದಯ ಗತಿಯ ವೈವಿಧ್ಯತೆ",
"Baby Cry Not Detected."	:	"ಮಗುವಿನ ಅಳು ಪತ್ತೆಯಾಗಿಲ್ಲ.",
"The baby cry detection process failed. Please check your connection or try again."	:	"ಮಗುವಿನ ಅಳು ಪತ್ತೆ ಪ್ರಕ್ರಿಯೆ ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ನಿಮ್ಮ ಸಂಪರ್ಕವನ್ನು ಪರಿಶೀಲಿಸಿ ಅಥವಾ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
"Retry"	:	"ಮರುಪ್ರಯತ್ನಿಸಿ",
"Please select Appointment Date"	:	"ದಯವಿಟ್ಟು ನೇಮಕಾತಿ ದಿನಾಂಕವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
"Please enter Diagnosis Description"	:	"ದಯವಿಟ್ಟು ರೋಗನಿರ್ಣಯದ ವಿವರಣೆಯನ್ನು ನಮೂದಿಸಿ",
"No data available"	:	"ಯಾವುದೇ ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲ",
"Pregnant"	:	"ಗರ್ಭಿಣಿ",
"Not Pregnant"	:	"ಗರ್ಭಿಣಿ ಅಲ್ಲ",
"Summary"	:	"ಸಾರಾಂಶ",
"Upcoming Appointments"	:	"ಮುಂಬರುವ ನೇಮಕಾತಿಗಳು",
"No appointments scheduled"	:	"ಯಾವುದೇ ನೇಮಕಾತಿಗಳನ್ನು ನಿಗದಿಪಡಿಸಲಾಗಿಲ್ಲ",
"No"	:	"ಸಂ",
"Yes"	:	"ಹೌದು",
"No appointments found"	:	"ಯಾವುದೇ ನೇಮಕಾತಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
"JioVio Healthcare"	:	"JioVio ಹೆಲ್ತ್‌ಕೇರ್",
"General Details"	:	"ಸಾಮಾನ್ಯ ವಿವರಗಳು",
"Partner Details"	:	"ಪಾಲುದಾರರ ವಿವರಗಳು",
"Pregnancy Details"	:	"ಗರ್ಭಧಾರಣೆಯ ವಿವರಗಳು",
"Address Details"	:	"ವಿಳಾಸ ವಿವರಗಳು",
"Contact Us"	:	"ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ",
"Something not Working"	:	"ಏನೋ ಕೆಲಸ ಮಾಡುತ್ತಿಲ್ಲ",
"Feature Request"	:	"ವೈಶಿಷ್ಟ್ಯ ವಿನಂತಿ",
"Question"	:	"ಪ್ರಶ್ನೆ",
"FeedBack"	:	"ಪ್ರತಿಕ್ರಿಯೆ",
"SEND"	:	"ಕಳುಹಿಸು",
"My Subscription"	:	"ನನ್ನ ಚಂದಾದಾರಿಕೆ",
"Language"	:	"ಭಾಷೆ",
"Terms & Conditions"	:	"ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳು",
"Privacy Policy"	:	"ಗೌಪ್ಯತೆ ನೀತಿ",
"Log Out"	:	"ಲಾಗ್ ಔಟ್ ಮಾಡಿ",
"Are you sure to logout?"	:	"ನೀವು ಲಾಗ್ಔಟ್ ಮಾಡಲು ಖಚಿತವಾಗಿರುವಿರಾ?",
"Cancel"	:	"ರದ್ದುಮಾಡಿ",
"Ok"	:	"ಸರಿ",
"Change Default"	:	"ಡೀಫಾಲ್ಟ್ ಬದಲಾಯಿಸಿ",
"Write Description"	:	"ವಿವರಣೆಯನ್ನು ಬರೆಯಿರಿ",
"Please enter Description"	:	"ದಯವಿಟ್ಟು ವಿವರಣೆಯನ್ನು ನಮೂದಿಸಿ",
"Door No"	:	"ಡೋರ್ ನಂ",
"Please enter Door No"	:	"ದಯವಿಟ್ಟು ಬಾಗಿಲು ಸಂಖ್ಯೆ ನಮೂದಿಸಿ",
"Street Name"	:	"ಬೀದಿ ಹೆಸರು",
"Please enter Street Name"	:	"ದಯವಿಟ್ಟು ಗಲ್ಲಿಯ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
"Pincode"	:	"ಪಿನ್‌ಕೋಡ್",
"Please enter Pincode"	:	"ದಯವಿಟ್ಟು ಪಿನ್‌ಕೋಡ್ ನಮೂದಿಸಿ",
"Search Area"	:	"ಹುಡುಕಾಟ ಪ್ರದೇಶ",
"Select Area Name"	:	"ಪ್ರದೇಶದ ಹೆಸರನ್ನು ಆಯ್ಕೆಮಾಡಿ",
"Enter your Name"	:	"ನಿಮ್ಮ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
"Please enter your name"	:	"ದಯವಿಟ್ಟು ನಿಮ್ಮ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
"Enter Email Id"	:	"ಇಮೇಲ್ ಐಡಿ ನಮೂದಿಸಿ",
"Please Select Gender"	:	"ದಯವಿಟ್ಟು ಲಿಂಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
"Age"	:	"ವಯಸ್ಸು",
"Please enter age"	:	"ದಯವಿಟ್ಟು ವಯಸ್ಸನ್ನು ನಮೂದಿಸಿ",
"Please enter correct age"	:	"ದಯವಿಟ್ಟು ಸರಿಯಾದ ವಯಸ್ಸನ್ನು ನಮೂದಿಸಿ",
"LMP Date"	:	"LMP ದಿನಾಂಕ",
"Please enter LMP Date"	:	"ದಯವಿಟ್ಟು LMP ದಿನಾಂಕವನ್ನು ನಮೂದಿಸಿ",
"ED Date"	:	"ED ದಿನಾಂಕ",
"Date of delivery"	:	"ವಿತರಣೆಯ ದಿನಾಂಕ",
"Please enter Delivery Date"	:	"ದಯವಿಟ್ಟು ವಿತರಣಾ ದಿನಾಂಕವನ್ನು ನಮೂದಿಸಿ",
"Please enter Partner Name"	:	"ದಯವಿಟ್ಟು ಪಾಲುದಾರರ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
"Partner Name"	:	"ಪಾಲುದಾರರ ಹೆಸರು",
"Please enter Partner Mobile Number"	:	"ದಯವಿಟ್ಟು ಪಾಲುದಾರರ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
"Partner Mobile Number"	:	"ಪಾಲುದಾರರ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
"Bed Time"	:	"ಮಲಗುವ ಸಮಯ",
"Please enter Date of Birth"	:	"ದಯವಿಟ್ಟು ಹುಟ್ಟಿದ ದಿನಾಂಕವನ್ನು ನಮೂದಿಸಿ",
"Wake Up Time"	:	"ವೇಕ್ ಅಪ್ ಟೈಮ್",
"Name"	:	"ಹೆಸರು",
"Please Select Parent Type"	:	"ದಯವಿಟ್ಟು ಪೋಷಕ ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
"Parent Type"	:	"ಪೋಷಕ ಪ್ರಕಾರ",
"Please Select Pregnant Status"	:	"ದಯವಿಟ್ಟು ಗರ್ಭಿಣಿ ಸ್ಥಿತಿಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
"Please enter Area"	:	"ದಯವಿಟ್ಟು ಪ್ರದೇಶವನ್ನು ನಮೂದಿಸಿ",
"Area"	:	"ಪ್ರದೇಶ",
"Services"	:	"ಸೇವೆಗಳು",
"AlloBaby"	:	"ಅಲೋಬೇಬಿ",
"Awareness"	:	"ಅರಿವು",
"Screening"	:	"ಸ್ಕ್ರೀನಿಂಗ್",
"Glucose Test"	:	"ಸ್ಕ್ರೀನಿಂಗ್",
"Ultrasound Test"	:	"ಅಲ್ಟ್ರಾಸೌಂಡ್ ಪರೀಕ್ಷೆ",
"Urine Test"	:	"ಮೂತ್ರ ಪರೀಕ್ಷೆ",
"Home"	:	"ಮನೆ",
"Service"	:	"ಸೇವೆ",
"Chat"	:	"ಚಾಟ್ ಮಾಡಿ",
"Logout"	:	"ಲಾಗ್ಔಟ್",
"Notification"	:	"ಅಧಿಸೂಚನೆ",
"ON"	:	"ಆನ್ ಆಗಿದೆ",
"OFF"	:	"ಆಫ್ ಆಗಿದೆ",
"ON/OFF"	:	"ಆನ್/ಆಫ್",
"AI Recommendation"	:	"AI ಶಿಫಾರಸು",
"Analyzing your health data..."	:	"ನಿಮ್ಮ ಆರೋಗ್ಯ ಡೇಟಾವನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
"No summary available"	:	"ಯಾವುದೇ ಸಾರಾಂಶ ಲಭ್ಯವಿಲ್ಲ",
"Book Appointment"	:	"ಪುಸ್ತಕ ನೇಮಕಾತಿ",
"SCAN AND ADD REPORT"	:	"ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ಮತ್ತು ವರದಿಯನ್ನು ಸೇರಿಸಿ",
"Allobot"	:	"ಅಲೋಬೋಟ್",
...babycrys
};


final Map<String, String> babycrys = {
"Hunger Crying"	:	"ಹಸಿವು ಅಳುವುದು",
"Sleepy Crying"	:	"ನಿದ್ರೆಯ ಅಳು",
"Pain Crying"	:	"ನೋವು ಅಳುವುದು",
"Discomfort Crying"	:	"ಅಸ್ವಸ್ಥತೆ ಅಳುವುದು",
"Colic Crying"	:	"ಕೊಲಿಕ್ ಅಳುವಿಕೆ",
"Attention Crying"	:	"ಕೊಲಿಕ್ ಅಳುವಿಕೆ",
"Rhythmic, repetitive cries that grow louder if the baby isn't fed. Often accompanied by hand-sucking and rooting behavior."	:	"ಮಗುವಿಗೆ ಆಹಾರವನ್ನು ನೀಡದಿದ್ದರೆ ಲಯಬದ್ಧ, ಪುನರಾವರ್ತಿತ ಅಳುಗಳು ಜೋರಾಗಿ ಬೆಳೆಯುತ್ತವೆ. ಆಗಾಗ್ಗೆ ಕೈ ಚೀಪುವುದು ಮತ್ತು ಬೇರುಬಿಡುವ ನಡವಳಿಕೆಯೊಂದಿಗೆ.",
"A whiny, nasal cry that sounds weaker than a hunger cry, often accompanied by yawning and eye-rubbing."	:	"ಹಸಿವಿನ ಕೂಗಿಗಿಂತ ದುರ್ಬಲವಾದ ಗೊಣಗುವ, ಮೂಗಿನ ಕೂಗು, ಆಗಾಗ್ಗೆ ಆಕಳಿಕೆ ಮತ್ತು ಕಣ್ಣು ಉಜ್ಜುವಿಕೆಯೊಂದಿಗೆ.",
"A sudden, high-pitched, intense cry that comes in bursts with breathing pauses. Often accompanied by physical tension."	:	"ಹಠಾತ್, ಎತ್ತರದ ಕೂಗು, ತೀವ್ರವಾದ ಕೂಗು ಉಸಿರಾಟದ ವಿರಾಮಗಳೊಂದಿಗೆ ಸ್ಫೋಟಗೊಳ್ಳುತ್ತದೆ. ಆಗಾಗ್ಗೆ ದೈಹಿಕ ಉದ್ವೇಗದೊಂದಿಗೆ.",
"A fussy, irritated cry that typically stops when the source of discomfort is addressed."	:	"ಅಸ್ವಸ್ಥತೆಯ ಮೂಲವನ್ನು ಪರಿಹರಿಸಿದಾಗ ಸಾಮಾನ್ಯವಾಗಿ ನಿಲ್ಲುವ ಗಲಾಟೆ, ಕಿರಿಕಿರಿಯ ಕೂಗು.",
"Prolonged, intense crying episodes, typically in the evening, with physical signs of distress."	:	"ದೀರ್ಘಕಾಲದ, ತೀವ್ರವಾದ ಅಳುವ ಪ್ರಸಂಗಗಳು, ಸಾಮಾನ್ಯವಾಗಿ ಸಂಜೆ, ಸಂಕಟದ ದೈಹಿಕ ಚಿಹ್ನೆಗಳೊಂದಿಗೆ.",
"A mild cry that starts softly and increases if ignored, often accompanied by eye contact and reaching out."	:	"ಸೌಮ್ಯವಾದ ಅಳುವಿಕೆಯು ಮೃದುವಾಗಿ ಪ್ರಾರಂಭವಾಗುತ್ತದೆ ಮತ್ತು ನಿರ್ಲಕ್ಷಿಸಿದರೆ ಹೆಚ್ಚಾಗುತ್ತದೆ, ಆಗಾಗ್ಗೆ ಕಣ್ಣಿನ ಸಂಪರ್ಕ ಮತ್ತು ತಲುಪುವಿಕೆಯೊಂದಿಗೆ.",
"Hunger cries are rhythmic, repetitive, and grow louder if the baby isn't fed."	:	"ಹಸಿವಿನ ಕೂಗು ಲಯಬದ್ಧವಾಗಿರುತ್ತದೆ, ಪುನರಾವರ್ತಿತವಾಗಿರುತ್ತದೆ ಮತ್ತು ಮಗುವಿಗೆ ಆಹಾರವನ್ನು ನೀಡದಿದ್ದರೆ ಜೋರಾಗಿ ಬೆಳೆಯುತ್ತದೆ.",
"Babies may also:"	:	"ಶಿಶುಗಳು ಸಹ ಈ ಕೆಳಗಿನವುಗಳನ್ನು ಮಾಡಬಹುದು:",
"• Suck on hands or fingers"	:	"• ಕೈಗಳು ಅಥವಾ ಬೆರಳುಗಳ ಮೇಲೆ ಚೀಪುವುದು",
"• Smack lips, root (turn head searching for a nipple)"	:	"• ತುಟಿಗಳು, ಬೇರುಗಳನ್ನು ಹೊಡೆಯಿರಿ (ಮೊಲೆತೊಟ್ಟನ್ನು ಹುಡುಕುತ್ತಾ ತಲೆಯನ್ನು ತಿರುಗಿಸಿ)",
"• Get fussy even after being comforted"	:	"• ಸಮಾಧಾನಗೊಂಡ ನಂತರವೂ ಗಲಾಟೆ ಮಾಡಿ",
"A whiny, nasal cry that may sound weaker than a hunger cry."	:	"ಹಸಿವಿನ ಕೂಗಿಗಿಂತ ದುರ್ಬಲವಾದ ಗೊಣಗುವ, ಮೂಗಿನ ಕೂಗು.",
"Babies may also:"	:	"ಶಿಶುಗಳು ಸಹ ಈ ಕೆಳಗಿನವುಗಳನ್ನು ಮಾಡಬಹುದು:",
"• Yawn frequently"	:	"• ಆಗಾಗ್ಗೆ ಆಕಳಿಕೆ",
"• Rub their eyes or pull their ears"	:	"• ಕಣ್ಣುಗಳನ್ನು ಉಜ್ಜಿಕೊಳ್ಳಿ ಅಥವಾ ಕಿವಿಗಳನ್ನು ಎಳೆಯಿರಿ",
"• Become fussy and harder to soothe"	:	"• ಗೊಂದಲಮಯವಾಗಿ ಮತ್ತು ಶಮನಗೊಳಿಸಲು ಕಷ್ಟವಾಗುವಂತೆ ಮಾಡಿ",
"A sudden, high-pitched, intense cry that may come in bursts with pauses for breath."	:	"ಹಠಾತ್, ಎತ್ತರದ ಕೂಗು, ತೀವ್ರವಾದ ಕೂಗು ಉಸಿರಾಟದ ವಿರಾಮಗಳೊಂದಿಗೆ ಸ್ಫೋಟಗೊಳ್ಳಬಹುದು.",
"Babies may also:"	:	"ಶಿಶುಗಳು ಸಹ ಈ ಕೆಳಗಿನವುಗಳನ್ನು ಮಾಡಬಹುದು:",
"• Clench fists or arch their back"	:	"• ಮುಷ್ಟಿಗಳನ್ನು ಬಿಗಿಹಿಡಿದು ಅಥವಾ ಬೆನ್ನನ್ನು ಬಾಗಿಸಿ",
"• Become stiff or tense"	:	"• ಗಟ್ಟಿಯಾಗುವುದು ಅಥವಾ ಉದ್ವಿಗ್ನರಾಗುವುದು",
"• Show signs of discomfort (scrunched face, difficulty calming down)"	:	"• ಅಸ್ವಸ್ಥತೆಯ ಚಿಹ್ನೆಗಳನ್ನು ತೋರಿಸಿ (ಮುಖವು ಕುಗ್ಗಿದೆ, ಶಾಂತವಾಗಲು ಕಷ್ಟವಾಗುತ್ತದೆ)",
"A fussy, irritated cry that may stop when the issue is resolved."	:	"ಸಮಸ್ಯೆ ಬಗೆಹರಿದಾಗ ನಿಲ್ಲಬಹುದಾದ ಗಲಾಟೆ, ಕಿರಿಕಿರಿಯ ಕೂಗು.",
"Babies may also:"	:	"ಶಿಶುಗಳು ಸಹ ಈ ಕೆಳಗಿನವುಗಳನ್ನು ಮಾಡಬಹುದು:",
"• Wiggle or squirm a lot"	:	"• ತುಂಬಾ ಗೊಣಗುವುದು ಅಥವಾ ನಡುಗುವುದು",
"• Tug at their clothing or ears"	:	"• ಅವರ ಬಟ್ಟೆ ಅಥವಾ ಕಿವಿಗಳನ್ನು ಎಳೆಯಿರಿ",
"• Appear restless or uneasy"	:	"• ಪ್ರಕ್ಷುಬ್ಧ ಅಥವಾ ಅಹಿತಕರವಾಗಿ ಕಾಣಿ",
"A prolonged, intense, high-pitched cry that often occurs in the evening."	:	"ದೀರ್ಘಕಾಲದ, ತೀವ್ರವಾದ, ಎತ್ತರದ ಕೂಗು ಆಗಾಗ್ಗೆ ಸಂಜೆ ಸಂಭವಿಸುತ್ತದೆ.",
"Babies may also:"	:	"ಶಿಶುಗಳು ಸಹ ಈ ಕೆಳಗಿನವುಗಳನ್ನು ಮಾಡಬಹುದು:",
"• Clench fists, arch their back, or pull up legs"	:	"• ಮುಷ್ಟಿಗಳನ್ನು ಬಿಗಿಹಿಡಿದು, ಬೆನ್ನನ್ನು ಬಾಗಿಸಿ, ಅಥವಾ ಕಾಲುಗಳನ್ನು ಮೇಲಕ್ಕೆ ಎಳೆಯಿರಿ",
"• Have a tense, bloated belly"	:	"• ಉದ್ವಿಗ್ನವಾದ, ಉಬ್ಬಿದ ಹೊಟ್ಟೆಯನ್ನು ಹೊಂದಿರಿ",
"• Be difficult to soothe, even after feeding"	:	"• ಹಾಲುಣಿಸಿದ ನಂತರವೂ ಶಮನಗೊಳಿಸಲು ಕಷ್ಟವಾಗುತ್ತದೆ",
"A mild, whimpering cry that starts softly and gets louder if ignored."	:	"ಸೌಮ್ಯವಾದ, ಗೊಣಗುವ ಕೂಗು ಮೃದುವಾಗಿ ಪ್ರಾರಂಭವಾಗುತ್ತದೆ ಮತ್ತು ನಿರ್ಲಕ್ಷಿಸಿದರೆ ಜೋರಾಗಿರುತ್ತದೆ.",
"Babies may also:"	:	"ಶಿಶುಗಳು ಸಹ ಈ ಕೆಳಗಿನವುಗಳನ್ನು ಮಾಡಬಹುದು:",
"• Make eye contact while crying"	:	"• ಅಳುವಾಗ ಕಣ್ಣಿನ ಸಂಪರ್ಕವನ್ನು ಮಾಡಿಕೊಳ್ಳಿ",
"• Reach out for comfort"	:	"• ಆರಾಮಕ್ಕಾಗಿ ಕೈ ಚಾಚಿ",
"• Stop crying quickly when picked up"	:	"• ಎತ್ತಿಕೊಂಡಾಗ ಬೇಗನೆ ಅಳುವುದನ್ನು ನಿಲ್ಲಿಸಿ",
"Feed Promptly – Responding early prevents excessive crying and makes feeding easier."	:	"ತಕ್ಷಣ ಆಹಾರ ನೀಡಿ - ಬೇಗನೆ ಪ್ರತಿಕ್ರಿಯಿಸುವುದು ಅತಿಯಾದ ಅಳುವಿಕೆಯನ್ನು ತಡೆಯುತ್ತದೆ ಮತ್ತು ಆಹಾರವನ್ನು ಸುಲಭಗೊಳಿಸುತ್ತದೆ.",
"Watch for Hunger Cues – Crying is a late sign; look for early signs like lip-smacking, rooting, sticking out tongue, or sucking on hands."	:	"ಹಸಿವಿನ ಸೂಚನೆಗಳನ್ನು ಗಮನಿಸಿ - ಅಳುವುದು ತಡವಾಗಿ ಬರುವ ಚಿಹ್ನೆ; ತುಟಿ ಬಡಿಯುವುದು, ಬೇರು ಬಿಡುವುದು, ನಾಲಿಗೆಯನ್ನು ಹೊರತೆಗೆಯುವುದು ಅಥವಾ ಕೈಗಳನ್ನು ಚೀಪುವುದು ಮುಂತಾದ ಆರಂಭಿಕ ಚಿಹ್ನೆಗಳನ್ನು ನೋಡಿ.",
"Ensure Proper Latch – If breastfeeding, ensure a deep latch to avoid discomfort."	:	"ಸರಿಯಾದ ಲಾಚ್ ಅನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ - ಸ್ತನ್ಯಪಾನ ಮಾಡುತ್ತಿದ್ದರೆ, ಅಸ್ವಸ್ಥತೆಯನ್ನು ತಪ್ಪಿಸಲು ಆಳವಾದ ಲಾಚ್ ಅನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ.",
"Check Feeding Schedule – Newborns need feeding every 2-3 hours."	:	"ಫೀಡಿಂಗ್ ವೇಳಾಪಟ್ಟಿಯನ್ನು ಪರಿಶೀಲಿಸಿ - ನವಜಾತ ಶಿಶುಗಳಿಗೆ ಪ್ರತಿ 2-3 ಗಂಟೆಗಳಿಗೊಮ್ಮೆ ಆಹಾರದ ಅಗತ್ಯವಿದೆ.",
"Burp Baby After Feeding – Helps prevent gas and fussiness."	:	"ಹಾಲುಣಿಸಿದ ನಂತರ ಮಗುವನ್ನು ಬರ್ಪ್ ಮಾಡಿ - ಗ್ಯಾಸ್ ಮತ್ತು ಗಲಾಟೆಯನ್ನು ತಡೆಯಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
"Look for Sleep Cues Early – Yawning, zoning out, or rubbing eyes signal it's time to sleep."	:	"ನಿದ್ರೆಯ ಸೂಚನೆಗಳನ್ನು ಬೇಗನೆ ಹುಡುಕಿ - ಆಕಳಿಕೆ, ವಲಯ ಮಾಡುವುದು ಅಥವಾ ಕಣ್ಣುಗಳನ್ನು ಉಜ್ಜುವುದು ಇದು ನಿದ್ರೆಯ ಸಮಯ ಎಂದು ಸೂಚಿಸುತ್ತದೆ.",
"Create a Calm Sleep Environment – Dim lights, reduce noise, and use white noise if needed."	:	"ಶಾಂತ ನಿದ್ರೆಯ ವಾತಾವರಣವನ್ನು ರಚಿಸಿ - ಮಂದ ದೀಪಗಳು, ಶಬ್ದವನ್ನು ಕಡಿಮೆ ಮಾಡಿ ಮತ್ತು ಅಗತ್ಯವಿದ್ದರೆ ಬಿಳಿ ಶಬ್ದವನ್ನು ಬಳಸಿ.",
"Use Gentle Rocking – Motion, swaddling, or a pacifier can help."	:	"ಸೌಮ್ಯ ರಾಕಿಂಗ್ ಬಳಸಿ - ಚಲನೆ, ಸ್ವಾಡ್ಲಿಂಗ್ ಅಥವಾ ಪ್ಯಾಸಿಫೈಯರ್ ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
"Follow a Sleep Routine – A consistent bedtime routine helps babies recognize sleep time."	:	"ನಿದ್ರೆಯ ದಿನಚರಿಯನ್ನು ಅನುಸರಿಸಿ - ಸ್ಥಿರವಾದ ಮಲಗುವ ಸಮಯದ ದಿನಚರಿ ಶಿಶುಗಳಿಗೆ ನಿದ್ರೆಯ ಸಮಯವನ್ನು ಗುರುತಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
"Avoid Overstimulation – Too much activity before bed can make sleep harder."	:	"ಅತಿಯಾದ ಪ್ರಚೋದನೆಯನ್ನು ತಪ್ಪಿಸಿ - ಮಲಗುವ ಮೊದಲು ಹೆಚ್ಚಿನ ಚಟುವಟಿಕೆಯು ನಿದ್ರೆಯನ್ನು ಕಷ್ಟಕರವಾಗಿಸುತ್ತದೆ.",
"Check for Obvious Issues – Look for diaper rash, teething pain, or tight clothing."	:	"ಸ್ಪಷ್ಟವಾದ ಸಮಸ್ಯೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ - ಡಯಾಪರ್ ದದ್ದು, ಹಲ್ಲುಜ್ಜುವ ನೋವು ಅಥವಾ ಬಿಗಿಯಾದ ಬಟ್ಟೆಗಳನ್ನು ನೋಡಿ.",
"Soothe with Gentle Touch – Skin-to-skin contact or holding them close can help."	:	"ಸೌಮ್ಯ ಸ್ಪರ್ಶದಿಂದ ಶಮನಗೊಳಿಸಿ - ಚರ್ಮದಿಂದ ಚರ್ಮದ ಸಂಪರ್ಕ ಅಥವಾ ಅವುಗಳನ್ನು ಹತ್ತಿರವಾಗಿ ಹಿಡಿದುಕೊಳ್ಳುವುದು ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
"Try Pain Relief Techniques – For teething, offer a chilled teether; for gas, try tummy massage."	:	"ನೋವು ನಿವಾರಕ ತಂತ್ರಗಳನ್ನು ಪ್ರಯತ್ನಿಸಿ - ಹಲ್ಲುಜ್ಜಲು, ತಂಪಾದ ಹಲ್ಲುಗಳನ್ನು ನೀಡಿ; ಗ್ಯಾಸ್ ಗಾಗಿ, ಹೊಟ್ಟೆಯ ಮಸಾಜ್ ಪ್ರಯತ್ನಿಸಿ.",
"Monitor for Fever or Illness – If crying persists with fever, vomiting, or lethargy, consult a doctor."	:	"ಜ್ವರ ಅಥವಾ ಅನಾರೋಗ್ಯದ ಮೇಲ್ವಿಚಾರಣೆ - ಜ್ವರ, ವಾಂತಿ ಅಥವಾ ಆಲಸ್ಯದೊಂದಿಗೆ ಅಳುವುದು ಮುಂದುವರಿದರೆ, ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.",
"Trust Your Instincts – If the baby seems in severe pain, seek medical advice immediately."	:	"ನಿಮ್ಮ ಪ್ರವೃತ್ತಿಗಳನ್ನು ನಂಬಿ - ಮಗುವು ತೀವ್ರ ನೋವಿನಿಂದ ಬಳಲುತ್ತಿದ್ದರೆ, ತಕ್ಷಣ ವೈದ್ಯಕೀಯ ಸಲಹೆಯನ್ನು ಪಡೆಯಿರಿ.",
"Check the Diaper – A wet or soiled diaper is a common cause of discomfort."	:	"ಡಯಾಪರ್ ಪರಿಶೀಲಿಸಿ - ಒದ್ದೆಯಾದ ಅಥವಾ ಕೊಳೆತ ಡಯಾಪರ್ ಅಸ್ವಸ್ಥತೆಗೆ ಸಾಮಾನ್ಯ ಕಾರಣವಾಗಿದೆ.",
"Ensure Comfortable Clothing – Dress baby in breathable, soft fabrics and check for tight clothing."	:	"ಆರಾಮದಾಯಕ ಬಟ್ಟೆಗಳನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ - ಮಗುವಿಗೆ ಉಸಿರಾಡಬಹುದಾದ, ಮೃದುವಾದ ಬಟ್ಟೆಗಳನ್ನು ಧರಿಸಿ ಮತ್ತು ಬಿಗಿಯಾದ ಬಟ್ಟೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.",
"Adjust Temperature – Feel baby's neck/back to see if they are too hot or cold."	:	"ತಾಪಮಾನವನ್ನು ಸರಿಹೊಂದಿಸಿ - ಮಗುವಿನ ಕುತ್ತಿಗೆ / ಬೆನ್ನು ತುಂಬಾ ಬಿಸಿಯಾಗಿದೆಯೇ ಅಥವಾ ತಣ್ಣಗಿದೆಯೇ ಎಂದು ಭಾವಿಸಿ.",
"Check for External Irritants – Tags, rough fabric, or hair wrapped around fingers/toes can cause irritation."	:	"ಬಾಹ್ಯ ಕಿರಿಕಿರಿಗಳನ್ನು ಪರಿಶೀಲಿಸಿ - ಟ್ಯಾಗ್ ಗಳು, ಒರಟು ಬಟ್ಟೆ, ಅಥವಾ ಬೆರಳುಗಳು / ಕಾಲ್ಬೆರಳುಗಳ ಸುತ್ತಲೂ ಸುತ್ತಿದ ಕೂದಲು ಕಿರಿಕಿರಿಯನ್ನು ಉಂಟುಮಾಡಬಹುದು.",
"Reposition Baby – Changing positions or holding them differently can sometimes help."	:	"ಮಗುವನ್ನು ಮರುಸ್ಥಾಪಿಸಿ - ಸ್ಥಾನಗಳನ್ನು ಬದಲಾಯಿಸುವುದು ಅಥವಾ ಅವುಗಳನ್ನು ವಿಭಿನ್ನವಾಗಿ ಹಿಡಿದಿಟ್ಟುಕೊಳ್ಳುವುದು ಕೆಲವೊಮ್ಮೆ ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
"Use Gentle Motions – Rocking, swaying, or holding baby in a 'colic carry' (on their tummy along your forearm) can help."	:	"ಸೌಮ್ಯ ಚಲನೆಗಳನ್ನು ಬಳಸಿ - ಮಗುವನ್ನು 'ಕೊಲಿಕ್ ಕ್ಯಾರಿ' ಯಲ್ಲಿ (ನಿಮ್ಮ ಮುಂಗೈಯ ಉದ್ದಕ್ಕೂ ಅವರ ಹೊಟ್ಟೆಯ ಮೇಲೆ) ಅಲುಗಾಡಿಸುವುದು, ಅಲುಗಾಡಿಸುವುದು ಅಥವಾ ಹಿಡಿದುಕೊಳ್ಳುವುದು ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
"Try White Noise – Rhythmic sounds, like a fan or heartbeat sound, can be soothing."	:	"ಬಿಳಿ ಶಬ್ದವನ್ನು ಪ್ರಯತ್ನಿಸಿ - ಫ್ಯಾನ್ ಅಥವಾ ಹೃದಯ ಬಡಿತದ ಧ್ವನಿಯಂತಹ ಲಯಬದ್ಧ ಶಬ್ದಗಳು ಹಿತಕರವಾಗಿರುತ್ತವೆ.",
"Burp Baby Well – Gas buildup can make colic worse. Burp frequently during feeds."	:	"ಬರ್ಪ್ ಬೇಬಿ ವೆಲ್ - ಗ್ಯಾಸ್ ನಿರ್ಮಾಣವು ಕೊಲಿಕ್ ಅನ್ನು ಇನ್ನಷ್ಟು ಹದಗೆಡಿಸುತ್ತದೆ. ಫೀಡ್ ಮಾಡುವಾಗ ಆಗಾಗ್ಗೆ ಬರ್ಪ್ ಮಾಡಿ.",
"Massage the Tummy – A gentle circular tummy massage can relieve gas."	:	"ಹೊಟ್ಟೆಯನ್ನು ಮಸಾಜ್ ಮಾಡಿ - ಮೃದುವಾದ ವೃತ್ತಾಕಾರದ ಹೊಟ್ಟೆಯ ಮಸಾಜ್ ಅನಿಲವನ್ನು ನಿವಾರಿಸುತ್ತದೆ.",
"Consult a Pediatrician – If colic persists, discuss options like probiotic drops or diet changes (for breastfeeding moms)."	:	"ಶಿಶುವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ - ಹೊಟ್ಟೆನೋವು ಮುಂದುವರಿದರೆ, ಪ್ರೋಬಯಾಟಿಕ್ ಹನಿಗಳು ಅಥವಾ ಆಹಾರ ಬದಲಾವಣೆಗಳಂತಹ ಆಯ್ಕೆಗಳನ್ನು ಚರ್ಚಿಸಿ (ಹಾಲುಣಿಸುವ ತಾಯಂದಿರಿಗೆ).",
"Respond with Reassurance – Holding, talking, or making eye contact helps babies feel secure."	:	"ಭರವಸೆಯೊಂದಿಗೆ ಪ್ರತಿಕ್ರಿಯಿಸಿ - ಹಿಡಿದಿಟ್ಟುಕೊಳ್ಳುವುದು, ಮಾತನಾಡುವುದು ಅಥವಾ ಕಣ್ಣಿನ ಸಂಪರ್ಕವನ್ನು ಮಾಡುವುದು ಶಿಶುಗಳಿಗೆ ಸುರಕ್ಷಿತ ಭಾವನೆಯನ್ನು ಅನುಭವಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
"Try Gentle Touch – A cuddle or soft pat on the back can be calming."	:	"ಸೌಮ್ಯ ಸ್ಪರ್ಶವನ್ನು ಪ್ರಯತ್ನಿಸಿ - ಬೆನ್ನಿನ ಮೇಲೆ ಮುದ್ದು ಅಥವಾ ಮೃದುವಾದ ತಟ್ಟುವಿಕೆಯು ಶಾಂತವಾಗಬಹುದು.",
"Engage with Soothing Sounds – Humming or talking in a calm voice can reassure the baby."	:	"ಹಿತವಾದ ಶಬ್ದಗಳೊಂದಿಗೆ ತೊಡಗಿಸಿಕೊಳ್ಳಿ - ಹಮ್ಮಿಂಗ್ ಅಥವಾ ಶಾಂತ ಧ್ವನಿಯಲ್ಲಿ ಮಾತನಾಡುವುದು ಮಗುವಿಗೆ ಭರವಸೆ ನೀಡುತ್ತದೆ.",
"Encourage Independent Comforting – Allow baby to self-soothe briefly before immediately responding."	:	"ಸ್ವತಂತ್ರ ಸಾಂತ್ವನವನ್ನು ಪ್ರೋತ್ಸಾಹಿಸಿ - ತಕ್ಷಣ ಪ್ರತಿಕ್ರಿಯಿಸುವ ಮೊದಲು ಮಗುವಿಗೆ ಸಂಕ್ಷಿಪ್ತವಾಗಿ ಸ್ವಯಂ ಶಮನಗೊಳಿಸಲು ಅವಕಾಶ ನೀಡಿ.",
"Maintain a Balance – Meeting attention needs is important, but consistency in response helps babies learn security."	:	"ಸಮತೋಲನವನ್ನು ಕಾಪಾಡಿಕೊಳ್ಳಿ - ಗಮನದ ಅಗತ್ಯಗಳನ್ನು ಪೂರೈಸುವುದು ಮುಖ್ಯ, ಆದರೆ ಪ್ರತಿಕ್ರಿಯೆಯಲ್ಲಿ ಸ್ಥಿರತೆಯು ಶಿಶುಗಳಿಗೆ ಸುರಕ್ಷತೆಯನ್ನು ಕಲಿಯಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.",


"Cry History"	:	"ಕ್ರೈ ಹಿಸ್ಟರಿ",
"Record"	:	"ದಾಖಲೆ",
"Allocry"	:	"ಹಂಚಿಕೆ",
"Baby can cry due to"	:	"ಬೇಬಿ ಕಾರಣ ಅಳಬಹುದು",
"Recording"	:	"ರೆಕಾರ್ಡಿಂಗ್",
"Start Recording"	:	"ರೆಕಾರ್ಡಿಂಗ್ ಪ್ರಾರಂಭಿಸಿ",
"Getting Your Baby Sound…"	:	"ನಿಮ್ಮ ಮಗುವಿನ ಧ್ವನಿಯನ್ನು ಪಡೆಯಲಾಗುತ್ತಿದೆ...",
"Try to avoid background noise"	:	"ಹಿನ್ನೆಲೆ ಶಬ್ದವನ್ನು ತಪ್ಪಿಸಲು ಪ್ರಯತ್ನಿಸಿ",
"High-pitched, intense crying often indicates pain or immediate needs."	:	"ಎತ್ತರದ, ತೀವ್ರವಾದ ಅಳುವುದು ಸಾಮಾನ್ಯವಾಗಿ ನೋವು ಅಥವಾ ತಕ್ಷಣದ ಅಗತ್ಯಗಳನ್ನು ಸೂಚಿಸುತ್ತದೆ.",
"Rhythmic crying that gets louder and softer might mean your baby is tired."	:	"ಲಯಬದ್ಧ ಅಳುವುದು ಗಟ್ಟಿಯಾಗಿ ಮತ್ತು ಮೃದುವಾಗಿ ನಿಮ್ಮ ಮಗು ದಣಿದಿದೆ ಎಂದರ್ಥ.",
"Short, low-pitched cries repeated every few seconds usually signal hunger."	:	"ಪ್ರತಿ ಕೆಲವು ಸೆಕೆಂಡಿಗೆ ಪುನರಾವರ್ತನೆಯಾಗುವ ಸಣ್ಣ, ಕಡಿಮೆ-ಪಿಚ್ ಅಳುವುದು ಸಾಮಾನ್ಯವಾಗಿ ಹಸಿವಿನ ಸಂಕೇತವಾಗಿದೆ.",
"Whimpering or whining sounds might indicate mild discomfort or wanting attention."	:	"ವಿಂಪರಿಂಗ್ ಮತ್ತು ವಿನಿಂಗ್ ಶಬ್ದವು ಸೌಮ್ಯ ಅಸ್ವಸ್ಥತೆ ಅಥವಾ ಗಮನವನ್ನು ಬಯಸುವುದನ್ನು ಸೂಚಿಸುತ್ತದೆ.",
"Long, high-pitched screams could be signs of colic or stomach pain."	:	"ಉದ್ದವಾದ, ಎತ್ತರದ ಕಿರುಚಾಟವು ಉದರಶೂಲೆ ಅಥವಾ ಹೊಟ್ಟೆ ನೋವಿನ ಲಕ್ಷಣಗಳಾಗಿರಬಹುದು.",
"Sudden, sharp cries might mean your baby is too hot or cold."	:	"ಹಠಾತ್, ತೀಕ್ಷ್ಣವಾದ ಅಳುವುದು ನಿಮ್ಮ ಮಗು ತುಂಬಾ ಬಿಸಿಯಾಗಿದೆ ಅಥವಾ ಶೀತವಾಗಿದೆ ಎಂದರ್ಥ.",
"Persistent crying with leg movement often indicates diaper change needs."	:	"ಕಾಲಿನ ಚಲನೆಯೊಂದಿಗೆ ನಿರಂತರ ಅಳುವುದು ಡಯಾಪರ್ ಬದಲಾವಣೆಯ ಅಗತ್ಯಗಳನ್ನು ಸೂಚಿಸುತ್ತದೆ.",
"Baby Cry Not Detected"	:	"ಮಗುವಿನ ಅಳು ಪತ್ತೆಯಾಗಿಲ್ಲ",


};