final Map<String, String> ma = {
    "Select Language": "भाषा निवडा",
    "Enter Mobile Number": "मोबाईल नंबर टाका",
    "SEND OTP": "OTP पाठवा",
    "How do you feel today ?": "तुम्हाला आज कसे वाटत आहे?",
    "Online": "ऑनलाईन",
    "Offline": "ऑफलाईन",
    "Image Uploaded": "प्रतिमा अपलोड केली",
    "Type a message": "संदेश टाइप करा",
    "Choose photo from :": "यामधून फोटो निवडा:",
    "Get Connected with doctors": "डॉक्टरांशी संपर्क साधा",
    "Connect with Doctor": "डॉक्टरशी कनेक्ट व्हा",
    "Connect with Health worker": "आरोग्य कर्मचाऱ्यांशी कनेक्ट व्हा",
    "Connect with AlloBot": "AlloBot शी कनेक्ट व्हा",
    "Sorry No Awareness Post": "क्षमस्व कोणताही जागरूकता पोस्ट नाही",
    "Checkup Completed": "तपासणी पूर्ण झाली",
    "Waiting for Doctor Feedback": "डॉक्टरांच्या प्रतिसादाची वाट पाहत आहे",
    "Checkup need to be done": "तपासणी करणे आवश्यक आहे",
    "Checkup": "तपासणी",
    "No Checkup Found": "कोणतीही तपासणी आढळली नाही",
    "Checkup Details": "तपासणी तपशील",
    "Doctor Name": "डॉक्टरांचे नाव",
    "Date:": "तारीख:",
    "Health Status:": "आरोग्य स्थिती:",
    "Case Summary": "केस सारांश",
    "Prescription": "औषधपत्र",
    "Next Appointment Time": "पुढील भेटीची वेळ",
    "Symptoms": "लक्षणे",
    "Vitals": "महत्वाचे मापदंड",
    "Add Prescription": "औषधपत्र जोडा",
    "ADD PRESCRIPTION": "औषधपत्र जोडा",
    "Click to Add Image": "प्रतिमा जोडण्यासाठी क्लिक करा",
    "View Prescription": "औषधपत्र पहा",
    "Error loading image": "प्रतिमा लोड करण्यात त्रुटी",
    "Prescription Type": "औषधपत्राचा प्रकार",
    "Date Added": "तारीख जोडली",
    "Description": "वर्णन",
    "Add Report": "अहवाल जोडा",
    "NO IMAGE": "प्रतिमा नाही",
    "Click Add Image Button": "प्रतिमा जोडा बटण क्लिक करा",
    "ADD IMAGE": "प्रतिमा जोडा",
    "ADD REPORT": "अहवाल जोडा",
    "Report": "अहवाल",
    "Scan and Add new Report": "स्कॅन करा आणि नवीन अहवाल जोडा",
    "Self Screening": "स्वयं तपासणी",
    "BACK": "मागे",
    "NEXT": "पुढे",
    "Finish": "समाप्त",
    "Summary Report": "सारांश अहवाल",
    "Submit": "सबमिट करा",
    "Let's begin the test": "चला परीक्षा सुरू करूया",
    "Hemoglobin Test": "हिमोग्लोबिन चाचणी",
    "Easily get your Reading by Performing the scans below": "खालील स्कॅन करून तुमचे रीडिंग सहज मिळवा",
    "Fetal Monitoring": "गर्भ निरीक्षण",
    "Upload Report": "अहवाल अपलोड करा",
    "Tap to Change": "बदलण्यासाठी टॅप करा",
    "Heart Rate": "हृदयाचा ठोका",
    "BPM": "बीपीएम",
    "Kick Count": "किक काउंट",
    "Tap to Increase the Count": "संख्या वाढवण्यासाठी टॅप करा",
    "Add Glucose Report": "ग्लुकोज अहवाल जोडा",
    "Blood Glucose Value": "रक्तातील साखरेचे मूल्य",
    "Add Hemoglobin Report": "हिमोग्लोबिन अहवाल जोडा",
    "Hemoglobin Value": "हिमोग्लोबिन मूल्य",
    "Ultra Sound": "अल्ट्रासाउंड",
    "Fasting": "उपवास",
    "At rest": "विश्रांतीत",
    "After Walk": "चालल्यानंतर",
    "Select Height": "उंची निवडा",
    "Select Weight": "वजन निवडा",
    "After walk": "चालल्यानंतर",
    "Address Information": "पत्त्याची माहिती",
    "Search": "शोधा",
    "Continue": "पुढे चला",
    "Phone Number": "फोन नंबर",
    "Profile Details": "प्रोफाइल तपशील",
    "Gender": "लिंग",
    "Male": "पुरुष",
    "Female": "स्त्री",
    "Select Blood Group": "रक्तगट निवडा",
    "Select Last cycle Date": "शेवटच्या चक्राची तारीख निवडा",
    "Are you my mom or dad?": "तुम्ही माझी आई किंवा बाबा आहात का?",
    "Dad": "बाबा",
    "Mom": "आई",
    "Enter your Partner Details": "तुमच्या जोडीदाराचे तपशील प्रविष्ट करा",
    "Pregnancy Status": "गर्भधारणेची स्थिती",
    "Partner Pregnancy Status": "जोडीदाराच्या गर्भधारणेची स्थिती",
    "Average Length of Cycles": "चक्रांची सरासरी लांबी",
    "Day": "दिवस",
    "Not yet started": "अजून सुरू झाले नाही",
    "NORMAL": "सामान्य",
    "Health Status": "आरोग्य स्थिती",
    "Last Screened": "शेवटची तपासणी",
    "GOLD": "सुवर्ण",
    "Subscription Plan": "सदस्यत्व योजना",
    "No News Feed": "कोणतेही न्यूज फीड नाही",
    "Probable Reason": "संभाव्य कारण",
    "Recommendations": "शिफारसी",
    "Hi!": "नमस्कार!",
    "How do you feel today?": "तुम्हाला आज कसे वाटत आहे?",
    "Select Exercise that have you done today?": "तुम्ही आज कोणता व्यायाम केला आहे ते निवडा?",
    "None": "काहीही नाही",
    "Select tablets that you have taken": "तुम्ही घेतलेल्या गोळ्या निवडा",
    "Sleep Duration": "झोपेची कालावधी",
    "Do you have any of these Symptoms?": "तुम्हाला यापैकी कोणती लक्षणे आहेत का?",
    "Baby Voice is Recording": "बाळाचा आवाज रेकॉर्ड होत आहे",
    "STOP": "थांबा",
    "Click the Record Button to Start Recording": "रेकॉर्डिंग सुरू करण्यासाठी रेकॉर्ड बटण क्लिक करा",
    "Record": "रेकॉर्ड",
    "How many Glass of water have you drunk today?": "तुम्ही आज किती ग्लास पाणी प्यालात?",
    "OTP Verification": "OTP पडताळणी",
    "Enter OTP sent to": "पाठवलेला OTP प्रविष्ट करा",
    "Verify and proceed": "पडताळणी करा आणि पुढे जा",
    "Appointment": "अपॉइंटमेंट",
    "Select Hospital": "रुग्णालय निवडा",
    "Select Doctor": "डॉक्टर निवडा",
    "Appointment Date": "अपॉइंटमेंटची तारीख",
    "Available slots": "उपलब्ध स्लॉट्स",
    "No Slots Available": "स्लॉट्स उपलब्ध नाहीत",
    "View Available Slots": "उपलब्ध स्लॉट्स पहा",
    "Start time Slot:": "सुरुवातीची वेळ स्लॉट:",
    "Diagnosis Description": "निदान वर्णन",
    "Book": "बुक करा",
    "Update": "अपडेट करा",
    "Respiratory Rate": "श्वसन दर",
    "Appointments": "अपॉइंटमेंट्स",
    "As a companion in your pregnancy we help you with the following": "तुमच्या गर्भधारणेत सोबती म्हणून आम्ही तुम्हाला खालील गोष्टींमध्ये मदत करतो",
    "Book An Appointment": "अपॉइंटमेंट बुक करा",
    "Pregnancy Monitoring": "गर्भधारणा निरीक्षण",
    "Help Line": "हेल्पलाईन",
    "Current Appointment": "सध्याची अपॉइंटमेंट",
    "No Upcoming Appointments": "कोणत्याही येणाऱ्या अपॉइंटमेंट्स नाहीत",
    "Time": "वेळ",
    "Status": "स्थिती",
    "Reason": "कारण",
    "Cancel Appointment": "अपॉइंटमेंट रद्द करा",
    "Show Appointment": "अपॉइंटमेंट दाखवा",
    "My Appointments": "माझ्या अपॉइंटमेंट्स",
    "Appointment Status": "अपॉइंटमेंटची स्थिती",
    "App Info": "अॅप माहिती",
    "CHECK FOR UPDATES": "अपडेट्ससाठी तपासा",
    "Edit Profile": "प्रोफाइल संपादित करा",
    "Help": "मदत",
    "Tell us what's going on": "काय चालू आहे ते आम्हाला सांगा",
    "Tell us why you're reaching us": "तुम्ही आमच्याशी का संपर्क साधत आहात ते आम्हाला सांगा",
    "How do you feel? (Optional)": "तुम्हाला कसे वाटते? (पर्यायी)",
    "My Hospital": "माझे रुग्णालय",
    "No hospitals found": "कोणतेही रुग्णालय आढळले नाही",
    "District:": "जिल्हा:",
    "Settings": "सेटिंग्ज",
    "English": "इंग्रजी",
    "Logout Successful": "यशस्वीरित्या लॉगआउट झाले",
    "Subscribe": "सबस्क्राइब करा",
    "Subscription": "सदस्यत्व",
    "Current Plan": "सध्याची योजना",
    "Monthly": "मासिक",
    "Yearly": "वार्षिक",
    "Based on patient reviews": "रुग्णांच्या अभिप्रायांवर आधारित",
    "Working Hours": "कामाचे तास",
    "Contact Information": "संपर्क माहिती",
    "Personalised Pregnancy Care": "वैयक्तिक गर्भधारणा काळजी",
    "Helps you to consult Doctor Virtually": "तुम्हाला व्हर्च्युअली डॉक्टरांशी सल्लामसलत करण्यास मदत करते",
    "Engage with Doctor through video and audio": "व्हिडिओ आणि ऑडिओद्वारे डॉक्टरांशी संवाद साधा",
    "Keep on track your Health": "तुमच्या आरोग्याचा मागोवा ठेवा",
    "By continuing, You agree that you have read and accept our": "पुढे जाऊन, तुम्ही आमचे वाचले आहे आणि स्वीकारले आहे याला सहमती देता",
    "T&C and Privacy Policy": "टी अँड सी आणि गोपनीयता धोरण",
    "Thinking...": "विचार करत आहे...",
    "Your maternal AI assistant is processing your question": "तुमचा मातृत्व AI सहाय्यक तुमच्या प्रश्नावर प्रक्रिया करत आहे",
    "Your Maternal AI Assistant": "तुमचा मातृत्व AI सहाय्यक",
    "Welcome to Allobot!": "अलोबॉटमध्ये आपले स्वागत आहे!",
    "I'm here to support you through your maternal journey. Ask me anything about pregnancy, childbirth, or early motherhood.": "मी तुमच्या मातृत्वाच्या प्रवासात तुम्हाला सहाय्य करण्यासाठी येथे आहे. गर्भावस्था, प्रसूती किंवा प्रारंभिक मातृत्वाबद्दल काहीही विचारा",
    "What You Can Ask Me:": "तुम्ही मला काय विचारू शकता:",
    "Pregnancy health tips": "गर्भावस्थेतील आरोग्य टिप्स",
    "Nutrition advice": "पोषण सल्ला",
    "Baby care basics": "बाळाची काळजी घेण्याची मूलतत्त्वे",
    "Trimester milestones": "त्रैमासिक टप्पे",
    "Ask Allobot...": "अलोबॉटला विचारा...",
    "Incoming Call": "येणारा कॉल",
    "Waiting": "प्रतीक्षा करत आहे",
    "No messages yet": "अजून कोणतेही संदेश नाहीत",
    "Tablets": "गोळ्या",
    "Units": "युनिट्स",
    "Timing": "वेळ",
    "No prescriptions found.": "कोणतीही प्रिस्क्रिप्शन सापडली नाहीत",
    "No description available": "कोणतेही वर्णन उपलब्ध नाही",
    "No reports found": "कोणतेही अहवाल सापडले नाहीत",
    "Report Details": "अहवालाचे तपशील",
    "Unknown Report Type": "अज्ञात अहवाल प्रकार",
    "Test Results": "चाचणी निकाल",
    "Delete Report": "अहवाल हटवा",
    "Are you sure you want to delete this report?": "तुम्हाला खात्री आहे की तुम्ही हा अहवाल हटवू इच्छिता?",
    "CANCEL": "रद्द करा",
    "DELETE": "हटवा",
    "Normal": "सामान्य",
    "Body pain": "शरीराची वेदना",
    "Burning Stomach": "पोट जळणे",
    "Cold cough": "सर्दी खोकला",
    "Dizziness": "चक्कर येणे",
    "Headache": "डोकेदुखी",
    "Vomiting": "उलटी",
    "Other": "इतर",
    "Blood Pressure": "रक्तदाब",
    "Temperature": "तापमान",
    "Blood Saturation": "रक्त संतृप्तता",
    "Blood Glucose": "रक्तातील साखर",
    "BMI": "बीएमआय",
    "HRV": "एचआरव्ही",
    "Baby Cry Not Detected.": "बाळाचे रडणे आढळले नाही.",
    "The baby cry detection process failed. Please check your connection or try again.": "बाळाचे रडणे शोधण्याची प्रक्रिया अयशस्वी झाली. कृपया तुमचे कनेक्शन तपासा किंवा पुन्हा प्रयत्न करा.",
    "Retry": "पुन्हा प्रयत्न करा",
    "Please select Appointment Date": "कृपया अपॉइंटमेंटची तारीख निवडा",
    "Please enter Diagnosis Description": "कृपया निदान वर्णन प्रविष्ट करा",
    "No data available": "कोणताही डेटा उपलब्ध नाही",
    "Pregnant": "गर्भवती",
    "Not Pregnant": "गर्भवती नाही",
    "Summary": "सारांश",
    "Upcoming Appointments": "येणाऱ्या अपॉइंटमेंट्स",
    "No appointments scheduled": "कोणत्याही अपॉइंटमेंट्स निश्चित केलेल्या नाहीत",
    "No": "नाही",
    "Yes": "होय",
    "No appointments found": "कोणत्याही अपॉइंटमेंट्स सापडल्या नाहीत",
    "JioVio Healthcare": "जिओविओ हेल्थकेअर",
    "General Details": "सामान्य तपशील",
    "Partner Details": "पार्टनरचे तपशील",
    "Pregnancy Details": "गर्भावस्थेचे तपशील",
    "Address Details": "पत्त्याचे तपशील",
    "Contact Us": "आमच्याशी संपर्क साधा",
    "Something not Working": "काहीतरी काम करत नाही",
    "Feature Request": "वैशिष्ट्य विनंती",
    "Question": "प्रश्न",
    "FeedBack": "अभिप्राय",
    "SEND": "पाठवा",
    "My Subscription": "माझे सबस्क्रिप्शन",
    "Language": "भाषा",
    "Terms & Conditions": "नियम आणि अटी",
    "Privacy Policy": "गोपनीयता धोरण",
    "Log Out": "लॉग आउट",
    "Are you sure to logout?": "तुम्हाला खात्री आहे की तुम्ही लॉग आउट करू इच्छिता?",
    "Cancel": "रद्द करा",
    "Ok": "ठीक आहे",
    "Change Default": "डीफॉल्ट बदला",
    "Write Description": "वर्णन लिहा",
    "Please enter Description": "कृपया वर्णन प्रविष्ट करा",
    "Door No": "दार क्रमांक",
    "Please enter Door No": "कृपया दार क्रमांक प्रविष्ट करा",
    "Street Name": "रस्त्याचे नाव",
    "Please enter Street Name": "कृपया रस्त्याचे नाव प्रविष्ट करा",
    "Pincode": "पिनकोड",
    "Please enter Pincode": "कृपया पिनकोड प्रविष्ट करा",
    "Search Area": "क्षेत्र शोधा",
    "Select Area Name": "क्षेत्राचे नाव निवडा",
    "Enter your Name": "तुमचे नाव प्रविष्ट करा",
    "Please enter your name": "कृपया तुमचे नाव प्रविष्ट करा",
    "Enter Email Id": "ईमेल आयडी प्रविष्ट करा",
    "Please Select Gender": "कृपया लिंग निवडा",
    "Age": "वय",
    "Please enter age": "कृपया वय प्रविष्ट करा",
    "Please enter corrent age": "कृपया योग्य वय प्रविष्ट करा",
    "LMP Date": "एलएमपी तारीख",
    "Please enter LMP Date": "कृपया एलएमपी तारीख प्रविष्ट करा",
    "ED Date": "ईडी तारीख",
    "Date of delivery": "डिलीव्हरीची तारीख",
    "Please enter Delivery Date": "कृपया डिलीव्हरीची तारीख प्रविष्ट करा",
    "Please enter Partner Name": "कृपया पार्टनरचे नाव प्रविष्ट करा",
    "Partner Name": "पार्टनरचे नाव",
    "Please enter Partner Mobile Number": "कृपया पार्टनरचा मोबाईल नंबर प्रविष्ट करा",
    "Partner Mobile Number": "पार्टनरचा मोबाईल नंबर",
    "Bed Time": "झोपण्याची वेळ",
    "Please enter Date of Birth": "कृपया जन्मतारीख प्रविष्ट करा",
    "Wake Up Time": "उठण्याची वेळ",
    "Name": "नाव",
    "Please Select Parent Type": "कृपया पालक प्रकार निवडा",
    "Parent Type": "पालक प्रकार",
    "Please Select Pregnant Status": "कृपया गर्भवती स्थिती निवडा",
    "Please enter Area": "कृपया क्षेत्र प्रविष्ट करा",
    "Area": "क्षेत्र",
    "Services": "सेवा",
    "AlloBaby": "अलोबेबी",
    "Awareness": "जागरूकता",
    "Screening": "स्क्रीनिंग",
    "Glucose Test": "ग्लुकोज टेस्ट",
    "Ultrasound Test": "अल्ट्रासाउंड टेस्ट",
    "Urine Test": "मूत्र तपासणी"
};