final Map<String, String> ma = {
  "english"	:	"marathi",
"Hunger Crying"	:	"भूक रडत आहे",
"Sleepy Crying"	:	"झोपेची रडत आहे",
"Pain Crying"	:	"वेदना रडणे",
"Discomfort Crying"	:	"अस्वस्थता रडणे",
"Colic Crying"	:	"पोटशूळ रडत आहे",
"Attention Crying"	:	"लक्ष रडणे",
"Rhythmic, repetitive cries that grow louder if the baby isn't fed. Often accompanied by hand-sucking and rooting behavior."	:	"लयबद्ध, पुनरावृत्ती रडणे जे बाळाला दूध पाजले नाही तर जोरात वाढते. अनेकदा हात चोखणे आणि रुटणे वर्तन होते.",
"A whiny, nasal cry that sounds weaker than a hunger cry, often accompanied by yawning and eye-rubbing."	:	"भुकेच्या रडण्यापेक्षा कमकुवत वाटणारी एक किंचाळणारी, अनुनासिक रडणे, बहुतेकदा जांभई आणि डोळे चोळणे.",
"A sudden, high-pitched, intense cry that comes in bursts with breathing pauses. Often accompanied by physical tension."	:	"श्वास ोच्छवासाच्या विरामाबरोबर येणारा अचानक, उंच, तीव्र आरडाओरडा फुटतो. अनेकदा शारीरिक तणावासोबत.",
"A fussy, irritated cry that typically stops when the source of discomfort is addressed."	:	"अस्वस्थतेच्या स्त्रोताकडे लक्ष दिल्यास सामान्यत: थांबणारी चिडचिडे, चिडचिडे रडणे.",
"Prolonged, intense crying episodes, typically in the evening, with physical signs of distress."	:	"दीर्घकाळ, तीव्र रडण्याचे भाग, सामान्यत: संध्याकाळी, त्रासाच्या शारीरिक चिन्हांसह.",
"A mild cry that starts softly and increases if ignored, often accompanied by eye contact and reaching out."	:	"एक सौम्य रडणे जे हळूहळू सुरू होते आणि दुर्लक्ष केल्यास वाढते, बर्याचदा डोळ्यांच्या संपर्कासह आणि पोहोचते.",
"Hunger cries are rhythmic, repetitive, and grow louder if the baby isn't fed."	:	"उपासमारीची ओरड लयबद्ध, पुनरावृत्ती असते आणि जर बाळाला दूध पाजले नाही तर ते अधिक तीव्र होते.",
"Babies may also:"	:	"मुले हे देखील करू शकतात:",
"• Suck on hands or fingers"	:	"• हात किंवा बोटांना चोखा",
"• Smack lips, root (turn head searching for a nipple)"	:	"• स्मैक ओठ, रूट (स्तनाग्र शोधण्यासाठी डोके फिरवा)",
"• Get fussy even after being comforted"	:	"• सांत्वन मिळाल्यानंतरही चिडचिड होते",
"A whiny, nasal cry that may sound weaker than a hunger cry."	:	"भुकेच्या रडण्यापेक्षा कमकुवत वाटू शकणारी एक चिडचिडे, अनुनासिक रडणे.",
"Babies may also:"	:	"मुले हे देखील करू शकतात:",
"• Yawn frequently"	:	"• वारंवार जांभई येणे",
"• Rub their eyes or pull their ears"	:	"• त्यांचे डोळे चोळा किंवा त्यांचे कान ओढा",
"• Become fussy and harder to soothe"	:	"• शांत करणे आणि शांत करणे कठीण होणे",
"A sudden, high-pitched, intense cry that may come in bursts with pauses for breath."	:	"एक अचानक, उंच, तीव्र रडणे जे श्वास ोच्छवासासाठी थांबून फुटू शकते.",
"Babies may also:"	:	"मुले हे देखील करू शकतात:",
"• Clench fists or arch their back"	:	"• त्यांच्या पाठीवर मुठी किंवा कमानी घाला",
"• Become stiff or tense"	:	"• ताठ किंवा तणावग्रस्त होणे",
"• Show signs of discomfort (scrunched face, difficulty calming down)"	:	"• अस्वस्थतेची चिन्हे दर्शविणे (कुरकुरलेला चेहरा, शांत होण्यास अडचण)",
"A fussy, irritated cry that may stop when the issue is resolved."	:	"एक गडबड, चिडचिडे रडणे जे समस्येचे निराकरण झाल्यावर थांबू शकते.",
"Babies may also:"	:	"मुले हे देखील करू शकतात:",
"• Wiggle or squirm a lot"	:	"• खूप हलणे किंवा चिडचिड करणे",
"• Tug at their clothing or ears"	:	"• त्यांचे कपडे किंवा कान दाबणे",
"• Appear restless or uneasy"	:	"• अस्वस्थ किंवा अस्वस्थ दिसणे",
"A prolonged, intense, high-pitched cry that often occurs in the evening."	:	"एक प्रदीर्घ, तीव्र, उंच-उंच रडणे जे बर्याचदा संध्याकाळी उद्भवते.",
"Babies may also:"	:	"मुले हे देखील करू शकतात:",
"• Clench fists, arch their back, or pull up legs"	:	"• मुठी दाबून घ्या, पाठ कमानी करा किंवा पाय वर काढा",
"• Have a tense, bloated belly"	:	"• तणावग्रस्त, फुगलेले पोट असणे",
"• Be difficult to soothe, even after feeding"	:	"• आहार दिल्यानंतरही शांत करणे कठीण आहे",
"A mild, whimpering cry that starts softly and gets louder if ignored."	:	"एक सौम्य, किंचाळणारा आरडाओरडा जो हळुवारपणे सुरू होतो आणि दुर्लक्षित केल्यास तीव्र होतो.",
"Babies may also:"	:	"मुले हे देखील करू शकतात:",
"• Make eye contact while crying"	:	"• रडताना डोळ्यांचा संपर्क साधा",
"• Reach out for comfort"	:	"• आरामासाठी पोहोचा",
"• Stop crying quickly when picked up"	:	"• उचलल्यावर पटकन रडणे थांबवा",
"Feed Promptly – Responding early prevents excessive crying and makes feeding easier."	:	"ताबडतोब आहार द्या - लवकर प्रतिसाद दिल्यास जास्त रडणे थांबते आणि खाणे सोपे होते.",
"Watch for Hunger Cues – Crying is a late sign; look for early signs like lip-smacking, rooting, sticking out tongue, or sucking on hands."	:	"भूक संकेतांसाठी पहा - रडणे हे उशीरा लक्षण आहे; ओठ चोळणे, रुळणे, जीभ चिकटवणे किंवा हात चोखणे यासारख्या सुरुवातीच्या चिन्हे शोधा.",
"Ensure Proper Latch – If breastfeeding, ensure a deep latch to avoid discomfort."	:	"योग्य लॅच सुनिश्चित करा - स्तनपान देत असल्यास, अस्वस्थता टाळण्यासाठी खोल कुंडी सुनिश्चित करा.",
"Check Feeding Schedule – Newborns need feeding every 2-3 hours."	:	"आहाराचे वेळापत्रक तपासा - नवजात बालकांना दर २-३ तासांनी आहार देणे आवश्यक आहे.",
"Burp Baby After Feeding – Helps prevent gas and fussiness."	:	"दूध पाजल्यानंतर बर्प बेबी - गॅस आणि चिडचिडेपणा टाळण्यास मदत करते.",
"Look for Sleep Cues Early – Yawning, zoning out, or rubbing eyes signal it's time to sleep."	:	"झोपेचे संकेत लवकर शोधा - जांभई येणे, झोन करणे किंवा डोळे चोळणे हे झोपेची वेळ असल्याचे सूचित करते.",
"Create a Calm Sleep Environment – Dim lights, reduce noise, and use white noise if needed."	:	"शांत झोपेचे वातावरण तयार करा - मंद दिवे, आवाज कमी करा आणि आवश्यक असल्यास पांढरा आवाज वापरा.",
"Use Gentle Rocking – Motion, swaddling, or a pacifier can help."	:	"सौम्य रॉकिंग वापरा - मोशन, स्वॅडलिंग किंवा पॅसिफायर मदत करू शकते.",
"Follow a Sleep Routine – A consistent bedtime routine helps babies recognize sleep time."	:	"स्लीप रूटीनफॉलो करा - सतत झोपण्याची दिनचर्या बाळांना झोपेची वेळ ओळखण्यास मदत करते.",
"Avoid Overstimulation – Too much activity before bed can make sleep harder."	:	"अतिउत्तेजना टाळा - झोपण्यापूर्वी जास्त क्रियाकलाप केल्याने झोप कठीण होऊ शकते.",
"Check for Obvious Issues – Look for diaper rash, teething pain, or tight clothing."	:	"स्पष्ट समस्या तपासा - डायपर पुरळ, दात येणे किंवा घट्ट कपडे शोधा.",
"Soothe with Gentle Touch – Skin-to-skin contact or holding them close can help."	:	"सौम्य स्पर्शाने शांत करा - त्वचेपासून त्वचेशी संपर्क साधणे किंवा त्यांना जवळ ठेवणे मदत करू शकते.",
"Try Pain Relief Techniques – For teething, offer a chilled teether; for gas, try tummy massage."	:	"वेदना कमी करण्याचे तंत्र वापरुन पहा - दात येण्यासाठी, थंड दात द्या; गॅससाठी पोटाचा मसाज करून पहा.",
"Monitor for Fever or Illness – If crying persists with fever, vomiting, or lethargy, consult a doctor."	:	"ताप किंवा आजारावर लक्ष ठेवा - ताप, उलट्या किंवा आळशीपणासह रडत राहिल्यास डॉक्टरांचा सल्ला घ्या.",
"Trust Your Instincts – If the baby seems in severe pain, seek medical advice immediately."	:	"आपल्या प्रवृत्तीवर विश्वास ठेवा - जर बाळाला तीव्र वेदना होत असतील तर ताबडतोब वैद्यकीय सल्ला घ्या.",
"Check the Diaper – A wet or soiled diaper is a common cause of discomfort."	:	"डायपर तपासा - ओला किंवा मातीयुक्त डायपर अस्वस्थतेचे सामान्य कारण आहे.",
"Ensure Comfortable Clothing – Dress baby in breathable, soft fabrics and check for tight clothing."	:	"आरामदायक कपडे सुनिश्चित करा - बाळाला श्वास घेण्यायोग्य, मऊ कपडे घाला आणि घट्ट कपडे तपासा.",
"Adjust Temperature – Feel baby's neck/back to see if they are too hot or cold."	:	"तापमान समायोजित करा - बाळाची मान / पाठ खूप गरम किंवा थंड आहे की नाही हे पाहण्यासाठी अनुभवा.",
"Check for External Irritants – Tags, rough fabric, or hair wrapped around fingers/toes can cause irritation."	:	"बाह्य चिडचिडेपणा तपासा - टॅग, रुक्ष कापड किंवा बोटे / बोटांभोवती गुंडाळलेले केस चिडचिड होऊ शकतात.",
"Reposition Baby – Changing positions or holding them differently can sometimes help."	:	"रिपोझिशन बेबी - पोझिशन बदलणे किंवा त्यांना वेगळ्या प्रकारे पकडणे कधीकधी मदत करू शकते.",
"Use Gentle Motions – Rocking, swaying, or holding baby in a 'colic carry' (on their tummy along your forearm) can help."	:	"सौम्य गती वापरा - बाळाला 'पोटशूळ कॅरी' मध्ये (आपल्या अग्रभागासह पोटावर) हलविणे, डोलणे किंवा पकडणे मदत करू शकते.",
"Try White Noise – Rhythmic sounds, like a fan or heartbeat sound, can be soothing."	:	"पांढरा आवाज वापरून पहा - पंखा किंवा हृदयाचे ठोके आवाजासारखे लयबद्ध आवाज सुखदायक असू शकतात.",
"Burp Baby Well – Gas buildup can make colic worse. Burp frequently during feeds."	:	"बर्प बेबी वेल - गॅस बिल्डअपमुळे पोटशूळ खराब होऊ शकतो. आहारादरम्यान वारंवार बुरशी येते.",
"Massage the Tummy – A gentle circular tummy massage can relieve gas."	:	"पोटाला मसाज करा - सौम्य गोलाकार पोटाच्या मालिशमुळे गॅस पासून आराम मिळतो.",
"Consult a Pediatrician – If colic persists, discuss options like probiotic drops or diet changes (for breastfeeding moms)."	:	"बालरोगतज्ञांचा सल्ला घ्या - पोटशूळ कायम राहिल्यास, प्रोबायोटिक थेंब किंवा आहारातील बदल (स्तनपान देणाऱ्या मातांसाठी) यासारख्या पर्यायांवर चर्चा करा.",
"Respond with Reassurance – Holding, talking, or making eye contact helps babies feel secure."	:	"आश् वासनाने प्रतिसाद द्या - धारण करणे, बोलणे किंवा डोळ्यांशी संपर्क साधणे बाळांना सुरक्षित वाटण्यास मदत करते.",
"Try Gentle Touch – A cuddle or soft pat on the back can be calming."	:	"सौम्य स्पर्श करून पहा - पाठीवर आलिंगन किंवा मऊ थाप शांत होऊ शकते.",
"Engage with Soothing Sounds – Humming or talking in a calm voice can reassure the baby."	:	"सुखदायक ध्वनींमध्ये गुंता - शांत आवाजात गुनगुनावणे किंवा बोलणे बाळाला आश्वस्त करू शकते.",
"Encourage Independent Comforting – Allow baby to self-soothe briefly before immediately responding."	:	"स्वतंत्र सांत्वनास प्रोत्साहित करा - ताबडतोब प्रतिसाद देण्यापूर्वी बाळाला थोडक्यात शांत होऊ द्या.",
"Maintain a Balance – Meeting attention needs is important, but consistency in response helps babies learn security."	:	"संतुलन राखणे - लक्ष देण्याच्या गरजा पूर्ण करणे महत्वाचे आहे, परंतु प्रतिसादातील सातत्य बाळांना सुरक्षितता शिकण्यास मदत करते.",
		
		
		
"Cry History"	:	"रडण्याचा इतिहास",
"Record"	:	"रेकॉर्ड",
"Allocry"	:	"अलॉकरी",
"Baby can cry due to"	:	"मुळे बाळ रडू शकते",
"Recording"	:	"रेकॉर्डिंग",
"Start Recording"	:	"रेकॉर्डिंग सुरू करा",
"Getting Your Baby Sound…"	:	"तुमच्या बाळाचा आवाज मिळवत आहे...",
"Try to avoid background noise"	:	"पार्श्वभूमीचा आवाज टाळण्याचा प्रयत्न करा",
"High-pitched, intense crying often indicates pain or immediate needs."	:	"तीव्र, तीव्र रडणे अनेकदा वेदना किंवा त्वरित गरजा दर्शवते.",
"Rhythmic crying that gets louder and softer might mean your baby is tired."	:	"लयबद्ध रडणे जे जोरात आणि मऊ होत आहे याचा अर्थ तुमचे बाळ थकले आहे",
"Short, low-pitched cries repeated every few seconds usually signal hunger."	:	"लहान, कमी आवाजाचे रडणे दर काही सेकंदात पुनरावृत्ती होते हे सहसा भूक दर्शवते.",
"Whimpering or whining sounds might indicate mild discomfort or wanting attention."	:	"कुजबुजणे किंवा ओरडणारे आवाज हे सौम्य अस्वस्थता किंवा लक्ष देण्याची इच्छा दर्शवू शकतात.",
"Long, high-pitched screams could be signs of colic or stomach pain."	:	"लांब, उंच किंचाळणे ही पोटशूळ किंवा पोटदुखीची लक्षणे असू शकतात.",
"Sudden, sharp cries might mean your baby is too hot or cold."	:	"अचानक, तीक्ष्ण रडणे म्हणजे तुमचे बाळ खूप गरम किंवा थंड आहे.",
"Persistent crying with leg movement often indicates diaper change needs."	:	"पायांच्या हालचालीसह सतत रडणे अनेकदा डायपर बदलण्याची गरज दर्शवते.",
"Baby Cry Not Detected"	:	"बाळाचे रडणे आढळले नाही",
		
"Select Language"	:	"भाषा निवडा",
"Enter Mobile Number"	:	"मोबाइल नंबर टाका",
"SEND OTP"	:	"ओटीपी पाठवा",
"How do you feel today ?"	:	"आज तुम्हाला कसे वाटते?.",
"Online"	:	"ऑनलाइन",
"Offline"	:	"ऑफलाइन",
"Image Uploaded"	:	"छायाचित्र अपलोड केले आहे",
"Type a message"	:	"मेसेज टाइप करा",
"Choose photo from"	:	"छायाचित्र निवडा",
"Get Connected with doctors"	:	"डॉक्टरांशी संपर्क साधा",
"Connect with Doctor"	:	"डॉक्टरांशी संपर्क करा",
"Connect with Health worker"	:	"आरोग्य कर्मचाऱ्याशी संपर्क साधा",
"Connect with AlloBot"	:	"अॅलोबॉटशी कनेक्ट व्हा",
"Sorry No Awareness Post"	:	"माफ करा, जागरूकतेचा पोस्ट नाही",
"Checkup Completed"	:	"चेकअप पूर्ण झाला",
"Waiting for Doctor Feedback"	:	"डॉक्टरांच्या अभिप्रायाची वाट पाहत आहे",
"Checkup need to be done"	:	"तपासणी करणे आवश्यक आहे",
"Checkup"	:	"चेकअप",
"No Checkup Found"	:	"चेकअप आढळला नाही",
"Checkup Details"	:	"तपासणीचे तपशील",
"Doctor Name"	:	"डॉक्टरचे नाव",
"Date"	:	"तारीख",
"Health Status"	:	"आरोग्य स्थिती",
"Case Summary"	:	"केस सारांश",
"Prescription"	:	"प्रिस्क्रिप्शन",
"Next Appointment Time"	:	"पुढील अपॉइंटमेंट वेळ",
"Symptoms"	:	"लक्षणे",
"Vitals"	:	"जीवनावश्यक वस्तू",
"Add Prescription"	:	"प्रिस्क्रिप्शन जोडा",
"ADD PRESCRIPTION"	:	"प्रिस्क्रिप्शन जोडा",
"Click to Add Image"	:	"प्रतिमा जोडण्यासाठी क्लिक करा",
"View Prescription"	:	"प्रिस्क्रिप्शन पहा",
"Error loading image"	:	"त्रुटी लोडिंग प्रतिमा",
"Prescription Type"	:	"प्रिस्क्रिप्शन प्रकार",
"Date Added"	:	"तारीख जोडली गेली",
"Description"	:	"वर्णन",
"Add Report"	:	"अहवाल जोडा",
"NO IMAGE"	:	"चित्र नाही",
"Click Add Image Button"	:	"प्रतिमा जोडा बटणावर क्लिक करा",
"ADD IMAGE"	:	"चित्र जोडा",
"ADD REPORT"	:	"रिपोर्ट जोडा",
"Report"	:	"रिपोर्ट",
"Scan and Add new Report"	:	"स्कॅन करा आणि नवीन रिपोर्ट जोडा",
"Self Screening"	:	"स्वत:ची स्क्रीनींग",
"BACK"	:	"पाठीमागे",
"NEXT"	:	"पुढे",
"Finish"	:	"पूर्ण करा",
"Summary Report"	:	"सारांश अहवाल",
"Submit"	:	"सबमिट करा",
"Let's begin the test"	:	"चला चाचणी सुरू करूया",
"Hemoglobin Test"	:	"हिमोग्लोबिन चाचणी",
"Easily get your Reading by Performing the scans below"	:	"खालील स्कॅन करून तुमचे वाचन सहज मिळवा",
"Fetal Monitoring"	:	"गर्भाचे निरीक्षण",
"Upload Report"	:	"अहवाल अपलोड करा",
"Tap to Change"	:	"बदलण्यासाठी टॅप करा",
"Heart Rate"	:	"हृदय गती",
"BPM"	:	"बीपीएम",
"Kick Count"	:	"किक काउंट",
"Tap to Increase the Count"	:	"संख्या वाढवण्यासाठी टॅप करा",
"Add Glucose Report"	:	"ग्लुकोज रिपोर्ट जोडा",
"Blood Glucose Value"	:	"रक्त ग्लुकोज मूल्य",
"Add Hemoglobin Report"	:	"हिमोग्लोबिन रिपोर्ट जोडा",
"Hemoglobin Value"	:	"हिमोग्लोबिन मूल्य",
"Ultra Sound"	:	"अल्ट्रासाऊंड",
"Fasting"	:	"उपवास",
"At rest"	:	"आरामात",
"After Walk"	:	"चाला नंतर",
"Select Height"	:	"उंची निवडा",
"Select Weight"	:	"वजन निवडा",
"After walk"	:	"चालल्यानंतर",
"Address Information"	:	"पत्ता माहिती",
"Search"	:	"शोधा",
"Continue"	:	"चालू ठेवा",
"Phone Number"	:	"फोन नंबर",
"Profile Details"	:	"प्रोफाइल तपशील",
"Gender"	:	"लिंग",
"Male"	:	"पुरुष",
"Female"	:	"स्त्री",
"Select Blood Group"	:	"रक्त गट निवडा",
"Select Last cycle Date"	:	"अंतिम सायकल तारीख निवडा",
"Are you my mom or dad?"	:	"तू माझी आई आहेस की बाबा?",
"Dad"	:	"बाबा",
"Mom"	:	"आई",
"Enter your Partner Details"	:	"तुमचा भागीदार तपशील प्रविष्ट करा",
"Pregnancy Status"	:	"गर्भधारणा स्थिती",
"Partner Pregnancy Status"	:	"जोडीदाराची गर्भधारणा स्थिती",
"Average Length of Cycles"	:	"सायकलची सरासरी लांबी",
"Day"	:	"दिवस",
"Not yet started"	:	"अजून सुरुवात झालेली नाही",
"NORMAL"	:	"सामान्य",
"Health Status"	:	"आरोग्य स्थिती",
"Last Screened"	:	"शेवटचे स्क्रीन केलेले",
"GOLD"	:	"सोने",
"Subscription Plan"	:	"सदस्यता योजना",
"No News Feed"	:	"बातम्या फीड नाही",
"Probable Reason"	:	"संभाव्य कारण",
"Recommendations"	:	"शिफारशी",
"Hi!"	:	"हाय!",
"How do you feel today?"	:	"आज कसं वाटतंय?",
"Select Exercise that have you done today?"	:	"तुम्ही आज केलेला व्यायाम निवडा?",
"None"	:	"काहीही नाही",
"Select tablets that you have taken"	:	"तुम्ही घेतलेल्या गोळ्या निवडा",
"Sleep Duration"	:	"झोपेचा कालावधी",
"Do you have any of these Symptoms?"	:	"तुम्हाला यापैकी कोणतीही लक्षणे आहेत का?",
"Baby Voice is Recording"	:	"बेबी व्हॉइस रेकॉर्डिंग आहे",
"STOP"	:	"थांबा",
"Click the Record Button to Start Recording"	:	"रेकॉर्डिंग सुरू करण्यासाठी रेकॉर्ड बटणावर क्लिक करा",
"Record"	:	"रेकॉर्ड",
"How many Glass of water have you drunk today?"	:	"आज तुम्ही किती ग्लास पाणी प्यायले आहे?",
"OTP Verification"	:	"OTP पडताळणी",
"Enter OTP sent to"	:	"यांना पाठवलेला ओटीपी एंटर करा",
"Verify and proceed"	:	"सत्यापित करा आणि पुढे जा",
"Appointment"	:	"नियुक्ती",
"Select Hospital"	:	"हॉस्पिटल निवडा",
"Select Doctor"	:	"डॉक्टर निवडा",
"Appointment Date"	:	"भेटीची तारीख",
"Available slots"	:	"उपलब्ध स्लॉट",
"No Slots Available"	:	"कोणतेही स्लॉट उपलब्ध नाहीत",
"View Available Slots"	:	"उपलब्ध स्लॉट पहा",
"Start time Slot"	:	"प्रारंभ वेळ स्लॉट",
"Diagnosis Description"	:	"निदान वर्णन",
"Book"	:	"पुस्तक",
"Update"	:	"अपडेट करा",
"Respiratory Rate"	:	"श्वसन दर",
"Appointments"	:	"भेटी",
"As a companion in your pregnancy we help you with the following"	:	"तुमच्या गरोदरपणातील साथीदार म्हणून आम्ही तुम्हाला खालील गोष्टींमध्ये मदत करतो",
"Book An Appointment"	:	"अपॉइंटमेंट बुक करा",
"Pregnancy Monitoring"	:	"गर्भधारणा निरीक्षण",
"Help Line"	:	"हेल्प लाइन",
"Current Appointment"	:	"सध्याची नियुक्ती",
"No Upcoming Appointments"	:	"आगामी भेटी नाहीत",
"Time"	:	"वेळ",
"Status"	:	"स्थिती",
"Reason"	:	"कारण",
"Cancel Appointment"	:	"भेट रद्द करा",
"Show Appointment"	:	"अपॉईंटमेंट दाखवा",
"My Appointments"	:	"माझ्या भेटी",
"Appointment Status"	:	"भेटीची स्थिती",
"App Info"	:	"ॲप माहिती",
"CHECK FOR UPDATES"	:	"अद्यतनांसाठी तपासा",
"Edit Profile"	:	"प्रोफाइल संपादित करा",
"Help"	:	"मदत करा",
"Tell us what's going on"	:	"काय चालले आहे ते सांगा",
"Tell us why you're reaching us"	:	"तुम्ही आमच्यापर्यंत का पोहोचत आहात ते आम्हाला सांगा",
"How do you feel? (Optional)"	:	"तुम्हाला कसे वाटते? (पर्यायी)",
"My Hospital"	:	"माझे हॉस्पिटल",
"No hospitals found"	:	"रुग्णालये सापडली नाहीत",
"District"	:	"जिल्हा",
"Settings"	:	"सेटिंग्ज",
"English"	:	"इंग्रजी",
"Logout Successful"	:	"लॉगआउट यशस्वी",
"Subscribe"	:	"सदस्यता घ्या",
"Subscription"	:	"वर्गणी",
"Current Plan"	:	"चालू योजना",
"Monthly"	:	"मासिक",
"Yearly"	:	"वार्षिक",
"Based on patient reviews"	:	"रुग्णांच्या पुनरावलोकनांवर आधारित",
"Working Hours"	:	"कामाचे तास",
"Contact Information"	:	"संपर्क माहिती",
"Personalised Pregnancy Care"	:	"वैयक्तिक गर्भधारणा काळजी",
"Helps you to consult Doctor Virtually"	:	"व्हर्चुअली डॉक्टरांचा सल्ला घेण्यास मदत करते",
"Engage with Doctor through video and audio"	:	"व्हिडिओ आणि ऑडिओद्वारे डॉक्टरांशी संपर्क साधा",
"Keep on track your Health"	:	"तुमच्या आरोग्याचा मागोवा ठेवा",
"By continuing, You agree that you have read and accept our"	:	"सुरू ठेवून, तुम्ही सहमत आहात की तुम्ही आमचे वाचले आणि स्वीकारले आहे",
"T&C and Privacy Policy"	:	"T&C आणि गोपनीयता धोरण",
"Thinking..."	:	"विचार करत आहे...",
"Your maternal AI assistant is processing your question"	:	"तुमचा मातृ AI सहाय्यक तुमच्या प्रश्नावर प्रक्रिया करत आहे",
"Your Maternal AI Assistant"	:	"तुमचा मॅटरनल एआय असिस्टंट",
"Welcome to Allobot!"	:	"Allobot मध्ये आपले स्वागत आहे!",
"I'm here to support you through your maternal journey. Ask me anything about pregnancy, childbirth, or early motherhood."	:	"मी तुमच्या मातृत्वाच्या प्रवासात तुम्हाला पाठिंबा देण्यासाठी येथे आहे. मला गर्भधारणा, बाळंतपण किंवा लवकर मातृत्व याबद्दल काहीही विचारा.",
"What You Can Ask Me"	:	"तुम्ही मला काय विचारू शकता:",
"Pregnancy health tips"	:	"गरोदरपणासाठी आरोग्य टिप्स",
"Nutrition advice"	:	"पोषण सल्ला",
"Baby care basics"	:	"बाळाच्या देखभालीचे मूलभूत तत्त्वे",
"Trimester milestones"	:	"त्रैमासिक महत्त्वाचे टप्पे",
"Ask Allobot..."	:	"अ‍ॅलोबोटला विचारा",
"Incoming Call"	:	"इनकमिंग कॉल",
"Waiting"	:	"वाट पाहत आहे",
"No messages yet"	:	"अद्याप कोणतेही संदेश नाहीत",
"Tablets"	:	"गोळ्या",
"Units"	:	"युनिट्स",
"Timing"	:	"वेळ",
"No prescriptions found."	:	"कोणताही नुस्खा आढळला नाही.",
"No description available"	:	"कोणतेही वर्णन उपलब्ध नाही",
"No reports found"	:	"कोणतेही अहवाल आढळले नाहीत",
"Report Details"	:	"अहवाल तपशील",
"Unknown Report Type"	:	"अज्ञात अहवाल प्रकार'",
"Test Results"	:	"चाचणी परिणाम",
"Delete Report"	:	"अहवाल हटवा",
"Are you sure you want to delete this report?"	:	"तुमची खात्री आहे की तुम्ही हा अहवाल हटवू इच्छिता?",
"CANCEL"	:	"रद्द करा",
"DELETE"	:	"हटवा",
"Normal"	:	"सामान्य",
"Body pain"	:	"शरीरदुखी",
"Burning Stomach"	:	"आगीसारखी पोटाची वेदना",
"Cold cough"	:	"सर्दी आणि खोकला",
"Dizziness"	:	"चक्कर येणे",
"Headache"	:	"डोकेदुखी",
"Vomiting"	:	"उलट्या होणे",
"Other"	:	"इतर",
"Blood Pressure"	:	"रक्तदाब",
"Temperature"	:	"तापमान",
"Blood Saturation"	:	"रक्त संपृक्तता",
"Blood Glucose"	:	"रक्तातील ग्लुकोज",
"BMI"	:	"बॉडी मास इंडेक्स",
"HRV"	:	"एचआरव्ही",
"Baby Cry Not Detected."	:	"बाळाचे रडणे आढळले नाही.",
"The baby cry detection process failed. Please check your connection or try again."	:	"बाळाचे रडणे शोधण्याची प्रक्रिया अयशस्वी झाली. कृपया तुमचे कनेक्शन तपासा किंवा पुन्हा प्रयत्न करा.",
"Retry"	:	"पुन्हा प्रयत्न करा",
"Please select Appointment Date"	:	"कृपया भेटीची तारीख निवडा",
"Please enter Diagnosis Description"	:	"कृपया निदान वर्णन प्रविष्ट करा",
"No data available"	:	"कोणताही डेटा उपलब्ध नाही",
"Pregnant"	:	"गरोदर",
"Not Pregnant"	:	"गर्भवती नाही",
"Summary"	:	"सारांश",
"Upcoming Appointments"	:	"आगामी भेटी",
"No appointments scheduled"	:	"नियोजित भेटी नाहीत",
"No"	:	"नाही",
"Yes"	:	"होय",
"No appointments found"	:	"भेटी मिळाल्या नाहीत",
"JioVio Healthcare"	:	"JioVio हेल्थकेअर",
"General Details"	:	"सामान्य तपशील",
"Partner Details"	:	"भागीदार तपशील",
"Pregnancy Details"	:	"गर्भधारणेचे तपशील",
"Address Details"	:	"पत्ता तपशील",
"Contact Us"	:	"आमच्याशी संपर्क साधा",
"Something not Working"	:	"काहीतरी काम करत नाही",
"Feature Request"	:	"वैशिष्ट्य विनंती",
"Question"	:	"प्रश्न",
"FeedBack"	:	"फीडबॅक",
"SEND"	:	"पाठवा",
"My Subscription"	:	"माझी सदस्यता",
"Language"	:	"भाषा",
"Terms & Conditions"	:	"नियम आणि अटी",
"Privacy Policy"	:	"गोपनीयता धोरण",
"Log Out"	:	"लॉग आउट करा",
"Are you sure to logout?"	:	"तुमची खात्री आहे की लॉगआउट कराल?",
"Cancel"	:	"रद्द करा",
"Ok"	:	"ठीक आहे",
"Change Default"	:	"डीफॉल्ट बदला",
"Write Description"	:	"वर्णन लिहा",
"Please enter Description"	:	"कृपया वर्णन प्रविष्ट करा",
"Door No"	:	"दरवाजा क्र",
"Please enter Door No"	:	"कृपया दरवाजा क्रमांक प्रविष्ट करा",
"Street Name"	:	"रस्त्याचे नाव",
"Please enter Street Name"	:	"कृपया मार्गाचे नाव प्रविष्ट करा",
"Pincode"	:	"पिनकोड",
"Please enter Pincode"	:	"कृपया पिनकोड प्रविष्ट करा",
"Search Area"	:	"क्षेत्र शोधा",
"Select Area Name"	:	"क्षेत्राचे नाव निवडा",
"Enter your Name"	:	"आपले नाव प्रविष्ट करा",
"Please enter your name"	:	"कृपया आपले नाव प्रविष्ट करा",
"Enter Email Id"	:	"ईमेल आयडी टाका",
"Please Select Gender"	:	"कृपया लिंग निवडा",
"Age"	:	"वय",
"Please enter age"	:	"कृपया वय प्रविष्ट करा",
"Please enter correct age"	:	"कृपया योग्य वय प्रविष्ट करा",
"LMP Date"	:	"LMP तारीख",
"Please enter LMP Date"	:	"कृपया LMP तारीख एंटर करा",
"ED Date"	:	"ED तारीख",
"Date of delivery"	:	"वितरणाची तारीख",
"Please enter Delivery Date"	:	"कृपया वितरण तारीख प्रविष्ट करा",
"Please enter Partner Name"	:	"कृपया भागीदाराचे नाव प्रविष्ट करा",
"Partner Name"	:	"भागीदाराचे नाव",
"Please enter Partner Mobile Number"	:	"कृपया भागीदार मोबाईल नंबर प्रविष्ट करा",
"Partner Mobile Number"	:	"भागीदार मोबाईल नंबर",
"Bed Time"	:	"झोपण्याची वेळ",
"Please enter Date of Birth"	:	"कृपया जन्मतारीख प्रविष्ट करा",
"Wake Up Time"	:	"उठण्याची वेळ",
"Name"	:	"नाव",
"Please Select Parent Type"	:	"कृपया पालक प्रकार निवडा",
"Parent Type"	:	"पालक प्रकार",
"Please Select Pregnant Status"	:	"कृपया गर्भवती स्थिती निवडा",
"Please enter Area"	:	"कृपया क्षेत्र प्रविष्ट करा",
"Area"	:	"क्षेत्रफळ",
"Services"	:	"सेवा",
"AlloBaby"	:	"हॅलो बाळा",
"Awareness"	:	"जाणीव",
"Screening"	:	"स्क्रीनिंग",
"Glucose Test"	:	"ग्लुकोज चाचणी",
"Ultrasound Test"	:	"अल्ट्रासाऊंड चाचणी",
"Urine Test"	:	"मूत्र चाचणी",
"Home"	:	"घर",
"Service"	:	"सेवा",
"Chat"	:	"गप्पा",
"Logout"	:	"लॉगआउट करा",
"Notification"	:	"सूचना",
"ON"	:	"चालू",
"OFF"	:	"बंद",
"ON/OFF"	:	"चालू/बंद",
"AI Recommendation"	:	"AI शिफारस",
"Analyzing your health data..."	:	"तुमच्या आरोग्य डेटाचे विश्लेषण करत आहे...",
"No summary available"	:	"कोणताही सारांश उपलब्ध नाही",
"Book Appointment"	:	"बुक अपॉइंटमेंट",
"SCAN AND ADD REPORT"	:	"स्कॅन करा आणि अहवाल जोडा",
"Allobot"	:	"अलोबोट",

};