final Map<String, String> ml = {

"english"	:	"Malayalam",
"Hunger Crying"	:	"വിശപ്പ് കരയുന്നു",
"Sleepy Crying"	:	"സ്ലീപ്പി ക്രൈയിംഗ്",
"Pain Crying"	:	"വേദന കരച്ചിൽ",
"Discomfort Crying"	:	"അസ്വസ്ഥത കരയുന്നു",
"Colic Crying"	:	"കോളിക് കരച്ചിൽ",
"Attention Crying"	:	"കരച്ചിൽ ശ്രദ്ധിക്കുക",
"Rhythmic, repetitive cries that grow louder if the baby isn't fed. Often accompanied by hand-sucking and rooting behavior."	:	"താളാത്മകവും ആവർത്തിച്ചുള്ളതുമായ കരച്ചിൽ കുഞ്ഞിന് ഭക്ഷണം നൽകിയില്ലെങ്കിൽ ഉച്ചത്തിൽ വളരുന്നു. പലപ്പോഴും കൈ മുലകുടിക്കുന്നതും വേരുപിടിക്കുന്നതുമായ പെരുമാറ്റം.",
"A whiny, nasal cry that sounds weaker than a hunger cry, often accompanied by yawning and eye-rubbing."	:	"വിശപ്പിൻ്റെ നിലവിളിയേക്കാൾ ദുർബലമായി തോന്നുന്ന, പലപ്പോഴും അലറലും കണ്ണ് തിരുമ്മലും ഉള്ള ഒരു മൂക്ക് കരച്ചിൽ.",
"A sudden, high-pitched, intense cry that comes in bursts with breathing pauses. Often accompanied by physical tension."	:	"പെട്ടെന്നുള്ള, ഉച്ചത്തിലുള്ള, തീവ്രമായ നിലവിളി, ശ്വാസോച്ഛ്വാസം നിർത്തലാക്കിക്കൊണ്ട് പൊട്ടിത്തെറിക്കുന്നു. പലപ്പോഴും ശാരീരിക സമ്മർദ്ദത്തോടൊപ്പമുണ്ട്.",
"A fussy, irritated cry that typically stops when the source of discomfort is addressed."	:	"അസ്വസ്ഥതയുടെ ഉറവിടം അഭിസംബോധന ചെയ്യുമ്പോൾ സാധാരണയായി നിർത്തുന്ന ഒരു ബഹളവും പ്രകോപിതവുമായ കരച്ചിൽ.",
"Prolonged, intense crying episodes, typically in the evening, with physical signs of distress."	:	"നീണ്ടുനിൽക്കുന്ന, തീവ്രമായ കരച്ചിൽ എപ്പിസോഡുകൾ, സാധാരണയായി വൈകുന്നേരങ്ങളിൽ, ശാരീരിക അസ്വസ്ഥതയുടെ ലക്ഷണങ്ങളോടെ.",
"A mild cry that starts softly and increases if ignored, often accompanied by eye contact and reaching out."	:	"മൃദുവായി ആരംഭിക്കുകയും അവഗണിക്കപ്പെട്ടാൽ വർദ്ധിക്കുകയും ചെയ്യുന്ന ഒരു നേരിയ കരച്ചിൽ, പലപ്പോഴും കണ്ണുമായി സമ്പർക്കം പുലർത്തുകയും കൈനീട്ടുകയും ചെയ്യുന്നു.",
"Hunger cries are rhythmic, repetitive, and grow louder if the baby isn't fed."	:	"വിശപ്പിന്റെ കരച്ചിൽ താളാത്മകവും ആവർത്തിക്കുന്നതുമാണ്, കുഞ്ഞിന് ഭക്ഷണം നൽകിയില്ലെങ്കിൽ അത് കൂടുതൽ ഉച്ചത്തിലാകും.",
"Babies may also:"	:	"കുഞ്ഞുങ്ങൾക്ക് ഇവയും ചെയ്യാം:",
"• Suck on hands or fingers"	:	"• കൈകളോ വിരലുകളോ ചപ്പി കുടിക്കുക",
"• Smack lips, root (turn head searching for a nipple)"	:	"• ചുണ്ടുകൾ, വേരുകൾ എന്നിവ ഇടുക (മുലക്കണ്ണിനായി തല തിരിക്കുക)",
"• Get fussy even after being comforted"	:	"• ആശ്വസിപ്പിച്ചതിനു ശേഷവും ബഹളമുണ്ടാക്കുക",
"A whiny, nasal cry that may sound weaker than a hunger cry."	:	"വിശപ്പിന്റെ കരച്ചിലിനേക്കാൾ ദുർബലമായി തോന്നിയേക്കാവുന്ന ഒരു ഞരങ്ങുന്ന, മൂക്കിലെ കരച്ചിൽ.",
"Babies may also:"	:	"കുഞ്ഞുങ്ങൾക്ക് ഇവയും ചെയ്യാം:",
"• Yawn frequently"	:	"• ഇടയ്ക്കിടെ അലറുക",
"• Rub their eyes or pull their ears"	:	"• അവരുടെ കണ്ണുകൾ തിരുമ്മുക അല്ലെങ്കിൽ ചെവി വലിക്കുക",
"• Become fussy and harder to soothe"	:	"• ബഹളമുണ്ടാക്കുകയും ആശ്വസിപ്പിക്കാൻ പ്രയാസപ്പെടുകയും ചെയ്യുക",
"A sudden, high-pitched, intense cry that may come in bursts with pauses for breath."	:	"പെട്ടെന്നുള്ള, ഉയർന്ന, തീവ്രമായ ഒരു കരച്ചിൽ ശ്വാസം നിലച്ചേക്കാം.",
"Babies may also:"	:	"കുഞ്ഞുങ്ങൾക്ക് ഇവയും ചെയ്യാം:",
"• Clench fists or arch their back"	:	"• മുഷ്ടി ചുരുട്ടുക അല്ലെങ്കിൽ പുറം വളയ്ക്കുക",
"• Become stiff or tense"	:	"• കഠിനമോ പിരിമുറുക്കമോ ആയിത്തീരുക",
"• Show signs of discomfort (scrunched face, difficulty calming down)"	:	"• അസ്വസ്ഥതയുടെ ലക്ഷണങ്ങൾ കാണിക്കുക (മുഖം ചുളിഞ്ഞത്, ശാന്തമാകാൻ ബുദ്ധിമുട്ട്)",
"A fussy, irritated cry that may stop when the issue is resolved."	:	"പ്രശ്നം പരിഹരിക്കപ്പെടുമ്പോൾ നിലച്ചേക്കാവുന്ന അസ്വസ്ഥവും പ്രകോപിതവുമായ ഒരു കരച്ചിൽ.",
"Babies may also:"	:	"കുഞ്ഞുങ്ങൾക്ക് ഇവയും ചെയ്യാം:",
"• Wiggle or squirm a lot"	:	"• ഒരുപാട് ചലിപ്പിക്കുക അല്ലെങ്കിൽ ഞെരുക്കുക",
"• Tug at their clothing or ears"	:	"• അവരുടെ വസ്ത്രത്തിലോ ചെവിയിലോ വലിക്കുക",
"• Appear restless or uneasy"	:	"• അസ്വസ്ഥതയോ അസ്വസ്ഥതയോ ആയി പ്രത്യക്ഷപ്പെടുക",
"A prolonged, intense, high-pitched cry that often occurs in the evening."	:	"വൈകുന്നേരങ്ങളിൽ പലപ്പോഴും സംഭവിക്കുന്ന ഒരു നീണ്ട, തീവ്രമായ, ഉയർന്ന നിലവിളി.",
"Babies may also:"	:	"കുഞ്ഞുങ്ങൾക്ക് ഇവയും ചെയ്യാം:",
"• Clench fists, arch their back, or pull up legs"	:	"• മുഷ്ടി ചുരുട്ടുക, പുറകോട്ട് വളയുക, അല്ലെങ്കിൽ കാലുകൾ മുകളിലേക്ക് വലിക്കുക",
"• Have a tense, bloated belly"	:	"• പിരിമുറുക്കമുള്ള, വീർത്ത വയറ് ഉണ്ടായിരിക്കുക",
"• Be difficult to soothe, even after feeding"	:	"• ഭക്ഷണം നൽകിയതിന് ശേഷവും ആശ്വസിപ്പിക്കാൻ പ്രയാസമാണ്",
"A mild, whimpering cry that starts softly and gets louder if ignored."	:	"മൃദുവായി തുടങ്ങുകയും അവഗണിക്കപ്പെട്ടാൽ കൂടുതൽ ഉച്ചത്തിലാകുകയും ചെയ്യുന്ന മൃദുലമായ കരച്ചിൽ.",
"Babies may also:"	:	"കുഞ്ഞുങ്ങൾക്ക് ഇവയും ചെയ്യാം:",
"• Make eye contact while crying"	:	"• കരയുമ്പോൾ കണ്ണുമായി ബന്ധപ്പെടുക",
"• Reach out for comfort"	:	"• ആശ്വാസത്തിനായി എത്തുക",
"• Stop crying quickly when picked up"	:	"• എടുക്കുമ്പോൾ പെട്ടെന്ന് കരച്ചിൽ നിർത്തുക",
"Feed Promptly – Responding early prevents excessive crying and makes feeding easier."	:	"ഉടനടി ഭക്ഷണം നൽകുക - നേരത്തെ പ്രതികരിക്കുന്നത് അമിതമായ കരച്ചിൽ തടയുകയും ഭക്ഷണം നൽകുന്നത് എളുപ്പമാക്കുകയും ചെയ്യുന്നു.",
"Watch for Hunger Cues – Crying is a late sign; look for early signs like lip-smacking, rooting, sticking out tongue, or sucking on hands."	:	"വിശപ്പ് സൂചനകൾക്കായി കാണുക - കരയുന്നത് വൈകിയ അടയാളമാണ്; ചുണ്ടുകൾ അടിക്കുക, വേരോടെ പിഴുതെറിയുക, നാവ് പുറത്തേക്ക് തള്ളുക, അല്ലെങ്കിൽ കൈകളിൽ മുലകുടിക്കുക തുടങ്ങിയ പ്രാരംഭ ലക്ഷണങ്ങൾ നോക്കുക.",
"Ensure Proper Latch – If breastfeeding, ensure a deep latch to avoid discomfort."	:	"ശരിയായ ലാച്ച് ഉറപ്പാക്കുക - മുലയൂട്ടുന്നുണ്ടെങ്കിൽ, അസ്വസ്ഥത ഒഴിവാക്കാൻ ആഴത്തിലുള്ള ലാച്ച് ഉറപ്പാക്കുക.",
"Check Feeding Schedule – Newborns need feeding every 2-3 hours."	:	"ഫീഡിംഗ് ഷെഡ്യൂൾ പരിശോധിക്കുക - നവജാതശിശുക്കൾക്ക് ഓരോ 2-3 മണിക്കൂറിലും ഭക്ഷണം ആവശ്യമാണ്.",
"Burp Baby After Feeding – Helps prevent gas and fussiness."	:	"ഭക്ഷണം നൽകിയതിന് ശേഷം ബേബി ബേബി - ഗ്യാസും ബഹളവും തടയാൻ സഹായിക്കുന്നു.",
"Look for Sleep Cues Early – Yawning, zoning out, or rubbing eyes signal it's time to sleep."	:	"നേരത്തെയുള്ള ഉറക്ക സൂചനകൾക്കായി തിരയുക - അലറുക, സോണിംഗ് ഔട്ട് ചെയ്യുക, അല്ലെങ്കിൽ കണ്ണുകൾ തിരുമ്മുക എന്നിവ ഉറങ്ങാനുള്ള സമയമായെന്ന് സൂചിപ്പിക്കുന്നു.",
"Create a Calm Sleep Environment – Dim lights, reduce noise, and use white noise if needed."	:	"ശാന്തമായ ഉറക്ക അന്തരീക്ഷം സൃഷ്ടിക്കുക - മങ്ങിയ ലൈറ്റുകൾ, ശബ്ദം കുറയ്ക്കുക, ആവശ്യമെങ്കിൽ വെളുത്ത ശബ്ദം ഉപയോഗിക്കുക.",
"Use Gentle Rocking – Motion, swaddling, or a pacifier can help."	:	"ജെൻ്റിൽ റോക്കിംഗ് ഉപയോഗിക്കുക - ചലനം, swaddling, അല്ലെങ്കിൽ ഒരു pacifier സഹായിക്കും.",
"Follow a Sleep Routine – A consistent bedtime routine helps babies recognize sleep time."	:	"ഒരു ഉറക്ക ദിനചര്യ പിന്തുടരുക - സ്ഥിരമായ ബെഡ്‌ടൈം ദിനചര്യ കുഞ്ഞുങ്ങളെ ഉറങ്ങുന്ന സമയം തിരിച്ചറിയാൻ സഹായിക്കുന്നു.",
"Avoid Overstimulation – Too much activity before bed can make sleep harder."	:	"അമിതമായ ഉത്തേജനം ഒഴിവാക്കുക - ഉറങ്ങുന്നതിന് മുമ്പുള്ള അമിതമായ പ്രവർത്തനം ഉറക്കം ദുഷ്കരമാക്കും.",
"Check for Obvious Issues – Look for diaper rash, teething pain, or tight clothing."	:	"വ്യക്തമായ പ്രശ്നങ്ങൾക്കായി പരിശോധിക്കുക - ഡയപ്പർ ചുണങ്ങു, പല്ലുവേദന, അല്ലെങ്കിൽ ഇറുകിയ വസ്ത്രങ്ങൾ എന്നിവ നോക്കുക.",
"Soothe with Gentle Touch – Skin-to-skin contact or holding them close can help."	:	"മൃദുലമായ സ്പർശനത്തിലൂടെ ശമിപ്പിക്കുക - ചർമ്മത്തിൽ നിന്ന് ചർമ്മത്തിൽ സമ്പർക്കം പുലർത്തുകയോ അവരെ അടുത്ത് പിടിക്കുകയോ ചെയ്യുന്നത് സഹായിക്കും.",
"Try Pain Relief Techniques – For teething, offer a chilled teether; for gas, try tummy massage."	:	"പെയിൻ റിലീഫ് ടെക്നിക്കുകൾ പരീക്ഷിക്കുക - പല്ലുതേയ്ക്കാൻ, ഒരു ശീതീകരിച്ച ദന്തർ വാഗ്ദാനം ചെയ്യുക; ഗ്യാസിനായി, വയറ് മസാജ് ചെയ്യാൻ ശ്രമിക്കുക.",
"Monitor for Fever or Illness – If crying persists with fever, vomiting, or lethargy, consult a doctor."	:	"പനിയോ അസുഖമോ നിരീക്ഷിക്കുക - പനി, ഛർദ്ദി അല്ലെങ്കിൽ അലസത എന്നിവയിൽ കരച്ചിൽ തുടരുകയാണെങ്കിൽ, ഒരു ഡോക്ടറെ സമീപിക്കുക.",
"Trust Your Instincts – If the baby seems in severe pain, seek medical advice immediately."	:	"നിങ്ങളുടെ സഹജാവബോധത്തെ വിശ്വസിക്കുക - കുഞ്ഞിന് കഠിനമായ വേദന തോന്നുന്നുവെങ്കിൽ, ഉടൻ വൈദ്യോപദേശം തേടുക.",
"Check the Diaper – A wet or soiled diaper is a common cause of discomfort."	:	"ഡയപ്പർ പരിശോധിക്കുക - നനഞ്ഞതോ മലിനമായതോ ആയ ഡയപ്പർ അസ്വസ്ഥതയുടെ ഒരു സാധാരണ കാരണമാണ്.",
"Ensure Comfortable Clothing – Dress baby in breathable, soft fabrics and check for tight clothing."	:	"സുഖപ്രദമായ വസ്ത്രങ്ങൾ ഉറപ്പാക്കുക - ശ്വസിക്കാൻ കഴിയുന്നതും മൃദുവായതുമായ തുണിത്തരങ്ങൾ കുഞ്ഞിനെ ധരിക്കുക, ഇറുകിയ വസ്ത്രങ്ങൾ പരിശോധിക്കുക.",
"Adjust Temperature – Feel baby's neck/back to see if they are too hot or cold."	:	"താപനില ക്രമീകരിക്കുക - കുഞ്ഞിൻ്റെ കഴുത്ത്/മുതുകിൽ അനുഭവപ്പെടുക, അവ വളരെ ചൂടാണോ തണുപ്പാണോ എന്ന് നോക്കുക.",
"Check for External Irritants – Tags, rough fabric, or hair wrapped around fingers/toes can cause irritation."	:	"ബാഹ്യ പ്രകോപനങ്ങൾ ഉണ്ടോയെന്ന് പരിശോധിക്കുക - ടാഗുകൾ, പരുക്കൻ തുണികൾ, അല്ലെങ്കിൽ വിരലുകളിൽ/കാൽവിരലുകളിൽ പൊതിഞ്ഞ മുടി പ്രകോപിപ്പിക്കാം.",
"Reposition Baby – Changing positions or holding them differently can sometimes help."	:	"പുനഃസ്ഥാപിക്കൽ ബേബി - സ്ഥാനങ്ങൾ മാറ്റുകയോ അവയെ വ്യത്യസ്തമായി പിടിക്കുകയോ ചെയ്യുന്നത് ചിലപ്പോൾ സഹായിക്കും.",
"Use Gentle Motions – Rocking, swaying, or holding baby in a 'colic carry' (on their tummy along your forearm) can help."	:	"മൃദുലമായ ചലനങ്ങൾ ഉപയോഗിക്കുക - കുഞ്ഞിനെ 'കോളിക് കാരി'യിൽ (നിങ്ങളുടെ കൈത്തണ്ടയിൽ അവരുടെ വയറ്റിൽ) കുലുക്കുക, കുലുക്കുക അല്ലെങ്കിൽ പിടിക്കുക.",
"Try White Noise – Rhythmic sounds, like a fan or heartbeat sound, can be soothing."	:	"വൈറ്റ് നോയ്സ് പരീക്ഷിക്കുക - ഫാൻ അല്ലെങ്കിൽ ഹൃദയമിടിപ്പ് ശബ്ദം പോലെയുള്ള താളാത്മകമായ ശബ്ദങ്ങൾ ശാന്തമാകും.",
"Burp Baby Well – Gas buildup can make colic worse. Burp frequently during feeds."	:	"ബേബി വെൽ - വാതകം അടിഞ്ഞുകൂടുന്നത് കോളിക്കിനെ കൂടുതൽ വഷളാക്കും. ഫീഡ് സമയത്ത് ഇടയ്ക്കിടെ പൊട്ടുക.",
"Massage the Tummy – A gentle circular tummy massage can relieve gas."	:	"വയറ് മസാജ് ചെയ്യുക - മൃദുവായ വൃത്താകൃതിയിലുള്ള വയറ് മസാജ് ചെയ്യുന്നത് വാതകം ഒഴിവാക്കും.",
"Consult a Pediatrician – If colic persists, discuss options like probiotic drops or diet changes (for breastfeeding moms)."	:	"ഒരു ശിശുരോഗവിദഗ്ദ്ധനെ സമീപിക്കുക - കോളിക് തുടരുകയാണെങ്കിൽ, പ്രോബയോട്ടിക് ഡ്രോപ്പുകൾ അല്ലെങ്കിൽ ഭക്ഷണത്തിലെ മാറ്റങ്ങൾ (മുലയൂട്ടുന്ന അമ്മമാർക്ക്) പോലുള്ള ഓപ്ഷനുകൾ ചർച്ച ചെയ്യുക.",
"Respond with Reassurance – Holding, talking, or making eye contact helps babies feel secure."	:	"ഉറപ്പോടെ പ്രതികരിക്കുക - പിടിക്കുക, സംസാരിക്കുക, അല്ലെങ്കിൽ കണ്ണിൽ സമ്പർക്കം പുലർത്തുക, കുഞ്ഞുങ്ങൾക്ക് സുരക്ഷിതത്വം തോന്നാൻ സഹായിക്കുന്നു.",
"Try Gentle Touch – A cuddle or soft pat on the back can be calming."	:	"മൃദുലമായ സ്പർശനം പരീക്ഷിക്കുക - മുതുകിൽ ആലിംഗനം ചെയ്യുകയോ മൃദുവായ തട്ടുകയോ ചെയ്യുന്നത് ശാന്തമാകും.",
"Engage with Soothing Sounds – Humming or talking in a calm voice can reassure the baby."	:	"ശാന്തമായ ശബ്ദങ്ങളുമായി ഇടപഴകുക - മൂളുകയോ ശാന്തമായ ശബ്ദത്തിൽ സംസാരിക്കുകയോ ചെയ്യുന്നത് കുഞ്ഞിന് ഉറപ്പുനൽകുന്നു.",
"Encourage Independent Comforting – Allow baby to self-soothe briefly before immediately responding."	:	"സ്വതന്ത്രമായ ആശ്വാസം പ്രോത്സാഹിപ്പിക്കുക - ഉടൻ പ്രതികരിക്കുന്നതിന് മുമ്പ് കുഞ്ഞിനെ സ്വയം ശാന്തമാക്കാൻ അനുവദിക്കുക.",
"Maintain a Balance – Meeting attention needs is important, but consistency in response helps babies learn security."	:	"ഒരു ബാലൻസ് നിലനിർത്തുക - ശ്രദ്ധയുടെ ആവശ്യങ്ങൾ നിറവേറ്റുന്നത് പ്രധാനമാണ്, എന്നാൽ പ്രതികരണത്തിൽ സ്ഥിരത പുലർത്തുന്നത് സുരക്ഷിതത്വം പഠിക്കാൻ കുഞ്ഞുങ്ങളെ സഹായിക്കുന്നു.",
"Cry History"	:	"ക്രൈ ഹിസ്റ്ററി",
"Record"	:	"അത് രേഖപ്പെടുത്തുക",
"Allocry"	:	"അലോക്രി",
"Baby can cry due to"	:	"കാരണം കുഞ്ഞിന് കരയാൻ കഴിയും",
"Recording"	:	"റെക്കോർഡിംഗ്",
"Start Recording"	:	"റെക്കോർഡിംഗ് ആരംഭിക്കുക",
"Getting Your Baby Sound…"	:	"നിങ്ങളുടെ കുഞ്ഞിൻ്റെ ശബ്ദം ലഭിക്കുന്നു...",
"Try to avoid background noise"	:	"പശ്ചാത്തല ശബ്ദം ഒഴിവാക്കാൻ ശ്രമിക്കുക",
"High-pitched, intense crying often indicates pain or immediate needs."	:	"ഉച്ചത്തിലുള്ള, തീവ്രമായ കരച്ചിൽ പലപ്പോഴും വേദനയെയോ അടിയന്തിര ആവശ്യങ്ങളെയോ സൂചിപ്പിക്കുന്നു.",
"Rhythmic crying that gets louder and softer might mean your baby is tired."	:	"താളാത്മകമായ കരച്ചിൽ ഉച്ചത്തിലും മൃദുലമായും വരുന്നത് നിങ്ങളുടെ കുഞ്ഞ് ക്ഷീണിതനാണെന്ന് അർത്ഥമാക്കാം.",
"Short, low-pitched cries repeated every few seconds usually signal hunger."	:	"ഓരോ ഏതാനും സെക്കൻഡിലും ആവർത്തിച്ചുള്ള ഹ്രസ്വവും താഴ്ന്നതുമായ നിലവിളികൾ സാധാരണയായി വിശപ്പിനെ സൂചിപ്പിക്കുന്നു.",
"Whimpering or whining sounds might indicate mild discomfort or wanting attention."	:	"വിമ്പറിംഗ് അല്ലെങ്കിൽ വിങ്ങിംഗ് ശബ്ദങ്ങൾ നേരിയ അസ്വാസ്ഥ്യത്തെയോ ശ്രദ്ധ ആഗ്രഹിക്കുന്നതിനെയോ സൂചിപ്പിക്കാം.",
"Long, high-pitched screams could be signs of colic or stomach pain."	:	"നീണ്ട, ഉയർന്ന നിലവിളി കോളിക്കിൻ്റെയോ വയറുവേദനയുടെയോ ലക്ഷണങ്ങളായിരിക്കാം.",
"Sudden, sharp cries might mean your baby is too hot or cold."	:	"പെട്ടെന്നുള്ള, മൂർച്ചയുള്ള കരച്ചിൽ നിങ്ങളുടെ കുട്ടി വളരെ ചൂടുള്ളതോ തണുത്തതോ ആണെന്ന് അർത്ഥമാക്കാം.",
"Persistent crying with leg movement often indicates diaper change needs."	:	"കാലിൻ്റെ ചലനത്തോടുകൂടിയ നിരന്തരമായ കരച്ചിൽ പലപ്പോഴും ഡയപ്പർ മാറ്റത്തിൻ്റെ ആവശ്യകതയെ സൂചിപ്പിക്കുന്നു.",
"Baby Cry Not Detected"	:	"കുഞ്ഞിൻ്റെ കരച്ചിൽ കണ്ടെത്തിയില്ല",
		
"Select Language"	:	"ഭാഷ തിരഞ്ഞെടുക്കുക",
"Enter Mobile Number"	:	"മൊബൈൽ നമ്പർ നൽകുക",
"SEND OTP"	:	"OTP അയയ്ക്കുക",
"How do you feel today ?"	:	"ഇന്ന് നിങ്ങൾക്ക് എങ്ങനെ തോന്നുന്നു?",
"Online"	:	"ഓൺലൈൻ",
"Offline"	:	"ഓഫ്‌ലൈൻ",
"Image Uploaded"	:	"ചിത്രം അപ്‌ലോഡ് ചെയ്തു",
"Type a message"	:	"ഒരു സന്ദേശം ടൈപ്പ് ചെയ്യുക",
"Choose photo from"	:	"നിന്ന് ഫോട്ടോ തിരഞ്ഞെടുക്കുക",
"Get Connected with doctors"	:	"ഡോക്ടർമാരുമായി ബന്ധപ്പെടുക",
"Connect with Doctor"	:	"ഡോക്ടറുമായി ബന്ധപ്പെടുക",
"Connect with Health worker"	:	"ആരോഗ്യ പ്രവർത്തകരുമായി ബന്ധപ്പെടുക",
"Connect with AlloBot"	:	"AlloBot-മായി ബന്ധിപ്പിക്കുക",
"Sorry No Awareness Post"	:	"ക്ഷമിക്കണം ബോധവൽക്കരണ പോസ്റ്റില്ല",
"Checkup Completed"	:	"പരിശോധന പൂർത്തിയായി",
"Waiting for Doctor Feedback"	:	"ഡോക്ടറുടെ പ്രതികരണത്തിനായി കാത്തിരിക്കുന്നു",
"Checkup need to be done"	:	"പരിശോധന നടത്തേണ്ടതുണ്ട്",
"Checkup"	:	"ചെക്ക് അപ്പ്",
"No Checkup Found"	:	"പരിശോധനയൊന്നും കണ്ടെത്തിയില്ല",
"Checkup Details"	:	"പരിശോധന വിശദാംശങ്ങൾ",
"Doctor Name"	:	"ഡോക്ടറുടെ പേര്",
"Date"	:	"തീയതി",
"Health Status"	:	"ആരോഗ്യ നില",
"Case Summary"	:	"കേസ് സംഗ്രഹം",
"Prescription"	:	"കുറിപ്പടി",
"Next Appointment Time"	:	"അടുത്ത അപ്പോയിൻ്റ്മെൻ്റ് സമയം",
"Symptoms"	:	"രോഗലക്ഷണങ്ങൾ",
"Vitals"	:	"ജീവകങ്ങൾ",
"Add Prescription"	:	"കുറിപ്പടി ചേർക്കുക",
"ADD PRESCRIPTION"	:	"കുറിപ്പടി ചേർക്കുക",
"Click to Add Image"	:	"ചിത്രം ചേർക്കാൻ ക്ലിക്ക് ചെയ്യുക",
"View Prescription"	:	"കുറിപ്പടി കാണുക",
"Error loading image"	:	"ചിത്രം ലോഡ് ചെയ്യുന്നതിൽ പിശക്",
"Prescription Type"	:	"കുറിപ്പടി തരം",
"Date Added"	:	"തീയതി ചേർത്തു",
"Description"	:	"വിവരണം",
"Add Report"	:	"റിപ്പോർട്ട് ചേർക്കുക",
"NO IMAGE"	:	"ചിത്രമൊന്നുമില്ല",
"Click Add Image Button"	:	"ചിത്രം ചേർക്കുക ബട്ടൺ ക്ലിക്ക് ചെയ്യുക",
"ADD IMAGE"	:	"ചിത്രം ചേർക്കുക",
"ADD REPORT"	:	"റിപ്പോർട്ട് ചേർക്കുക",
"Report"	:	"റിപ്പോർട്ട് ചെയ്യുക",
"Scan and Add new Report"	:	"സ്കാൻ ചെയ്ത് പുതിയ റിപ്പോർട്ട് ചേർക്കുക",
"Self Screening"	:	"స్వీయ స్క్రీనింగ్",
"BACK"	:	"തിരികെ",
"NEXT"	:	"അടുത്തത്",
"Finish"	:	"പൂർത്തിയാക്കുക",
"Summary Report"	:	"സംഗ്രഹ റിപ്പോർട്ട്",
"Submit"	:	"സമർപ്പിക്കുക",
"Let's begin the test"	:	"നമുക്ക് ടെസ്റ്റ് തുടങ്ങാം",
"Hemoglobin Test"	:	"ഹീമോഗ്ലോബിൻ ടെസ്റ്റ്",
"Easily get your Reading by Performing the scans below"	:	"ചുവടെയുള്ള സ്കാനുകൾ നടത്തി നിങ്ങളുടെ വായന എളുപ്പത്തിൽ നേടുക",
"Fetal Monitoring"	:	"ഗര്ഭപിണ്ഡത്തിൻ്റെ നിരീക്ഷണം",
"Upload Report"	:	"റിപ്പോർട്ട് അപ്‌ലോഡ് ചെയ്യുക",
"Tap to Change"	:	"മാറ്റാൻ ടാപ്പ് ചെയ്യുക",
"Heart Rate"	:	"ഹൃദയമിടിപ്പ്",
"BPM"	:	"ബിപിഎം",
"Kick Count"	:	"കിക്ക് കൗണ്ട്",
"Tap to Increase the Count"	:	"എണ്ണം വർദ്ധിപ്പിക്കാൻ ടാപ്പ് ചെയ്യുക",
"Add Glucose Report"	:	"ഗ്ലൂക്കോസ് റിപ്പോർട്ട് ചേർക്കുക",
"Blood Glucose Value"	:	"രക്തത്തിലെ ഗ്ലൂക്കോസിൻ്റെ മൂല്യം",
"Add Hemoglobin Report"	:	"ഹീമോഗ്ലോബിൻ റിപ്പോർട്ട് ചേർക്കുക",
"Hemoglobin Value"	:	"ഹീമോഗ്ലോബിൻ മൂല്യം",
"Ultra Sound"	:	"അൾട്രാസൗണ്ട്",
"Fasting"	:	"ഉപവാസം",
"At rest"	:	"വിശ്രമത്തിലാണ്",
"After Walk"	:	"നടത്തത്തിന് ശേഷം",
"Select Height"	:	"ഉയരം തിരഞ്ഞെടുക്കുക",
"Select Weight"	:	"ഭാരം തിരഞ്ഞെടുക്കുക",
"After walk"	:	"നടത്തത്തിന് ശേഷം",
"Address Information"	:	"വിലാസ വിവരം",
"Search"	:	"തിരയുക",
"Continue"	:	"തുടരുക",
"Phone Number"	:	"ഫോൺ നമ്പർ",
"Profile Details"	:	"പ്രൊഫൈൽ വിശദാംശങ്ങൾ",
"Gender"	:	"ലിംഗഭേദം",
"Male"	:	"പുരുഷൻ",
"Female"	:	"സ്ത്രീ",
"Select Blood Group"	:	"രക്തഗ്രൂപ്പ് തിരഞ്ഞെടുക്കുക",
"Select Last cycle Date"	:	"അവസാന സൈക്കിൾ തീയതി തിരഞ്ഞെടുക്കുക",
"Are you my mom or dad?"	:	"നീ എൻ്റെ അമ്മയോ അച്ഛനോ?",
"Dad"	:	"അച്ഛൻ",
"Mom"	:	"അമ്മ",
"Enter your Partner Details"	:	"നിങ്ങളുടെ പങ്കാളിയുടെ വിശദാംശങ്ങൾ നൽകുക",
"Pregnancy Status"	:	"ഗർഭാവസ്ഥയുടെ അവസ്ഥ",
"Partner Pregnancy Status"	:	"പങ്കാളിയുടെ ഗർഭാവസ്ഥയുടെ അവസ്ഥ",
"Average Length of Cycles"	:	"സൈക്കിളുകളുടെ ശരാശരി ദൈർഘ്യം",
"Day"	:	"ദിവസം",
"Not yet started"	:	"ഇതുവരെ തുടങ്ങിയിട്ടില്ല",
"NORMAL"	:	"സാധാരണ",
"Health Status"	:	"ആരോഗ്യ നില",
"Last Screened"	:	"അവസാനം പ്രദർശിപ്പിച്ചത്",
"GOLD"	:	"സ്വർണ്ണം",
"Subscription Plan"	:	"സബ്സ്ക്രിപ്ഷൻ പ്ലാൻ",
"No News Feed"	:	"വാർത്താ ഫീഡ് ഇല്ല",
"Probable Reason"	:	"സാധ്യതയുള്ള കാരണം",
"Recommendations"	:	"ശുപാർശകൾ",
"Hi!"	:	"ഹായ്!",
"How do you feel today?"	:	"ഇന്ന് നിങ്ങൾക്ക് എന്തു തോന്നുന്നു?",
"Select Exercise that have you done today?"	:	"നിങ്ങൾ ഇന്ന് ചെയ്ത വ്യായാമം തിരഞ്ഞെടുക്കുക?",
"None"	:	"ഒന്നുമില്ല",
"Select tablets that you have taken"	:	"നിങ്ങൾ എടുത്ത ടാബ്‌ലെറ്റുകൾ തിരഞ്ഞെടുക്കുക",
"Sleep Duration"	:	"ഉറക്കത്തിൻ്റെ ദൈർഘ്യം",
"Do you have any of these Symptoms?"	:	"നിങ്ങൾക്ക് ഈ ലക്ഷണങ്ങളിൽ എന്തെങ്കിലും ഉണ്ടോ?",
"Baby Voice is Recording"	:	"ബേബി വോയ്സ് റെക്കോർഡ് ചെയ്യുന്നു",
"STOP"	:	"നിർത്തുക",
"Click the Record Button to Start Recording"	:	"റെക്കോർഡിംഗ് ആരംഭിക്കാൻ റെക്കോർഡ് ബട്ടൺ ക്ലിക്ക് ചെയ്യുക",
"Record"	:	"രേഖപ്പെടുത്തുക",
"How many Glass of water have you drunk today?"	:	"ഇന്ന് നിങ്ങൾ എത്ര ഗ്ലാസ് വെള്ളം കുടിച്ചു?",
"OTP Verification"	:	"OTP പരിശോധന",
"Enter OTP sent to"	:	"അയച്ച OTP നൽകുക",
"Verify and proceed"	:	"പരിശോധിച്ച് തുടരുക",
"Appointment"	:	"നിയമനം",
"Select Hospital"	:	"ആശുപത്രി തിരഞ്ഞെടുക്കുക",
"Select Doctor"	:	"ഡോക്ടറെ തിരഞ്ഞെടുക്കുക",
"Appointment Date"	:	"അപ്പോയിൻ്റ്മെൻ്റ് തീയതി",
"Available slots"	:	"ലഭ്യമായ സ്ലോട്ടുകൾ",
"No Slots Available"	:	"സ്ലോട്ടുകളൊന്നും ലഭ്യമല്ല",
"View Available Slots"	:	"ലഭ്യമായ സ്ലോട്ടുകൾ കാണുക",
"Start time Slot"	:	"ആരംഭ സമയ സ്ലോട്ട്",
"Diagnosis Description"	:	"രോഗനിർണയ വിവരണം",
"Book"	:	"പുസ്തകം",
"Update"	:	"അപ്ഡേറ്റ്",
"Respiratory Rate"	:	"ശ്വസന നിരക്ക്",
"Appointments"	:	"നിയമനങ്ങൾ",
"As a companion in your pregnancy we help you with the following"	:	"നിങ്ങളുടെ ഗർഭാവസ്ഥയിൽ ഒരു കൂട്ടാളി എന്ന നിലയിൽ ഞങ്ങൾ ഇനിപ്പറയുന്നവയിൽ നിങ്ങളെ സഹായിക്കുന്നു",
"Book An Appointment"	:	"ഒരു അപ്പോയിൻ്റ്മെൻ്റ് ബുക്ക് ചെയ്യുക",
"Pregnancy Monitoring"	:	"ഗർഭാവസ്ഥ നിരീക്ഷണം",
"Help Line"	:	"ഹെൽപ്പ് ലൈൻ",
"Current Appointment"	:	"നിലവിലെ നിയമനം",
"No Upcoming Appointments"	:	"വരാനിരിക്കുന്ന അപ്പോയിൻ്റ്മെൻ്റുകളൊന്നുമില്ല",
"Time"	:	"സമയം",
"Status"	:	"നില",
"Reason"	:	"കാരണം",
"Cancel Appointment"	:	"അപ്പോയിൻ്റ്മെൻ്റ് റദ്ദാക്കുക",
"Show Appointment"	:	"അപ്പോയിൻ്റ്മെൻ്റ് കാണിക്കുക",
"My Appointments"	:	"എൻ്റെ നിയമനങ്ങൾ",
"Appointment Status"	:	"നിയമന നില",
"App Info"	:	"ആപ്പ് വിവരം",
"CHECK FOR UPDATES"	:	"അപ്ഡേറ്റുകൾക്കായി പരിശോധിക്കുക",
"Edit Profile"	:	"പ്രൊഫൈൽ എഡിറ്റ് ചെയ്യുക",
"Help"	:	"സഹായം",
"Tell us what's going on"	:	"എന്താണ് സംഭവിക്കുന്നതെന്ന് ഞങ്ങളോട് പറയുക",
"Tell us why you're reaching us"	:	"എന്തുകൊണ്ടാണ് നിങ്ങൾ ഞങ്ങളെ സമീപിക്കുന്നതെന്ന് ഞങ്ങളോട് പറയുക",
"How do you feel? (Optional)"	:	"നിനക്ക് എന്തുതോന്നുന്നു? (ഓപ്ഷണൽ)",
"My Hospital"	:	"എൻ്റെ ആശുപത്രി",
"No hospitals found"	:	"ആശുപത്രികളൊന്നും കണ്ടെത്തിയില്ല",
"District"	:	"ജില്ല",
"Settings"	:	"ക്രമീകരണങ്ങൾ",
"English"	:	"ഇംഗ്ലീഷ്",
"Logout Successful"	:	"ലോഗ്ഔട്ട് വിജയിച്ചു",
"Subscribe"	:	"സബ്സ്ക്രൈബ് ചെയ്യുക",
"Subscription"	:	"സബ്സ്ക്രിപ്ഷൻ",
"Current Plan"	:	"നിലവിലെ പ്ലാൻ",
"Monthly"	:	"പ്രതിമാസ",
"Yearly"	:	"വർഷം തോറും",
"Based on patient reviews"	:	"രോഗികളുടെ അവലോകനങ്ങളെ അടിസ്ഥാനമാക്കി",
"Working Hours"	:	"ജോലി സമയം",
"Contact Information"	:	"ബന്ധപ്പെടാനുള്ള വിവരങ്ങൾ",
"Personalised Pregnancy Care"	:	"വ്യക്തിഗത ഗർഭ പരിചരണം",
"Helps you to consult Doctor Virtually"	:	"ഫലത്തിൽ ഡോക്ടറെ സമീപിക്കാൻ നിങ്ങളെ സഹായിക്കുന്നു",
"Engage with Doctor through video and audio"	:	"വീഡിയോയിലൂടെയും ഓഡിയോയിലൂടെയും ഡോക്ടറുമായി ഇടപഴകുക",
"Keep on track your Health"	:	"നിങ്ങളുടെ ആരോഗ്യം ട്രാക്ക് ചെയ്യുക",
"By continuing, You agree that you have read and accept our"	:	"തുടരുന്നതിലൂടെ, നിങ്ങൾ വായിക്കുകയും അംഗീകരിക്കുകയും ചെയ്തുവെന്ന് നിങ്ങൾ സമ്മതിക്കുന്നു",
"T&C and Privacy Policy"	:	"ടി&സിയും സ്വകാര്യതാ നയവും",
"Thinking..."	:	"ചിന്തിക്കുന്നു...",
"Your maternal AI assistant is processing your question"	:	"നിങ്ങളുടെ മാതൃ AI അസിസ്റ്റൻ്റ് നിങ്ങളുടെ ചോദ്യം പ്രോസസ്സ് ചെയ്യുന്നു",
"Your Maternal AI Assistant"	:	"നിങ്ങളുടെ മാതൃ AI അസിസ്റ്റൻ്റ്",
"Welcome to Allobot!"	:	"അലോബോട്ടിലേക്ക് സ്വാഗതം!",
"I'm here to support you through your maternal journey. Ask me anything about pregnancy, childbirth, or early motherhood."	:	"നിങ്ങളുടെ മാതൃ യാത്രയിൽ നിങ്ങളെ പിന്തുണയ്ക്കാൻ ഞാൻ ഇവിടെയുണ്ട്. ഗർഭധാരണം, പ്രസവം, അല്ലെങ്കിൽ നേരത്തെയുള്ള മാതൃത്വം എന്നിവയെക്കുറിച്ച് എന്നോട് ചോദിക്കൂ.",
"What You Can Ask Me"	:	"നിങ്ങൾക്ക് എന്നോട് എന്താണ് ചോദിക്കാൻ കഴിയുക",
"Pregnancy health tips"	:	"ഗർഭധാരണത്തിനുള്ള ആരോഗ്യ നുറുങ്ങുകൾ",
"Nutrition advice"	:	"പോഷകാഹാര ഉപദേശം",
"Baby care basics"	:	"ശിശു സംരക്ഷണത്തിൻ്റെ അടിസ്ഥാനകാര്യങ്ങൾ",
"Trimester milestones"	:	"ത്രിമാസത്തിലെ നാഴികക്കല്ലുകൾ",
"Ask Allobot..."	:	"അലോബോട്ടിനോട് ചോദിക്കൂ...",
"Incoming Call"	:	"ഇൻകമിംഗ് കോൾ",
"Waiting"	:	"കാത്തിരിക്കുന്നു",
"No messages yet"	:	"ഇതുവരെ സന്ദേശങ്ങളൊന്നുമില്ല",
"Tablets"	:	"ഗുളികകൾ",
"Units"	:	"യൂണിറ്റുകൾ",
"Timing"	:	"സമയക്രമീകരണം",
"No prescriptions found."	:	"കുറിപ്പടികളൊന്നും കണ്ടെത്തിയില്ല.",
"No description available"	:	"വിവരണമൊന്നും ലഭ്യമല്ല",
"No reports found"	:	"റിപ്പോർട്ടുകളൊന്നും കണ്ടെത്തിയില്ല",
"Report Details"	:	"വിശദാംശങ്ങൾ റിപ്പോർട്ട് ചെയ്യുക",
"Unknown Report Type"	:	"അജ്ഞാത റിപ്പോർട്ട് തരം",
"Test Results"	:	"ടെസ്റ്റ് ഫലങ്ങൾ",
"Delete Report"	:	"റിപ്പോർട്ട് ഇല്ലാതാക്കുക",
"Are you sure you want to delete this report?"	:	"ഈ റിപ്പോർട്ട് ഇല്ലാതാക്കണമെന്ന് തീർച്ചയാണോ?",
"CANCEL"	:	"റദ്ദാക്കുക",
"DELETE"	:	"ഇല്ലാതാക്കുക",
"Normal"	:	"സാധാരണ",
"Body pain"	:	"ശരീര വേദന",
"Burning Stomach"	:	"കത്തുന്ന വയറ്",
"Cold cough"	:	"തണുത്ത ചുമ",
"Dizziness"	:	"തലകറക്കം",
"Headache"	:	"തലവേദന",
"Vomiting"	:	"ഛർദ്ദി",
"Other"	:	"മറ്റുള്ളവ",
"Blood Pressure"	:	"രക്തസമ്മർദ്ദം",
"Temperature"	:	"താപനില",
"Blood Saturation"	:	"രക്ത സാച്ചുറേഷൻ",
"Blood Glucose"	:	"രക്തത്തിലെ ഗ്ലൂക്കോസ്",
"BMI"	:	"ബിഎംഐ",
"HRV"	:	"എച്ച്.ആർ.വി",
"Baby Cry Not Detected."	:	"കുഞ്ഞിൻ്റെ കരച്ചിൽ കണ്ടെത്തിയില്ല.",
"The baby cry detection process failed. Please check your connection or try again."	:	"കുഞ്ഞിൻ്റെ കരച്ചിൽ കണ്ടെത്തൽ പ്രക്രിയ പരാജയപ്പെട്ടു. ദയവായി നിങ്ങളുടെ കണക്ഷൻ പരിശോധിക്കുക അല്ലെങ്കിൽ വീണ്ടും ശ്രമിക്കുക.",
"Retry"	:	"വീണ്ടും ശ്രമിക്കുക",
"Please select Appointment Date"	:	"അപ്പോയിൻ്റ്മെൻ്റ് തീയതി തിരഞ്ഞെടുക്കുക",
"Please enter Diagnosis Description"	:	"ദയവായി രോഗനിർണയ വിവരണം നൽകുക",
"No data available"	:	"ഡാറ്റ ലഭ്യമല്ല",
"Pregnant"	:	"ഗർഭിണിയാണ്",
"Not Pregnant"	:	"ഗർഭിണിയല്ല",
"Summary"	:	"സംഗ്രഹം",
"Upcoming Appointments"	:	"വരാനിരിക്കുന്ന നിയമനങ്ങൾ",
"No appointments scheduled"	:	"അപ്പോയിൻ്റ്‌മെൻ്റുകളൊന്നും ഷെഡ്യൂൾ ചെയ്തിട്ടില്ല",
"No"	:	"ഇല്ല",
"Yes"	:	"അതെ",
"No appointments found"	:	"നിയമനങ്ങളൊന്നും കണ്ടെത്തിയില്ല",
"JioVio Healthcare"	:	"ജിയോവിയോ ഹെൽത്ത് കെയർ",
"General Details"	:	"പൊതുവായ വിശദാംശങ്ങൾ",
"Partner Details"	:	"പങ്കാളിയുടെ വിശദാംശങ്ങൾ",
"Pregnancy Details"	:	"ഗർഭത്തിൻറെ വിശദാംശങ്ങൾ",
"Address Details"	:	"വിലാസത്തിൻ്റെ വിശദാംശങ്ങൾ",
"Contact Us"	:	"ഞങ്ങളെ സമീപിക്കുക",
"Something not Working"	:	"എന്തോ പ്രവർത്തിക്കുന്നില്ല",
"Feature Request"	:	"ഫീച്ചർ അഭ്യർത്ഥന",
"Question"	:	"ചോദ്യം",
"FeedBack"	:	"ഫീഡ്ബാക്ക്",
"SEND"	:	"അയയ്ക്കുക",
"My Subscription"	:	"എൻ്റെ സബ്സ്ക്രിപ്ഷൻ",
"Language"	:	"ഭാഷ",
"Terms & Conditions"	:	"നിബന്ധനകളും വ്യവസ്ഥകളും",
"Privacy Policy"	:	"സ്വകാര്യതാ നയം",
"Log Out"	:	"ലോഗ് ഔട്ട് ചെയ്യുക",
"Are you sure to logout?"	:	"ലോഗ്ഔട്ട് ചെയ്യുമെന്ന് ഉറപ്പാണോ?",
"Cancel"	:	"റദ്ദാക്കുക",
"Ok"	:	"ശരി",
"Change Default"	:	"സ്ഥിരസ്ഥിതി മാറ്റുക",
"Write Description"	:	"വിവരണം എഴുതുക",
"Please enter Description"	:	"ദയവായി വിവരണം നൽകുക",
"Door No"	:	"ഡോർ നമ്പർ",
"Please enter Door No"	:	"ദയവായി ഡോർ നമ്പർ നൽകുക",
"Street Name"	:	"തെരുവിൻ്റെ പേര്",
"Please enter Street Name"	:	"തെരുവിൻ്റെ പേര് നൽകുക",
"Pincode"	:	"പിൻകോഡ്",
"Please enter Pincode"	:	"ദയവായി പിൻകോഡ് നൽകുക",
"Search Area"	:	"തിരയൽ ഏരിയ",
"Select Area Name"	:	"ഏരിയയുടെ പേര് തിരഞ്ഞെടുക്കുക",
"Enter your Name"	:	"നിങ്ങളുടെ പേര് നൽകുക",
"Please enter your name"	:	"ദയവായി നിങ്ങളുടെ പേര് നൽകുക",
"Enter Email Id"	:	"ഇമെയിൽ ഐഡി നൽകുക",
"Please Select Gender"	:	"ദയവായി ലിംഗഭേദം തിരഞ്ഞെടുക്കുക",
"Age"	:	"പ്രായം",
"Please enter age"	:	"ദയവായി പ്രായം നൽകുക",
"Please enter correct age"	:	"ദയവായി ശരിയായ പ്രായം നൽകുക",
"LMP Date"	:	"LMP തീയതി",
"Please enter LMP Date"	:	"ദയവായി LMP തീയതി നൽകുക",
"ED Date"	:	"ED തീയതി",
"Date of delivery"	:	"ഡെലിവറി തീയതി",
"Please enter Delivery Date"	:	"ഡെലിവറി തീയതി നൽകുക",
"Please enter Partner Name"	:	"പങ്കാളിയുടെ പേര് നൽകുക",
"Partner Name"	:	"പങ്കാളിയുടെ പേര്",
"Please enter Partner Mobile Number"	:	"പങ്കാളി മൊബൈൽ നമ്പർ നൽകുക",
"Partner Mobile Number"	:	"പങ്കാളി മൊബൈൽ നമ്പർ",
"Bed Time"	:	"ബെഡ് ടൈം",
"Please enter Date of Birth"	:	"ദയവായി ജനനത്തീയതി നൽകുക",
"Wake Up Time"	:	"ഉണരേണ്ട സമയം",
"Name"	:	"പേര്",
"Please Select Parent Type"	:	"ദയവായി രക്ഷാകർതൃ തരം തിരഞ്ഞെടുക്കുക",
"Parent Type"	:	"രക്ഷാകർതൃ തരം",
"Please Select Pregnant Status"	:	"ദയവായി ഗർഭിണിയുടെ അവസ്ഥ തിരഞ്ഞെടുക്കുക",
"Please enter Area"	:	"ദയവായി ഏരിയ നൽകുക",
"Area"	:	"ഏരിയ",
"Services"	:	"സേവനങ്ങൾ",
"AlloBaby"	:	"അലോബേബി",
"Awareness"	:	"അവബോധം",
"Screening"	:	"സ്ക്രീനിംഗ്",
"Glucose Test"	:	"ഗ്ലൂക്കോസ് ടെസ്റ്റ്",
"Ultrasound Test"	:	"അൾട്രാസൗണ്ട് ടെസ്റ്റ്",
"Urine Test"	:	"മൂത്ര പരിശോധന",
"Home"	:	"വീട്",
"Service"	:	"സേവനം",
"Chat"	:	"ചാറ്റ്",
"Logout"	:	"പുറത്തുകടക്കുക",
"Notification"	:	"അറിയിപ്പ്",
"ON"	:	"ഓൺ",
"OFF"	:	"ഓഫ്",
"ON/OFF"	:	"ഓൺ/ഓഫ്",
"AI Recommendation"	:	"AI ശുപാർശ",
"Analyzing your health data..."	:	"നിങ്ങളുടെ ആരോഗ്യ ഡാറ്റ വിശകലനം ചെയ്യുന്നു...",
"No summary available"	:	"സംഗ്രഹം ലഭ്യമല്ല",
"Book Appointment"	:	"നിയമനം ബുക്ക് ചെയ്യുക",
"SCAN AND ADD REPORT"	:	"സ്കാൻ ചെയ്ത് റിപ്പോർട്ട് ചേർക്കുക",
"Allobot"	:	"അല്ലൊബോട്ട്",

};