final Map<String, String> ta = {
    "Select Language": "மொழியை தேர்ந்தெடுக்கவும்",
    "Enter Mobile Number": "மொபைல் எண்ணை உள்ளிடவும்",
    "SEND OTP": "OTP அனுப்பவும்",
    "How do you feel today ?": "இன்று நீங்கள் எப்படி உணர்கிறீர்கள்?",
    "Online": "ஆன்லைன்",
    "Offline": "ஆஃப்லைன்",
    "Image Uploaded": "படம் பதிவேற்றப்பட்டது",
    "Type a message": "செய்தியை தட்டச்சு செய்யவும்",
    "Choose photo from :": "இதிலிருந்து புகைப்படத்தைத் தேர்ந்தெடுக்கவும்:",
    "Get Connected with doctors": "மருத்துவர்களுடன் தொடர்பு கொள்ளுங்கள்",
    "Connect with Doctor": "டாக்டருடன் இணைக்கவும்",
    "Connect with Health worker": "சுகாதார ஊழியருடன் இணைக்கவும்",
    "Connect with AlloBot": "AlloBot உடன் இணைக்கவும்",
    "Sorry No Awareness Post": "மன்னிக்கவும் விழிப்புணர்வு பதிவு இல்லை",
    "Checkup Completed": "சோதனை முடிந்தது",
    "Waiting for Doctor Feedback": "மருத்துவரின் கருத்துக்காக காத்திருக்கிறேன்",
    "Checkup need to be done": "சோதனை செய்யப்பட வேண்டும்",
    "Checkup": "சோதனை",
    "No Checkup Found": "சோதனை எதுவும் இல்லை",
    "Checkup Details": "சோதனை விவரங்கள்",
    "Doctor Name": "மருத்துவர் பெயர்",
    "Date:": "தேதி:",
    "Health Status:": "சுகாதார நிலை:",
    "Case Summary": "விவரக்குறிப்பு",
    "Prescription": "மருந்துச்சீட்டு",
    "Next Appointment Time": "அடுத்த சந்திப்பு நேரம்",
    "Symptoms": "அறிகுறிகள்",
    "Vitals": "உயிர்கள்",
    "Add Prescription": "மருந்துச் சீட்டைச் சேர்க்கவும்",
    "ADD PRESCRIPTION": "மருந்துச் சீட்டைச் சேர்க்கவும்",
    "Click to Add Image": "படத்தைச் சேர்க்க கிளிக் செய்யவும்",
    "View Prescription": "மருந்துச்சீட்டைப் பார்க்கவும்",
    "Error loading image": "படத்தை ஏற்றுவதில் பிழை",
    "Prescription Type": "மருந்து வகை",
    "Date Added": "தேதி சேர்க்கப்பட்டது",
    "Description": "விளக்கம்",
    "Add Report": "அறிக்கையைச் சேர்",
    "NO IMAGE": "படம் இல்லை",
    "Click Add Image Button": "படத்தைச் சேர் பொத்தானைக் கிளிக் செய்யவும்",
    "ADD IMAGE": "படத்தைச் சேர்",
    "ADD REPORT": "அறிக்கையைச் சேர்",
    "Report": "அறிக்கை",
    "Scan and Add new Report": "ஸ்கேன் செய்து புதிய அறிக்கையைச் சேர்க்கவும்",
    "Self Screening": "சுய திரையிடல்",
    "BACK": "பின்செல்",
    "NEXT": "அடுத்து",
    "Finish": "முடிக்கவும்",
    "Summary Report": "சுருக்க அறிக்கை",
    "Submit": "சமர்ப்பிக்கவும்",
    "Let's begin the test": "சோதனையைத் தொடங்குவோம்",
    "Hemoglobin Test": "ஹீமோகுளோபின் சோதனை",
    "Easily get your Reading by Performing the scans below": "கீழே உள்ள ஸ்கேன்களைச் செய்வதன் மூலம் உங்கள் வாசிப்பை எளிதாகப் பெறுங்கள்",
    "Fetal Monitoring": "கரு கண்காணிப்பு",
    "Upload Report": "பதிவேற்ற அறிக்கை",
    "Tap to Change": "மாற்ற தட்டவும்",
    "Heart Rate": "இதய துடிப்பு",
    "BPM": "பிபிஎம்",
    "Kick Count": "உதை எண்ணிக்கை",
    "Tap to Increase the Count": "எண்ணிக்கையை அதிகரிக்க தட்டவும்",
    "Add Glucose Report": "குளுக்கோஸ் அறிக்கையைச் சேர்க்கவும்",
    "Blood Glucose Value": "இரத்த குளுக்கோஸ் மதிப்பு",
    "Add Hemoglobin Report": "ஹீமோகுளோபின் அறிக்கையைச் சேர்க்கவும்",
    "Hemoglobin Value": "ஹீமோகுளோபின் மதிப்பு",
    "Ultra Sound": "அல்ட்ராசவுண்ட்",
    "Fasting": "உண்ணாவிரதம்",
    "At rest": "ஓய்வில்",
    "After Walk": "நடந்த பிறகு",
    "Select Height": "உயரத்தைத் தேர்ந்தெடுக்கவும்",
    "Select Weight": "எடையைத் தேர்ந்தெடுக்கவும்",
    "After walk": "நடந்த பிறகு",
    "Address Information": "முகவரி தகவல்",
    "Search": "தேடல்",
    "Continue": "தொடரவும்",
    "Phone Number": "தொலைபேசி எண்",
    "Profile Details": "சுயவிவர விவரங்கள்",
    "Gender": "பாலினம்",
    "Male": "ஆண்",
    "Female": "பெண்",
    "Select Blood Group": "இரத்த வகையைத் தேர்ந்தெடுக்கவும்",
    "Select Last cycle Date": "கடைசி சுழற்சி தேதியைத் தேர்ந்தெடுக்கவும்",
    "Are you my mom or dad?": "நீங்கள் என் அம்மா அல்லது அப்பாவா?",
    "Dad": "அப்பா",
    "Mom": "அம்மா",
    "Enter your Partner Details": "உங்கள் துணை விவரங்களை உள்ளிடவும்",
    "Pregnancy Status": "கர்ப்ப நிலை",
    "Partner Pregnancy Status": "துணையின் கர்ப்ப நிலை",
    "Average Length of Cycles": "சுழற்சிகளின் சராசரி நீளம்",
    "Day": "நாள்",
    "Not yet started": "இன்னும் தொடங்கவில்லை",
    "NORMAL": "சாதாரண",
    "Health Status": "சுகாதார நிலை",
    "Last Screened": "கடைசியாக திரையிடப்பட்டது",
    "GOLD": "தங்கம்",
    "Subscription Plan": "சந்தா திட்டம்",
    "No News Feed": "செய்தி ஊட்டம் இல்லை",
    "Probable Reason": "சாத்தியமான காரணம்",
    "Recommendations": "பரிந்துரைகள்",
    "Hi!": "வணக்கம்!",
    "How do you feel today?": "இன்று நீங்கள் எப்படி உணர்கிறீர்கள்?",
    "Select Exercise that have you done today?": "இன்று நீங்கள் செய்த உடற்பயிற்சியைத் தேர்ந்தெடுக்கவும்?",
    "None": "எதுவுமில்லை",
    "Select tablets that you have taken": "நீங்கள் எடுத்துக்கொண்ட மாத்திரைகளைத் தேர்ந்தெடுக்கவும்",
    "Sleep Duration": "தூக்க காலம்",
    "Do you have any of these Symptoms?": "இந்த அறிகுறிகள் ஏதேனும் உங்களுக்கு உள்ளதா?",
    "Baby Voice is Recording": "குழந்தை குரல் பதிவு செய்யப்படுகிறது",
    "STOP": "நிறுத்து",
    "Click the Record Button to Start Recording": "பதிவு செய்யத் தொடங்க பதிவு பொத்தானைக் கிளிக் செய்யவும்",
    "Record": "பதிவு",
    "How many Glass of water have you drunk today?": "இன்று நீங்கள் எத்தனை கண்ணாடி தண்ணீர் குடித்தீர்கள்?",
    "OTP Verification": "OTP சரிபார்ப்பு",
    "Enter OTP sent to": "அனுப்பப்பட்ட OTPஐ உள்ளிடவும்",
    "Verify and proceed": "சரிபார்த்து தொடரவும்",
    "Appointment": "சந்திப்பு",
    "Select Hospital": "மருத்துவமனையைத் தேர்ந்தெடுக்கவும்",
    "Select Doctor": "மருத்துவரைத் தேர்ந்தெடுக்கவும்",
    "Appointment Date": "சந்திப்பு தேதி",
    "Available slots": "கிடைக்கும் நேர இடைவெளிகள்",
    "No Slots Available": "நேர இடைவெளிகள் இல்லை",
    "View Available Slots": "கிடைக்கும் நேர இடைவெளிகளைக் காண்க",
    "Start time Slot:": "தொடக்க நேர இடைவெளி:",
    "Diagnosis Description": "நோய் கண்டறிதல் விளக்கம்",
    "Book": "முன்பதிவு",
    "Update": "புதுப்பிக்கவும்",
    "Respiratory Rate": "சுவாச விகிதம்",
    "Appointments": "சந்திப்புகள்",
    "As a companion in your pregnancy we help you with the following": "உங்கள் கர்ப்பகாலத்தில் ஒரு துணையாக பின்வருவனவற்றில் உங்களுக்கு உதவுகிறோம்",
    "Book An Appointment": "சந்திப்பை முன்பதிவு செய்யுங்கள்",
    "Pregnancy Monitoring": "கர்ப்ப கண்காணிப்பு",
    "Help Line": "உதவி எண்",
    "Current Appointment": "தற்போதைய சந்திப்பு",
    "No Upcoming Appointments": "வரவிருக்கும் சந்திப்புகள் இல்லை",
    "Time": "நேரம்",
    "Status": "நிலை",
    "Reason": "காரணம்",
    "Cancel Appointment": "சந்திப்பை ரத்து செய்",
    "Show Appointment": "சந்திப்பைக் காட்டு",
    "My Appointments": "என் சந்திப்புகள்",
    "Appointment Status": "சந்திப்பு நிலை",
    "App Info": "பயன்பாட்டு தகவல்",
    "CHECK FOR UPDATES": "புதுப்பிப்புகளைச் சரிபார்க்கவும்",
    "Edit Profile": "சுயவிவரத்தைத் திருத்து",
    "Help": "உதவி",
    "Tell us what's going on": "என்ன நடக்கிறது என்பதை எங்களிடம் சொல்லுங்கள்",
    "Tell us why you're reaching us": "நீங்கள் ஏன் எங்களை தொடர்பு கொள்கிறீர்கள் என்பதை எங்களிடம் சொல்லுங்கள்",
    "How do you feel? (Optional)": "நீங்கள் எப்படி உணர்கிறீர்கள்? (விருப்பம்)",
    "My Hospital": "என் மருத்துவமனை",
    "No hospitals found": "மருத்துவமனைகள் எதுவும் கிடைக்கவில்லை",
    "District:": "மாவட்டம்:",
    "Settings": "அமைப்புகள்",
    "English": "ஆங்கிலம்",
    "Logout Successful": "வெற்றிகரமாக வெளியேறியது",
    "Subscribe": "சந்தா செய்",
    "Subscription": "சந்தா",
    "Current Plan": "தற்போதைய திட்டம்",
    "Monthly": "மாதாந்திர",
    "Yearly": "வருடாந்திர",
    "Based on patient reviews": "நோயாளிகளின் மதிப்புரைகளின் அடிப்படையில்",
    "Working Hours": "வேலை நேரம்",
    "Contact Information": "தொடர்பு தகவல்",
    "Personalised Pregnancy Care": "தனிப்பயனாக்கப்பட்ட கர்ப்ப பராமரிப்பு",
    "Helps you to consult Doctor Virtually": "டாக்டரிடம் மெய்நிகர் ஆலோசனை பெற உதவுகிறது",
    "Engage with Doctor through video and audio": "வீடியோ மற்றும் ஆடியோ மூலம் டாக்டருடன் ஈடுபடுங்கள்",
    "Keep on track your Health": "உங்கள் ஆரோக்கியத்தை கண்காணித்து வாருங்கள்",
    "By continuing, You agree that you have read and accept our": "தொடர்வதன் மூலம், நீங்கள் படித்து ஏற்றுக்கொண்டதாக ஒப்புக்கொள்கிறீர்கள்",
    "T&C and Privacy Policy": "டி&சி மற்றும் தனியுரிமைக் கொள்கை",
    // "Allobot": "அலோபோட்",
    "Thinking...": "சிந்திக்கிறது...",
    "Your maternal AI assistant is processing your question": "உங்கள் தாய்வழி AI உதவியாளர் உங்கள் கேள்வியை செயலாக்குகிறார்",
    "Your Maternal AI Assistant": "உங்கள் தாய்வழி AI உதவியாளர்",
    "Welcome to Allobot!": "அலோபோட்டுக்கு வரவேற்கிறோம்!",
    "I'm here to support you through your maternal journey. Ask me anything about pregnancy, childbirth, or early motherhood.": "உங்கள் தாய்வழி பயணத்தில் உங்களுக்கு ஆதரவளிக்க நான் இங்கு வந்துள்ளேன். கர்ப்பம், பிரசவம் அல்லது ஆரம்ப தாய்மை பற்றி என்னிடம் எதையும் கேளுங்கள்",
    "What You Can Ask Me:": "நீங்கள் என்னிடம் என்ன கேட்கலாம்:",
    "Pregnancy health tips": "கர்ப்பகால ஆரோக்கிய குறிப்புகள்",
    "Nutrition advice": "ஊட்டச்சத்து ஆலோசனை",
    "Baby care basics": "குழந்தை பராமரிப்பு அடிப்படைகள்",
    "Trimester milestones": "மூன்று மாத மைல்கற்கள்",
    "Ask Allobot...": "அலோபோட்டிடம் கேளுங்கள்...",
    "Incoming Call": "உள்வரும் அழைப்பு",
    "Waiting": "காத்திருக்கிறது",
    "No messages yet": "இதுவரை செய்திகள் இல்லை",
    "Tablets": "மாத்திரைகள்",
    "Units": "அலகுகள்",
    "Timing": "நேரம்",
    "No prescriptions found.": "மருந்துச்சீட்டுகள் எதுவும் கிடைக்கவில்லை",
    "No description available": "விளக்கம் இல்லை",
    "No reports found": "அறிக்கைகள் எதுவும் கிடைக்கவில்லை",
    "Report Details": "அறிக்கை விவரங்கள்",
    "Unknown Report Type": "அறியப்படாத அறிக்கை வகை",
    "Test Results": "சோதனை முடிவுகள்",
    "Delete Report": "அறிக்கையை நீக்கு",
    "Are you sure you want to delete this report?": "இந்த அறிக்கையை நிச்சயமாக நீக்க விரும்புகிறீர்களா?",
    "CANCEL": "ரத்துசெய்",
    "DELETE": "நீக்கு",
    "Normal": "சாதாரண",
    "Body pain": "உடல் வலி",
    "Burning Stomach": "எரியும் வயிறு",
    "Cold cough": "சளி இருமல்",
    "Dizziness": "தலைச்சுற்றல்",
    "Headache": "தலைவலி",
    "Vomiting": "வாந்தி",
    "Other": "மற்றவை",
    "Blood Pressure": "இரத்த அழுத்தம்",
    "Temperature": "வெப்பநிலை",
    "Blood Saturation": "இரத்த செறிவு",
    "Blood Glucose": "இரத்த சர்க்கரை",
    "BMI": "பிஎம்ஐ",
    "HRV": "எச்ஆர்வி",
    "Baby Cry Not Detected.": "குழந்தை அழுகை கண்டறியப்படவில்லை.",
    "The baby cry detection process failed. Please check your connection or try again.": "குழந்தை அழுகை கண்டறிதல் செயல்முறை தோல்வியுற்றது. உங்கள் இணைப்பை சரிபார்க்கவும் அல்லது மீண்டும் முயற்சிக்கவும்.",
    "Retry": "மீண்டும் முயற்சிக்கவும்",
    "Please select Appointment Date": "சந்திப்பு தேதியைத் தேர்ந்தெடுக்கவும்",
    "Please enter Diagnosis Description": "நோய் கண்டறிதல் விளக்கத்தை உள்ளிடவும்",
    "No data available": "தரவு எதுவும் இல்லை",
    "Pregnant": "கர்ப்பிணி",
    "Not Pregnant": "கர்ப்பிணி அல்ல",
    "Summary": "சுருக்கம்",
    "Upcoming Appointments": "வரவிருக்கும் சந்திப்புகள்",
    "No appointments scheduled": "சந்திப்புகள் எதுவும் திட்டமிடப்படவில்லை",
    "No": "இல்லை",
    "Yes": "ஆம்",
    "No appointments found": "சந்திப்புகள் எதுவும் கிடைக்கவில்லை",
    "JioVio Healthcare": "ஜியோவியோ சுகாதாரம்",
    "General Details": "பொது விவரங்கள்",
    "Partner Details": "துணை விவரங்கள்",
    "Pregnancy Details": "கர்ப்ப விவரங்கள்",
    "Address Details": "முகவரி விவரங்கள்",
    "Contact Us": "எங்களை தொடர்பு கொள்ளுங்கள்",
    "Something not Working": "ஏதோ வேலை செய்யவில்லை",
    "Feature Request": "அம்ச கோரிக்கை",
    "Question": "கேள்வி",
    "FeedBack": "கருத்து",
    "SEND": "அனுப்பு",
    "My Subscription": "எனது சந்தா",
    "Language": "மொழி",
    "Terms & Conditions": "விதிமுறைகள் & நிபந்தனைகள்",
    "Privacy Policy": "தனியுரிமைக் கொள்கை",
    "Log Out": "வெளியேறு",
    "Are you sure to logout?": "வெளியேற விரும்புகிறீர்களா?",
    "Cancel": "ரத்துசெய்",
    "Ok": "சரி",
    "Change Default": "இயல்புநிலையை மாற்று",
    "Write Description": "விளக்கத்தை எழுதுங்கள்",
    "Please enter Description": "விளக்கத்தை உள்ளிடவும்",
    "Door No": "கதவு எண்",
    "Please enter Door No": "கதவு எண்ணை உள்ளிடவும்",
    "Street Name": "தெரு பெயர்",
    "Please enter Street Name": "தெரு பெயரை உள்ளிடவும்",
    "Pincode": "அஞ்சல் குறியீடு",
    "Please enter Pincode": "அஞ்சல் குறியீட்டை உள்ளிடவும்",
    "Search Area": "தேடல் பகுதி",
    "Select Area Name": "பகுதி பெயரைத் தேர்ந்தெடுக்கவும்",
    "Enter your Name": "உங்கள் பெயரை உள்ளிடவும்",
    "Please enter your name": "உங்கள் பெயரை உள்ளிடவும்",
    "Enter Email Id": "மின்னஞ்சல் ஐடியை உள்ளிடவும்",
    "Please Select Gender": "பாலினத்தைத் தேர்ந்தெடுக்கவும்",
    "Age": "வயது",
    "Please enter age": "வயதை உள்ளிடவும்",
    "Please enter corrent age": "சரியான வயதை உள்ளிடவும்",
    "LMP Date": "எல்எம்பி தேதி",
    "Please enter LMP Date": "எல்எம்பி தேதியை உள்ளிடவும்",
    "ED Date": "இடி தேதி",
    "Date of delivery": "பிரசவ தேதி",
    "Please enter Delivery Date": "பிரசவ தேதியை உள்ளிடவும்",
    "Please enter Partner Name": "துணையின் பெயரை உள்ளிடவும்",
    "Partner Name": "துணையின் பெயர்",
    "Please enter Partner Mobile Number": "துணையின் கைபேசி எண்ணை உள்ளிடவும்",
    "Partner Mobile Number": "துணையின் கைபேசி எண்",
    "Bed Time": "படுக்கை நேரம்",
    "Please enter Date of Birth": "பிறந்த தேதியை உள்ளிடவும்",
    "Wake Up Time": "எழும் நேரம்",
    "Name": "பெயர்",
    "Please Select Parent Type": "பெற்றோர் வகையைத் தேர்ந்தெடுக்கவும்",
    "Parent Type": "பெற்றோர் வகை",
    "Please Select Pregnant Status": "கர்ப்ப நிலையைத் தேர்ந்தெடுக்கவும்",
    "Please enter Area": "பகுதியை உள்ளிடவும்",
    "Area": "பகுதி",
    "Services": "சேவைகள்",
    "AlloBaby": "அலோபேபி",
    "Awareness" : "விழிப்புணர்வு",
    "Screening" : "திரையிடல்",
    "Glucose Test": "குளுக்கோஸ் பரிசோதனை",
    "Ultrasound Test": "அல்ட்ராசவுண்ட் பரிசோதனை",
    "Urine Test": "சிறுநீர் பரிசோதனை",


  ...babycrys,


};


final Map<String, String> babycrys = {
"Hunger Crying" : 	"பசி அழுகை",
"Sleepy Crying" : 	"தூக்கக் கலக்கம் அழுகை",
"Pain Crying" : 	"வலி அழுகை",
"Discomfort Crying" : 	"அதிர்ச்சியுடன் அழுகை",
"Colic Crying" : 	"கோலிக் அழுகை",
"Attention Crying" : 	"கவன அழுகை",

"Hunger Cry" : 	"பசி அழுகை",
"Sleepy Cry" : 	"தூக்கக் கலக்கம் அழுகை",
"Pain Cry" : 	"வலி அழுகை",
"Discomfort Cry" : 	"அதிர்ச்சியுடன் அழுகை",
"Colic Cry" : 	"கோலிக் அழுகை",
"Attention Cry" : 	"கவன அழுகை",
	
	
"Rhythmic, repetitive cries that grow louder if the baby isn't fed. Often accompanied by hand-sucking and rooting behavior.":	"குழந்தைக்கு பாலூட்டாவிட்டால் சத்தமாக வளரும் தாள, மீண்டும் மீண்டும் அழுகை. பெரும்பாலும் கை உறிஞ்சுதல் மற்றும் வேர்விடும் நடத்தையுடன்.",
"A whiny, nasal cry that sounds weaker than a hunger cry, often accompanied by yawning and eye-rubbing." :	"பசி அழுகையைக் காட்டிலும் பலவீனமாக ஒலிக்கும் ஒரு சிணுங்கல், நாசி அழுகை, பெரும்பாலும் கொட்டாவி மற்றும் கண் தேய்த்தல்.",
"A sudden, high-pitched, intense cry that comes in bursts with breathing pauses. Often accompanied by physical tension." :	"திடீரென்று, உயர்ந்த, தீவிரமான அழுகை மூச்சு நிறுத்தங்களுடன் வெடிக்கிறது. பெரும்பாலும் உடல் பதற்றத்துடன் சேர்ந்து.",
"A fussy, irritated cry that typically stops when the source of discomfort is addressed." :	"ஒரு வம்பு, எரிச்சலூட்டும் அழுகை, இது பொதுவாக அசௌகரியத்தின் மூலத்தை நிவர்த்தி செய்யும்போது நிறுத்தப்படும்.",
"Prolonged, intense crying episodes, typically in the evening, with physical signs of distress." :	"நீடித்த, தீவிர அழுகை அத்தியாயங்கள், பொதுவாக மாலையில், துயரத்தின் உடல் அறிகுறிகளுடன்.",
"A mild cry that starts softly and increases if ignored, often accompanied by eye contact and reaching out." :	"மென்மையாகத் தொடங்கி அலட்சியப்படுத்தினால் அதிகரிக்கும் ஒரு லேசான அழுகை, பெரும்பாலும் கண் தொடர்பு மற்றும் அடையும்.",
	
	
"Hunger cries are rhythmic, repetitive, and grow louder if the baby isn't fed.":	"குழந்தைக்கு உணவளிக்காவிட்டால் பசி அழுகை தாளம், மீண்டும் மீண்டும் மற்றும் சத்தமாக வளரும்.",
"Babies may also" :	"குழந்தைகளும் இருக்கலாம்:",
"• Suck on hands or fingers" :	"• கைகள் அல்லது விரல்களில் உறிஞ்சுதல்",
"• Smack lips, root (turn head searching for a nipple)" :	"• ஸ்மாக் உதடுகள், வேர் (ஒரு முலைக்காம்பைத் தேடும் தலையைத் திருப்பு)",
"• Get fussy even after being comforted" :	"• ஆறுதல் சொன்ன பிறகும் வம்பு செய்யுங்கள்",
	
	
"A whiny, nasal cry that may sound weaker than a hunger cry.":"	பசியின் அழுகையைக் காட்டிலும் பலவீனமாக ஒலிக்கக்கூடிய ஒரு சிணுங்கல், மூக்கு அழுகை.",
"Babies may also:":"	குழந்தைகளும் இருக்கலாம்:",
"• Yawn frequently":"	• அடிக்கடி கொட்டாவி விடுங்கள்",
"• Rub their eyes or pull their ears":"	•கண்களைத் தேய்த்தல் அல்லது காதுகளைப் பிடித்து இழுத்தல்",
"• Become fussy and harder to soothe":"• வம்பு மற்றும் ஆற்றுவதற்கு கடினமாக மாறும்",
	
	
"A sudden, high-pitched, intense cry that may come in bursts with pauses for breath.":	"திடீரென்று, அதிக சுருதியில், தீவிரமான அழுகை மூச்சு நிறுத்தங்களுடன் வெடிக்கக்கூடும்.",
"Babies may also:":	"குழந்தைகளும் இருக்கலாம்:",
"• Clench fists or arch their back":	"• முஷ்டியை மடக்கவும் அல்லது முதுகை வளைக்கவும்",
"• Become stiff or tense":	"• விறைப்பாக அல்லது பதட்டமாக மாறுதல்",
"• Show signs of discomfort (scrunched face, difficulty calming down)":	"• அசௌகரியத்தின் அறிகுறிகளைக் காட்டுங்கள் (சுருங்கிய முகம், அமைதியடைவதில் சிரமம்)",
	
	
"A fussy, irritated cry that may stop when the issue is resolved." :	"பிரச்சினை தீர்க்கப்பட்டவுடன் நிறுத்தக்கூடிய ஒரு வம்பு, எரிச்சலூட்டும் அழுகை.",
"Babies may also:" :	"குழந்தைகளும் இருக்கலாம்:",
"• Wiggle or squirm a lot" :	"• நிறைய அசை அல்லது நெளிவு",
"• Tug at their clothing or ears" :	"• அவர்களின் ஆடை அல்லது காதுகளை இழுக்கவும்",
"• Appear restless or uneasy" :	"• அமைதியற்ற அல்லது சங்கடமான தோற்றம்",
	
	
"A prolonged, intense, high-pitched cry that often occurs in the evening." :	"மாலையில் அடிக்கடி நிகழும் ஒரு நீண்ட, தீவிரமான, உயர்ந்த அழுகை.",
"Babies may also:" :	"குழந்தைகளும் இருக்கலாம்:",
"• Clench fists, arch their back, or pull up legs" :	"• முஷ்டியை மடக்குதல், முதுகை வளைத்தல் அல்லது கால்களை மேலே இழுத்தல்",
"• Have a tense, bloated belly" :	"• பதட்டமான, வீங்கிய வயிறு",
"• Be difficult to soothe, even after feeding" :	"• உணவளித்த பிறகும் ஆறுதல் அளிப்பது கடினம்",
	
	
"A mild, whimpering cry that starts softly and gets louder if ignored." :	"மெல்லிய குரலில் தொடங்கி அலட்சியப்படுத்தினால் இன்னும் சத்தமாக ஒலிக்கும் அழுகை.",
"Babies may also:" :	"குழந்தைகளும் இருக்கலாம்:",
"• Make eye contact while crying" :	"• அழும்போது கண் தொடர்பு கொள்ளுங்கள்",
"• Reach out for comfort" :	"• ஆறுதலுக்காக அடையுங்கள்",
"• Stop crying quickly when picked up" :	"• எடுத்தவுடன் உடனடியாக அழுகையை நிறுத்துங்கள்",
	
	
"Feed Promptly – Responding early prevents excessive crying and makes feeding easier." :	"உடனடியாக உணவளிக்கவும் - ஆரம்பத்தில் பதிலளிப்பது அதிகப்படியான அழுகையைத் தடுக்கிறது மற்றும் உணவளிப்பதை எளிதாக்குகிறது.",
"Watch for Hunger Cues – Crying is a late sign; look for early signs like lip-smacking, rooting, sticking out tongue, or sucking on hands." :	"பசி குறிப்புகளைக் கவனியுங்கள் - அழுவது தாமதமான அறிகுறி; உதடு-ஸ்மாக்கிங், வேர்விடும், நாக்கை வெளியே ஒட்டிக்கொள்வது அல்லது கைகளில் உறிஞ்சுவது போன்ற ஆரம்ப அறிகுறிகளைத் தேடுங்கள்.",
"Ensure Proper Latch – If breastfeeding, ensure a deep latch to avoid discomfort." :	"சரியான தாழ்ப்பாள் இருப்பதை உறுதி செய்யவும் - தாய்ப்பால் கொடுத்தால், அசௌகரியத்தைத் தவிர்க்க ஆழமான தாழ்ப்பாளை உறுதிப்படுத்தவும்.",
"Check Feeding Schedule – Newborns need feeding every 2-3 hours." :	"உணவு அட்டவணையை சரிபார்க்கவும் - புதிதாகப் பிறந்த குழந்தைகளுக்கு ஒவ்வொரு 2-3 மணி நேரத்திற்கும் உணவளிக்க வேண்டும்.",
"Burp Baby After Feeding – Helps prevent gas and fussiness." :	"பாலூட்டிய பிறகு குழந்தை ஏப்பம் - வாயு மற்றும் வம்புகளைத் தடுக்க உதவுகிறது.",
	
	
"Look for Sleep Cues Early – Yawning, zoning out, or rubbing eyes signal it's time to sleep." :	"ஆரம்பத்தில் தூக்கக் குறிப்புகளைத் தேடுங்கள் - கொட்டாவி விடுதல், மண்டலப்படுத்துதல் அல்லது கண்களைத் தேய்த்தல் இது தூங்குவதற்கான நேரம் என்பதற்கான சமிக்ஞை.",
"Create a Calm Sleep Environment – Dim lights, reduce noise, and use white noise if needed." :	"அமைதியான தூக்க சூழலை உருவாக்கவும் - மங்கலான விளக்குகள், சத்தத்தைக் குறைத்து, தேவைப்பட்டால் வெள்ளை சத்தத்தைப் பயன்படுத்தவும்.",
"Use Gentle Motions – Rocking, swaying, or holding baby in a 'colic carry' (on their tummy along your forearm) can help." :	"ஜென்டில் ராக்கிங்கைப் பயன்படுத்தவும் - இயக்கம், ஸ்வாட்லிங் அல்லது ஒரு அமைதிப்படுத்தி உதவும்.",
"Follow a Sleep Routine – A consistent bedtime routine helps babies recognize sleep time." :	"ஒரு தூக்க வழக்கத்தைப் பின்பற்றுங்கள் - ஒரு நிலையான படுக்கை நேர வழக்கம் குழந்தைகளுக்கு தூக்க நேரத்தை அடையாளம் காண உதவுகிறது.",
"Avoid Overstimulation – Too much activity before bed can make sleep harder." :	"அதிகப்படியான தூண்டுதலைத் தவிர்க்கவும் - படுக்கைக்கு முன் அதிக செயல்பாடு தூக்கத்தை கடினமாக்கும்.",
	
	
"Check for Obvious Issues – Look for diaper rash, teething pain, or tight clothing." :	"வெளிப்படையான சிக்கல்களைச் சரிபார்க்கவும் - டயபர் சொறி, பல் வலி அல்லது இறுக்கமான ஆடைகளைத் தேடுங்கள்.",
"Soothe with Gentle Touch – Skin-to-skin contact or holding them close can help." :	"மென்மையான தொடுதலுடன் ஆற்றவும் - தோல்-க்கு-தோல் தொடர்பு அல்லது அவற்றை நெருக்கமாக வைத்திருப்பது உதவும்.",
"Try Pain Relief Techniques – For teething, offer a chilled teether; for gas, try tummy massage." :	"வலி நிவாரண நுட்பங்களை முயற்சிக்கவும் - பல் துலக்குவதற்கு, குளிர்ந்த டீத்தரை வழங்குங்கள்; வாயுவுக்கு, வயிற்று மசாஜ் முயற்சிக்கவும்.",
"Monitor for Fever or Illness – If crying persists with fever, vomiting, or lethargy, consult a doctor." :	"காய்ச்சல் அல்லது நோய்க்கான கண்காணிப்பு - காய்ச்சல், வாந்தி அல்லது சோம்பலுடன் அழுகை தொடர்ந்தால், மருத்துவரை அணுகவும்.",
"Trust Your Instincts – If the baby seems in severe pain, seek medical advice immediately." :	"உங்கள் உள்ளுணர்வை நம்புங்கள் - குழந்தை கடுமையான வலியில் இருந்தால், உடனடியாக மருத்துவ ஆலோசனையைப் பெறவும்.",
	
	
"Check the Diaper – A wet or soiled diaper is a common cause of discomfort." :	"டயப்பரை சரிபார்க்கவும் - ஈரமான அல்லது அழுக்கு டயப்பர் அசௌகரியத்திற்கு ஒரு பொதுவான காரணமாகும்.",
"Ensure Comfortable Clothing – Dress baby in breathable, soft fabrics and check for tight clothing." :	"வசதியான ஆடைகளை உறுதிப்படுத்தவும் - குழந்தையை சுவாசிக்கக்கூடிய, மென்மையான துணிகளில் ஆடை அணிவித்து, இறுக்கமான ஆடைகளை சரிபார்க்கவும்.",
"Adjust Temperature – Feel baby's neck/back to see if they are too hot or cold." :	"வெப்பநிலையை சரிசெய்யவும் - குழந்தையின் கழுத்து / முதுகை உணருங்கள், அவை மிகவும் சூடாக அல்லது குளிராக இருக்கிறதா என்பதைப் பார்க்கவும்.",
"Check for External Irritants – Tags, rough fabric, or hair wrapped around fingers/toes can cause irritation." :	"வெளிப்புற எரிச்சலூட்டிகளைச் சரிபார்க்கவும் - குறிச்சொற்கள், கடினமான துணி அல்லது விரல்கள் / கால்விரல்களைச் சுற்றி மூடப்பட்டிருக்கும் முடி எரிச்சலை ஏற்படுத்தும்.",
"Reposition Baby – Changing positions or holding them differently can sometimes help." :	"இடமாற்றம் குழந்தை - நிலைகளை மாற்றுவது அல்லது அவற்றை வித்தியாசமாக வைத்திருப்பது சில நேரங்களில் உதவும்.",
	
	
"Use Gentle Motions – Rocking, swaying, or holding baby in a colic carry (on their tummy along your forearm) can help." :	"மென்மையான இயக்கங்களைப் பயன்படுத்துங்கள் - குழந்தையை 'கோலிக் கேரியில்' (உங்கள் முன்கையில் அவர்களின் வயிற்றில்) ராக்கிங், அசைத்தல் அல்லது வைத்திருப்பது உதவும்.",
"Try White Noise – Rhythmic sounds, like a fan or heartbeat sound, can be soothing." :	"வெள்ளை சத்தத்தை முயற்சிக்கவும் - விசிறி அல்லது இதய துடிப்பு ஒலி போன்ற தாள ஒலிகள் இனிமையாக இருக்கும்.",
"Burp Baby Well – Gas buildup can make colic worse. Burp frequently during feeds." :	"ஏப்பம் குழந்தை கிணறு - வாயு உருவாக்கம் கோலிக்கை மோசமாக்கும். தாய்ப்பால் கொடுக்கும் போது அடிக்கடி ஏப்பம் விடவும்.",
"Massage the Tummy – A gentle circular tummy massage can relieve gas." :	"வயிற்றை மசாஜ் செய்யுங்கள் - ஒரு மென்மையான வட்ட வயிற்று மசாஜ் வாயுவைக் குறைக்கும்.",
"Consult a Pediatrician – If colic persists, discuss options like probiotic drops or diet changes (for breastfeeding moms)." :	"ஒரு குழந்தை மருத்துவரை அணுகவும் - கோலிக் தொடர்ந்தால், புரோபயாடிக் சொட்டுகள் அல்லது உணவு மாற்றங்கள் (தாய்ப்பால் கொடுக்கும் அம்மாக்களுக்கு) போன்ற விருப்பங்களைப் பற்றி விவாதிக்கவும்.",
	
	
"Respond with Reassurance – Holding, talking, or making eye contact helps babies feel secure." :	"உறுதியுடன் பதிலளிக்கவும் - வைத்திருப்பது, பேசுவது அல்லது கண் தொடர்பு கொள்வது குழந்தைகள் பாதுகாப்பாக உணர உதவுகிறது.",
"Try Gentle Touch – A cuddle or soft pat on the back can be calming." :	"மென்மையான தொடுதலை முயற்சிக்கவும் - முதுகில் ஒரு அரவணைப்பு அல்லது மென்மையான தட்டு அமைதியாக இருக்கும்.",
"Engage with Soothing Sounds – Humming or talking in a calm voice can reassure the baby." :	"இனிமையான ஒலிகளுடன் ஈடுபடுங்கள் - ஹம்மிங் அல்லது அமைதியான குரலில் பேசுவது குழந்தைக்கு உறுதியளிக்கும்.",
"Encourage Independent Comforting – Allow baby to self-soothe briefly before immediately responding." :	"சுயாதீன ஆறுதலளிப்பதை ஊக்குவிக்கவும் - உடனடியாக பதிலளிப்பதற்கு முன்பு குழந்தையை சுருக்கமாக சுயமாக ஆற்ற அனுமதிக்கவும்.",
"Maintain a Balance – Meeting attention needs is important, but consistency in response helps babies learn security." :	"ஒரு சமநிலையை பராமரிக்கவும் - கவனத் தேவைகளைப் பூர்த்தி செய்வது முக்கியம், ஆனால் பதிலில் நிலைத்தன்மை குழந்தைகளுக்கு பாதுகாப்பைக் கற்றுக்கொள்ள உதவுகிறது.",

  "Cry History":"அழுகை வரலாறு",
"Record" :"பதிவைத் தொடங்கவும்"


};



// final Map<String, String> ta = {
//   //registersation screen

//   "Helps you to consult patient Virtually":
//       "உண்மையில் நோயாளியைக் கலந்தாலோசிக்க உங்களுக்கு உதவுகிறது",
//   "Engage with patient through video and audio":
//       "வீடியோ மற்றும் ஆடியோ மூலம் நோயாளியுடன் ஈடுபடுங்கள்",
//   "Keeps on track your patient Health":
//       "உங்கள் நோயாளியின் ஆரோக்கியத்தை கண்காணிக்கும்",
//   "Username": "பயனர் பெயர்",
//   "password": "கடவுச்சொல்",
//   "CONTINUE": "தொடரவும்",
//   "By continuing, You agree that you have read and accept our T&C and Privacy Policy":
//       "தொடர்வதன் மூலம், எங்கள் T&C மற்றும் தனியுரிமைக் கொள்கையைப் படித்து ஏற்றுக்கொண்டீர்கள் என்பதை ஒப்புக்கொள்கிறீர்கள்",
//   "LoggedIn Successfully": "புகுபதிகை வெற்றிகரமாக",
//   "Invalid Credential": "தவறான நற்சான்றிதழ்",

// //Home Screen

//   "AlloLab": "அலோலேப்",
//   "Welcome": "வணக்கம்",
//   "Worker ID": "தொழிலாளி ஐடி",
//   "Recently Added Patient": "சமீபத்தில் சேர்க்கப்பட்ட நோயாளி",
//   "Mobile No:": "அலைபேசி எண்:",
//   "Start Screening": "திரையிடல் தொடங்கு",
//   "Select Language": "மொழியை தேர்ந்தெடுங்கள்",
//   "English": "ஆங்கிலம்",
//   "Tamil": "தமிழ்",
//   "Hindi": "இந்தி",
//   "Face Recognition": "முகத்தை அடையாளம் காணுதல்",
//   "Start Screening with Face Recongnition":
//       "முகம் அங்கீகாரத்துடன் திரையிடலைத் தொடங்கு",
//   "CAPTURE": "பிடிப்பு",
//   "User Not Found": "பயனர் கிடைக்கவில்லை",
//   "Search with Phone Number": "தொலைபேசி எண்ணைக் கொண்டு தேடு",
//   "Enter Phone Number": "தொலைபேசி எண்ணை உள்ளிடவும்",
//   "Add New Patient": "புதிய நோயாளியைச் சேர்",
//   "Add Patient to Start Screening": "திரையிடல் தொடங்க நோயாளியைச் சேர்க்கவும்",
//   "Personal Details": "தனிப்பட்ட விவரங்கள்",
//   "Capture Image": "படத்தை பிடி",
//   "Name": "பெயர்",
//   "EmailID": "மின்னஞ்சல் முகவரி",
//   "Phone Number": "தொலைபேசி எண்",
//   "Gender": "பாலினம்",
//   "Male": "ஆண்",
//   "Female": "பெண்",
//   "Blood Group": "இரத்த வகை",
//   "Date of Birth": "பிறந்த தேதி",
//   "Age": "வயது",
//   "OK": "சரி",
//   "CANCEL": "ரத்துசெய்",
//   "Address Details": "முகவரி விவரங்கள்",
//   "AddressLine": "முகவரி",
//   "Pincode": "அஞ்சல் குறியீடு",
//   "City": "நகரம்",
//   "State": "நிலை",
//   "Enter Correct Pincode": "சரியான பின்கோடை உள்ளிடவும்",
//   "Patient Name": "நோயாளியின் பெயர்",
//   "Checkup Details": "சரிபார்ப்பு விவரங்கள்",
//   "Appointment": "நியமனம்",
//   "Book an Appointment": "ஒரு சந்திப்பை முன்பதிவு செய்யுங்கள்",
//   "Select Doctor": "டாக்டரை தேர்ந்தெடு",
//   "Appointment Date": "அப்பயிண்ட்மெண்ட் தேதி",
//   "View Available Slots": "கிடைக்கும் இடங்களைக் காண்க",
//   "No Slot Selected": "ஸ்லாட் எதுவும் தேர்ந்தெடுக்கப்படவில்லை",
//   "Diagnosis Desc": "நோயறிதல் விவரம்",
//   "Book": "பதிவு",
//   "Appointment Book Successfully": "அப்பாயிண்ட்மெண்ட் புத்தகம் வெற்றிகரமாக",
//   "CheckUp": "சோதனை",
//   "No CheckUp found": "சோதனை இல்லை",
//   "Today": "இன்று",
//   "No available slot for selected date":
//       "தேர்ந்தெடுக்கப்பட்ட தேதிக்கு ஸ்லாட் இல்லை",
//   "View appointment": "அப்பயிண்ட்மெண்ட் பார்க்கவும்",
//   "completed": "நிறைவு",
//   "Appointments": "நியமனங்கள்",
//   "Upcoming": "வரவிருக்கும்",
//   "Date": "தேதி",
//   "Time": "நேரம்",
//   "Status": "நிலை",
//   "View Appointment": "அப்பாயிண்ட்மெண்ட் பார்க்கவும்",
//   "Cancel Appointment": "அப்பயிண்ட்மெண்ட்டை ரத்து செய்",
//   "Add Symptoms and Vitals": "அறிகுறிகள் மற்றும் உயிர்களைச் சேர்",
//   "Select Symptoms": "அறிகுறிகளைத் தேர்ந்தெடு",
//   "Body Pain": "உடல் வலி",
//   "Burning Stomach": "எரியும் வயிறு",
//   "Cold Cough": "சளி இருமல்",
//   "Dizziness": "தலைச்சுற்றல்",
//   "Headache": "தலைவலி",
//   "Vomiting": "வாந்தி",
//   "NEXT": "அடுத்தது",
//   "Vitals": "உயிரினங்கள்",
//   "Blood Pressue": "இரத்த அழுத்தம்",
//   "Temperature": "வெப்ப நிலை",
//   "Blood Saturation": "இரத்த செறிவு",
//   "Heart Rate": "இதய துடிப்பு",
//   "Blood Glucose": "இரத்த குளுக்கோஸ்",
//   "BMI": "பிஎம்ஐ",
//   "Respiratory Rate": "சுவாச விகிதம்",
//   "HRV": "எச்ஆர்வி",
//   "BACK": "மீண்டும்",
//   "SAVE": "சேமி",
//   "CheckUp Added Sucessfully": "சரிபார்ப்பு வெற்றிகரமாக சேர்க்கப்பட்டது",
//   "CheckUp completed": "சோதனை முடிந்தது",
//   "COMPLETED": "நிறைவு",
//   "Appointment Status": "நியமன நிலை",
//   "Doctor Name": "டாக்டர் பெயர்",
//   "Health Status": "சுகாதார நிலை",
//   "NORMAL": "இயல்பு",
//   "Case Summary": "வழக்கு சுருக்கம்",
//   "Prescription": "மருந்து",
//   "Tablets": "மாத்திரைகள்",
//   "Units": "அலகுகள்",
//   "Timing": "நேரம்",
//   "Requested lab supported": "கோரிய ஆய்வகம் ஆதரிக்கப்படுகிறது",
//   "Next Appointment Date": "அடுத்த சந்திப்பு தேதி",
//   "Next Appointment Time": "அடுத்த சந்திப்பு நேரம்",
//   "Symptoms": "அறிகுறிகள்",
//   "Are you sure to cancel the appointment?":
//       "நிச்சயமாக அப்பாயின்ட்மென்ட்டை ரத்து செய்யலாமா?",
//   "Screening": "திரையிடல்",
//   "Go to Screening": "ஸ்கிரீனிங்கிற்கு செல்",
//   "Reports": "அறிக்கைகள்",
//   "Report Details": "அறிக்கை விவரங்கள்",
//   "Report": "அறிக்கை",
//   "SCAN AND ADD NEW REPORT": "ஸ்கேன் செய்து புதிய அறிக்கையைச் சேர்",
//   "Click Add Images Button": "படங்களைச் சேர் பொத்தானைக் கிளிக் செய்க",
//   "NO IMAGE": "உருவம் இல்லை",
//   "No Report Added": "அறிக்கை சேர்க்கப்படவில்லை",
//   "ADD IMAGE": "படத்தைச் சேர்",
//   "Choose Photo from :": "இதில் இருந்து புகைப்படத்தைத் தேர்ந்தெடுங்கள் :",
//   "Type of Report": "அறிக்கை வகை",
//   "Write Description": "விளக்கத்தை எழுது",
//   "ADD REPORT": "அறிக்கையைச் சேர்",
//   "Report Added Successfully": "அறிக்கை வெற்றிகரமாக சேர்க்கப்பட்டது",
//   "Report Deleted Successfully": "அறிக்கை வெற்றிகரமாக நீக்கப்பட்டது",
//   "Report Date": "அறிக்கை தேதி",
//   "Report Time": "அறிக்கை நேரம்",
//   "Report Desc": "அறிக்கை விவரம்",
//   "UPDATE IMAGE": "படத்தைப் புதுப்பி",
//   "DELETE REPORT": "அறிக்கையை நீக்கு",
//   "UPDATE REPORT": "புதுப்பிப்பு அறிக்கை",
//   "Report Updated Successfully": "அறிக்கை வெற்றிகரமாக புதுப்பிக்கப்பட்டது",
//   "Education": "கல்வி",
//   "Knowledge Transfer": "அறிவு பரிமாற்றம்",
//   "Sorry No Awareness Post Found":
//       "மன்னிக்கவும் விழிப்புணர்வு இடுகை எதுவும் கிடைக்கவில்லை",
//   "Patient List": "நோயாளிகள் பட்டியல்",
//   "Search Patient By Name": "பெயரால் நோயாளியைத் தேடுங்கள்",

// //Chat screen

//   "Chat": "அரட்டை",
//   "PATIENTS": "நோயாளிகள்",
//   "DOCTORS": "டாக்டர்கள்",
//   "NURSE": "செவிலியர்",
//   "Type a message": "செய்தியை உள்ளிடவும்",
//   "View Case Details": "வழக்கு விவரங்களைக் காண்க",

// //Settings Screen

//   "Settings": "அமைப்புகள்",
//   "Worker ID": "பணியாளர் ஐடி",
//   "General Details": "பொது விவரங்கள்",
//   "Name": "பெயர்",
//   "Year of Experience": "அனுபவ ஆண்டு",
//   "Title": "தலைப்பு",
//   "Address Details": "முகவரி விவரங்கள்",
//   "Address": "முகவரி",
//   "Pincode": "அஞ்சல் குறியீடு",
//   "Edit Profile": "சுயவிவரத்தைத் திருத்து",
//   "Notification": "அறிவிப்பு",
//   "ON": "ஆன்",
//   "OFF": "ஆஃப்",
//   "Terms & Conditions": "விதிமுறைகளும் நிபந்தனைகளும்",
//   "Privacy Policy": "தனியுரிமைக் கொள்கை",
//   "Help": "உதவி",
//   "Contact Us": "எங்களை தொடர்பு கொள்ள",
//   "Tell us what's going on": "என்ன நடக்கிறது என்று சொல்லுங்கள்",
//   "Tell us why you're reaching us":
//       "நீங்கள் ஏன் எங்களை அணுகுகிறீர்கள் என்று சொல்லுங்கள்",
//   "Something not Working": "ஏதோ வேலை செய்யவில்லை",
//   "Feature Request": "சிறப்பு விண்ணப்பம்",
//   "Question": "கேள்வி",
//   "FeedBack": "பின்னூட்டம்",
//   "How do you feel? (Optional)": "நீங்கள் எப்படி உணர்கிறீர்கள்? (விரும்பினால்)",
//   "SEND": "அனுப்பு",
//   "App Info": "பயன்பாட்டுத் தகவல்",
//   "Log out": "வெளியேறு",
//   "Are you sure to log out?": "நீங்கள் நிச்சயமாக வெளியேறுகிறீர்களா?",
//   "No": "இல்லை",
//   "Yes": "ஆம்"
// };
