final Map<String, String> ta = {
    "Select Language": "மொழியை தேர்ந்தெடுக்கவும்",
    "Enter Mobile Number": "மொபைல் எண்ணை உள்ளிடவும்",
    "SEND OTP": "OTP அனுப்பவும்",
    "How do you feel today ?": "இன்று நீங்கள் எப்படி உணர்கிறீர்கள்?",
    "Online": "ஆன்லைன்",
    "Offline": "ஆஃப்லைன்",
    "Image Uploaded": "படம் பதிவேற்றப்பட்டது",
    "Type a message": "செய்தியை தட்டச்சு செய்யவும்",
    "Choose photo from :": "இதிலிருந்து புகைப்படத்தைத் தேர்ந்தெடுக்கவும்:",
    "Get Connected with doctors": "மருத்துவர்களுடன் தொடர்பு கொள்ளுங்கள்",
    "Connect with Doctor": "டாக்டருடன் இணைக்கவும்",
    "Connect with Health worker": "சுகாதார ஊழியருடன் இணைக்கவும்",
    "Connect with AlloBot": "AlloBot உடன் இணைக்கவும்",
    "Sorry No Awareness Post": "மன்னிக்கவும் விழிப்புணர்வு பதிவு இல்லை",
    "Checkup Completed": "சோதனை முடிந்தது",
    "Waiting for Doctor Feedback": "மருத்துவரின் கருத்துக்காக காத்திருக்கிறேன்",
    "Checkup need to be done": "சோதனை செய்யப்பட வேண்டும்",
    "Checkup": "சோதனை",
    "No Checkup Found": "சோதனை எதுவும் இல்லை",
    "Checkup Details": "சோதனை விவரங்கள்",
    "Doctor Name": "மருத்துவர் பெயர்",
    "Date:": "தேதி:",
    "Health Status:": "சுகாதார நிலை:",
    "Case Summary": "விவரக்குறிப்பு",
    "Prescription": "மருந்துச்சீட்டு",
    "Next Appointment Time": "அடுத்த சந்திப்பு நேரம்",
    "Symptoms": "அறிகுறிகள்",
    "Vitals": "உயிர்கள்",
    "Add Prescription": "மருந்துச் சீட்டைச் சேர்க்கவும்",
    "ADD PRESCRIPTION": "மருந்துச் சீட்டைச் சேர்க்கவும்",
    "Click to Add Image": "படத்தைச் சேர்க்க கிளிக் செய்யவும்",
    "View Prescription": "மருந்துச்சீட்டைப் பார்க்கவும்",
    "Error loading image": "படத்தை ஏற்றுவதில் பிழை",
    "Prescription Type": "மருந்து வகை",
    "Date Added": "தேதி சேர்க்கப்பட்டது",
    "Description": "விளக்கம்",
    "Add Report": "அறிக்கையைச் சேர்",
    "NO IMAGE": "படம் இல்லை",
    "Click Add Image Button": "படத்தைச் சேர் பொத்தானைக் கிளிக் செய்யவும்",
    "ADD IMAGE": "படத்தைச் சேர்",
    "ADD REPORT": "அறிக்கையைச் சேர்",
    "Report": "அறிக்கை",
    "Scan and Add new Report": "ஸ்கேன் செய்து புதிய அறிக்கையைச் சேர்க்கவும்",
    "Self Screening": "சுய திரையிடல்",
    "BACK": "பின்செல்",
    "NEXT": "அடுத்து",
    "Finish": "முடிக்கவும்",
    "Summary Report": "சுருக்க அறிக்கை",
    "Submit": "சமர்ப்பிக்கவும்",
    "Let's begin the test": "சோதனையைத் தொடங்குவோம்",
    "Hemoglobin Test": "ஹீமோகுளோபின் சோதனை",
    "Easily get your Reading by Performing the scans below": "கீழே உள்ள ஸ்கேன்களைச் செய்வதன் மூலம் உங்கள் வாசிப்பை எளிதாகப் பெறுங்கள்",
    "Fetal Monitoring": "கரு கண்காணிப்பு",
    "Upload Report": "பதிவேற்ற அறிக்கை",
    "Tap to Change": "மாற்ற தட்டவும்",
    "Heart Rate": "இதய துடிப்பு",
    "BPM": "பிபிஎம்",
    "Kick Count": "உதை எண்ணிக்கை",
    "Tap to Increase the Count": "எண்ணிக்கையை அதிகரிக்க தட்டவும்",
    "Add Glucose Report": "குளுக்கோஸ் அறிக்கையைச் சேர்க்கவும்",
    "Blood Glucose Value": "இரத்த குளுக்கோஸ் மதிப்பு",
    "Add Hemoglobin Report": "ஹீமோகுளோபின் அறிக்கையைச் சேர்க்கவும்",
    "Hemoglobin Value": "ஹீமோகுளோபின் மதிப்பு",
    "Ultra Sound": "அல்ட்ராசவுண்ட்",
    "Fasting": "உண்ணாவிரதம்",
    "At rest": "ஓய்வில்",
    "After Walk": "நடந்த பிறகு",
    "Select Height": "உயரத்தைத் தேர்ந்தெடுக்கவும்",
    "Select Weight": "எடையைத் தேர்ந்தெடுக்கவும்",
    "After walk": "நடந்த பிறகு",
    "Address Information": "முகவரி தகவல்",
    "Search": "தேடல்",
    "Continue": "தொடரவும்",
    "Phone Number": "தொலைபேசி எண்",
    "Profile Details": "சுயவிவர விவரங்கள்",
    "Gender": "பாலினம்",
    "Male": "ஆண்",
    "Female": "பெண்",
    "Select Blood Group": "இரத்த வகையைத் தேர்ந்தெடுக்கவும்",
    "Select Last cycle Date": "கடைசி சுழற்சி தேதியைத் தேர்ந்தெடுக்கவும்",
    "Are you my mom or dad?": "நீங்கள் என் அம்மா அல்லது அப்பாவா?",
    "Dad": "அப்பா",
    "Mom": "அம்மா",
    "Enter your Partner Details": "உங்கள் துணை விவரங்களை உள்ளிடவும்",
    "Pregnancy Status": "கர்ப்ப நிலை",
    "Partner Pregnancy Status": "துணையின் கர்ப்ப நிலை",
    "Average Length of Cycles": "சுழற்சிகளின் சராசரி நீளம்",
    "Day": "நாள்",
    "Not yet started": "இன்னும் தொடங்கவில்லை",
    "NORMAL": "சாதாரண",
    "Health Status": "சுகாதார நிலை",
    "Last Screened": "கடைசியாக திரையிடப்பட்டது",
    "GOLD": "தங்கம்",
    "Subscription Plan": "சந்தா திட்டம்",
    "No News Feed": "செய்தி ஊட்டம் இல்லை",
    "Probable Reason": "சாத்தியமான காரணம்",
    "Recommendations": "பரிந்துரைகள்",
    "Hi!": "வணக்கம்!",
    "How do you feel today?": "இன்று நீங்கள் எப்படி உணர்கிறீர்கள்?",
    "Select Exercise that have you done today?": "இன்று நீங்கள் செய்த உடற்பயிற்சியைத் தேர்ந்தெடுக்கவும்?",
    "None": "எதுவுமில்லை",
    "Select tablets that you have taken": "நீங்கள் எடுத்துக்கொண்ட மாத்திரைகளைத் தேர்ந்தெடுக்கவும்",
    "Sleep Duration": "தூக்க காலம்",
    "Do you have any of these Symptoms?": "இந்த அறிகுறிகள் ஏதேனும் உங்களுக்கு உள்ளதா?",
    "Baby Voice is Recording": "குழந்தை குரல் பதிவு செய்யப்படுகிறது",
    "STOP": "நிறுத்து",
    "Click the Record Button to Start Recording": "பதிவு செய்யத் தொடங்க பதிவு பொத்தானைக் கிளிக் செய்யவும்",
    "Record": "பதிவு",
    "How many Glass of water have you drunk today?": "இன்று நீங்கள் எத்தனை கண்ணாடி தண்ணீர் குடித்தீர்கள்?",
    "OTP Verification": "OTP சரிபார்ப்பு",
    "Enter OTP sent to": "அனுப்பப்பட்ட OTPஐ உள்ளிடவும்",
    "Verify and proceed": "சரிபார்த்து தொடரவும்",
    "Appointment": "சந்திப்பு",
    "Select Hospital": "மருத்துவமனையைத் தேர்ந்தெடுக்கவும்",
    "Select Doctor": "மருத்துவரைத் தேர்ந்தெடுக்கவும்",
    "Appointment Date": "சந்திப்பு தேதி",
    "Available slots": "கிடைக்கும் நேர இடைவெளிகள்",
    "No Slots Available": "நேர இடைவெளிகள் இல்லை",
    "View Available Slots": "கிடைக்கும் நேர இடைவெளிகளைக் காண்க",
    "Start time Slot:": "தொடக்க நேர இடைவெளி:",
    "Diagnosis Description": "நோய் கண்டறிதல் விளக்கம்",
    "Book": "முன்பதிவு",
    "Update": "புதுப்பிக்கவும்",
    "Respiratory Rate": "சுவாச விகிதம்",
    "Appointments": "சந்திப்புகள்",
    "As a companion in your pregnancy we help you with the following": "உங்கள் கர்ப்பகாலத்தில் ஒரு துணையாக பின்வருவனவற்றில் உங்களுக்கு உதவுகிறோம்",
    "Book An Appointment": "சந்திப்பை முன்பதிவு செய்யுங்கள்",
    "Pregnancy Monitoring": "கர்ப்ப கண்காணிப்பு",
    "Help Line": "உதவி எண்",
    "Current Appointment": "தற்போதைய சந்திப்பு",
    "No Upcoming Appointments": "வரவிருக்கும் சந்திப்புகள் இல்லை",
    "Time": "நேரம்",
    "Status": "நிலை",
    "Reason": "காரணம்",
    "Cancel Appointment": "சந்திப்பை ரத்து செய்",
    "Show Appointment": "சந்திப்பைக் காட்டு",
    "My Appointments": "என் சந்திப்புகள்",
    "Appointment Status": "சந்திப்பு நிலை",
    "App Info": "பயன்பாட்டு தகவல்",
    "CHECK FOR UPDATES": "புதுப்பிப்புகளைச் சரிபார்க்கவும்",
    "Edit Profile": "சுயவிவரத்தைத் திருத்து",
    "Help": "உதவி",
    "Tell us what's going on": "என்ன நடக்கிறது என்பதை எங்களிடம் சொல்லுங்கள்",
    "Tell us why you're reaching us": "நீங்கள் ஏன் எங்களை தொடர்பு கொள்கிறீர்கள் என்பதை எங்களிடம் சொல்லுங்கள்",
    "How do you feel? (Optional)": "நீங்கள் எப்படி உணர்கிறீர்கள்? (விருப்பம்)",
    "My Hospital": "என் மருத்துவமனை",
    "No hospitals found": "மருத்துவமனைகள் எதுவும் கிடைக்கவில்லை",
    "District:": "மாவட்டம்:",
    "Settings": "அமைப்புகள்",
    "English": "ஆங்கிலம்",
    "Logout Successful": "வெற்றிகரமாக வெளியேறியது",
    "Subscribe": "சந்தா செய்",
    "Subscription": "சந்தா",
    "Current Plan": "தற்போதைய திட்டம்",
    "Monthly": "மாதாந்திர",
    "Yearly": "வருடாந்திர",
    "Based on patient reviews": "நோயாளிகளின் மதிப்புரைகளின் அடிப்படையில்",
    "Working Hours": "வேலை நேரம்",
    "Contact Information": "தொடர்பு தகவல்",
    "Personalised Pregnancy Care": "தனிப்பயனாக்கப்பட்ட கர்ப்ப பராமரிப்பு",
    "Helps you to consult Doctor Virtually": "டாக்டரிடம் மெய்நிகர் ஆலோசனை பெற உதவுகிறது",
    "Engage with Doctor through video and audio": "வீடியோ மற்றும் ஆடியோ மூலம் டாக்டருடன் ஈடுபடுங்கள்",
    "Keep on track your Health": "உங்கள் ஆரோக்கியத்தை கண்காணித்து வாருங்கள்",
    "By continuing, You agree that you have read and accept our": "தொடர்வதன் மூலம், நீங்கள் படித்து ஏற்றுக்கொண்டதாக ஒப்புக்கொள்கிறீர்கள்",
    "T&C and Privacy Policy": "டி&சி மற்றும் தனியுரிமைக் கொள்கை",
    // "Allobot": "அலோபோட்",
    "Thinking...": "சிந்திக்கிறது...",
    "Your maternal AI assistant is processing your question": "உங்கள் தாய்வழி AI உதவியாளர் உங்கள் கேள்வியை செயலாக்குகிறார்",
    "Your Maternal AI Assistant": "உங்கள் தாய்வழி AI உதவியாளர்",
    "Welcome to Allobot!": "அலோபோட்டுக்கு வரவேற்கிறோம்!",
    "I'm here to support you through your maternal journey. Ask me anything about pregnancy, childbirth, or early motherhood.": "உங்கள் தாய்வழி பயணத்தில் உங்களுக்கு ஆதரவளிக்க நான் இங்கு வந்துள்ளேன். கர்ப்பம், பிரசவம் அல்லது ஆரம்ப தாய்மை பற்றி என்னிடம் எதையும் கேளுங்கள்",
    "What You Can Ask Me:": "நீங்கள் என்னிடம் என்ன கேட்கலாம்:",
    "Pregnancy health tips": "கர்ப்பகால ஆரோக்கிய குறிப்புகள்",
    "Nutrition advice": "ஊட்டச்சத்து ஆலோசனை",
    "Baby care basics": "குழந்தை பராமரிப்பு அடிப்படைகள்",
    "Trimester milestones": "மூன்று மாத மைல்கற்கள்",
    "Ask Allobot...": "அலோபோட்டிடம் கேளுங்கள்...",
    "Incoming Call": "உள்வரும் அழைப்பு",
    "Waiting": "காத்திருக்கிறது",
    "No messages yet": "இதுவரை செய்திகள் இல்லை",
    "Tablets": "மாத்திரைகள்",
    "Units": "அலகுகள்",
    "Timing": "நேரம்",
    "No prescriptions found.": "மருந்துச்சீட்டுகள் எதுவும் கிடைக்கவில்லை",
    "No description available": "விளக்கம் இல்லை",
    "No reports found": "அறிக்கைகள் எதுவும் கிடைக்கவில்லை",
    "Report Details": "அறிக்கை விவரங்கள்",
    "Unknown Report Type": "அறியப்படாத அறிக்கை வகை",
    "Test Results": "சோதனை முடிவுகள்",
    "Delete Report": "அறிக்கையை நீக்கு",
    "Are you sure you want to delete this report?": "இந்த அறிக்கையை நிச்சயமாக நீக்க விரும்புகிறீர்களா?",
    "CANCEL": "ரத்துசெய்",
    "DELETE": "நீக்கு",
    "Normal": "சாதாரண",
    "Body pain": "உடல் வலி",
    "Burning Stomach": "எரியும் வயிறு",
    "Cold cough": "சளி இருமல்",
    "Dizziness": "தலைச்சுற்றல்",
    "Headache": "தலைவலி",
    "Vomiting": "வாந்தி",
    "Other": "மற்றவை",
    "Blood Pressure": "இரத்த அழுத்தம்",
    "Temperature": "வெப்பநிலை",
    "Blood Saturation": "இரத்த செறிவு",
    "Blood Glucose": "இரத்த சர்க்கரை",
    "BMI": "பிஎம்ஐ",
    "HRV": "எச்ஆர்வி",
    "Baby Cry Not Detected.": "குழந்தை அழுகை கண்டறியப்படவில்லை.",
    "The baby cry detection process failed. Please check your connection or try again.": "குழந்தை அழுகை கண்டறிதல் செயல்முறை தோல்வியுற்றது. உங்கள் இணைப்பை சரிபார்க்கவும் அல்லது மீண்டும் முயற்சிக்கவும்.",
    "Retry": "மீண்டும் முயற்சிக்கவும்",
    "Please select Appointment Date": "சந்திப்பு தேதியைத் தேர்ந்தெடுக்கவும்",
    "Please enter Diagnosis Description": "நோய் கண்டறிதல் விளக்கத்தை உள்ளிடவும்",
    "No data available": "தரவு எதுவும் இல்லை",
    "Pregnant": "கர்ப்பிணி",
    "Not Pregnant": "கர்ப்பிணி அல்ல",
    "Summary": "சுருக்கம்",
    "Upcoming Appointments": "வரவிருக்கும் சந்திப்புகள்",
    "No appointments scheduled": "சந்திப்புகள் எதுவும் திட்டமிடப்படவில்லை",
    "No": "இல்லை",
    "Yes": "ஆம்",
    "No appointments found": "சந்திப்புகள் எதுவும் கிடைக்கவில்லை",
    "JioVio Healthcare": "ஜியோவியோ சுகாதாரம்",
    "General Details": "பொது விவரங்கள்",
    "Partner Details": "துணை விவரங்கள்",
    "Pregnancy Details": "கர்ப்ப விவரங்கள்",
    "Address Details": "முகவரி விவரங்கள்",
    "Contact Us": "எங்களை தொடர்பு கொள்ளுங்கள்",
    "Something not Working": "ஏதோ வேலை செய்யவில்லை",
    "Feature Request": "அம்ச கோரிக்கை",
    "Question": "கேள்வி",
    "FeedBack": "கருத்து",
    "SEND": "அனுப்பு",
    "My Subscription": "எனது சந்தா",
    "Language": "மொழி",
    "Terms & Conditions": "விதிமுறைகள் & நிபந்தனைகள்",
    "Privacy Policy": "தனியுரிமைக் கொள்கை",
    "Log Out": "வெளியேறு",
    "Are you sure to logout?": "வெளியேற விரும்புகிறீர்களா?",
    "Cancel": "ரத்துசெய்",
    "Ok": "சரி",
    "Change Default": "இயல்புநிலையை மாற்று",
    "Write Description": "விளக்கத்தை எழுதுங்கள்",
    "Please enter Description": "விளக்கத்தை உள்ளிடவும்",
    "Door No": "கதவு எண்",
    "Please enter Door No": "கதவு எண்ணை உள்ளிடவும்",
    "Street Name": "தெரு பெயர்",
    "Please enter Street Name": "தெரு பெயரை உள்ளிடவும்",
    "Pincode": "அஞ்சல் குறியீடு",
    "Please enter Pincode": "அஞ்சல் குறியீட்டை உள்ளிடவும்",
    "Search Area": "தேடல் பகுதி",
    "Select Area Name": "பகுதி பெயரைத் தேர்ந்தெடுக்கவும்",
    "Enter your Name": "உங்கள் பெயரை உள்ளிடவும்",
    "Please enter your name": "உங்கள் பெயரை உள்ளிடவும்",
    "Enter Email Id": "மின்னஞ்சல் ஐடியை உள்ளிடவும்",
    "Please Select Gender": "பாலினத்தைத் தேர்ந்தெடுக்கவும்",
    "Age": "வயது",
    "Please enter age": "வயதை உள்ளிடவும்",
    "Please enter corrent age": "சரியான வயதை உள்ளிடவும்",
    "LMP Date": "எல்எம்பி தேதி",
    "Please enter LMP Date": "எல்எம்பி தேதியை உள்ளிடவும்",
    "ED Date": "இடி தேதி",
    "Date of delivery": "பிரசவ தேதி",
    "Please enter Delivery Date": "பிரசவ தேதியை உள்ளிடவும்",
    "Please enter Partner Name": "துணையின் பெயரை உள்ளிடவும்",
    "Partner Name": "துணையின் பெயர்",
    "Please enter Partner Mobile Number": "துணையின் கைபேசி எண்ணை உள்ளிடவும்",
    "Partner Mobile Number": "துணையின் கைபேசி எண்",
    "Bed Time": "படுக்கை நேரம்",
    "Please enter Date of Birth": "பிறந்த தேதியை உள்ளிடவும்",
    "Wake Up Time": "எழும் நேரம்",
    "Name": "பெயர்",
    "Please Select Parent Type": "பெற்றோர் வகையைத் தேர்ந்தெடுக்கவும்",
    "Parent Type": "பெற்றோர் வகை",
    "Please Select Pregnant Status": "கர்ப்ப நிலையைத் தேர்ந்தெடுக்கவும்",
    "Please enter Area": "பகுதியை உள்ளிடவும்",
    "Area": "பகுதி",
    "Services": "சேவைகள்",
    "AlloBaby": "அலோபேபி",
    "Awareness" : "விழிப்புணர்வு",
    "Screening" : "திரையிடல்",
    "Glucose Test": "குளுக்கோஸ் பரிசோதனை",
    "Ultrasound Test": "அல்ட்ராசவுண்ட் பரிசோதனை",
    "Urine Test": "சிறுநீர் பரிசோதனை"

};



// final Map<String, String> ta = {
//   //registersation screen

//   "Helps you to consult patient Virtually":
//       "உண்மையில் நோயாளியைக் கலந்தாலோசிக்க உங்களுக்கு உதவுகிறது",
//   "Engage with patient through video and audio":
//       "வீடியோ மற்றும் ஆடியோ மூலம் நோயாளியுடன் ஈடுபடுங்கள்",
//   "Keeps on track your patient Health":
//       "உங்கள் நோயாளியின் ஆரோக்கியத்தை கண்காணிக்கும்",
//   "Username": "பயனர் பெயர்",
//   "password": "கடவுச்சொல்",
//   "CONTINUE": "தொடரவும்",
//   "By continuing, You agree that you have read and accept our T&C and Privacy Policy":
//       "தொடர்வதன் மூலம், எங்கள் T&C மற்றும் தனியுரிமைக் கொள்கையைப் படித்து ஏற்றுக்கொண்டீர்கள் என்பதை ஒப்புக்கொள்கிறீர்கள்",
//   "LoggedIn Successfully": "புகுபதிகை வெற்றிகரமாக",
//   "Invalid Credential": "தவறான நற்சான்றிதழ்",

// //Home Screen

//   "AlloLab": "அலோலேப்",
//   "Welcome": "வணக்கம்",
//   "Worker ID": "தொழிலாளி ஐடி",
//   "Recently Added Patient": "சமீபத்தில் சேர்க்கப்பட்ட நோயாளி",
//   "Mobile No:": "அலைபேசி எண்:",
//   "Start Screening": "திரையிடல் தொடங்கு",
//   "Select Language": "மொழியை தேர்ந்தெடுங்கள்",
//   "English": "ஆங்கிலம்",
//   "Tamil": "தமிழ்",
//   "Hindi": "இந்தி",
//   "Face Recognition": "முகத்தை அடையாளம் காணுதல்",
//   "Start Screening with Face Recongnition":
//       "முகம் அங்கீகாரத்துடன் திரையிடலைத் தொடங்கு",
//   "CAPTURE": "பிடிப்பு",
//   "User Not Found": "பயனர் கிடைக்கவில்லை",
//   "Search with Phone Number": "தொலைபேசி எண்ணைக் கொண்டு தேடு",
//   "Enter Phone Number": "தொலைபேசி எண்ணை உள்ளிடவும்",
//   "Add New Patient": "புதிய நோயாளியைச் சேர்",
//   "Add Patient to Start Screening": "திரையிடல் தொடங்க நோயாளியைச் சேர்க்கவும்",
//   "Personal Details": "தனிப்பட்ட விவரங்கள்",
//   "Capture Image": "படத்தை பிடி",
//   "Name": "பெயர்",
//   "EmailID": "மின்னஞ்சல் முகவரி",
//   "Phone Number": "தொலைபேசி எண்",
//   "Gender": "பாலினம்",
//   "Male": "ஆண்",
//   "Female": "பெண்",
//   "Blood Group": "இரத்த வகை",
//   "Date of Birth": "பிறந்த தேதி",
//   "Age": "வயது",
//   "OK": "சரி",
//   "CANCEL": "ரத்துசெய்",
//   "Address Details": "முகவரி விவரங்கள்",
//   "AddressLine": "முகவரி",
//   "Pincode": "அஞ்சல் குறியீடு",
//   "City": "நகரம்",
//   "State": "நிலை",
//   "Enter Correct Pincode": "சரியான பின்கோடை உள்ளிடவும்",
//   "Patient Name": "நோயாளியின் பெயர்",
//   "Checkup Details": "சரிபார்ப்பு விவரங்கள்",
//   "Appointment": "நியமனம்",
//   "Book an Appointment": "ஒரு சந்திப்பை முன்பதிவு செய்யுங்கள்",
//   "Select Doctor": "டாக்டரை தேர்ந்தெடு",
//   "Appointment Date": "அப்பயிண்ட்மெண்ட் தேதி",
//   "View Available Slots": "கிடைக்கும் இடங்களைக் காண்க",
//   "No Slot Selected": "ஸ்லாட் எதுவும் தேர்ந்தெடுக்கப்படவில்லை",
//   "Diagnosis Desc": "நோயறிதல் விவரம்",
//   "Book": "பதிவு",
//   "Appointment Book Successfully": "அப்பாயிண்ட்மெண்ட் புத்தகம் வெற்றிகரமாக",
//   "CheckUp": "சோதனை",
//   "No CheckUp found": "சோதனை இல்லை",
//   "Today": "இன்று",
//   "No available slot for selected date":
//       "தேர்ந்தெடுக்கப்பட்ட தேதிக்கு ஸ்லாட் இல்லை",
//   "View appointment": "அப்பயிண்ட்மெண்ட் பார்க்கவும்",
//   "completed": "நிறைவு",
//   "Appointments": "நியமனங்கள்",
//   "Upcoming": "வரவிருக்கும்",
//   "Date": "தேதி",
//   "Time": "நேரம்",
//   "Status": "நிலை",
//   "View Appointment": "அப்பாயிண்ட்மெண்ட் பார்க்கவும்",
//   "Cancel Appointment": "அப்பயிண்ட்மெண்ட்டை ரத்து செய்",
//   "Add Symptoms and Vitals": "அறிகுறிகள் மற்றும் உயிர்களைச் சேர்",
//   "Select Symptoms": "அறிகுறிகளைத் தேர்ந்தெடு",
//   "Body Pain": "உடல் வலி",
//   "Burning Stomach": "எரியும் வயிறு",
//   "Cold Cough": "சளி இருமல்",
//   "Dizziness": "தலைச்சுற்றல்",
//   "Headache": "தலைவலி",
//   "Vomiting": "வாந்தி",
//   "NEXT": "அடுத்தது",
//   "Vitals": "உயிரினங்கள்",
//   "Blood Pressue": "இரத்த அழுத்தம்",
//   "Temperature": "வெப்ப நிலை",
//   "Blood Saturation": "இரத்த செறிவு",
//   "Heart Rate": "இதய துடிப்பு",
//   "Blood Glucose": "இரத்த குளுக்கோஸ்",
//   "BMI": "பிஎம்ஐ",
//   "Respiratory Rate": "சுவாச விகிதம்",
//   "HRV": "எச்ஆர்வி",
//   "BACK": "மீண்டும்",
//   "SAVE": "சேமி",
//   "CheckUp Added Sucessfully": "சரிபார்ப்பு வெற்றிகரமாக சேர்க்கப்பட்டது",
//   "CheckUp completed": "சோதனை முடிந்தது",
//   "COMPLETED": "நிறைவு",
//   "Appointment Status": "நியமன நிலை",
//   "Doctor Name": "டாக்டர் பெயர்",
//   "Health Status": "சுகாதார நிலை",
//   "NORMAL": "இயல்பு",
//   "Case Summary": "வழக்கு சுருக்கம்",
//   "Prescription": "மருந்து",
//   "Tablets": "மாத்திரைகள்",
//   "Units": "அலகுகள்",
//   "Timing": "நேரம்",
//   "Requested lab supported": "கோரிய ஆய்வகம் ஆதரிக்கப்படுகிறது",
//   "Next Appointment Date": "அடுத்த சந்திப்பு தேதி",
//   "Next Appointment Time": "அடுத்த சந்திப்பு நேரம்",
//   "Symptoms": "அறிகுறிகள்",
//   "Are you sure to cancel the appointment?":
//       "நிச்சயமாக அப்பாயின்ட்மென்ட்டை ரத்து செய்யலாமா?",
//   "Screening": "திரையிடல்",
//   "Go to Screening": "ஸ்கிரீனிங்கிற்கு செல்",
//   "Reports": "அறிக்கைகள்",
//   "Report Details": "அறிக்கை விவரங்கள்",
//   "Report": "அறிக்கை",
//   "SCAN AND ADD NEW REPORT": "ஸ்கேன் செய்து புதிய அறிக்கையைச் சேர்",
//   "Click Add Images Button": "படங்களைச் சேர் பொத்தானைக் கிளிக் செய்க",
//   "NO IMAGE": "உருவம் இல்லை",
//   "No Report Added": "அறிக்கை சேர்க்கப்படவில்லை",
//   "ADD IMAGE": "படத்தைச் சேர்",
//   "Choose Photo from :": "இதில் இருந்து புகைப்படத்தைத் தேர்ந்தெடுங்கள் :",
//   "Type of Report": "அறிக்கை வகை",
//   "Write Description": "விளக்கத்தை எழுது",
//   "ADD REPORT": "அறிக்கையைச் சேர்",
//   "Report Added Successfully": "அறிக்கை வெற்றிகரமாக சேர்க்கப்பட்டது",
//   "Report Deleted Successfully": "அறிக்கை வெற்றிகரமாக நீக்கப்பட்டது",
//   "Report Date": "அறிக்கை தேதி",
//   "Report Time": "அறிக்கை நேரம்",
//   "Report Desc": "அறிக்கை விவரம்",
//   "UPDATE IMAGE": "படத்தைப் புதுப்பி",
//   "DELETE REPORT": "அறிக்கையை நீக்கு",
//   "UPDATE REPORT": "புதுப்பிப்பு அறிக்கை",
//   "Report Updated Successfully": "அறிக்கை வெற்றிகரமாக புதுப்பிக்கப்பட்டது",
//   "Education": "கல்வி",
//   "Knowledge Transfer": "அறிவு பரிமாற்றம்",
//   "Sorry No Awareness Post Found":
//       "மன்னிக்கவும் விழிப்புணர்வு இடுகை எதுவும் கிடைக்கவில்லை",
//   "Patient List": "நோயாளிகள் பட்டியல்",
//   "Search Patient By Name": "பெயரால் நோயாளியைத் தேடுங்கள்",

// //Chat screen

//   "Chat": "அரட்டை",
//   "PATIENTS": "நோயாளிகள்",
//   "DOCTORS": "டாக்டர்கள்",
//   "NURSE": "செவிலியர்",
//   "Type a message": "செய்தியை உள்ளிடவும்",
//   "View Case Details": "வழக்கு விவரங்களைக் காண்க",

// //Settings Screen

//   "Settings": "அமைப்புகள்",
//   "Worker ID": "பணியாளர் ஐடி",
//   "General Details": "பொது விவரங்கள்",
//   "Name": "பெயர்",
//   "Year of Experience": "அனுபவ ஆண்டு",
//   "Title": "தலைப்பு",
//   "Address Details": "முகவரி விவரங்கள்",
//   "Address": "முகவரி",
//   "Pincode": "அஞ்சல் குறியீடு",
//   "Edit Profile": "சுயவிவரத்தைத் திருத்து",
//   "Notification": "அறிவிப்பு",
//   "ON": "ஆன்",
//   "OFF": "ஆஃப்",
//   "Terms & Conditions": "விதிமுறைகளும் நிபந்தனைகளும்",
//   "Privacy Policy": "தனியுரிமைக் கொள்கை",
//   "Help": "உதவி",
//   "Contact Us": "எங்களை தொடர்பு கொள்ள",
//   "Tell us what's going on": "என்ன நடக்கிறது என்று சொல்லுங்கள்",
//   "Tell us why you're reaching us":
//       "நீங்கள் ஏன் எங்களை அணுகுகிறீர்கள் என்று சொல்லுங்கள்",
//   "Something not Working": "ஏதோ வேலை செய்யவில்லை",
//   "Feature Request": "சிறப்பு விண்ணப்பம்",
//   "Question": "கேள்வி",
//   "FeedBack": "பின்னூட்டம்",
//   "How do you feel? (Optional)": "நீங்கள் எப்படி உணர்கிறீர்கள்? (விரும்பினால்)",
//   "SEND": "அனுப்பு",
//   "App Info": "பயன்பாட்டுத் தகவல்",
//   "Log out": "வெளியேறு",
//   "Are you sure to log out?": "நீங்கள் நிச்சயமாக வெளியேறுகிறீர்களா?",
//   "No": "இல்லை",
//   "Yes": "ஆம்"
// };
