final Map<String, String> tl = {
"english"	:	"Telugu",
"Hunger Crying"	:	"ఆకలి ఏడుపు",
"Sleepy Crying"	:	"స్లీపీ క్రయింగ్",
"Pain Crying"	:	"నొప్పి ఏడుపు",
"Discomfort Crying"	:	"అసౌకర్యం ఏడుపు",
"Colic Crying"	:	"కోలిక్ క్రయింగ్",
"Attention Crying"	:	"అటెన్షన్ క్రయింగ్",
"Rhythmic, repetitive cries that grow louder if the baby isn't fed. Often accompanied by hand-sucking and rooting behavior."	:	"శిశువుకు ఆహారం ఇవ్వకపోతే, రిథమిక్, పునరావృత ఏడుపులు బిగ్గరగా పెరుగుతాయి. తరచుగా చేతితో పీల్చటం మరియు వేళ్ళు పెరిగే ప్రవర్తనతో కూడి ఉంటుంది.",
"A whiny, nasal cry that sounds weaker than a hunger cry, often accompanied by yawning and eye-rubbing."	:	"ఆకలి కేకలు కంటే బలహీనంగా ధ్వనించే విసురు, ముక్కు ఏడుపు, తరచుగా ఆవులించడం మరియు కళ్ళు రుద్దడం వంటివి ఉంటాయి.",
"A sudden, high-pitched, intense cry that comes in bursts with breathing pauses. Often accompanied by physical tension."	:	"అకస్మాత్తుగా, ఎత్తైన, తీవ్రమైన కేకలు, శ్వాస విరామాలతో పేలవచ్చు. తరచుగా శారీరక ఒత్తిడితో కూడి ఉంటుంది.",
"A fussy, irritated cry that typically stops when the source of discomfort is addressed."	:	"అసౌకర్యం యొక్క మూలాన్ని పరిష్కరించినప్పుడు సాధారణంగా ఆగిపోయే గజిబిజి, చిరాకుతో కూడిన ఏడుపు.",
"Prolonged, intense crying episodes, typically in the evening, with physical signs of distress."	:	"సుదీర్ఘమైన, తీవ్రమైన ఏడుపు ఎపిసోడ్‌లు, సాధారణంగా సాయంత్రం, బాధ యొక్క శారీరక సంకేతాలతో.",
"A mild cry that starts softly and increases if ignored, often accompanied by eye contact and reaching out."	:	"మృదువుగా మొదలవుతుంది మరియు విస్మరించినట్లయితే పెరుగుతుంది, ఇది తరచుగా కంటిచూపు మరియు చేరుకోవడంతో పాటుగా ఉంటుంది.",
"Hunger cries are rhythmic, repetitive, and grow louder if the baby isn't fed."	:	"ఆకలి కేకలు లయబద్ధంగా ఉంటాయి, పునరావృతమవుతాయి మరియు శిశువుకు ఆహారం ఇవ్వకపోతే బిగ్గరగా పెరుగుతాయి.",
"Babies may also:"	:	"పిల్లలు కూడా ఉండవచ్చు:",
"• Suck on hands or fingers"	:	"• చేతులు లేదా వేళ్లను పీల్చుకోండి",
"• Smack lips, root (turn head searching for a nipple)"	:	"• స్మాక్ పెదవులు, రూట్ (తలను తిప్పి చనుమొన కోసం వెతుకుతూ)",
"• Get fussy even after being comforted"	:	"• ఓదార్చిన తర్వాత కూడా గజిబిజిగా ఉండండి",
"A whiny, nasal cry that may sound weaker than a hunger cry."	:	"ఆకలి కేకలు కంటే బలహీనంగా వినిపించే విసురు, నాసికా ఏడుపు.",
"Babies may also:"	:	"పిల్లలు కూడా ఉండవచ్చు:",
"• Yawn frequently"	:	"• తరచుగా ఆవలించు",
"• Rub their eyes or pull their ears"	:	"• వారి కళ్లను రుద్దండి లేదా వారి చెవులను లాగండి",
"• Become fussy and harder to soothe"	:	"• కంగారుగా మరియు ఉపశమనానికి కష్టంగా మారండి",
"A sudden, high-pitched, intense cry that may come in bursts with pauses for breath."	:	"అకస్మాత్తుగా, ఎత్తైన, తీవ్రమైన కేకలు ఊపిరి పీల్చుకోవడం కోసం విరామాలతో పేలవచ్చు.",
"Babies may also:"	:	"పిల్లలు కూడా ఉండవచ్చు:",
"• Clench fists or arch their back"	:	"• పిడికిలి బిగించండి లేదా వాటి వీపును వంచండి",
"• Become stiff or tense"	:	"• గట్టిగా లేదా ఉద్రిక్తంగా మారండి",
"• Show signs of discomfort (scrunched face, difficulty calming down)"	:	"• అసౌకర్యానికి సంబంధించిన సంకేతాలను చూపండి (ముఖం చిట్లడం, శాంతించడంలో ఇబ్బంది)",
"A fussy, irritated cry that may stop when the issue is resolved."	:	"సమస్య పరిష్కరించబడినప్పుడు ఆగిపోయే గజిబిజిగా, చిరాకుతో కూడిన ఏడుపు.",
"Babies may also:"	:	"పిల్లలు కూడా ఉండవచ్చు:",
"• Wiggle or squirm a lot"	:	"• చాలా విగ్లే లేదా స్క్విర్మ్",
"• Tug at their clothing or ears"	:	"• వారి దుస్తులు లేదా చెవులను లాగండి",
"• Appear restless or uneasy"	:	"• అశాంతిగా లేదా అశాంతిగా కనిపిస్తారు",
"A prolonged, intense, high-pitched cry that often occurs in the evening."	:	"సాయంత్రం తరచుగా సంభవించే సుదీర్ఘమైన, తీవ్రమైన, ఎత్తైన ఏడుపు.",
"Babies may also:"	:	"పిల్లలు కూడా ఉండవచ్చు:",
"• Clench fists, arch their back, or pull up legs"	:	"• పిడికిలి బిగించండి, వాటి వీపును వంచండి లేదా కాళ్లను పైకి లాగండి",
"• Have a tense, bloated belly"	:	"• ఉద్విగ్నమైన, ఉబ్బిన బొడ్డు కలిగి ఉండండి",
"• Be difficult to soothe, even after feeding"	:	"• తినిపించిన తర్వాత కూడా ఉపశమనం పొందడం కష్టం",
"A mild, whimpering cry that starts softly and gets louder if ignored."	:	"విస్మరించినట్లయితే మృదువుగా మొదలవుతుంది మరియు బిగ్గరగా వచ్చే ఒక తేలికపాటి, విప్పింగ్ కేడ్.",
"Babies may also:"	:	"పిల్లలు కూడా ఉండవచ్చు:",
"• Make eye contact while crying"	:	"• ఏడుస్తున్నప్పుడు కంటికి పరిచయం చేయండి",
"• Reach out for comfort"	:	"• సౌకర్యం కోసం చేరుకోండి",
"• Stop crying quickly when picked up"	:	"• తీసుకున్నప్పుడు త్వరగా ఏడుపు ఆపండి",
"Feed Promptly – Responding early prevents excessive crying and makes feeding easier."	:	"తక్షణమే ఫీడ్ చేయండి - ముందుగా స్పందించడం వల్ల అధిక ఏడుపు నిరోధిస్తుంది మరియు ఆహారం తీసుకోవడం సులభం అవుతుంది.",
"Watch for Hunger Cues – Crying is a late sign; look for early signs like lip-smacking, rooting, sticking out tongue, or sucking on hands."	:	"ఆకలి సూచనల కోసం చూడండి - ఏడుపు ఆలస్యం సంకేతం; పెదవులను కొట్టడం, వేళ్ళు పెట్టడం, నాలుకను బయటకు తీయడం లేదా చేతులు పీల్చుకోవడం వంటి ప్రారంభ సంకేతాల కోసం చూడండి.",
"Ensure Proper Latch – If breastfeeding, ensure a deep latch to avoid discomfort."	:	"సరైన గొళ్ళెం నిర్ధారించుకోండి - తల్లిపాలు ఇస్తున్నట్లయితే, అసౌకర్యాన్ని నివారించడానికి లోతైన గొళ్ళెం ఉండేలా చూసుకోండి.",
"Check Feeding Schedule – Newborns need feeding every 2-3 hours."	:	"ఫీడింగ్ షెడ్యూల్‌ను తనిఖీ చేయండి - నవజాత శిశువులకు ప్రతి 2-3 గంటలకు ఆహారం అవసరం.",
"Burp Baby After Feeding – Helps prevent gas and fussiness."	:	"ఫీడింగ్ తర్వాత బర్ప్ బేబీ - గ్యాస్ మరియు ఫస్సీని నిరోధించడంలో సహాయపడుతుంది.",
"Look for Sleep Cues Early – Yawning, zoning out, or rubbing eyes signal it's time to sleep."	:	"త్వరగా నిద్రపోయే సూచనల కోసం వెతకండి – ఆవులించడం, జోన్ అవుట్ చేయడం లేదా కళ్ళు రుద్దడం ఇది నిద్రపోవడానికి సమయం అని సూచిస్తుంది.",
"Create a Calm Sleep Environment – Dim lights, reduce noise, and use white noise if needed."	:	"ప్రశాంతమైన నిద్ర వాతావరణాన్ని సృష్టించండి - డిమ్ లైట్లు, శబ్దాన్ని తగ్గించండి మరియు అవసరమైతే తెల్లని శబ్దాన్ని ఉపయోగించండి.",
"Use Gentle Rocking – Motion, swaddling, or a pacifier can help."	:	"జెంటిల్ రాకింగ్ ఉపయోగించండి - మోషన్, స్వాడ్లింగ్ లేదా పాసిఫైయర్ సహాయపడుతుంది.",
"Follow a Sleep Routine – A consistent bedtime routine helps babies recognize sleep time."	:	"స్లీప్ రొటీన్‌ని అనుసరించండి - స్థిరమైన నిద్రవేళ రొటీన్ పిల్లలు నిద్ర సమయాన్ని గుర్తించడంలో సహాయపడుతుంది.",
"Avoid Overstimulation – Too much activity before bed can make sleep harder."	:	"ఓవర్‌స్టిమ్యులేషన్‌ను నివారించండి - పడుకునే ముందు చాలా ఎక్కువ వ్యాయామం నిద్రను కష్టతరం చేస్తుంది.",
"Check for Obvious Issues – Look for diaper rash, teething pain, or tight clothing."	:	"స్పష్టమైన సమస్యల కోసం తనిఖీ చేయండి - డైపర్ దద్దుర్లు, దంతాల నొప్పి లేదా గట్టి దుస్తులు కోసం చూడండి.",
"Soothe with Gentle Touch – Skin-to-skin contact or holding them close can help."	:	"సున్నిత స్పర్శతో ఉపశమనాన్ని పొందండి - చర్మం నుండి చర్మానికి పరిచయం లేదా వాటిని దగ్గరగా పట్టుకోవడం సహాయపడుతుంది.",
"Try Pain Relief Techniques – For teething, offer a chilled teether; for gas, try tummy massage."	:	"పెయిన్ రిలీఫ్ టెక్నిక్స్ ప్రయత్నించండి - దంతాల కోసం, చల్లబడిన పళ్ళను అందించండి; గ్యాస్ కోసం, కడుపు మసాజ్ ప్రయత్నించండి.",
"Monitor for Fever or Illness – If crying persists with fever, vomiting, or lethargy, consult a doctor."	:	"జ్వరం లేదా అనారోగ్యం కోసం మానిటర్ - జ్వరం, వాంతులు లేదా నీరసంతో ఏడుపు కొనసాగితే, వైద్యుడిని సంప్రదించండి.",
"Trust Your Instincts – If the baby seems in severe pain, seek medical advice immediately."	:	"మీ స్వభావాన్ని విశ్వసించండి - శిశువుకు తీవ్రమైన నొప్పి అనిపిస్తే, వెంటనే వైద్య సలహా తీసుకోండి.",
"Check the Diaper – A wet or soiled diaper is a common cause of discomfort."	:	"డైపర్‌ని తనిఖీ చేయండి - తడి లేదా మురికి డైపర్ అసౌకర్యానికి ఒక సాధారణ కారణం.",
"Ensure Comfortable Clothing – Dress baby in breathable, soft fabrics and check for tight clothing."	:	"సౌకర్యవంతమైన దుస్తులను నిర్ధారించుకోండి - శ్వాసక్రియకు, మృదువైన బట్టలు మరియు బిగుతుగా ఉండే దుస్తులను తనిఖీ చేయండి.",
"Adjust Temperature – Feel baby's neck/back to see if they are too hot or cold."	:	"ఉష్ణోగ్రతను సర్దుబాటు చేయండి – శిశువు యొక్క మెడ/వెనుక భాగం చాలా వేడిగా లేదా చల్లగా ఉన్నాయో లేదో చూడటానికి.",
"Check for External Irritants – Tags, rough fabric, or hair wrapped around fingers/toes can cause irritation."	:	"బాహ్య చికాకులను తనిఖీ చేయండి - ట్యాగ్‌లు, కఠినమైన బట్ట లేదా జుట్టును వేళ్లు/కాలి చుట్టూ చుట్టడం వల్ల చికాకు కలుగుతుంది.",
"Reposition Baby – Changing positions or holding them differently can sometimes help."	:	"పునఃస్థాపన బేబీ - స్థానాలను మార్చడం లేదా వాటిని భిన్నంగా పట్టుకోవడం కొన్నిసార్లు సహాయపడుతుంది.",
"Use Gentle Motions – Rocking, swaying, or holding baby in a 'colic carry' (on their tummy along your forearm) can help."	:	"సున్నితమైన కదలికలను ఉపయోగించండి - పిల్లవాడిని 'కోలిక్ క్యారీ'లో (మీ ముంజేయి వెంట వారి పొట్టపై) రాకింగ్ చేయడం, ఊగడం లేదా పట్టుకోవడం సహాయపడుతుంది.",
"Try White Noise – Rhythmic sounds, like a fan or heartbeat sound, can be soothing."	:	"వైట్ నాయిస్ ప్రయత్నించండి - ఫ్యాన్ లేదా హార్ట్ బీట్ సౌండ్ వంటి రిథమిక్ ధ్వనులు ఓదార్పునిస్తాయి.",
"Burp Baby Well – Gas buildup can make colic worse. Burp frequently during feeds."	:	"బర్ప్ బేబీ వెల్ - గ్యాస్ బిల్డప్ కోలిక్ ను మరింత తీవ్రతరం చేస్తుంది. ఫీడ్ సమయంలో తరచుగా బర్ప్ చేయండి.",
"Massage the Tummy – A gentle circular tummy massage can relieve gas."	:	"పొట్టను మసాజ్ చేయండి - సున్నితమైన వృత్తాకార పొట్ట మసాజ్ గ్యాస్ నుండి ఉపశమనం కలిగిస్తుంది.",
"Consult a Pediatrician – If colic persists, discuss options like probiotic drops or diet changes (for breastfeeding moms)."	:	"శిశువైద్యుని సంప్రదించండి - కడుపు నొప్పి కొనసాగితే, ప్రోబయోటిక్ డ్రాప్స్ లేదా డైట్ మార్పులు (తల్లిపాలు ఇచ్చే తల్లులకు) వంటి ఎంపికలను చర్చించండి.",
"Respond with Reassurance – Holding, talking, or making eye contact helps babies feel secure."	:	"భరోసాతో ప్రతిస్పందించండి - పట్టుకోవడం, మాట్లాడటం లేదా కంటికి పరిచయం చేయడం వల్ల పిల్లలు సురక్షితంగా ఉంటారు.",
"Try Gentle Touch – A cuddle or soft pat on the back can be calming."	:	"సున్నితమైన స్పర్శను ప్రయత్నించండి - వీపుపై గట్టిగా కౌగిలించుకోవడం లేదా మెత్తగా తట్టడం ప్రశాంతంగా ఉంటుంది.",
"Engage with Soothing Sounds – Humming or talking in a calm voice can reassure the baby."	:	"మెత్తగాపాడిన శబ్దాలతో నిమగ్నమవ్వండి - హమ్మింగ్ లేదా ప్రశాంత స్వరంలో మాట్లాడటం శిశువుకు భరోసానిస్తుంది.",
"Encourage Independent Comforting – Allow baby to self-soothe briefly before immediately responding."	:	"ఇండిపెండెంట్ కంఫర్టింగ్‌ను ప్రోత్సహించండి - వెంటనే ప్రతిస్పందించే ముందు శిశువును క్లుప్తంగా స్వీయ-ఓదార్పును అనుమతించండి.",
"Maintain a Balance – Meeting attention needs is important, but consistency in response helps babies learn security."	:	"సమతుల్యతను కాపాడుకోండి - శ్రద్ధ అవసరాలను తీర్చడం ముఖ్యం, కానీ ప్రతిస్పందనలో స్థిరత్వం పిల్లలు భద్రతను నేర్చుకోవడంలో సహాయపడుతుంది.",
		
		
		
"Cry History"	:	"క్రై హిస్టరీ",
"Record"	:	"రికార్డ్ చేయండి",
"Allocry"	:	"కేటాయింపు",
"Baby can cry due to"	:	"బేబీ కారణంగా ఏడవవచ్చు",
"Recording"	:	"రికార్డింగ్",
"Start Recording"	:	"రికార్డింగ్ ప్రారంభించండి",
"Getting Your Baby Sound…"	:	"మీ బిడ్డ ధ్వనిని పొందుతోంది…",
"Try to avoid background noise"	:	"నేపథ్య శబ్దాన్ని నివారించడానికి ప్రయత్నించండి",
"High-pitched, intense crying often indicates pain or immediate needs."	:	"అధిక పిచ్, తీవ్రమైన ఏడుపు తరచుగా నొప్పి లేదా తక్షణ అవసరాలను సూచిస్తుంది.",
"Rhythmic crying that gets louder and softer might mean your baby is tired."	:	"బిగ్గరగా మరియు మృదువుగా ఉండే లయబద్ధమైన ఏడుపు మీ బిడ్డ అలసిపోయిందని అర్థం కావచ్చు.",
"Short, low-pitched cries repeated every few seconds usually signal hunger."	:	"ప్రతి కొన్ని సెకన్లకు పునరావృతమయ్యే చిన్న, తక్కువ పిచ్ ఏడుపులు సాధారణంగా ఆకలిని సూచిస్తాయి.",
"Whimpering or whining sounds might indicate mild discomfort or wanting attention."	:	"గుసగుసలాడే లేదా విసుక్కునే శబ్దాలు తేలికపాటి అసౌకర్యాన్ని లేదా శ్రద్ధ కోరడాన్ని సూచిస్తాయి.",
"Long, high-pitched screams could be signs of colic or stomach pain."	:	"పొడవైన, ఎత్తైన అరుపులు కోలిక్ లేదా కడుపు నొప్పికి సంకేతాలు కావచ్చు.",
"Sudden, sharp cries might mean your baby is too hot or cold."	:	"ఆకస్మిక, పదునైన ఏడుపు మీ బిడ్డ చాలా వేడిగా లేదా చల్లగా ఉందని అర్థం కావచ్చు.",
"Persistent crying with leg movement often indicates diaper change needs."	:	"లెగ్ కదలికతో నిరంతర ఏడుపు తరచుగా డైపర్ మార్పు అవసరాలను సూచిస్తుంది.",
"Baby Cry Not Detected"	:	"శిశువు ఏడుపు గుర్తించబడలేదు",
		
"Select Language"	:	"భాషను ఎంచుకోండి",
"Enter Mobile Number"	:	"మొబైల్ నంబర్‌ని నమోదు చేయండి",
"SEND OTP"	:	"OTPని పంపండి",
"How do you feel today ?"	:	"ఈ రోజు మీకు ఎలా అనిపిస్తుంది?",
"Online"	:	"ఆన్‌లైన్",
"Offline"	:	"ఆఫ్‌లైన్",
"Image Uploaded"	:	"చిత్రం అప్‌లోడ్ చేయబడింది",
"Type a message"	:	"సందేశాన్ని టైప్ చేయండి",
"Choose photo from"	:	"నుండి ఫోటోను ఎంచుకోండి",
"Get Connected with doctors"	:	"వైద్యులతో కనెక్ట్ అవ్వండి",
"Connect with Doctor"	:	"డాక్టర్‌తో కనెక్ట్ అవ్వండి",
"Connect with Health worker"	:	"ఆరోగ్య కార్యకర్తతో కనెక్ట్ అవ్వండి",
"Connect with AlloBot"	:	"AlloBotతో కనెక్ట్ అవ్వండి",
"Sorry No Awareness Post"	:	"సారీ నో అవేర్‌నెస్ పోస్ట్",
"Checkup Completed"	:	"తనిఖీ పూర్తయింది",
"Waiting for Doctor Feedback"	:	"డాక్టర్ ఫీడ్‌బ్యాక్ కోసం వేచి ఉంది",
"Checkup need to be done"	:	"చెకప్ చేయాల్సి ఉంటుంది",
"Checkup"	:	"తనిఖీ",
"No Checkup Found"	:	"తనిఖీ ఏదీ కనుగొనబడలేదు",
"Checkup Details"	:	"తనిఖీ వివరాలు",
"Doctor Name"	:	"డాక్టర్ పేరు",
"Date"	:	"తేదీ",
"Health Status"	:	"ఆరోగ్య స్థితి",
"Case Summary"	:	"కేసు సారాంశం",
"Prescription"	:	"ప్రిస్క్రిప్షన్",
"Next Appointment Time"	:	"తదుపరి అపాయింట్‌మెంట్ సమయం",
"Symptoms"	:	"లక్షణాలు",
"Vitals"	:	"ప్రాణాధారాలు",
"Add Prescription"	:	"ప్రిస్క్రిప్షన్ జోడించండి",
"ADD PRESCRIPTION"	:	"ప్రిస్క్రిప్షన్ జోడించండి",
"Click to Add Image"	:	"చిత్రాన్ని జోడించడానికి క్లిక్ చేయండి",
"View Prescription"	:	"ప్రిస్క్రిప్షన్ చూడండి",
"Error loading image"	:	"చిత్రాన్ని లోడ్ చేయడంలో లోపం",
"Prescription Type"	:	"ప్రిస్క్రిప్షన్ రకం",
"Date Added"	:	"తేదీ జోడించబడింది",
"Description"	:	"వివరణ",
"Add Report"	:	"నివేదికను జోడించండి",
"NO IMAGE"	:	"చిత్రం లేదు",
"Click Add Image Button"	:	"చిత్రం జోడించు బటన్ క్లిక్ చేయండి",
"ADD IMAGE"	:	"చిత్రాన్ని జోడించు",
"ADD REPORT"	:	"నివేదికను జోడించండి",
"Report"	:	"నివేదించండి",
"Scan and Add new Report"	:	"స్కాన్ చేసి, కొత్త నివేదికను జోడించండి",
"Self Screening"	:	"స్వీయ స్క్రీనింగ్",
"BACK"	:	"వెనుకకు",
"NEXT"	:	"తదుపరి",
"Finish"	:	"ముగించు",
"Summary Report"	:	"సారాంశ నివేదిక",
"Submit"	:	"సమర్పించండి",
"Let's begin the test"	:	"పరీక్షను ప్రారంభిద్దాం",
"Hemoglobin Test"	:	"హిమోగ్లోబిన్ పరీక్ష",
"Easily get your Reading by Performing the scans below"	:	"దిగువ స్కాన్‌లను చేయడం ద్వారా మీ పఠనాన్ని సులభంగా పొందండి",
"Fetal Monitoring"	:	"పిండం పర్యవేక్షణ",
"Upload Report"	:	"నివేదికను అప్‌లోడ్ చేయండి",
"Tap to Change"	:	"మార్చడానికి నొక్కండి",
"Heart Rate"	:	"హృదయ స్పందన రేటు",
"BPM"	:	"ప్రతి నిమిషం బీట్‌లు",
"Kick Count"	:	"కిక్ కౌంట్",
"Tap to Increase the Count"	:	"గణనను పెంచడానికి నొక్కండి",
"Add Glucose Report"	:	"గ్లూకోజ్ నివేదికను జోడించండి",
"Blood Glucose Value"	:	"రక్తంలో గ్లూకోజ్ విలువ",
"Add Hemoglobin Report"	:	"హిమోగ్లోబిన్ నివేదికను జోడించండి",
"Hemoglobin Value"	:	"హిమోగ్లోబిన్ విలువ",
"Ultra Sound"	:	"అల్ట్రాసౌండ్",
"Fasting"	:	"ఉపవాసం",
"At rest"	:	"విశ్రాంతిలో",
"After Walk"	:	"నడక తర్వాత",
"Select Height"	:	"ఎత్తు ఎంచుకోండి",
"Select Weight"	:	"బరువును ఎంచుకోండి",
"After walk"	:	"నడక తర్వాత",
"Address Information"	:	"చిరునామా సమాచారం",
"Search"	:	"శోధించండి",
"Continue"	:	"కొనసాగించు",
"Phone Number"	:	"ఫోన్ నంబర్",
"Profile Details"	:	"ప్రొఫైల్ వివరాలు",
"Gender"	:	"లింగం",
"Male"	:	"పురుషుడు",
"Female"	:	"స్త్రీ",
"Select Blood Group"	:	"బ్లడ్ గ్రూప్ ఎంచుకోండి",
"Select Last cycle Date"	:	"చివరి చక్రం తేదీని ఎంచుకోండి",
"Are you my mom or dad?"	:	"నువ్వు నా అమ్మా నాన్నవా?",
"Dad"	:	"నాన్న",
"Mom"	:	"అమ్మ",
"Enter your Partner Details"	:	"మీ భాగస్వామి వివరాలను నమోదు చేయండి",
"Pregnancy Status"	:	"గర్భధారణ స్థితి",
"Partner Pregnancy Status"	:	"భాగస్వామి గర్భధారణ స్థితి",
"Average Length of Cycles"	:	"చక్రాల సగటు పొడవు",
"Day"	:	"రోజు",
"Not yet started"	:	"ఇంకా ప్రారంభం కాలేదు",
"NORMAL"	:	"సాధారణ",
"Health Status"	:	"ఆరోగ్య స్థితి",
"Last Screened"	:	"చివరిగా ప్రదర్శించబడింది",
"GOLD"	:	"బంగారం",
"Subscription Plan"	:	"సబ్‌స్క్రిప్షన్ ప్లాన్",
"No News Feed"	:	"న్యూస్ ఫీడ్ లేదు",
"Probable Reason"	:	"సంభావ్య కారణం",
"Recommendations"	:	"సిఫార్సులు",
"Hi!"	:	"హాయ్!",
"How do you feel today?"	:	"ఈరోజు మీకు ఎలా అనిపిస్తుంది?",
"Select Exercise that have you done today?"	:	"మీరు ఈరోజు చేసిన వ్యాయామాన్ని ఎంచుకోవాలా?",
"None"	:	"ఏదీ లేదు",
"Select tablets that you have taken"	:	"మీరు తీసుకున్న టాబ్లెట్‌లను ఎంచుకోండి",
"Sleep Duration"	:	"నిద్ర వ్యవధి",
"Do you have any of these Symptoms?"	:	"మీకు ఈ లక్షణాలు ఏవైనా ఉన్నాయా?",
"Baby Voice is Recording"	:	"బేబీ వాయిస్ రికార్డింగ్ అవుతోంది",
"STOP"	:	"ఆపు",
"Click the Record Button to Start Recording"	:	"రికార్డింగ్ ప్రారంభించడానికి రికార్డ్ బటన్‌ను క్లిక్ చేయండి",
"Record"	:	"రికార్డ్ చేయండి",
"How many Glass of water have you drunk today?"	:	"ఈరోజు మీరు ఎన్ని గ్లాసుల నీళ్లు తాగారు?",
"OTP Verification"	:	"OTP ధృవీకరణ",
"Enter OTP sent to"	:	"పంపిన OTPని నమోదు చేయండి",
"Verify and proceed"	:	"ధృవీకరించండి మరియు కొనసాగండి",
"Appointment"	:	"అపాయింట్‌మెంట్",
"Select Hospital"	:	"ఆసుపత్రిని ఎంచుకోండి",
"Select Doctor"	:	"వైద్యుడిని ఎంచుకోండి",
"Appointment Date"	:	"అపాయింట్‌మెంట్ తేదీ",
"Available slots"	:	"అందుబాటులో ఉన్న స్లాట్లు",
"No Slots Available"	:	"స్లాట్లు ఏవీ అందుబాటులో లేవు",
"View Available Slots"	:	"అందుబాటులో ఉన్న స్లాట్‌లను వీక్షించండి",
"Start time Slot"	:	"ప్రారంభ సమయ స్లాట్",
"Diagnosis Description"	:	"రోగనిర్ధారణ వివరణ",
"Book"	:	"పుస్తకం",
"Update"	:	"నవీకరించు",
"Respiratory Rate"	:	"శ్వాసకోశ రేటు",
"Appointments"	:	"నియామకాలు",
"As a companion in your pregnancy we help you with the following"	:	"మీ ప్రెగ్నెన్సీలో తోడుగా మేము ఈ క్రింది వాటితో మీకు సహాయం చేస్తాము",
"Book An Appointment"	:	"అపాయింట్‌మెంట్ బుక్ చేయండి",
"Pregnancy Monitoring"	:	"గర్భధారణ పర్యవేక్షణ",
"Help Line"	:	"హెల్ప్ లైన్",
"Current Appointment"	:	"ప్రస్తుత నియామకం",
"No Upcoming Appointments"	:	"రాబోయే అపాయింట్‌మెంట్‌లు లేవు",
"Time"	:	"సమయం",
"Status"	:	"స్థితి",
"Reason"	:	"కారణం",
"Cancel Appointment"	:	"అపాయింట్‌మెంట్ రద్దు చేయండి",
"Show Appointment"	:	"అపాయింట్‌మెంట్ చూపించు",
"My Appointments"	:	"నా అపాయింట్‌మెంట్‌లు",
"Appointment Status"	:	"చిత్రాన్ని జోడించు",
"App Info"	:	"యాప్ సమాచారం",
"CHECK FOR UPDATES"	:	"నవీకరణల కోసం తనిఖీ చేయండి",
"Edit Profile"	:	"ప్రొఫైల్‌ని సవరించండి",
"Help"	:	"సహాయం",
"Tell us what's going on"	:	"ఏమి జరుగుతుందో మాకు చెప్పండి",
"Tell us why you're reaching us"	:	"మీరు మమ్మల్ని ఎందుకు చేరుకుంటున్నారో మాకు చెప్పండి",
"How do you feel? (Optional)"	:	"మీకు ఎలా అనిపిస్తుంది? (ఐచ్ఛికం)",
"My Hospital"	:	"నా హాస్పిటల్",
"No hospitals found"	:	"ఆసుపత్రులు లేవు",
"District"	:	"జిల్లా",
"Settings"	:	"సెట్టింగ్‌లు",
"English"	:	"ఇంగ్లీష్",
"Logout Successful"	:	"లాగ్ అవుట్ విజయవంతమైంది",
"Subscribe"	:	"సభ్యత్వం పొందండి",
"Subscription"	:	"చందా",
"Current Plan"	:	"ప్రస్తుత ప్రణాళిక",
"Monthly"	:	"నెలవారీ",
"Yearly"	:	"సంవత్సరానికి",
"Based on patient reviews"	:	"రోగి సమీక్షల ఆధారంగా",
"Working Hours"	:	"పని గంటలు",
"Contact Information"	:	"సంప్రదింపు సమాచారం",
"Personalised Pregnancy Care"	:	"వ్యక్తిగతీకరించిన గర్భధారణ సంరక్షణ",
"Helps you to consult Doctor Virtually"	:	"వర్చువల్‌గా డాక్టర్‌ని సంప్రదించడానికి మీకు సహాయం చేస్తుంది",
"Engage with Doctor through video and audio"	:	"వీడియో మరియు ఆడియో ద్వారా డాక్టర్‌తో సన్నిహితంగా ఉండండి",
"Keep on track your Health"	:	"మీ ఆరోగ్యాన్ని ట్రాక్ చేస్తూ ఉండండి",
"By continuing, You agree that you have read and accept our"	:	"కొనసాగించడం ద్వారా, మీరు మా చదివినట్లు మరియు అంగీకరించినట్లు అంగీకరిస్తున్నారు",
"T&C and Privacy Policy"	:	"T&C మరియు గోప్యతా విధానం",
"Thinking..."	:	"ఆలోచిస్తూ...",
"Your maternal AI assistant is processing your question"	:	"మీ మెటర్నల్ AI అసిస్టెంట్ మీ ప్రశ్నను ప్రాసెస్ చేస్తున్నారు",
"Your Maternal AI Assistant"	:	"మీ మెటర్నల్ AI అసిస్టెంట్",
"Welcome to Allobot!"	:	"Allobotకి స్వాగతం!",
"I'm here to support you through your maternal journey. Ask me anything about pregnancy, childbirth, or early motherhood."	:	"మీ మాతృ ప్రయాణంలో మీకు మద్దతు ఇవ్వడానికి నేను ఇక్కడ ఉన్నాను. గర్భం, ప్రసవం లేదా ప్రారంభ మాతృత్వం గురించి ఏదైనా నన్ను అడగండి.",
"What You Can Ask Me"	:	"మీరు నన్ను ఏమి అడగవచ్చు",
"Pregnancy health tips"	:	"గర్భధారణ ఆరోగ్య చిట్కాలు",
"Nutrition advice"	:	"పోషకాహార సలహా",
"Baby care basics"	:	"బేబీ కేర్ బేసిక్స్",
"Trimester milestones"	:	"త్రైమాసిక మైలురాళ్ళు",
"Ask Allobot..."	:	"Allobotని అడగండి...",
"Incoming Call"	:	"ఇన్‌కమింగ్ కాల్",
"Waiting"	:	"వేచి ఉంది",
"No messages yet"	:	"ఇంకా సందేశాలు లేవు",
"Tablets"	:	"టాబ్లెట్లు",
"Units"	:	"యూనిట్లు",
"Timing"	:	"సమయపాలన",
"No prescriptions found."	:	"ప్రిస్క్రిప్షన్‌లు ఏవీ కనుగొనబడలేదు.",
"No description available"	:	"వివరణ అందుబాటులో లేదు",
"No reports found"	:	"నివేదికలు ఏవీ కనుగొనబడలేదు",
"Report Details"	:	"రిపోర్ట్ వివరాలు",
"Unknown Report Type"	:	"తెలియని నివేదిక రకం",
"Test Results"	:	"పరీక్ష ఫలితాలు",
"Delete Report"	:	"నివేదికను తొలగించండి",
"Are you sure you want to delete this report?"	:	"మీరు ఖచ్చితంగా ఈ నివేదికను తొలగించాలనుకుంటున్నారా?",
"CANCEL"	:	"రద్దు చేయి",
"DELETE"	:	"తొలగించు",
"Normal"	:	"సాధారణ",
"Body pain"	:	"శరీర నొప్పి",
"Burning Stomach"	:	"కడుపు మండుతోంది",
"Cold cough"	:	"జలుబు దగ్గు",
"Dizziness"	:	"తల తిరగడం",
"Headache"	:	"తలనొప్పి",
"Vomiting"	:	"వాంతులు అవుతున్నాయి",
"Other"	:	"ఇతర",
"Blood Pressure"	:	"రక్త పీడనం",
"Temperature"	:	"ఉష్ణోగ్రత",
"Blood Saturation"	:	"రక్త సంతృప్తత",
"Blood Glucose"	:	"రక్తంలో గ్లూకోజ్",
"BMI"	:	"ప్రతి నిమిషం బీట్‌లు",
"HRV"	:	"హార్ట్ రేట్ వేరియబిలిటీ",
"Baby Cry Not Detected."	:	"శిశువు ఏడుపు గుర్తించబడలేదు.",
"The baby cry detection process failed. Please check your connection or try again."	:	"శిశువు ఏడుపును గుర్తించే ప్రక్రియ విఫలమైంది. దయచేసి మీ కనెక్షన్‌ని తనిఖీ చేయండి లేదా మళ్లీ ప్రయత్నించండి.",
"Retry"	:	"మళ్లీ ప్రయత్నించండి",
"Please select Appointment Date"	:	"దయచేసి అపాయింట్‌మెంట్ తేదీని ఎంచుకోండి",
"Please enter Diagnosis Description"	:	"దయచేసి రోగనిర్ధారణ వివరణను నమోదు చేయండి",
"No data available"	:	"డేటా అందుబాటులో లేదు",
"Pregnant"	:	"గర్భవతి",
"Not Pregnant"	:	"గర్భవతి కాదు",
"Summary"	:	"సారాంశం",
"Upcoming Appointments"	:	"రాబోయే అపాయింట్‌మెంట్‌లు",
"No appointments scheduled"	:	"అపాయింట్‌మెంట్‌లు షెడ్యూల్ చేయబడలేదు",
"No"	:	"నం",
"Yes"	:	"అవును",
"No appointments found"	:	"అపాయింట్‌మెంట్‌లు ఏవీ కనుగొనబడలేదు",
"JioVio Healthcare"	:	"JioVio Healthcare",
"General Details"	:	"సాధారణ వివరాలు",
"Partner Details"	:	"భాగస్వామి వివరాలు",
"Pregnancy Details"	:	"గర్భం వివరాలు",
"Address Details"	:	"చిరునామా వివరాలు",
"Contact Us"	:	"మమ్మల్ని సంప్రదించండి",
"Something not Working"	:	"ఏదో పని చేయడం లేదు",
"Feature Request"	:	"ఫీచర్ అభ్యర్థన",
"Question"	:	"ప్రశ్న",
"FeedBack"	:	"అభిప్రాయం",
"SEND"	:	"పంపండి",
"My Subscription"	:	"నా చందా",
"Language"	:	"భాష",
"Terms & Conditions"	:	"నిబంధనలు & షరతులు",
"Privacy Policy"	:	"గోప్యతా విధానం",
"Log Out"	:	"లాగ్ అవుట్ చేయండి",
"Are you sure to logout?"	:	"మీరు ఖచ్చితంగా లాగ్ అవుట్ చేస్తారా?",
"Cancel"	:	"రద్దు చేయి",
"Ok"	:	"సరే",
"Change Default"	:	"డిఫాల్ట్‌ని మార్చండి",
"Write Description"	:	"వివరణ వ్రాయండి",
"Please enter Description"	:	"దయచేసి వివరణను నమోదు చేయండి",
"Door No"	:	"డోర్ నెం",
"Please enter Door No"	:	"దయచేసి డోర్ నెం",
"Street Name"	:	"వీధి పేరు",
"Please enter Street Name"	:	"దయచేసి వీధి పేరును నమోదు చేయండి",
"Pincode"	:	"పిన్ కోడ్",
"Please enter Pincode"	:	"దయచేసి పిన్‌కోడ్‌ని నమోదు చేయండి",
"Search Area"	:	"శోధన ప్రాంతం",
"Select Area Name"	:	"ప్రాంతం పేరును ఎంచుకోండి",
"Enter your Name"	:	"మీ పేరును నమోదు చేయండి",
"Please enter your name"	:	"దయచేసి మీ పేరును నమోదు చేయండి",
"Enter Email Id"	:	"ఇమెయిల్ ఐడిని నమోదు చేయండి",
"Please Select Gender"	:	"దయచేసి లింగాన్ని ఎంచుకోండి",
"Age"	:	"వయస్సు",
"Please enter age"	:	"దయచేసి వయస్సుని నమోదు చేయండి",
"Please enter correct age"	:	"దయచేసి సరైన వయస్సును నమోదు చేయండి",
"LMP Date"	:	"LMP తేదీ",
"Please enter LMP Date"	:	"దయచేసి LMP తేదీని నమోదు చేయండి",
"ED Date"	:	"ED తేదీ",
"Date of delivery"	:	"డెలివరీ తేదీ",
"Please enter Delivery Date"	:	"దయచేసి డెలివరీ తేదీని నమోదు చేయండి",
"Please enter Partner Name"	:	"దయచేసి భాగస్వామి పేరును నమోదు చేయండి",
"Partner Name"	:	"భాగస్వామి పేరు",
"Please enter Partner Mobile Number"	:	"దయచేసి భాగస్వామి మొబైల్ నంబర్‌ను నమోదు చేయండి",
"Partner Mobile Number"	:	"భాగస్వామి మొబైల్ నంబర్",
"Bed Time"	:	"పడుకునే సమయం",
"Please enter Date of Birth"	:	"దయచేసి పుట్టిన తేదీని నమోదు చేయండి",
"Wake Up Time"	:	"వేక్ అప్ టైమ్",
"Name"	:	"పేరు",
"Please Select Parent Type"	:	"దయచేసి పేరెంట్ రకాన్ని ఎంచుకోండి",
"Parent Type"	:	"పేరెంట్ రకం",
"Please Select Pregnant Status"	:	"దయచేసి గర్భిణీ స్థితిని ఎంచుకోండి",
"Please enter Area"	:	"దయచేసి ప్రాంతాన్ని నమోదు చేయండి",
"Area"	:	"ప్రాంతం",
"Services"	:	"సేవలు",
"AlloBaby"	:	"",
"Awareness"	:	"అవగాహన",
"Screening"	:	"స్క్రీనింగ్",
"Glucose Test"	:	"గ్లూకోజ్ పరీక్ష",
"Ultrasound Test"	:	"అల్ట్రాసౌండ్ పరీక్ష",
"Urine Test"	:	"మూత్ర పరీక్ష",
"Home"	:	"హోమ్",
"Service"	:	"సేవ",
"Chat"	:	"చాట్ చేయండి",
"Logout"	:	"లాగ్అవుట్",
"Notification"	:	"నోటిఫికేషన్",
"ON"	:	"ఆన్",
"OFF"	:	"ఆఫ్",
"ON/OFF"	:	"ఆన్/ఆఫ్",
"AI Recommendation"	:	"AI సిఫార్సు",
"Analyzing your health data..."	:	"మీ ఆరోగ్య డేటాను విశ్లేషిస్తోంది...",
"No summary available"	:	"సారాంశం అందుబాటులో లేదు",
"Book Appointment"	:	"బుక్ అపాయింట్‌మెంట్",
"SCAN AND ADD REPORT"	:	"స్కాన్ చేసి, నివేదికను జోడించండి",
"Allobot"	:	"అలోబోట్",
};