// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDTIZnQCNHOYfhO2knrgr8HlJMzldTKzY',
    appId: '1:492221570730:web:d0b8d7b3370ba2c4ea7ad3',
    messagingSenderId: '492221570730',
    projectId: 'savemom-healthcare',
    authDomain: 'savemom-healthcare.firebaseapp.com',
    storageBucket: 'savemom-healthcare.appspot.com',
    measurementId: 'G-WSGMSYQR18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyVPpgSEVJpi77S8Q5aN9VLSsaJjz0UKI',
    appId: '1:492221570730:android:fd8cfb51ae84f987ea7ad3',
    messagingSenderId: '492221570730',
    projectId: 'savemom-healthcare',
    storageBucket: 'savemom-healthcare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbjOuTSEt1EXZPnmIPRqxwkKX4XzpWANQ',
    appId: '1:492221570730:ios:4dca18407d2438d8ea7ad3',
    messagingSenderId: '492221570730',
    projectId: 'savemom-healthcare',
    storageBucket: 'savemom-healthcare.appspot.com',
    androidClientId: '492221570730-0bgdn40820ooplpsn14undq682ejhcu0.apps.googleusercontent.com',
    iosClientId: '492221570730-uke4nsigflvfmmku1mu115seo01j23te.apps.googleusercontent.com',
    iosBundleId: 'com.example.allobaby',
  );
}
